/** Broad user-facing lure/fly choices. poolTypeId is an explicit reviewed palette, not a depth or rig question. */
export const PICKER_CHOICES = [
  {
    "id": "soft_plastic_worm",
    "label": "Soft plastic worm",
    "categoryId": "soft_plastics",
    "poolTypeId": "stick_worm",
    "legacyTypeIds": [
      "stick_worm",
      "finesse_worm",
      "ribbon_tail_worm",
      "ned_bait",
    ],
    "description":
      "Soft plastic worms, including stick, straight-tail, ribbon-tail, and Ned-style baits.",
    "searchAliases": [
      "Stick worm",
      "stick bait",
      "wacky worm",
      "Senko",
      "Finesse / straight-tail worm",
      "shaky head worm",
      "drop shot worm",
      "Ribbon-tail worm",
      "ribbontail",
      "curly tail worm",
      "Ned-style bait",
      "Ned rig",
      "TRD",
    ],
  },
  {
    "id": "soft_craw",
    "label": "Craw / creature bait",
    "categoryId": "soft_plastics",
    "poolTypeId": "soft_craw",
    "legacyTypeIds": [
      "soft_craw",
      "creature_bait",
    ],
    "description": "Soft crawfish and creature baits with claws or appendages.",
    "searchAliases": [
      "Soft craw",
      "crawfish",
      "crayfish",
      "Texas rig craw",
      "Creature / beaver bait",
      "brush hog",
      "beaver",
      "creature",
    ],
  },
  {
    "id": "soft_tube",
    "label": "Tube",
    "categoryId": "soft_plastics",
    "poolTypeId": "soft_tube",
    "legacyTypeIds": [
      "soft_tube",
    ],
    "description": "A hollow cylindrical body with a fringed tail.",
    "searchAliases": [
      "Tube",
      "tube jig",
    ],
  },
  {
    "id": "curly_tail_grub",
    "label": "Grub",
    "categoryId": "soft_plastics",
    "poolTypeId": "curly_tail_grub",
    "legacyTypeIds": [
      "curly_tail_grub",
    ],
    "description": "A short grub body with one curved swimming tail.",
    "searchAliases": [
      "Curly-tail grub",
      "twister tail",
      "grub",
    ],
  },
  {
    "id": "soft_jerkbait",
    "label": "Soft jerkbait",
    "categoryId": "soft_plastics",
    "poolTypeId": "soft_jerkbait",
    "legacyTypeIds": [
      "soft_jerkbait",
      "straight_tail_minnow",
    ],
    "description": "A soft minnow profile with a forked or pointed tail.",
    "searchAliases": [
      "Soft jerkbait",
      "fluke",
      "Straight-tail minnow",
      "drop shot minnow",
      "finesse minnow",
    ],
  },
  {
    "id": "paddle_tail_swimbait",
    "label": "Paddletail",
    "categoryId": "soft_plastics",
    "poolTypeId": "paddle_tail_swimbait",
    "legacyTypeIds": [
      "paddle_tail_swimbait",
    ],
    "description": "A soft baitfish body ending in a paddle tail.",
    "searchAliases": [
      "Paddle-tail swimbait",
      "paddletail",
      "boot tail",
    ],
  },
  {
    "id": "soft_toad",
    "label": "Soft toad",
    "categoryId": "soft_plastics",
    "poolTypeId": "soft_toad",
    "legacyTypeIds": [
      "soft_toad",
    ],
    "description": "A solid soft-plastic frog with two swimming legs.",
    "searchAliases": [
      "Soft toad",
      "buzz frog",
      "soft frog",
    ],
  },
  {
    "id": "skirted_jig",
    "label": "Skirted jig",
    "categoryId": "jigs_spinners",
    "poolTypeId": "structure_jig",
    "legacyTypeIds": [
      "structure_jig",
      "football_jig",
      "finesse_jig",
      "swim_jig",
    ],
    "description":
      "A compact skirted jig for a coordinated skirt and trailer pattern.",
    "searchAliases": [
      "Flipping / structure jig",
      "casting jig",
      "flipping jig",
      "Football jig",
      "football head",
      "Finesse jig",
      "compact skirt jig",
      "Swim jig",
      "swimming jig",
    ],
  },
  {
    "id": "hair_jig",
    "label": "Hair jig",
    "categoryId": "jigs_spinners",
    "poolTypeId": "hair_jig",
    "legacyTypeIds": [
      "hair_jig",
    ],
    "description":
      "A jig dressed with hair or soft feathers rather than a silicone skirt.",
    "searchAliases": [
      "Hair / marabou jig",
      "bucktail jig",
      "marabou jig",
    ],
  },
  {
    "id": "spinnerbait",
    "label": "Spinnerbait",
    "categoryId": "jigs_spinners",
    "poolTypeId": "spinnerbait",
    "legacyTypeIds": [
      "spinnerbait",
    ],
    "description": "A bent-wire lure with blades above a skirted hook.",
    "searchAliases": [
      "Spinnerbait",
      "safety pin spinner",
    ],
  },
  {
    "id": "bladed_jig",
    "label": "Bladed jig",
    "categoryId": "jigs_spinners",
    "poolTypeId": "bladed_jig",
    "legacyTypeIds": [
      "bladed_jig",
    ],
    "description": "A skirted jig with a vibration blade at its head.",
    "searchAliases": [
      "Bladed jig",
      "ChatterBait",
      "vibrating jig",
    ],
  },
  {
    "id": "buzzbait",
    "label": "Buzzbait",
    "categoryId": "jigs_spinners",
    "poolTypeId": "buzzbait",
    "legacyTypeIds": [
      "buzzbait",
    ],
    "description": "A wire lure with a surface propeller above a skirted hook.",
    "searchAliases": [
      "Buzzbait",
      "buzz bait",
    ],
  },
  {
    "id": "inline_spinner",
    "label": "Inline spinner",
    "categoryId": "jigs_spinners",
    "poolTypeId": "inline_spinner",
    "legacyTypeIds": [
      "inline_spinner",
      "bucktail_spinner",
    ],
    "description": "A blade rotating around a straight wire body.",
    "searchAliases": [
      "Inline spinner",
      "Rooster Tail",
      "Mepps",
      "Large bucktail spinner",
      "musky bucktail",
    ],
  },
  {
    "id": "underspin",
    "label": "Underspin",
    "categoryId": "jigs_spinners",
    "poolTypeId": "underspin",
    "legacyTypeIds": [
      "underspin",
    ],
    "description":
      "A baitfish-shaped soft body with a small blade suspended beneath.",
    "searchAliases": [
      "Underspin",
      "under spin",
    ],
  },
  {
    "id": "crankbait",
    "label": "Crankbait",
    "categoryId": "hard_baits",
    "poolTypeId": "medium_crankbait",
    "legacyTypeIds": [
      "squarebill",
      "flat_sided_crankbait",
      "medium_crankbait",
      "deep_crankbait",
    ],
    "description":
      "Billed crankbaits, including squarebills and shallow or deep divers.",
    "searchAliases": [
      "Squarebill crankbait",
      "square bill",
      "Flat-sided crankbait",
      "flat side crank",
      "Medium-diving crankbait",
      "medium diver",
      "Deep-diving crankbait",
      "deep diver",
    ],
  },
  {
    "id": "lipless_crankbait",
    "label": "Lipless crankbait",
    "categoryId": "hard_baits",
    "poolTypeId": "lipless_crankbait",
    "legacyTypeIds": [
      "lipless_crankbait",
    ],
    "description": "A flat-sided sinking hard bait with no diving lip.",
    "searchAliases": [
      "Lipless crankbait",
      "rattle trap",
    ],
  },
  {
    "id": "hard_jerkbait",
    "label": "Jerkbait",
    "categoryId": "hard_baits",
    "poolTypeId": "hard_jerkbait",
    "legacyTypeIds": [
      "hard_jerkbait",
      "floating_minnow",
      "pull_jerk_bait",
    ],
    "description":
      "A slender hard minnow with a small lip for darting retrieves.",
    "searchAliases": [
      "Hard jerkbait",
      "suspending jerkbait",
      "Floating minnow plug",
      "trout plug",
      "floating minnowbait",
      "Pull / jerk bait",
      "musky jerk bait",
      "pull bait",
    ],
  },
  {
    "id": "hard_swimbait",
    "label": "Hard swimbait",
    "categoryId": "hard_baits",
    "poolTypeId": "hard_swimbait",
    "legacyTypeIds": [
      "hard_swimbait",
      "glidebait",
    ],
    "description":
      "A jointed hard baitfish body; distinct from a soft paddle tail.",
    "searchAliases": [
      "Hard swimbait",
      "jointed swimbait",
      "Glidebait",
      "glide bait",
    ],
  },
  {
    "id": "spoon",
    "label": "Spoon",
    "categoryId": "metal_baits",
    "poolTypeId": "casting_spoon",
    "legacyTypeIds": [
      "casting_spoon",
      "weedless_spoon",
      "trolling_spoon",
      "jigging_spoon",
    ],
    "description": "A curved metal spoon with a trailing hook.",
    "searchAliases": [
      "Casting spoon",
      "casting metal spoon",
      "Weedless spoon",
      "weed guard spoon",
      "Trolling spoon",
      "flutter trolling spoon",
      "Jigging spoon",
      "vertical spoon",
    ],
  },
  {
    "id": "topwater",
    "label": "Topwater lure",
    "categoryId": "hard_baits",
    "poolTypeId": "walking_bait",
    "legacyTypeIds": [
      "walking_bait",
      "hard_popper",
      "prop_bait",
      "plopper_bait",
      "wake_bait",
    ],
    "description":
      "Hard surface lures, including walking baits, poppers, prop baits, and wake baits.",
    "searchAliases": [
      "Walking bait",
      "walk the dog",
      "spook",
      "Hard-bait popper",
      "conventional popper",
      "pop r",
      "Prop bait",
      "propeller bait",
      "Plopper bait",
      "rotating tail topwater",
      "Wake bait",
      "surface wakebait",
    ],
  },
  {
    "id": "hollow_frog",
    "label": "Hollow-body frog",
    "categoryId": "hard_baits",
    "poolTypeId": "hollow_frog",
    "legacyTypeIds": [
      "hollow_frog",
    ],
    "description": "A collapsible frog body with an upward-facing double hook.",
    "searchAliases": [
      "Hollow-body frog",
      "hollow frog",
    ],
  },
  {
    "id": "streamer",
    "label": "Streamer fly",
    "categoryId": "flies",
    "poolTypeId": "baitfish_streamer",
    "legacyTypeIds": [
      "woolly_bugger",
      "leech_streamer",
      "baitfish_streamer",
      "clouser_streamer",
      "articulated_streamer",
      "sculpin_streamer",
      "crawfish_streamer",
      "pike_streamer",
      "flash_streamer",
    ],
    "description":
      "Subsurface streamer flies tied with hair, feathers, or synthetic fibers.",
    "searchAliases": [
      "Woolly Bugger",
      "wooly bugger",
      "Leech streamer",
      "rabbit strip leech",
      "balanced leech",
      "Baitfish / minnow streamer",
      "Deceiver",
      "bucktail streamer",
      "Zonker",
      "Clouser-style streamer",
      "Clouser minnow",
      "Articulated streamer",
      "Game Changer",
      "Dungeon",
      "Sculpin streamer",
      "sculpzilla",
      "muddler",
      "Crawfish streamer",
      "crayfish fly",
      "craw fly",
      "Large pike streamer",
      "pike bunny",
      "large predator streamer",
      "Flash streamer",
      "Flash Fly",
    ],
  },
  {
    "id": "fly_popper",
    "label": "Fly popper",
    "categoryId": "flies",
    "poolTypeId": "fly_popper",
    "legacyTypeIds": [
      "fly_popper",
    ],
    "description":
      "A cupped foam, cork, or hair fly head with a dressed single hook, tail, and optional legs.",
    "searchAliases": [
      "Fly popper",
      "bass bug",
      "foam popper",
      "deer hair popper",
    ],
  },
] as const;
