import type { CellKey, PoolResearchProfile } from "./researchSchema.ts";

/**
 * Release-facing visual curation for the broad Color Match choices most likely to
 * be used by beginners. These are deliberately small sets of distinguishable
 * optical strategies, not rankings and not claims about fish biology.
 */
const rationale = (
  principle: string,
  application: string,
): Record<CellKey, string> => ({
  clear_sunny: `${principle} In high visibility with direct light, ${application}`,
  clear_cloudy: `${principle} In high visibility with diffuse light, ${application}`,
  stained_sunny: `${principle} In moderate visibility with direct light, ${application}`,
  stained_cloudy: `${principle} In moderate visibility with diffuse light, ${application}`,
  dirty_sunny: `${principle} In short visibility, ${application}`,
  dirty_cloudy: `${principle} In short visibility, ${application}`,
});

export const VISUAL_CURATION_PROFILES: readonly PoolResearchProfile[] = [
  {
    id: "visual_20260908_worm",
    sourceIds: ["plastic_clarity", "hard_light", "visual_palette_simplification", "verified_senko_2026"],
    principle: "The worm pool keeps a compact set of visibly different translucent, midtone, dark and marked recipes.",
    extension: "Water clarity and available light determine the optical set. Species, forage, season, location, depth and presentation are not inferred. Flake and laminate variants were removed when they duplicated an already represented visual strategy.",
    cells: {
      clear_sunny: ["plastic_green_pumpkin", "plastic_watermelon_seed", "plastic_watermelon_red", "plastic_pumpkinseed", "plastic_black"],
      clear_cloudy: ["plastic_green_pumpkin", "plastic_black", "plastic_black_blue", "plastic_junebug"],
      stained_sunny: ["plastic_green_pumpkin", "plastic_watermelon_red", "plastic_black_blue", "plastic_junebug", "plastic_gp_chart_tail"],
      stained_cloudy: ["plastic_green_pumpkin", "plastic_black", "plastic_black_blue", "plastic_junebug", "plastic_gp_chart_tail"],
      dirty_sunny: ["plastic_black", "plastic_black_blue", "plastic_junebug", "plastic_gp_chart_tail"],
      dirty_cloudy: ["plastic_black", "plastic_black_blue", "plastic_junebug", "plastic_gp_chart_tail"],
    },
    lightPolicy: "documented_direction_editorial_application",
    rationale: rationale(
      "Every eligible worm color has equal status; list order has no meaning.",
      "the pool favors distinct opacity, silhouette and accent treatments without claiming one will catch more fish.",
    ),
  },
  {
    id: "visual_20260908_craw_creature",
    sourceIds: ["plastic_clarity", "hard_light", "visual_palette_simplification", "mister_twister_2026_creature"],
    principle: "Craw and creature plastics use a compact mix of midtone, translucent, dark and two-tone contrast recipes.",
    extension: "Brown/orange is included as a documented creature-bait construction because its large color boundary is visually distinct. No claim is made about local crawfish, forage or seasonal color change.",
    cells: {
      clear_sunny: ["plastic_green_pumpkin", "plastic_watermelon_seed", "plastic_watermelon_red", "plastic_brown_orange_tail"],
      clear_cloudy: ["plastic_green_pumpkin", "plastic_black_blue", "plastic_junebug", "plastic_brown_orange_tail"],
      stained_sunny: ["plastic_green_pumpkin", "plastic_black_blue", "plastic_junebug", "plastic_brown_orange_tail"],
      stained_cloudy: ["plastic_green_pumpkin", "plastic_black_blue", "plastic_junebug", "plastic_brown_orange_tail"],
      dirty_sunny: ["plastic_green_pumpkin", "plastic_black_blue", "plastic_junebug", "plastic_brown_orange_tail"],
      dirty_cloudy: ["plastic_green_pumpkin", "plastic_black_blue", "plastic_junebug", "plastic_brown_orange_tail"],
    },
    lightPolicy: "documented_direction_editorial_application",
    rationale: rationale(
      "Every eligible craw/creature color has equal status; list order has no meaning.",
      "the pool retains distinguishable whole-body and two-tone treatments without inferring prey color.",
    ),
  },
  {
    id: "visual_20260908_grub",
    sourceIds: ["plastic_clarity", "hard_light", "metal_blade", "mister_twister_2026_grub"],
    principle: "Curly-tail grubs use established grub colors spanning pearl, translucent flash, earth tone, dark and bright opaque treatments.",
    extension: "The grub no longer inherits a worm-only palette. Current manufacturer catalogs establish that these constructions are real grub offerings; exact condition placement remains a conservative visual editorial decision.",
    cells: {
      clear_sunny: ["plastic_pearl", "plastic_smoke_silver", "plastic_pumpkinseed", "plastic_black"],
      clear_cloudy: ["plastic_pearl", "plastic_smoke", "plastic_green_pumpkin", "plastic_black"],
      stained_sunny: ["plastic_pearl", "plastic_chartreuse", "plastic_pumpkinseed", "plastic_green_pumpkin", "plastic_black"],
      stained_cloudy: ["plastic_pearl", "plastic_chartreuse", "plastic_green_pumpkin", "plastic_black"],
      dirty_sunny: ["plastic_pearl", "plastic_chartreuse", "plastic_black", "plastic_black_blue"],
      dirty_cloudy: ["plastic_pearl", "plastic_chartreuse", "plastic_black", "plastic_black_blue"],
    },
    lightPolicy: "documented_direction_editorial_application",
    rationale: rationale(
      "Every eligible grub color has equal status; list order has no meaning.",
      "the pool uses visibly different body treatments that are commercially recognizable on a curly-tail grub.",
    ),
  },
  {
    id: "visual_20260908_paddletail",
    sourceIds: ["plastic_clarity", "plastic_jerk", "hard_light", "visual_palette_simplification", "verified_keitech_2026"],
    principle: "Paddletails use pale, translucent-flash, olive/pearl, midtone and dark silhouette treatments appropriate to a swimming soft-plastic body.",
    extension: "Junebug and redundant dark variants were removed from the primary pool. Olive/pearl is not carried into short-visibility cells because its subtle two-tone boundary is less distinct there; this is an optical editorial boundary, not a catch claim.",
    cells: {
      clear_sunny: ["plastic_pearl", "plastic_olive_pearl", "plastic_smoke_silver", "plastic_green_pumpkin", "plastic_black"],
      clear_cloudy: ["plastic_pearl", "plastic_olive_pearl", "plastic_green_pumpkin", "plastic_black"],
      stained_sunny: ["plastic_pearl", "plastic_olive_pearl", "plastic_green_pumpkin", "plastic_black_blue", "plastic_chart_white"],
      stained_cloudy: ["plastic_pearl", "plastic_green_pumpkin", "plastic_black", "plastic_black_blue", "plastic_chart_white"],
      dirty_sunny: ["plastic_pearl", "plastic_black", "plastic_black_blue", "plastic_chart_white"],
      dirty_cloudy: ["plastic_pearl", "plastic_black", "plastic_black_blue", "plastic_chart_white"],
    },
    lightPolicy: "documented_direction_editorial_application",
    rationale: rationale(
      "Every eligible paddletail color has equal status; list order has no meaning.",
      "the pool balances body opacity, reflection and silhouette while avoiding minor flake changes as separate strategies.",
    ),
  },
  {
    id: "visual_20260908_skirted_jig",
    sourceIds: ["jig_bottom", "jig_muddy", "swim_jig", "skirt_palette", "visual_palette_simplification"],
    principle: "The broad skirted-jig choice represents both bottom-contact and swimming constructions with a concise set of coordinated skirt/trailer recipes.",
    extension: "White and white/chartreuse prevent the broad choice from silently behaving like a bottom-jig-only selector. Earth tones and dark silhouettes remain represented. No forage identity is inferred from the olive/brown/orange recipe.",
    cells: {
      clear_sunny: ["jig_white", "jig_green_pumpkin", "jig_brown_orange", "jig_bluegill"],
      clear_cloudy: ["jig_white", "jig_green_pumpkin", "jig_brown_orange", "jig_black_blue"],
      stained_sunny: ["jig_white", "jig_white_chartreuse", "jig_green_pumpkin", "jig_brown_orange", "jig_black_blue"],
      stained_cloudy: ["jig_white", "jig_white_chartreuse", "jig_brown_orange", "jig_black_blue", "jig_black"],
      dirty_sunny: ["jig_white_chartreuse", "jig_brown_orange", "jig_black_blue", "jig_black"],
      dirty_cloudy: ["jig_white_chartreuse", "jig_brown_orange", "jig_black_blue", "jig_black"],
    },
    lightPolicy: "documented_direction_editorial_application",
    rationale: rationale(
      "Every eligible skirted-jig color has equal status; list order has no meaning.",
      "the pool spans pale, earth-tone, marked and dark coordinated constructions without assuming how the jig will be retrieved.",
    ),
  },
  {
    id: "visual_20260908_bladed_jig",
    sourceIds: ["spinner_components", "skirt_palette", "swim_jig", "bladed_finish", "bladed_known", "zman_fire_craw"],
    principle: "Bladed-jig choices recommend coordinated skirt/trailer colors; the metal blade is illustration hardware unless a future recipe explicitly includes it.",
    extension: "Fire craw adds a documented red/orange/black high-contrast construction. Plain chartreuse was removed where white/chartreuse already represents the same bright strategy. Condition placement is editorial; biological and seasonal claims from source material are not used.",
    cells: {
      clear_sunny: ["bladed_white_silver", "bladed_white_chartreuse", "bladed_green_pumpkin"],
      clear_cloudy: ["bladed_white_silver", "bladed_green_pumpkin", "bladed_black_blue"],
      stained_sunny: ["bladed_white_silver", "bladed_white_chartreuse", "bladed_green_pumpkin", "bladed_black_blue", "bladed_fire_craw"],
      stained_cloudy: ["bladed_white_silver", "bladed_white_chartreuse", "bladed_green_pumpkin", "bladed_black_blue", "bladed_fire_craw"],
      dirty_sunny: ["bladed_white_silver", "bladed_white_chartreuse", "bladed_black_blue", "bladed_fire_craw"],
      dirty_cloudy: ["bladed_white_silver", "bladed_white_chartreuse", "bladed_black_blue", "bladed_fire_craw"],
    },
    lightPolicy: "documented_direction_editorial_application",
    rationale: rationale(
      "Every eligible bladed-jig color has equal status; list order has no meaning.",
      "the pool uses distinct pale, bright, earth-tone, dark and red/orange treatments; blade finish is not silently prescribed.",
    ),
  },
  {
    id: "visual_20260908_underspin",
    sourceIds: ["spinner_components", "plastic_jerk", "metal_contrast", "underspin_known", "underspin_body_guidance", "verified_keitech_2026"],
    principle: "Underspin choices distinguish pale, olive/pearl, gold-tone, bright-marked and dark body/head treatments.",
    extension: "Junebug and plain chartreuse were removed where they duplicated another dark or bright strategy. The small underspin blade is neutral illustration hardware, not a hidden finish recommendation.",
    cells: {
      clear_sunny: ["underspin_pearl_silver", "underspin_olive_silver", "underspin_gold"],
      clear_cloudy: ["underspin_pearl_silver", "underspin_olive_silver", "underspin_gold"],
      stained_sunny: ["underspin_pearl_silver", "underspin_olive_silver", "underspin_gold", "underspin_white_chartreuse", "underspin_black_blue"],
      stained_cloudy: ["underspin_pearl_silver", "underspin_olive_silver", "underspin_gold", "underspin_white_chartreuse", "underspin_black_blue"],
      dirty_sunny: ["underspin_pearl_silver", "underspin_gold", "underspin_white_chartreuse", "underspin_black_blue"],
      dirty_cloudy: ["underspin_pearl_silver", "underspin_gold", "underspin_white_chartreuse", "underspin_black_blue"],
    },
    lightPolicy: "retain_without_supported_exclusion",
    rationale: rationale(
      "Every eligible underspin color has equal status; list order has no meaning.",
      "the pool uses distinct body/head treatments without turning incidental blade hardware into another color choice.",
    ),
  },
  {
    id: "visual_20260908_crankbait",
    sourceIds: ["hard_light", "hard_natural", "hard_opaque", "hard_multi", "visual_palette_simplification"],
    principle: "Crankbait finishes use a compact set of translucent, metallic, natural-painted, pale opaque and high-contrast patterns.",
    extension: "Near-duplicate silver sides and multiple muted painted patterns were reduced so minor accent changes do not gain extra probability. Billed and lipless baits share these finish families, but retain their own physical lure construction.",
    cells: {
      clear_sunny: ["hard_ghost", "hard_silver_black", "hard_gold_black", "hard_perch", "hard_brown_craw"],
      clear_cloudy: ["hard_pearl", "hard_silver_blue", "hard_gold_black", "hard_perch", "hard_brown_craw"],
      stained_sunny: ["hard_pearl", "hard_gold_black", "hard_perch", "hard_red_craw", "hard_chartreuse_back", "hard_firetiger"],
      stained_cloudy: ["hard_pearl", "hard_gold_black", "hard_red_craw", "hard_chartreuse_back", "hard_firetiger"],
      dirty_sunny: ["hard_pearl", "hard_red_craw", "hard_chartreuse_back", "hard_firetiger"],
      dirty_cloudy: ["hard_pearl", "hard_red_craw", "hard_chartreuse_back", "hard_firetiger"],
    },
    lightPolicy: "documented_direction_editorial_application",
    rationale: rationale(
      "Every eligible hard-bait finish has equal status; list order has no meaning.",
      "the pool favors meaningfully different opacity, reflectivity and large painted boundaries instead of minor accent changes.",
    ),
  },
];

export const VISUAL_CURATION_TYPE_IDS = [
  "stick_worm",
  "soft_craw",
  "creature_bait",
  "curly_tail_grub",
  "paddle_tail_swimbait",
  "structure_jig",
  "bladed_jig",
  "underspin",
  "medium_crankbait",
  "lipless_crankbait",
] as const;

/** One family per meaningfully distinct appearance within each curated pool. */
export const VISUAL_FAMILIES: Readonly<Record<string, string>> = {
  plastic_green_pumpkin: "midtone-green",
  plastic_watermelon_seed: "translucent-green-black",
  plastic_watermelon_red: "translucent-green-red",
  plastic_pumpkinseed: "translucent-tan",
  plastic_black: "solid-black",
  plastic_black_blue: "black-blue-flake",
  plastic_junebug: "purple-green-flake",
  plastic_gp_chart_tail: "green-bright-tail",
  plastic_brown_orange_tail: "brown-orange-boundary",
  plastic_pearl: "pearl-pale",
  plastic_smoke: "translucent-smoke",
  plastic_smoke_silver: "translucent-smoke-silver",
  plastic_chartreuse: "solid-bright",
  plastic_olive_pearl: "olive-pearl-boundary",
  plastic_chart_white: "bright-pale-boundary",
  jig_white: "jig-pale",
  jig_green_pumpkin: "jig-midtone-green",
  jig_brown_orange: "jig-brown-orange",
  jig_bluegill: "jig-olive-brown-orange",
  jig_white_chartreuse: "jig-bright-pale",
  jig_black_blue: "jig-black-blue",
  jig_black: "jig-solid-black",
  bladed_white_silver: "bladed-pale",
  bladed_white_chartreuse: "bladed-bright-pale",
  bladed_green_pumpkin: "bladed-midtone-green",
  bladed_black_blue: "bladed-black-blue",
  bladed_fire_craw: "bladed-red-orange-black",
  underspin_pearl_silver: "underspin-pale",
  underspin_olive_silver: "underspin-olive-pearl",
  underspin_gold: "underspin-gold-tone",
  underspin_white_chartreuse: "underspin-bright-pale",
  underspin_black_blue: "underspin-black-blue",
  hard_ghost: "hard-translucent",
  hard_silver_black: "hard-silver-black",
  hard_silver_blue: "hard-silver-blue",
  hard_gold_black: "hard-gold",
  hard_perch: "hard-muted-bars",
  hard_brown_craw: "hard-muted-brown",
  hard_pearl: "hard-pale-opaque",
  hard_red_craw: "hard-red-dark",
  hard_chartreuse_back: "hard-bright-dark-back",
  hard_firetiger: "hard-bright-bars",
};
