/**
 * howToFishPhrases — technique instructions for a given family.
 *
 * Keyed on: family_id × motion_type
 * 14-18 variants each — picked deterministically by date + species seed.
 * Keep tactical and specific. ≤ 20 words per phrase.
 */

import type { MotionType } from "../contracts/behavior.ts";
import type { FlyFamilyId, LureFamilyId } from "../contracts/families.ts";

type FamilyId = LureFamilyId | FlyFamilyId;

// Grouped by motion type for families where the family_id match isn't needed
export const HOW_TO_FISH_BY_MOTION: Record<
  MotionType,
  readonly string[]
> = {
  steady: [
    "Steady, medium-speed retrieve just above the bottom. Keep contact with structure.",
    "Reel at a consistent clip — vary only if fish follow but don't commit.",
    "Slow-roll through the zone, letting the action do the work.",
    "Maintain constant contact and reel speed — let the lure track naturally through the zone.",
    "Straight retrieve at a pace that keeps you in the fish zone. No pauses needed.",
    "Lock in a steady retrieve and let the profile do the work — change speed only on follows.",
    "Keep your rod tip low and reel at a steady pace. Let the lure swim on its own.",
    "Find the speed that keeps it in the strike zone and hold that pace for the full retrieve.",
    "Consistent reel speed through the target area. If you feel a bump, keep going — they will commit.",
    "Match your reel speed to the current so the lure tracks naturally with minimal effort.",
    "Point the rod at the lure and wind at a comfortable pace. Simplicity catches fish here.",
    "Slow and steady wins it. Keep the lure swimming at a speed that feels natural, not rushed.",
    "A reliable medium-speed retrieve covers the most water while staying in the bite zone.",
    "Don't overthink it — reel smoothly at a medium clip and let the lure do what it was designed to do.",
  ],
  hop: [
    "Lift the rod tip, let it fall, reel up slack. Repeat on or near the bottom.",
    "Short hops along the bottom with a full pause on each fall.",
    "Pop-hop retrieve — keep contact with the substrate throughout.",
    "Two-foot hop, let it fall completely, pause 2 seconds, repeat. Stay in contact.",
    "Hop it off the bottom and follow the fall — most strikes happen on the descent.",
    "Quick upward snap, then reel to keep contact with the bottom on the fall.",
    "Small hops with a tight line on the fall. You want to feel the bottom after every lift.",
    "Lift-drop-pause. Keep the hops short and the pauses deliberate. Let fish make a decision.",
    "Bounce it along the bottom like a crawfish darting between rocks. Short lifts, quick drops.",
    "Snap the rod tip up one foot, follow it back down. The fall is the bite window.",
    "Repeated short hops with a dead pause between each one. Stay patient on the bottom.",
    "Pop it up off structure, let it flutter down naturally. Keep constant bottom contact.",
    "Lift and drop with the rod tip, reeling only to collect slack. The rod does the work.",
    "Quick upward lift, then let gravity take over. Stay in contact and watch for a tick on the fall.",
  ],
  twitch_pause: [
    "Two quick twitches, then a full 2-3 second pause. Strike on the fall.",
    "Snap the rod tip down, pause. Fish often hit on the pause.",
    "Erratic twitch-twitch-pause — mimic a disoriented baitfish.",
    "Twitch twice sharply, pause long enough to feel the bottom, repeat.",
    "Quick rod snaps followed by a dead pause — the hesitation triggers the bite.",
    "Irregular twitch cadence with longer pauses when fish are following but not eating.",
    "Short snap, long pause. Let the bait sit motionless until the next twitch.",
    "Mix up the cadence — two twitches, then pause. Then one twitch and a longer pause.",
    "Snap it twice, let it sit dead still. The longer the pause, the more committed the bite.",
    "Rhythmic twitch-twitch-glide. Let the lure drift between bursts of action.",
    "One sharp snap, then wait. Give the fish 3-4 full seconds to decide before moving again.",
    "Quick wrist snaps with slack in the line. The lure needs to dart, not slide.",
    "Alternate between short fast twitches and long pauses. Let the fish tell you which cadence works.",
    "Snap the rod tip downward and immediately feed slack. The lure should jolt and then hang.",
  ],
  rip: [
    "Hard, fast rip off the bottom, then let it flutter back down.",
    "Rip the lure aggressively, triggering a reflex strike on the drop.",
    "Burn it fast — rip-rip-rip with just enough pause to let it sink.",
    "Violent upward rod sweep, follow it down on a semi-slack line. Strikes happen on the drop.",
    "Rip hard off structure, pause immediately. The flutter after the rip is the trigger.",
    "Fast aggressive strips — get it moving fast and let the bottom contact create the erratic action.",
    "Rip it upward sharply, then drop the rod tip and let the lure flutter back. Stay tight.",
    "Hard upward snap, controlled fall. Most fish eat it during the flutter, not the rip.",
    "Aggressive lift-and-drop with full rod sweeps. Cover water quickly with maximum flash.",
    "Rip it two or three feet off the bottom, let it sink back on a semi-tight line.",
    "Fast and violent — snap it off structure and let the erratic fall trigger reaction bites.",
    "Rip hard enough to feel the lure vibrate, then kill it. The sudden stop gets the bite.",
    "Quick upward rip, followed by a controlled free-fall. Set the hook on any tick during the drop.",
    "Short violent rips near cover. The aggressive motion draws fish out of tight spots.",
  ],
  sweep: [
    "Long, sweeping rod arc to the side, then reel back to position.",
    "Sweep the fly across current in a long arc, let it swing to dangle.",
    "Slow, broad sweep through the strike zone — works well on large streamers.",
    "Extend the rod sweeping across the current, then swing it back upstream.",
    "Broad arc with the rod from upstream to downstream — let the current do the work.",
    "Sweep slowly across the seam, pause at the end of the arc before the next cast.",
    "Long slow rod sweep from one side to the other. Let the fly track through the feeding lane.",
    "Sweep the rod in a wide arc and let the streamer glide through the column naturally.",
    "Smooth sweeping motion — no jerky movements. The fly should look like it is cruising, not fleeing.",
    "Sweep across the current seam, then hold at the end of the arc. Fish often eat at the hang.",
    "Keep the sweep slow and deliberate. The fly needs time to track fully through the zone.",
    "Arc the rod tip from upstream to down. The broadside profile during the sweep is what triggers the eat.",
    "Sweep, pause, sweep. Give the fly time to hang between sweeps and let fish close the distance.",
    "Smooth sweeping retrieve that keeps the fly swimming broadside through the strike zone.",
  ],
  walk: [
    "Rhythmic rod tip twitches with slack line — keep the cadence consistent.",
    "Walk-the-dog with steady left-right action. Vary pace if fish follow.",
    "Loose-wrist rod twitches to walk the lure side-to-side over the target.",
    "Short snap-snap cadence with minimal rod movement — keep the lure in the zone.",
    "Slack between twitches is key — too tight and it won't walk. Stay loose.",
    "Walk it over the target area with a steady pop-pop-pause rhythm.",
    "Downward rod twitches with a low rod tip. Let the bait glide between each snap.",
    "Consistent left-right cadence at a moderate pace. Speed up only when fish are tracking.",
    "Light wrist twitches — the less you move the rod, the better the walk. Keep it subtle.",
    "Work the slack — snap, pause, snap. The lure needs room to swing side to side.",
    "Walk it slowly over the strike zone. Don't rush it — the side-to-side action draws fish in.",
    "Quick subtle twitches with a low rod tip and plenty of line slack between snaps.",
    "Maintain a steady walking rhythm. The bait should move at a natural pace, not sprint across the surface.",
    "Two quick snaps, then a brief pause. Resume the walk. The pause often triggers the strike.",
  ],
  pop: [
    "Short, sharp rod pop to create a splash, then pause 2-3 seconds.",
    "Pop-pause-pop. Let rings dissipate before the next pop.",
    "Aggressive pops for active fish; slower pops when fish are subtle.",
    "One hard pop, long pause. Give fish time to commit before the next disturbance.",
    "Vary pop intensity — loud pops to locate fish, softer pops once they are close.",
    "Pop it into position over cover, pause until the rings die, pop again. Be patient.",
    "Sharp downward snap to create a blooping pop. Let the splash settle completely before the next one.",
    "Pop it once, count to three, pop again. The stillness between pops is what sells it.",
    "Mix loud and soft pops — start aggressive to draw attention, then go quiet to close the deal.",
    "Pop and wait. Pop and wait. The pause is more important than the pop.",
    "One strong pop near structure, then let it sit motionless. Fish often strike during the silence.",
    "Short pops with the rod tip pointed at the water. Keep the lure in the target zone as long as possible.",
    "Pop it sharply, then let it drift naturally on the surface. The quiet glide after the pop triggers bites.",
    "Start with gentle pops. If fish are active, increase intensity until they commit.",
  ],
  drag: [
    "Dead slow bottom drag. Pull a few inches, pause, repeat.",
    "Drag along the substrate — don't lift off the bottom.",
    "Ultra-slow bottom drag. Let the lure do the work with minimal angler input.",
    "Inch it forward, keep rod pressure consistent, pause for 3 seconds between moves.",
    "Stay in contact with the bottom at all times — lift and you lose the fish.",
    "Dead stick it, drag it a foot, dead stick again. Patience wins this game.",
    "Slowly pull it along the bottom, pausing after every few inches. Let fish find it.",
    "Keep it on the bottom. Move it just enough to create a small puff of silt, then stop.",
    "Barely move it — the tiniest drag followed by a long pause is the whole presentation.",
    "Think of dragging it at half the speed you think is right. Then go even slower.",
    "Maintain constant bottom contact and move it only an inch or two at a time.",
    "Let it sit for 10 seconds after every drag. The motionless pause is when fish commit.",
    "Drag-stop-wait. The less you move it, the more confident the bite will be.",
    "A slow steady pull along the bottom with no lifting. The lure should never leave the substrate.",
  ],
  swing: [
    "Cast across current, mend for a dead drift, let it swing to below you.",
    "Swing the fly on a tight line — speed up or slow down with rod angle.",
    "Cross-current cast, let the fly swing tight across the seam.",
    "Quarter-downstream cast, controlled mend, swing the fly through the bucket.",
    "Let it drift, then swing it fully broadside through the run before recast.",
    "Lead with the rod tip on the swing — slowing it down or speeding it up changes the depth.",
    "Cast at a 45-degree angle downstream and let the current sweep the fly across.",
    "Mend upstream to slow the swing, or downstream to speed it up. Control the pace with mends.",
    "Let the fly swing from the far side all the way to your bank. Fish often eat at the hang-down.",
    "Swing it through the seam at a natural pace. Add a short strip at the end of the swing.",
    "Quarter-downstream cast, upstream mend, then let the current do the work. Strip at the dangle.",
    "Tight-line swing through the run. The fly should track broadside through the fish's window.",
    "Cast across, mend once, then let the fly swing freely. Follow with the rod tip as it arcs below you.",
    "Controlled swing through the feeding lane. Add a little hand-twist at the end to extend the drift.",
  ],
};

// Family-specific overrides when the motion-based default isn't enough
export const HOW_TO_FISH_FAMILY_OVERRIDE: Partial<
  Record<FamilyId, readonly string[]>
> = {
  topwater_frog: [
    "Cast to cover, let rings settle, then walk it across the mat.",
    "Fish slow over pads and matted grass — pause near any opening.",
    "Slow walking retrieve across vegetation — fish hit when it enters a pocket.",
    "Land it on the mat, pause 3 full seconds, then walk to the nearest gap.",
    "Walk-the-frog retrieve with a pause every 6-8 inches over thick cover.",
    "Let it sit completely still after landing — then walk it across the mat to the open water edge.",
    "Target any gap in the vegetation. Walk it slowly toward the opening and pause right at the edge.",
    "Drop it on the thickest mat you can find, then walk it to the nearest pocket.",
    "Walk it slowly over the thickest cover. When you reach a gap, let it sit for 3 seconds.",
    "Pitch to the back edge of the mat and walk it toward open water. Fish blow up at the edge.",
    "Slow crawl over heavy cover — pause at every hole, gap, or thin spot in the mat.",
    "Land it soft, wait for the splash rings to disappear, then start a slow walk-the-frog retrieve.",
    "Stay patient over thick cover. One slow walk, one pause. Repeat. The blowup will come.",
    "Twitch it across pads with long pauses between moves. Fish need time to track it from below.",
  ],
  lipless_crankbait: [
    "Yo-yo retrieve: rip up, let it flutter, repeat. Stay in contact with grass.",
    "Steady medium reel through the water column, or yo-yo in grass.",
    "Burn and kill — fast reel, sudden stop. Reaction bite on the fall.",
    "Rip it free from grass, let it flutter back down, feel for the tick-tick before striking.",
    "High-speed burn just above the grass tops — pause when it snags and let it float free.",
    "Yo-yo it along the bottom: rip up sharply, drop back, repeat. Most bites come on the flutter.",
    "Rip it through submerged grass and let it fall when it tears free. The erratic drop triggers bites.",
    "Steady retrieve along the grass line. When it snags, rip it free — that is the trigger.",
    "Cast to the grass edge, let it sink, then burn it back just above the cover tops.",
    "Fast burn near the surface, or slow yo-yo on the bottom. Match the depth to where fish are sitting.",
    "Pull it through grass, pause when it hangs up, then rip free. Fish eat on the escape.",
    "Medium-speed retrieve with occasional sharp rod snaps to change the vibration.",
    "Rip-and-fall through the grass. Let it tick the top of the cover on every hop.",
    "Steady reel at medium speed — if you feel a bump or tick, pause briefly and let it flutter.",
  ],
  diving_crankbait: [
    "Cast long, hold rod tip down, and reel at a consistent pace.",
    "Banging the bill off bottom structure triggers reaction strikes.",
    "Vary retrieve speed — pause after contacting cover and let it float up.",
    "Keep the rod tip low and pointed at the lure for maximum dive depth.",
    "Contact bottom deliberately — the deflection off rocks and wood triggers bites.",
    "Crank it down, then vary the speed and pause after every deflection.",
    "Long cast, steady crank, and let the bill do the work against the bottom.",
    "Reel it into hard cover — the deflection off rocks, stumps, and gravel is the trigger.",
    "Pause for a half-second after every bottom contact. The float-up pause triggers reaction bites.",
    "Keep the rod low and reel at a pace that keeps the bill digging into the substrate.",
    "Burn it down to depth, then slow-roll it through the target zone along the bottom.",
    "Cast past the target, crank it to depth, and deflect it off anything hard you can find.",
    "Steady crank through rocky bottoms — every deflection off structure is a chance for a bite.",
    "Mix up your reel speed — three fast cranks, then slow it down for two. The change of pace triggers strikes.",
  ],
  jerkbait: [
    "Twitch-twitch-pause. Let the bait hang long enough for fish to commit.",
    "Sharp downward snaps with slack line, then a full pause between moves.",
    "Work it like a wounded baitfish: two snaps, pause, then one quick twitch.",
    "Twitch it over grass or around cover, letting it glide and stall in place.",
    "Vary pause length until fish tell you what cadence they want.",
    "Snap it hard, feed a touch of slack, and let it suspend like a stunned shad.",
    "Two hard twitches, then let it sit for 5-10 seconds. The longer the pause, the bigger the fish.",
    "Sharp downward jerks with a low rod tip. The bait should dart, not slide.",
    "Twitch, pause, twitch. The bait needs to look confused and vulnerable between movements.",
    "Experiment with pause length — start with 2 seconds and go up to 10 until you find the window.",
    "Snap it twice, then dead-stop it. The motionless suspend is what closes the deal.",
    "Erratic cadence — no two twitches should look the same. Dying baitfish are not predictable.",
    "Work it with sharp snaps and plenty of slack. The bait needs room to dart freely.",
    "Light twitches in cold water, aggressive rips in warm water. Match the cadence to fish activity.",
  ],
  spinnerbait: [
    "Slow-roll along the bottom or burn just beneath the surface.",
    "Helicopter the blades down walls of wood or rock structure.",
    "Run it through any break, edge, or inside corner at a steady clip.",
    "Slow-roll over hard bottom — keep the blades ticking through the strike zone.",
    "Cast past cover, reel fast to depth, then slow-roll through the strike zone.",
    "Let it helicopter along vertical structure — fish hit on the fall with tight line.",
    "Bump it off wood, stumps, and laydowns. The deflection triggers reaction bites.",
    "Slow-roll it deep along the bottom, letting the blades vibrate just above the substrate.",
    "Burn it fast just under the surface for aggressive fish chasing baitfish.",
    "Cast tight to cover, let it sink on a tight line, then reel it back through the target.",
    "Vary your retrieve speed from slow to fast until fish commit. The blades adjust automatically.",
    "Keep the rod tip high for shallow running, low for deeper tracking through the zone.",
    "Tick the bottom or bump cover on every cast. The flash and vibration change on contact draws strikes.",
    "Slow-roll near the bottom in cold water, burn it near the surface in warm water.",
  ],
  casting_spoon: [
    "Cast to feeding fish or structure, reel at medium speed with slight rod tip action.",
    "Flutter it down then reel fast — flash triggers reaction bites.",
    "Wobble on a slow reel or jig it lightly for finicky fish.",
    "Cast over schools and reel fast to trigger reaction strikes on the initial drop.",
    "Let it sink to depth, reel a few cranks, let it flutter back down. Repeat.",
    "Fan cast around structure and reel at medium speed with occasional rod drops.",
    "Cast past the target, let it sink, then sweep the rod and let it flutter back.",
    "Vertical jigging in deep water — drop it to the bottom and snap it up repeatedly.",
    "Steady retrieve with occasional pauses. The flutter on the pause is what triggers the bite.",
    "Cast it long and reel at a steady medium clip. The wobble does the work.",
    "Let it free-fall on a semi-tight line. Watch for the line to jump on the drop.",
    "Rip it off the bottom, let it flutter, rip again. The flash-and-fall combination is deadly.",
    "Slow flutter spoon retrieves near the bottom for neutral fish that won't chase.",
    "Cast and count it down to the target depth, then reel steadily with the rod tip low.",
  ],
  shrimp_crab_plastic: [
    "Dead-drop to the bottom, drag slowly, and pause near any cover.",
    "Pitch under mangroves or onto flats edges, drag slowly to the fish.",
    "Ultra-slow drag or dead stick — let the scent and profile do the work.",
    "Pitch ahead of tailing fish, let it sink completely, and wait for the line to move.",
    "Cast to structure, let it sink, then inch it forward with 6-inch drags and long pauses.",
    "Dead stick it on the bottom near cover — fish often pick it up without any rod movement.",
    "Let it sit on the bottom and wait. Move it only if you don't get a bite in 30 seconds.",
    "Under a popping cork, suspend it at the right depth and let the pop draw fish in.",
    "Slow hop along the bottom near oyster bars and grass edges. Pause after every hop.",
    "Pitch to structure, let it fall to the bottom, then barely twitch it in place.",
    "Fish it under a cork with slow pops, or free-line it to the bottom and dead-stick.",
    "Cast ahead of the fish's path, let it sink, and wait for the pickup. Don't move it.",
    "Short slow drags near the bottom with 5-second pauses between moves. Less is more.",
    "Free-line it to the bottom in current and let it drift naturally along the seam.",
  ],
  large_profile_swimbait: [
    "Slow, steady bottom roll — keep the tail kicking consistently.",
    "Glide it through open water or over structure at a deliberate pace.",
    "Slow-roll on a wide-gap hook. Let the body sway naturally.",
    "Cast deep, slow-roll it back on the bottom — let the tail do the work.",
    "Keep it barely moving at depth — big profile fish eat what looks like an easy meal.",
    "Work it along the outside edge of structure at walking pace — one body-length per two cranks.",
    "Slow retrieve near the bottom with occasional pauses to let it glide and stall.",
    "Match the retrieve speed to a real baitfish — not sprinting, just cruising naturally.",
    "Let it sink to the target depth, then reel just fast enough to keep the tail moving.",
    "Slow-roll it past ambush points — beside laydowns, rocks, and drop-offs.",
    "Glide it through deep water near main-lake structure. The profile alone draws attention.",
    "Barely moving at depth is the key. Big fish want an easy meal, not a chase.",
    "Cast parallel to the bank and slow-roll it along the bottom contour.",
    "Dead-slow retrieve through the strike zone. The oversized profile triggers big fish instincts.",
  ],
  streamer_baitfish: [
    "Strip-strip-pause. Vary strip speed until fish commit.",
    "Long, fast strips with occasional pauses — imitate fleeing bait.",
    "Short quick strips near structure, slow down in open water.",
    "Two long strips, pause 2 seconds, then one short strip — vary the cadence.",
    "Fast strips near the surface, slower strips as you count it down to depth.",
    "Mix short and long strips erratically — no consistent cadence. Baitfish are not consistent.",
    "Strip it through the feeding lane with a mix of speeds. Let the fly dart and pause.",
    "Short sharp strips near cover, then let it drift motionless for a beat.",
    "Three fast strips, one slow strip, pause. Change it up until you find the trigger.",
    "Vary your strip length — 6-inch pulls near structure, 18-inch pulls in open water.",
    "Strip it across the current seam and let it swing at the end. Fish eat at the hang.",
    "Fast strips to mimic a fleeing baitfish, or slow strips to imitate a wounded one.",
    "Keep the strips sharp and let the fly dart. The erratic movement triggers predatory instincts.",
    "Two quick strips, dead pause, one long strip. Repeat. The hesitation is the trigger.",
  ],
  streamer_articulated: [
    "Long, aggressive strips to make the fly undulate fully.",
    "Mix strip cadences — big fish often hit on the hesitation.",
    "Dead drift followed by a hard strip — the pause-then-dart is key.",
    "Two hard pulls, hesitate, one more — the articulation needs speed to work.",
    "Fast erratic strips near the bank, then let it swing back through deep water.",
    "Strip hard three times, then let it hang in current for a full 3 seconds before the next set.",
    "Aggressive strips to get the full undulation. This fly needs speed to look alive.",
    "Strip-strip-pause near structure. The size and movement draw fish from a distance.",
    "Let it swing through the run on a tight line, then strip it aggressively at the end.",
    "Hard strips followed by a complete dead stop. The sudden stillness triggers the eat.",
    "Cast tight to the bank, strip it away fast. Big streamers work best fished aggressively.",
    "Mix long sweeping strips with short sharp ones. The articulated body changes action on each pull.",
    "Strip it across current and let it hang broadside in the flow. Fish often eat at the swing.",
    "Fast and aggressive near the bank, slow and deliberate in deep water. Match the context.",
  ],
  topwater_popper_fly: [
    "Hard strip to pop the fly, then a 3-second pause. Repeat.",
    "Pop with authority — let the rings die before the next strip.",
    "Aggressive pops for active fish; slow it down if fish are wary.",
    "One sharp haul-strip to pop, then strip out slack while waiting. Don't rush.",
    "Pop it into position, wait for the surface to settle completely, pop again.",
    "Vary pop intensity — loud hard pops to locate, gentle pops once fish are on the fly.",
    "One strong pop, long pause. Let the surface go completely flat before the next strip.",
    "Quick double-pop, then a dead pause. The second pop often draws the commitment.",
    "Pop it over structure and let it sit motionless until you see a boil or swirl.",
    "Mix aggressive pops with quiet gurgles. Start loud to draw attention, then go subtle.",
    "Pop, wait 5 seconds, pop again. The pause is where the fish makes its decision.",
    "Strip sharply to pop, then let the fly sit completely still. Patience closes the deal.",
    "Work it slowly over the target area with deliberate pops and long pauses between moves.",
    "Pop once near structure, then let it drift naturally on the surface before the next pop.",
  ],
  slider_diver_fly: [
    "Strip and let it dive, pause and let it resurface. Repeat.",
    "Short quick strips to dive, then a pause to float back up.",
    "Vary strip speed — the dive-and-float action triggers subsurface strikes.",
    "Two quick strips to get it under, pause 2 seconds, let it rise, repeat.",
    "Strip aggressively to dive it, then go completely still — the rise triggers the eat.",
    "Medium strips to get it diving, long pause — fish often eat it on the way back up.",
    "Push it under with two strips, then let it float back to the surface. The rise is the trigger.",
    "Dive it under overhanging cover with a sharp strip, then let it pop back up naturally.",
    "Quick strip to dive, slow rise to the surface. Repeat. The up-and-down motion draws fish in.",
    "Strip-strip-pause. The fly dives on the strips and floats back up on the pause.",
    "Work it through the top foot of water — diving and rising like an injured baitfish.",
    "Erratic strips to push it under, followed by a calm float back to the surface.",
    "Strip it under near structure, let it rise next to cover. Fish ambush from below.",
    "Vary the dive depth by changing strip length. Short strips stay shallow, long strips go deeper.",
  ],
  shrimp_fly: [
    "Lead the fish and strip into its path. One or two short strips.",
    "Cast ahead of the fish, let it sink to depth, then short precise strips.",
    "Dead drift in current or short hops in still water.",
    "Lead the fish by 6 feet, let the fly settle, then one short strip as it approaches.",
    "Cast well ahead, mend for natural drift, then a single strip when the fish is close.",
    "Let it sink fully to the bottom, then one slow strip — wait for the take.",
    "Short subtle strips near the bottom. Shrimp don't sprint — keep it slow and natural.",
    "Lead the fish, let the fly sink completely, then give one gentle twitch.",
    "Under a dock or mangrove, let it sink and dead drift. One strip if the fish passes by.",
    "Cast ahead of cruising fish, let it settle to the bottom, and wait for the eat.",
    "Tiny hops along the bottom — short 2-inch strips with pauses between each one.",
    "Dead drift it through the feeding lane in moving water. Add a strip only near the end.",
    "Let it sink to the bottom and sit. One strip when the fish is within 3 feet.",
    "Short slow strips that barely move the fly. Shrimp drift more than they swim.",
  ],
  crab_fly: [
    "Lead the fish by 6 feet, let it sink, and give a slow single strip when in range.",
    "Cast ahead of a tailing fish, let the fly sink, and wait for the eat.",
    "Slow drag along the bottom — resist the urge to over-strip.",
    "Put it down and leave it alone — tailing fish will find it.",
    "One cast, let it sink completely, then never move it until the fish is on it.",
    "Cast past the tailing fish, strip it into position, then freeze. Wait for the line to pull.",
    "Let it sit motionless on the bottom. Crabs don't swim — they sit still.",
    "Lead the fish generously, let it sink, and wait. Movement scares more fish than it attracts.",
    "Dead bottom — no strips. The fly should just sit there like a real crab would.",
    "Cast well ahead, let it settle completely, and watch for the fish to tip down on it.",
    "One tiny strip to get the fish's attention, then freeze. Let it eat on its own terms.",
    "Cast past the target, strip into position, then stop all movement. Watch for the head-down eat.",
    "Place it on the bottom in the fish's path and do absolutely nothing. Patience is everything.",
    "The hardest part is doing nothing. Cast it, let it sink, and wait for the tip of the rod to load.",
  ],
  leech_worm_fly: [
    "Long, slow pulls on the swing. Pause between strips.",
    "Dead drift or slow swing with occasional short strips.",
    "Slow to medium strip retrieve with pauses — the wiggle does the work.",
    "Let it swing on a tight line, then hand-twist it back through slow water.",
    "Single slow strips with a 3-second hand-pause — the natural movement is the trigger.",
    "Swing through the run, then let it dangle at the end of the swing before recasting.",
    "Slow strips with long pauses. The marabou or rabbit breathes on the pause and that is the trigger.",
    "Dead drift it through the run, then let it swing below you and strip it back slowly.",
    "Hand-twist retrieve through slow water. Keep it moving just enough to pulse the materials.",
    "Swing it through the seam, let it hang at the end, then slow-strip it back. Fish eat at every stage.",
    "Long deliberate strips with a full pause between each one. The fly moves naturally on its own.",
    "Let it swing through the run and dangle below you for 5 seconds before picking up.",
    "Slow retrieve with tiny rod-tip twitches to add life to the materials. Don't rush it.",
    "Dead drift it deep, then strip it up through the water column. Trout eat it on the rise.",
  ],

  // ── New lure families ─────────────────────────────────────────────────────

  ned_rig: [
    "Drag it slowly across the bottom — shake the rod tip to add subtle vibration.",
    "Light rod-tip shakes while dragging. Keep it on or near the bottom at all times.",
    "Cast to structure, let it sink, then micro-shake and drag. Pause after every 2 feet.",
    "Dead-slow drag with constant bottom contact. Tiny rod tip twitches keep the tail moving.",
    "Let it sit after the cast for 5 seconds, then drag a foot and pause. Repeat.",
    "Shake-drag-pause on the bottom. The subtle movement is what sells it — don't overwork it.",
    "Barely move it along the bottom. A few inches of drag, then a long pause.",
    "Light rod-tip shakes in place for 5-10 seconds, then drag forward one foot. Repeat.",
    "Cast to a hard spot, let it sink to the bottom, and shake it in place without dragging.",
    "Micro-hops along the bottom — just enough movement to keep the tail quivering.",
    "Shake it on the bottom near structure. When you drag, move it no more than 6 inches at a time.",
    "Let it sit motionless after the cast, then shake gently in place. Less movement catches more fish.",
    "Drag-pause-shake. The combination of subtle movement and stillness triggers cautious fish.",
    "Keep it on the bottom at all times. The moment it lifts off the substrate, you lose the bite.",
  ],
  drop_shot: [
    "Drop the weight to the bottom and shake the bait in place with light rod-tip action.",
    "Hold the weight on bottom, twitch the rod tip to make the bait dance above.",
    "Shake in place, then drag the weight a foot and shake again. Keep the bait off bottom.",
    "Let the sinker sit on bottom — all the action comes from shaking the rod tip.",
    "Vertical over structure: lower to depth and shake in place. Move only when fish aren't there.",
    "Cast out, let it sink, shake 5-10 seconds in place, drag a foot, repeat.",
    "Light rod-tip shakes to make the bait quiver above the bottom. Don't move the weight.",
    "Shake it in place near structure until a fish commits. Be patient — they are watching.",
    "Vertical presentation: lower to the target depth and shake with the lightest rod-tip action possible.",
    "Cast to a spot, let the weight hit bottom, then shake the bait suspended above it.",
    "Barely move the rod tip — just enough to make the bait twitch. Subtlety catches fish here.",
    "Drag the weight slowly along the bottom, pausing to shake in place every few feet.",
    "Nose-hook the bait for maximum action. Light shakes make it dart and dance above the weight.",
    "Keep the weight on the bottom and let the bait hover. All the work happens at the rod tip.",
  ],
  blade_bait: [
    "Snap the rod tip up sharply, let it flutter back down on a tight line.",
    "Vertical jigging: lift 1-2 feet, let it fall, strike on the drop.",
    "Rip-and-drop — snap it off the bottom and follow it back with the rod tip.",
    "Lift sharply, then control the fall on semi-slack. Most bites happen on the flutter.",
    "Short vertical snaps directly below the boat — keep it tight to structure.",
    "Snap-jigging: sharp upward pop, controlled fall, repeat. Watch the line for ticks.",
    "Vertical lift-and-drop over deep structure. Keep the snaps short and controlled.",
    "Snap it up one to two feet, then follow it back down with the rod tip. Set on any tick.",
    "Rip it off the bottom and let it vibrate on the fall. The flutter is the entire presentation.",
    "Short sharp snaps near the bottom. The vibration on the lift draws fish, the fall gets the bite.",
    "Vertical presentation is best — drop it straight down and snap-jig in place.",
    "Lift sharply, feel for the vibration, let it flutter back down. Stay tight to the line on the fall.",
    "Cast it out and let it sink to the bottom, then snap-jig it back with lift-and-drop retrieves.",
    "Keep snaps tight and controlled — 12 to 18 inches of lift, then controlled flutter back down.",
  ],
  buzzbait: [
    "Start reeling the second it hits water — keep the blade churning on the surface.",
    "Fast retrieve to keep it on top. Don't let it sink or the blade stops.",
    "Burn it across the surface over grass and cover — fast and loud.",
    "Reel fast enough to keep the blade breaking the surface. Speed is everything.",
    "Cast past the target, reel fast to get it on plane, then run it right over the cover.",
    "Keep steady fast speed — the blade needs to churn continuously to work.",
    "The moment it hits the water, start reeling. The blade must stay on the surface at all times.",
    "Burn it along grass edges, laydowns, and shoreline cover. Fish blow up from below.",
    "Reel fast and steady — the clacking blade on the surface is the entire presentation.",
    "Cast tight to cover and burn it past every laydown, dock, and grass edge you can reach.",
    "Speed is key — if the blade stops spinning, you are going too slow.",
    "Run it right over the thickest cover you can find. The commotion draws fish from deep.",
    "Cast parallel to the bank and burn it across every likely ambush point at full speed.",
    "Keep the rod tip high and reel fast. The louder and faster, the better for dirty water.",
  ],
  swim_jig: [
    "Swim it through grass tops at a steady pace, letting the skirt pulse.",
    "Tick the tops of vegetation — the deflection triggers reaction bites.",
    "Steady retrieve through cover, varying speed to bump grass and wood.",
    "Reel it through the upper canopy of grass — bump and go, bump and go.",
    "Cast over grass beds, reel steadily just above the cover line.",
    "Swim it through any laydown or grass edge — the weedless head lets you go right through.",
    "Steady reel through vegetation with the rod tip at 10 o'clock. Bump everything in your path.",
    "Cast to the back of grass pockets and swim it out through the cover.",
    "Reel it at a pace that keeps the skirt pulsing naturally. Not too fast, not too slow.",
    "Tick grass, bump wood, and deflect off structure. Every contact point is a bite opportunity.",
    "Swim it parallel to the grass line, ticking the edge of the cover on every cast.",
    "Steady retrieve with occasional rod-tip twitches to change the skirt action.",
    "Fish it through any cover you would throw a spinnerbait, but with a more natural profile.",
    "Reel it through thick cover at a steady clip — the weedless design lets you go where others can't.",
  ],
  bucktail_jig: [
    "Sweep the rod and let the hair pulse in the current, then drop it back.",
    "Cast up-current, let it swing through the strike zone, jig on the drop.",
    "Slow bounce along the bottom with sweeping rod movements — the hair does the work.",
    "Cast to structure, let it sink, then sweep-and-drop through the zone.",
    "Jig it in the current — the bucktail breathes on the fall and that triggers the eat.",
    "Sweep across and downstream, let the current push the hair profile, jig on each pause.",
    "Cast into the current and let it sweep through the strike zone naturally.",
    "Bounce it along the bottom near structure — the hair pulsing on each drop is the trigger.",
    "Reel it slowly through current seams, letting the bucktail breathe and pulse with each sweep.",
    "Cast past the structure, let it sink, then sweep-jig it back through the target zone.",
    "Slow sweep-and-drop near jetties, bridges, and channel edges. Cover the water column.",
    "Let it swing through the current on a tight line, then jig it on the drop at the end.",
    "Fan-cast and jig it back along the bottom with sweeping rod movements.",
    "Work it through structure with a slow bounce retrieve. The hair does all the work on the fall.",
  ],
  wacky_rig: [
    "Cast to the target and let it fall on completely slack line. Watch for the twitch.",
    "Free-fall is everything — slack line, let it shimmy down. Strikes happen on the drop.",
    "Cast, let it sink on slack, twitch once, let it fall again. Repeat until you are deep.",
    "Skip it under docks and let it fall freely — don't impart any action on the initial drop.",
    "Slack-line fall. One light twitch at mid-depth, then let it continue sinking.",
    "Let the worm do all the work — the horizontal shimmy on the fall is the whole presentation.",
    "Cast to a dock, seawall, or laydown and let it sink on a completely slack line.",
    "Don't touch it on the initial fall. Just watch the line for any movement or twitch.",
    "Free-fall to the bottom, one light twitch, then let it fall again. Repeat all the way down.",
    "Skip it far under docks and let it shimmy down on slack line. Strikes are subtle — watch the line.",
    "The slower it falls, the better. Keep the line slack and let gravity do the work.",
    "One gentle twitch at mid-depth, then let it continue its free-fall to the bottom.",
    "Cast to shade, cover, or structure and let it sink naturally. The worm does all the work.",
    "Slack line is critical. Any tension on the line kills the natural shimmy that triggers bites.",
  ],
  topwater_prop: [
    "Short twitches with long pauses — let the prop blades create disturbance.",
    "Twitch-twitch, then dead pause for 3-5 seconds. The prop sputters and stops.",
    "Work it slow — one pop, long wait. Let the ripples die before the next twitch.",
    "Twitch it once sharply, then let it sit completely still. The prop churn is the trigger.",
    "Short sharp twitches to activate the props, then a dead-stick pause over the target.",
    "Slow twitching near cover — the prop noise draws fish from deeper than you would expect.",
    "One quick twitch to spin the props, then wait for the water to go still. Repeat.",
    "Short twitches with 5-second pauses. The sputtering props and long silences draw fish in.",
    "Pop the props once, let it sit, pop again. The noise-then-silence cadence is the trigger.",
    "Work it slowly over likely ambush points. One twitch, long pause, one twitch, long pause.",
    "Twitch it just enough to activate the prop blades, then let it sit completely motionless.",
    "Slow and steady near structure — the intermittent prop noise calls fish from a distance.",
    "One sharp pop to create the disturbance, then don't touch it until the ripples disappear.",
    "Walk it slowly with prop sputters between each twitch. The combination of walk and churn is deadly.",
  ],

  // ── New fly families ──────────────────────────────────────────────────────

  crawfish_streamer: [
    "Short strips along the bottom with full pauses — crawfish don't swim far.",
    "Hop-strip it on the bottom: short pull, let it settle, repeat.",
    "Crawl it along rocky substrate — two-inch strips with a 3-second dead pause.",
    "Let it sink completely, then short aggressive strips to mimic a fleeing crawfish.",
    "Bottom-contact strips — drag, pause, twitch. Keep the fly on or near the rocks.",
    "Dead drift it into the zone, then short strip-strip-pause to trigger the strike.",
    "Short hops along the bottom with full pauses between. Keep it tight to the substrate.",
    "Let it settle on the bottom, then pop it up with a quick strip and let it drop back down.",
    "Crawfish scoot, they don't swim. Keep strips short and let the fly settle between each move.",
    "Hop it through rocky runs with 2-inch strips and 3-second pauses. Stay on the bottom.",
    "Dead drift it through the seam, then short-strip it across the bottom on the swing.",
    "Tiny strips along the bottom — barely enough to move the fly. Crawfish move slowly.",
    "Strip it once to get the fish's attention, then let it sit on the bottom and wait.",
    "Short aggressive strip to mimic a fleeing crawfish, then dead pause for 5 seconds.",
  ],
  sand_eel_fly: [
    "Long, fast strips without pause — sand eels don't stop moving.",
    "Continuous stripping at a fast pace. Keep the fly moving through the school.",
    "Strip fast and steadily — no pauses. Match the bait's constant motion.",
    "Fast hand-over-hand strips. Keep the fly racing through the strike zone.",
    "Long aggressive strips in quick succession — imitate a fleeing sand eel.",
    "Fast strip all the way back to the rod tip — don't slow down or pause.",
    "Nonstop fast strips from the moment the fly lands until you pick up to recast.",
    "Keep it moving — sand eels never stop. Strip at a pace that matches a fleeing baitfish.",
    "Long fast pulls without any hesitation. The fly should never sit still in the water.",
    "Strip as fast as you can maintain — the speed imitates fleeing bait that predators chase.",
    "Continuous retrieve with long strips. Don't pause or slow down for any reason.",
    "Fast and aggressive all the way back. Sand eels move fast and so should your fly.",
    "Hand-over-hand stripping at speed. Keep the rod tip low and the line tight.",
    "Strip it through the school at full speed — fish will eat the one that looks like it is trying to escape.",
  ],
  gold_spoon: [
    "Steady retrieve across the flat — let the wobble do the work.",
    "Slow, steady reel across shallow grass. Pause when you feel a bump.",
    "Keep it ticking the top of the grass and let the flash draw fish in.",
    "Fan-cast the flat with a medium retrieve. Speed up on follows.",
    "Slow-roll it just above the bottom, then speed up near potholes and edges.",
    "Weedless spoon over grass — bump it off stems for a reaction strike.",
    "Cast across the flat and reel at a steady medium pace. The wobble does the work.",
    "Tick the top of the grass with every retrieve. The deflection triggers reaction bites.",
    "Fan-cast the flat and cover water. The flash draws fish from a distance.",
    "Reel at a steady pace just above the grass tops. Speed up near potholes and drop-offs.",
    "Let the spoon wobble naturally — don't add any rod-tip action. The design is the presentation.",
    "Cast to muddy spots, potholes, and grass edges where fish are ambushing bait.",
    "Slow-roll it across the flat for neutral fish. Speed it up when you see tailing activity.",
    "Fan-cast and retrieve at a pace that keeps the spoon ticking the grass without hanging up.",
  ],
  topwater_plug: [
    "Walk-the-dog across the surface at dawn — pause near structure and edges.",
    "Short twitches with long pauses next to mangroves and dock lights.",
    "Slow walking retrieve along shorelines and drop-offs at first light.",
    "Pop and pause near structure. Let the rings settle before the next twitch.",
    "Walk it across the flat at a moderate pace. Speed up if fish are blowing up.",
    "Work it tight to mangroves and seawalls — quiet twitches draw snook out.",
    "Walk it slowly past docks, mangroves, and shoreline structure. Pause at every likely ambush spot.",
    "Dawn and dusk are prime windows. Walk it slowly across the surface near structure.",
    "Short twitches near mangrove roots and dock pilings. The quiet pop draws fish from cover.",
    "Walk it across the surface with a steady cadence. Pause next to any shadow or structure.",
    "Pop it once near a mangrove root, then let it sit for 5 seconds before the next twitch.",
    "Slow walking retrieve at first light along the bank. Cover the shoreline methodically.",
    "Cast tight to structure and work it back with short twitches and long pauses.",
    "Walk it across the flat and speed up the cadence when you see fish blowing up on bait.",
  ],
  soft_jerkbait_coastal: [
    "Twitch-twitch-pause on a light jighead. Let it sink between twitches.",
    "Slow jerk-and-pause retrieve — imitate a stunned mullet drifting in current.",
    "Work it through the water column with a slow twitch and long pause.",
    "Cast to structure, let it sink, then twitch it back with erratic pauses.",
    "Light jighead, slow fall, darting twitches — let fish eat on the pause.",
    "Jerk it two or three times, then let it suspend. Most strikes come on the drop.",
    "Twitch it near docks and mangroves — the darting action imitates a fleeing mullet.",
    "Let it sink on a light jighead, then twitch-pause back through the zone.",
    "Cast past the target, let it sink to depth, then jerk it erratically through the strike zone.",
    "Short twitches near structure with long pauses between. The pause is the bite window.",
    "Work it like a wounded baitfish — erratic twitches, long pauses, and a slow sinking fall.",
    "Cast to current seams and dock lights. Twitch twice, let it drift, twitch again.",
    "Slow fall on a light jighead is the key. Twitch it just enough to dart, then let it drop.",
    "Fish it near the bottom around structure with short jerks and dead pauses between.",
  ],
};
