-- Seed species_aliases with slang, regional names, and short-forms that
-- anglers actually say or type. Each alias maps to one canonical species.
-- Where the same alias is used regionally for different species (e.g.,
-- "redeye" is Redeye Bass in the South and slang for Rock Bass in some
-- areas), we attach it to both with different weights — the voice parser
-- picks the highest-weight match, or surfaces ambiguity to the user.
--
-- Idempotent via the existing unique(species_id, normalized_alias) index.

insert into public.species_aliases (species_id, alias_text, weight)
values
  -- ============================================================
  -- bass
  -- ============================================================
  ('largemouth_bass',     'largemouth',           100),
  ('largemouth_bass',     'lmb',                  100),
  ('largemouth_bass',     'largie',                95),
  ('largemouth_bass',     'bucketmouth',           90),
  ('largemouth_bass',     'green bass',            80),
  ('largemouth_bass',     'hawg',                  70),
  ('largemouth_bass',     'bass',                  60),
  ('smallmouth_bass',     'smallmouth',           100),
  ('smallmouth_bass',     'smb',                  100),
  ('smallmouth_bass',     'smallie',               95),
  ('smallmouth_bass',     'bronze bass',           85),
  ('smallmouth_bass',     'brown bass',            80),
  ('smallmouth_bass',     'bronzeback',            85),
  ('spotted_bass',        'spotted',              100),
  ('spotted_bass',        'kentucky bass',         95),
  ('spotted_bass',        'kentucky spotted',      90),
  ('spotted_bass',        'spot',                  70),
  ('florida_bass',        'florida largemouth',   100),
  ('florida_bass',        'florida-strain',        90),
  ('florida_bass',        'florida lmb',           95),
  ('alabama_bass',        'alabama spotted',       95),
  ('alabama_bass',        'al bass',               80),
  ('shoal_bass',          'shoalie',               90),
  ('redeye_bass',         'redeye',                95),
  ('redeye_bass',         'red eye bass',          90),
  ('guadalupe_bass',      'texas bass',            70),
  ('guadalupe_bass',      'guadalupe',            100),
  ('suwannee_bass',       'suwannee',             100),
  ('choctaw_bass',        'choctaw',              100),
  ('meanmouth_bass',      'meanmouth',            100),

  -- ============================================================
  -- panfish
  -- ============================================================
  ('bluegill',            'bream',                 95),
  ('bluegill',            'brim',                  85),
  ('bluegill',            'sunny',                 75),
  ('bluegill',            'gill',                  90),
  ('bluegill',            'sunfish',               60),
  ('bluegill',            'panfish',               50),
  ('redear_sunfish',      'shellcracker',          95),
  ('redear_sunfish',      'redear',                95),
  ('redear_sunfish',      'cherry gill',           70),
  ('redear_sunfish',      'stumpknocker',          60),
  ('pumpkinseed',         'punkie',                85),
  ('pumpkinseed',         'pond perch',            70),
  ('rock_bass',           'goggleeye',             85),
  ('rock_bass',           'rocky',                 75),
  ('rock_bass',           'redeye',                60),
  ('green_sunfish',       'green sunny',           85),
  ('green_sunfish',       'rubbertail',            70),
  ('redbreast_sunfish',   'redbreast',            100),
  ('redbreast_sunfish',   'sun perch',             75),
  ('redbreast_sunfish',   'robin',                 60),
  ('longear_sunfish',     'longear',              100),
  ('warmouth',            'warmouth perch',        95),
  ('warmouth',            'goggleeye',             70),
  ('warmouth',            'mud bass',              65),
  ('hybrid_bluegill',     'hybrid bream',          95),
  ('hybrid_bluegill',     'hybrid sunny',          85),
  ('spotted_sunfish',     'spotted',               80),
  ('spotted_sunfish',     'stumpknocker',          75),
  ('sacramento_perch',    'sac perch',             95),
  ('flier',               'flier',                100),
  ('coppernose_bluegill', 'coppernose',           100),
  ('coppernose_bluegill', 'copperhead bream',      80),

  -- ============================================================
  -- crappie
  -- ============================================================
  ('black_crappie',       'crappie',               90),
  ('black_crappie',       'black specks',          95),
  ('black_crappie',       'specks',                80),
  ('black_crappie',       'speck',                 75),
  ('black_crappie',       'papermouth',            80),
  ('black_crappie',       'slab',                  75),
  ('black_crappie',       'sac-a-lait',            80),
  ('black_crappie',       'calico',                70),
  ('white_crappie',       'crappie',               90),
  ('white_crappie',       'white specks',          95),
  ('white_crappie',       'papermouth',            80),
  ('white_crappie',       'sac-a-lait',            80),
  ('white_crappie',       'speckled crappie',      75),
  ('magnolia_crappie',    'magnolia',             100),
  ('magnolia_crappie',    'hybrid crappie',        85),
  ('blacknose_crappie',   'blacknose',            100),
  ('blacknose_crappie',   'blackstripe crappie',   90),

  -- ============================================================
  -- walleye_perch
  -- ============================================================
  ('walleye',             'eyes',                  85),
  ('walleye',             'walter',                75),
  ('walleye',             'marble eye',            70),
  ('walleye',             'jack salmon',           60),
  ('walleye',             'walleyed pike',         70),
  ('yellow_perch',        'perch',                 90),
  ('yellow_perch',        'ringed perch',          80),
  ('yellow_perch',        'jack perch',            70),
  ('yellow_perch',        'lake perch',            75),
  ('sauger',              'sand pike',             85),
  ('saugeye',             'walleye-sauger hybrid', 80),

  -- ============================================================
  -- pike_muskie
  -- ============================================================
  ('northern_pike',       'pike',                 100),
  ('northern_pike',       'jack',                  75),
  ('northern_pike',       'jackfish',              85),
  ('northern_pike',       'snake',                 70),
  ('northern_pike',       'hammer handle',         70),
  ('northern_pike',       'water wolf',            65),
  ('northern_pike',       'gator',                 60),
  ('muskellunge',         'musky',                100),
  ('muskellunge',         'muskie',               100),
  ('muskellunge',         'lunge',                 80),
  ('chain_pickerel',      'pickerel',              90),
  ('chain_pickerel',      'jack pickerel',         80),
  ('chain_pickerel',      'chain',                 75),
  ('chain_pickerel',      'eastern pickerel',      80),
  ('tiger_muskie',        'tiger',                 90),
  ('tiger_muskie',        'tiger pike',            85),
  ('redfin_pickerel',     'redfin',               100),
  ('grass_pickerel',      'grass jack',            85),
  ('grass_pickerel',      'mud pickerel',          80),

  -- ============================================================
  -- catfish
  -- ============================================================
  ('channel_catfish',     'channel cat',          100),
  ('channel_catfish',     'channel',               90),
  ('channel_catfish',     'fiddler',               75),
  ('blue_catfish',        'blue cat',             100),
  ('blue_catfish',        'blue',                  90),
  ('blue_catfish',        'high finned blue',      75),
  ('blue_catfish',        'humpback blue',         70),
  ('flathead_catfish',    'flathead',             100),
  ('flathead_catfish',    'mud cat',               85),
  ('flathead_catfish',    'shovelhead',            80),
  ('flathead_catfish',    'yellow cat',            85),
  ('flathead_catfish',    'app cat',               65),
  ('yellow_bullhead',     'yellow bull',           95),
  ('yellow_bullhead',     'yellow horned pout',    80),
  ('brown_bullhead',      'brown bull',            95),
  ('brown_bullhead',      'horned pout',           85),
  ('black_bullhead',      'black bull',            95),
  ('black_bullhead',      'bullhead',              80),
  ('white_catfish',       'white cat',            100),
  ('white_catfish',       'forked tail bullhead',  70),

  -- ============================================================
  -- striped_white_bass
  -- ============================================================
  ('striped_bass',        'striper',              100),
  ('striped_bass',        'rockfish',              90),
  ('striped_bass',        'linesider',             85),
  ('striped_bass',        'striped',               90),
  ('hybrid_striped_bass', 'wiper',                100),
  ('hybrid_striped_bass', 'hybrid striper',        95),
  ('hybrid_striped_bass', 'sunshine bass',         90),
  ('hybrid_striped_bass', 'palmetto bass',         90),
  ('white_bass',          'silver bass',           90),
  ('white_bass',          'sand bass',             85),
  ('yellow_bass',         'yellow',                70),
  ('yellow_bass',         'barfish',               75),
  ('white_perch',         'silver perch',          80),

  -- ============================================================
  -- gar_bowfin
  -- ============================================================
  ('alligator_gar',       'gator gar',            100),
  ('alligator_gar',       'alligator',             85),
  ('bowfin',              'dogfish',               80),
  ('bowfin',              'mudfish',               90),
  ('bowfin',              'grinnel',               90),
  ('bowfin',              'cypress trout',         70),
  ('bowfin',              'choupique',             85),
  ('longnose_gar',        'longnose',             100),
  ('longnose_gar',        'longjaw',               80),
  ('spotted_gar',         'spotty gar',            85),
  ('shortnose_gar',       'shortnose',            100),
  ('florida_gar',         'florida',               80),

  -- ============================================================
  -- cichlid
  -- ============================================================
  ('peacock_bass',        'peacock',              100),
  ('peacock_bass',        'butterfly peacock',     95),
  ('peacock_bass',        'pavon',                 80),
  ('mayan_cichlid',       'mayan',                100),
  ('mayan_cichlid',       'atomic sunfish',        75),
  ('blue_tilapia',        'tilapia',               80),
  ('oscar',               'oscar fish',            95),
  ('mozambique_tilapia',  'mozambique',           100),
  ('redbelly_tilapia',    'redbelly',             100),
  ('jaguar_guapote',      'jaguar',                95),
  ('jaguar_guapote',      'guapote',              100),

  -- ============================================================
  -- trout_char
  -- ============================================================
  ('rainbow_trout',       'rainbow',              100),
  ('rainbow_trout',       'bow',                   80),
  ('rainbow_trout',       'rainbow t',             70),
  ('brown_trout',         'brown',                100),
  ('brown_trout',         'german brown',          85),
  ('brown_trout',         'loch leven',            70),
  ('brook_trout',         'brookie',              100),
  ('brook_trout',         'brook',                 90),
  ('brook_trout',         'speckled trout',        80),
  ('brook_trout',         'square tail',           70),
  ('brook_trout',         'speck',                 60),
  ('steelhead',           'steelie',              100),
  ('steelhead',           'steel',                 90),
  ('steelhead',           'sea-run rainbow',       75),
  ('lake_trout',          'laker',                100),
  ('lake_trout',          'mac',                   85),
  ('lake_trout',          'mackinaw',              95),
  ('lake_trout',          'gray trout',            75),
  ('lake_trout',          'togue',                 85),
  ('cutthroat_trout',     'cutty',                100),
  ('cutthroat_trout',     'cutt',                  85),
  ('cutthroat_trout',     'native trout',          70),
  ('tiger_trout',         'tiger',                 75),
  ('bull_trout',          'bull',                  95),
  ('splake',              'splake',               100),
  ('dolly_varden',        'dolly',                100),
  ('mountain_whitefish',  'whitefish',             90),
  ('mountain_whitefish',  'mountain whitey',       85),
  ('mountain_whitefish',  'rocky mountain whitefish', 80),
  ('golden_trout',        'golden',                95),
  ('arctic_char',         'char',                  90),
  ('arctic_char',         'arctic',                75),

  -- ============================================================
  -- salmon
  -- ============================================================
  ('chinook_salmon',      'king',                 100),
  ('chinook_salmon',      'king salmon',          100),
  ('chinook_salmon',      'tyee',                  85),
  ('chinook_salmon',      'spring salmon',         80),
  ('coho_salmon',         'silver',                90),
  ('coho_salmon',         'silver salmon',        100),
  ('coho_salmon',         'coho',                 100),
  ('sockeye_salmon',      'red',                   75),
  ('sockeye_salmon',      'red salmon',            95),
  ('sockeye_salmon',      'sockeye',              100),
  ('sockeye_salmon',      'blueback',              80),
  ('atlantic_salmon',     'atlantic',              90),
  ('atlantic_salmon',     'salmo salar',           70),
  ('kokanee',             'koke',                 100),
  ('kokanee',             'kickaninny',            70),
  ('landlocked_atlantic_salmon', 'landlocked salmon', 100),
  ('landlocked_atlantic_salmon', 'sebago salmon',  90),
  ('landlocked_atlantic_salmon', 'ouananiche',     80),
  ('pink_salmon',         'humpy',                100),
  ('pink_salmon',         'humpback',              85),
  ('pink_salmon',         'pink',                  95),
  ('chum_salmon',         'dog salmon',            95),
  ('chum_salmon',         'keta',                  80),
  ('chum_salmon',         'chum',                 100),

  -- ============================================================
  -- carp_roughfish
  -- ============================================================
  ('common_carp',         'carp',                  90),
  ('common_carp',         'german carp',           80),
  ('common_carp',         'european carp',         75),
  ('grass_carp',          'grass',                 75),
  ('grass_carp',          'amur',                  85),
  ('grass_carp',          'white amur',            90),
  ('freshwater_drum',     'drum',                  95),
  ('freshwater_drum',     'sheepshead',            70),
  ('freshwater_drum',     'gaspergou',             80),
  ('smallmouth_buffalo',  'small buffalo',         85),
  ('smallmouth_buffalo',  'razorback',             75),
  ('bigmouth_buffalo',    'big buffalo',           85),
  ('bigmouth_buffalo',    'gourdhead',             70),
  ('white_sucker',        'sucker',                85),
  ('white_sucker',        'common white sucker',   75),
  ('redhorse_sucker',     'redhorse',             100),
  ('mirror_carp',         'mirror',                90),
  ('bighead_carp',        'bighead',              100),
  ('bighead_carp',        'big head',              85),
  ('silver_carp',         'silver',                75),
  ('silver_carp',         'flying carp',           90),
  ('black_buffalo',       'black buff',            90),
  ('goldfish',            'goldie',                90),
  ('black_carp',          'mussel cracker',        70),
  ('northern_hogsucker',  'hog sucker',            95),
  ('northern_hogsucker',  'hognose',               80),
  ('koi',                 'koi carp',              90),
  ('leather_carp',        'leather',               90),

  -- ============================================================
  -- saltwater_inshore
  -- ============================================================
  ('redfish',             'red drum',             100),
  ('redfish',             'channel bass',          85),
  ('redfish',             'red',                   80),
  ('redfish',             'spottail',              80),
  ('redfish',             'puppy drum',            85),
  ('redfish',             'bull red',              90),
  ('speckled_trout',      'speck',                100),
  ('speckled_trout',      'spotted seatrout',      95),
  ('speckled_trout',      'sea trout',             85),
  ('speckled_trout',      'specks',                90),
  ('speckled_trout',      'trout',                 60),
  ('snook',               'linesider',             80),
  ('snook',               'sergeant fish',         70),
  ('snook',               'robalo',                85),
  ('sheepshead',          'sheep',                 90),
  ('sheepshead',          'convict fish',          85),
  ('black_drum',          'black',                 70),
  ('black_drum',          'big black',             75),
  ('black_drum',          'old drum',              75),
  ('summer_flounder',     'fluke',                100),
  ('summer_flounder',     'flounder',              80),
  ('summer_flounder',     'summer fluke',          90),
  ('tarpon',              'silver king',           95),
  ('tarpon',              'poon',                  90),
  ('bluefish',            'blue',                  85),
  ('bluefish',            'choppers',              90),
  ('bluefish',            'snappers',              70),
  ('bluefish',            'tailor',                75),
  ('spanish_mackerel',    'spanish',               95),
  ('spanish_mackerel',    'mac',                   75),
  ('spanish_mackerel',    'mackerel',              80),
  ('mangrove_snapper',    'mangrove',             100),
  ('mangrove_snapper',    'gray snapper',          90),
  ('mangrove_snapper',    'black snapper',         75),
  ('cobia',               'lemon fish',            85),
  ('cobia',               'crab eater',            75),
  ('cobia',               'ling',                  80),
  ('pompano',             'pomp',                  90),
  ('pompano',             'florida pompano',       95),
  ('weakfish',            'weakie',                95),
  ('weakfish',            'sea trout',             70),
  ('weakfish',            'gray trout',            85),
  ('weakfish',            'tiderunner',            80),
  ('southern_flounder',   'flounder',              70),
  ('southern_flounder',   'doormat',               80),
  ('crevalle_jack',       'jack',                  90),
  ('crevalle_jack',       'jack crevalle',        100),
  ('permit',              'palometa',              80),
  ('bonefish',            'bone',                  95),
  ('bonefish',            'gray ghost',            80),
  ('atlantic_croaker',    'croaker',              100),
  ('atlantic_croaker',    'hardhead',              80),
  ('ladyfish',            'lady',                  85),
  ('ladyfish',            'ten pounder',           90),
  ('ladyfish',            'skipjack',              70),
  ('false_albacore',      'fat albert',            85),
  ('false_albacore',      'albie',                100),
  ('false_albacore',      'little tunny',          95),
  ('false_albacore',      'bonita',                75),
  ('winter_flounder',     'blackback',             95),
  ('winter_flounder',     'lemon sole',            85),
  ('southern_kingfish',   'whiting',               95),
  ('southern_kingfish',   'sea mullet',            80),
  ('southern_kingfish',   'king whiting',          85),
  ('spadefish',           'spade',                 85),
  ('gray_triggerfish',    'trigger',               90),
  ('atlantic_bonito',     'bonito',                95),
  ('atlantic_bonito',     'bonita',                85),

  -- ============================================================
  -- sturgeon_paddlefish
  -- ============================================================
  ('white_sturgeon',      'white sturg',           80),
  ('lake_sturgeon',       'lake sturg',            80),
  ('lake_sturgeon',       'rock sturgeon',         70),
  ('paddlefish',          'spoonbill',             95),
  ('paddlefish',          'spoonbill cat',         80),
  ('shortnose_sturgeon',  'shortnose sturg',       80),
  ('atlantic_sturgeon',   'atlantic sturg',        80),
  ('gulf_sturgeon',       'gulf sturg',            80),

  -- ============================================================
  -- shad_herring
  -- ============================================================
  ('american_shad',       'shad',                  90),
  ('american_shad',       'white shad',            85),
  ('american_shad',       'atlantic shad',         80),
  ('american_shad',       'common shad',           75),
  ('hickory_shad',        'hickory',               90),
  ('hickory_shad',        'hickory jack',          80),
  ('rainbow_smelt',       'smelt',                 95),
  ('alewife',             'sawbelly',              90),
  ('alewife',             'gray herring',          80),
  ('blueback_herring',    'blueback',              90),
  ('blueback_herring',    'glut herring',          75),

  -- ============================================================
  -- other_freshwater
  -- ============================================================
  ('northern_snakehead',  'snakehead',             95),
  ('northern_snakehead',  'frankenfish',           85),
  ('northern_snakehead',  'channa',                70),
  ('burbot',              'lawyer',                90),
  ('burbot',              'eelpout',               90),
  ('burbot',              'cusk',                  85),
  ('burbot',              'ling',                  70),
  ('american_eel',        'eel',                   95),
  ('bullseye_snakehead',  'bullseye',              95),
  ('bullseye_snakehead',  'florida snakehead',     90),
  ('mooneye',             'toothed herring',       80),
  ('fallfish',            'silverside',            70),
  ('fallfish',            'corporal',              75)
on conflict (species_id, normalized_alias) do nothing;
