-- Seed fly_aliases with short-forms ("PT", "BWO", "EHC"), misspellings
-- ("woolly" vs "wooly bugger"), regional names, and common variants
-- (bead-head versions resolved to base pattern). Powers voice parsing
-- and typeahead.

insert into public.fly_aliases (fly_id, alias_text, weight)
select fc.id, na.alias_text, na.weight
from public.fly_catalog fc
join (values
  -- ============================================================
  -- dry_fly
  -- ============================================================
  ('Adams'::text,                          'adams dry'::text,             95::int),
  ('Parachute Adams',                      'parachute',                   80),
  ('Parachute Adams',                      'para adams',                  90),
  ('Blue-Winged Olive (BWO)',              'bwo',                        100),
  ('Blue-Winged Olive (BWO)',              'blue winged olive',           95),
  ('Blue-Winged Olive (BWO)',              'olive',                       70),
  ('Pale Morning Dun (PMD)',               'pmd',                        100),
  ('Pale Morning Dun (PMD)',               'pale morning',                90),
  ('Sulphur',                              'sulfur',                      95),
  ('Light Cahill',                         'cahill',                      85),
  ('March Brown',                          'march brown dry',             95),
  ('Mahogany Dun',                         'mahogany',                    90),
  ('Trico',                                'trico spinner',               90),
  ('Trico',                                'tricos',                      85),
  ('Green Drake',                          'drake',                       70),
  ('Green Drake',                          'green drake dry',             95),
  ('Brown Drake',                          'brown drake dry',             95),
  ('Hex (Hexagenia)',                      'hex',                        100),
  ('Hex (Hexagenia)',                      'hexagenia',                   95),
  ('Mayfly Spinner',                       'spinner',                     85),
  ('Mayfly Spinner',                       'spinner fly',                 90),
  ('Comparadun',                           'compara dun',                 90),
  ('Klinkhammer',                          'klink',                       90),
  ('Elk Hair Caddis',                      'ehc',                        100),
  ('Elk Hair Caddis',                      'elk hair',                    95),
  ('Elk Hair Caddis',                      'elk caddis',                  90),
  ('X-Caddis',                             'x caddis',                    95),
  ('Goddard Caddis',                       'goddard',                     90),
  ('Henryville Caddis',                    'henryville',                  90),
  ('Stimulator',                           'stimi',                       90),
  ('Stimulator',                           'stim',                        85),
  ('Sofa Pillow',                          'sofa pillow dry',             95),
  ('Salmon Fly Dry',                       'salmon fly',                  90),
  ('Yellow Sally',                         'sally',                       80),
  ('Foam Hopper',                          'hopper',                      90),
  ('Foam Hopper',                          'grasshopper fly',             80),
  ('Chubby Chernobyl',                    'chubby',                      90),
  ('Chubby Chernobyl',                    'chernobyl ant',                85),
  ('Madam X',                              'madam x',                    100),
  ('Foam Ant',                             'ant',                         85),
  ('Foam Ant',                             'flying ant',                  75),
  ('Foam Beetle',                          'beetle',                      85),
  ('Cricket',                              'cricket fly',                 95),
  ('Cicada',                               'cicada fly',                  95),
  ('Royal Wulff',                          'wulff',                       85),
  ('Royal Wulff',                          'royal wulff dry',             95),
  ('Royal Coachman',                       'royal coachman dry',          95),
  ('Humpy',                                'humpy dry',                   95),
  ('H&L Variant',                          'h and l',                     85),

  -- ============================================================
  -- nymph
  -- ============================================================
  ('Pheasant Tail Nymph',                  'pheasant tail',              100),
  ('Pheasant Tail Nymph',                  'pt',                          95),
  ('Pheasant Tail Nymph',                  'pt nymph',                    95),
  ('Flashback Pheasant Tail',              'flashback pt',               100),
  ('Frenchie',                             'frenchie nymph',              95),
  ('Hare''s Ear Nymph',                    'hare ear',                    95),
  ('Hare''s Ear Nymph',                    'hares ear',                   95),
  ('Hare''s Ear Nymph',                    'gold ribbed hares ear',       95),
  ('Hare''s Ear Nymph',                    'grhe',                        90),
  ('Bead Head Hare''s Ear',                'bh hares ear',               100),
  ('Bead Head Hare''s Ear',                'bh he',                       90),
  ('Prince Nymph',                         'prince',                      90),
  ('Copper John',                          'cj',                          85),
  ('Lightning Bug',                        'lightning bug nymph',         95),
  ('Pat''s Rubber Legs',                   'rubber legs',                 95),
  ('Pat''s Rubber Legs',                   'pats rubber legs',            95),
  ('Pat''s Rubber Legs',                   'turd',                        70),
  ('Stonefly Nymph',                       'stone',                       80),
  ('Stonefly Nymph',                       'stonefly',                    95),
  ('Kaufmann''s Stone',                    'kaufmanns stone',             95),
  ('Kaufmann''s Stone',                    'kaufmann stone',              95),
  ('Czech Nymph',                          'czech',                       85),
  ('Czech Nymph',                          'euro nymph',                  85),
  ('Perdigon',                             'perdy',                       90),
  ('Perdigon',                             'perdigon nymph',              95),
  ('Caddis Pupa',                          'caddis pupa nymph',           95),
  ('Sparkle Pupa',                         'sparkle pupa nymph',          95),
  ('Squirmy Worm',                         'squirmy',                     95),
  ('Squirmy Worm',                         'squirmy wormy',               90),
  ('San Juan Worm',                        'san juan',                    95),
  ('San Juan Worm',                        'sjw',                         85),
  ('Walt''s Worm',                         'walts worm',                 100),
  ('Mop Fly',                              'mop',                         85),
  ('Pink Squirrel',                        'pink squirrel nymph',         95),
  ('Zebra Midge',                          'zebra',                       80),
  ('Disco Midge',                          'disco',                       80),
  ('WD-40',                                'wd40',                       100),
  ('WD-40',                                'wd 40',                       95),
  ('RS-2',                                 'rs2',                        100),
  ('RS-2',                                 'rs 2',                        95),
  ('Sow Bug / Scud',                       'scud',                        95),
  ('Sow Bug / Scud',                       'sow bug',                     95),
  ('Sow Bug / Scud',                       'sowbug',                      90),
  ('Cranefly Larva',                       'cranefly',                    95),
  ('Cranefly Larva',                       'crane fly larva',             90),

  -- ============================================================
  -- streamer
  -- ============================================================
  ('Wooly Bugger',                         'woolly bugger',               95),
  ('Wooly Bugger',                         'bugger',                      90),
  ('Wooly Bugger',                         'wb',                          70),
  ('Wooly Worm',                           'woolly worm',                 95),
  ('Sculpzilla',                           'sculpzilla streamer',         95),
  ('Muddler Minnow',                       'muddler',                     95),
  ('Mini Sculpin',                         'sculpin streamer',            85),
  ('Zonker',                               'zonker streamer',             95),
  ('Mickey Finn',                          'mickey',                      80),
  ('Bunny Leech',                          'bunny',                       80),
  ('Bunny Leech',                          'bunny streamer',              90),
  ('Sparkle Minnow',                       'sparkle minnow streamer',     95),
  ('Sex Dungeon',                          'dungeon',                     90),
  ('Sex Dungeon',                          'galloup dungeon',             95),
  ('Mini Sex Dungeon',                     'mini dungeon',                95),
  ('Slumpbuster',                          'slumpbuster streamer',        95),
  ('Heifer Groomer',                       'heifer',                      85),
  ('Drunk & Disorderly',                   'drunk and disorderly',        95),
  ('Drunk & Disorderly',                   'd and d',                     85),
  ('Bow River Bugger',                     'bow river',                   85),
  ('Articulated Streamer',                 'articulated',                 80),
  ('Articulated Streamer',                 'art streamer',                85),
  ('Game Changer (Trout/Bass)',            'game changer',                95),
  ('Mini Loop Streamer',                   'mini loop',                   85),
  ('Trout Spey Streamer',                  'trout spey',                  90),
  ('Trout Spey Streamer',                  'spey fly',                    80),

  -- ============================================================
  -- wet_fly
  -- ============================================================
  ('Soft Hackle',                          'soft hackle wet',             95),
  ('Partridge & Orange',                   'partridge orange',            95),
  ('Partridge & Yellow',                   'partridge yellow',            95),
  ('Hare''s Ear Wet',                      'hares ear wet',               95),
  ('March Brown Wet',                      'march brown wet fly',         95),
  ('Greenwell''s Glory',                   'greenwells glory',           100),

  -- ============================================================
  -- warmwater_bass_fly
  -- ============================================================
  ('Bass Popper',                          'bass popper fly',            100),
  ('Bass Popper',                          'popper fly',                  85),
  ('Boogle Bug',                           'boogle',                      90),
  ('Gurgler',                              'gurgler fly',                 95),
  ('Dahlberg Diver',                       'dahlberg',                    95),
  ('Dahlberg Diver',                       'diver',                       80),
  ('Murdich Minnow',                       'murdich',                     95),
  ('Bass Game Changer',                    'bass changer',                90),
  ('Bass Slider',                          'slider',                      75),
  ('Bass Slider',                          'bass slider fly',             95),
  ('Frog Fly',                             'froggy',                      75),
  ('Bass Worm Fly',                        'bass worm',                   90),
  ('Bream Killer',                         'bream killer fly',            95),
  ('Foam Spider',                          'spider fly',                  85),
  ('Mini Bug',                             'mini bug fly',                90),
  ('Crawdad Pattern',                      'crawdad fly',                 95),
  ('Crawdad Pattern',                      'crawfish fly',                90),
  ('Crawdad Pattern',                      'crayfish fly',                85),
  ('Damselfly Nymph',                      'damsel',                      90),
  ('Damselfly Nymph',                      'damselfly',                   95),
  ('Articulated Trout Tease',              'trout tease',                 90),

  -- ============================================================
  -- saltwater_fly
  -- ============================================================
  ('Clouser Minnow',                       'clouser',                    100),
  ('Lefty''s Deceiver',                    'deceiver',                    95),
  ('Lefty''s Deceiver',                    'lefty',                       80),
  ('Lefty''s Deceiver',                    'leftys deceiver',             95),
  ('Crab Pattern (Merkin)',                'merkin',                     100),
  ('Crab Pattern (Merkin)',                'crab fly',                    90),
  ('Shrimp Pattern (Gotcha)',              'gotcha',                     100),
  ('Shrimp Pattern (Gotcha)',              'shrimp fly',                  85),
  ('Bonefish Bitters',                     'bitters',                     90),
  ('Tarpon Toad',                          'tarpon toad fly',             95),
  ('Tarpon Streamer',                      'tarpon streamer fly',         95),
  ('Redfish Toad',                         'redfish toad fly',            95),
  ('Crease Fly',                           'crease',                      90),
  ('Spawning Shrimp',                      'spawning shrimp fly',         95),
  ('Squimp',                               'squimp fly',                  95),
  ('Sand Eel Pattern',                     'sand eel',                    95),
  ('EP Baitfish',                          'ep baitfish fly',             95),
  ('EP Baitfish',                          'enrico puglisi',              90),
  ('Shock & Awe',                          'shock and awe',               95),
  ('Surf Candy',                           'surf candy fly',              95),

  -- ============================================================
  -- egg_attractor
  -- ============================================================
  ('Egg Pattern',                          'egg',                         85),
  ('Egg Pattern',                          'egg fly',                     95),
  ('Glo Bug',                              'glow bug',                    90),
  ('Bead Egg',                             'bead egg fly',                95),
  ('Sucker Spawn',                         'sucker spawn fly',            95),
  ('Estaz Egg',                            'estaz',                       95),
  ('Y2K Egg',                              'y2k',                         95),
  ('Steelhead Worm',                       'steelhead worm fly',          95),
  ('Intruder',                             'intruder fly',                95)
) as na(canonical_name, alias_text, weight)
  on fc.canonical_name = na.canonical_name
on conflict (fly_id, normalized_alias) do nothing;
