export const RIVER_RUN_REASON_CODES = [
  "gauge_fresh",
  "gauge_stale",
  "gauge_missing",
  "gauge_older_than_24h",
  "gauge_metric_missing",
  "gauge_reach_limited",
  "baseline_missing",
  "baseline_insufficient_history",
  "weather_fresh",
  "weather_stale",
  "weather_missing",
  "rain_missing",
  "dry_72h",
  "light_rain_48h",
  "meaningful_rain_48h",
  "strong_rain_48h",
  "heavy_rain_48h",
  "flow_trend_unknown",
  "flow_falling_24h",
  "flow_stable_24h",
  "flow_rising_24h",
  "flow_meaningful_rise_24h",
  "flow_sharp_rise_24h",
  "very_low_flow_band",
  "low_flow_band",
  "normal_flow_band",
  "ideal_flow_band",
  "high_fishable_flow_band",
  "very_high_flow_band",
  "blown_out_flow_band",
  "temperature_measured",
  "temperature_adjusted_reference",
  "temperature_air_proxy",
  "temperature_unavailable",
  "temperature_neutral_missing",
  "temperature_cooling",
  "temperature_strong_cooling",
  "temperature_warming",
  "temperature_strong_warming",
  "temperature_too_warm_cap",
  "stage_pre_run",
  "stage_beginning",
  "stage_building",
  "stage_peak",
  "stage_tapering",
  "stage_ending",
  "stage_post_run",
  "schedule_ahead",
  "schedule_on_schedule",
  "schedule_behind",
  "schedule_uncertain",
  "schedule_limited_source_days",
  "schedule_missing_yesterday_gauge",
  "schedule_missing_required_inputs",
  "run_strength_weak",
  "run_strength_light",
  "run_strength_medium",
  "run_strength_strong",
  "run_strength_signature",
  "data_quality_fresh",
  "data_quality_partial",
  "data_quality_stale",
  "data_quality_limited",
  "building_presence_limited_push",
  "peak_presence_weak_push",
  "good_fishability_low_presence",
  "strong_push_low_fishability",
  "behind_schedule_strong_push",
  "pre_run_ahead_schedule",
] as const;

export type RiverRunReasonCode = typeof RIVER_RUN_REASON_CODES[number];

const RIVER_RUN_REASON_CODE_SET = new Set<string>(RIVER_RUN_REASON_CODES);

export function isRiverRunReasonCode(
  value: string,
): value is RiverRunReasonCode {
  return RIVER_RUN_REASON_CODE_SET.has(value);
}
