import type { EngineContext } from "../../../howFishingEngine/contracts/context.ts";
import type { ArchetypeProfileV4 } from "../contracts.ts";
import { fly } from "./factory.ts";

const L = "freshwater_lake_pond" as const satisfies EngineContext;
const R = "freshwater_river" as const satisfies EngineContext;

/**
 * Full warmwater/trout fly catalog — Appendix A §22.2 (authoritative) plus
 * targeted post-cutover additions for mainstream exact-fit breadth.
 * `display_name` and `how_to_fish_variants` from v3 where the id existed.
 */
export const FLY_ARCHETYPES_V4: readonly ArchetypeProfileV4[] = [
  fly({
    id: "clouser_minnow",
    display_name: "Clouser Minnow",
    family_group: "streamer_weighted",
    column: "mid",
    primary_pace: "medium",
    secondary_pace: "fast",
    forage_tags: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    species_allowed: ["smallmouth_bass", "largemouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Cast across or slightly downstream, let it jig toward you with short strips so the weighted eyes keep the fly tracking hook-point up.",
      "Strip in short, consistent pulls so the dumbbell eyes make the fly jig up and down; let it sink between strips to stay hook-point up throughout.",
      "Cast and let the weighted eyes sink the fly, then retrieve with a strip-pause cadence that makes it dart upward on the strip and dive back on the pause.",
    ],
  }),
  fly({
    id: "deceiver",
    display_name: "Deceiver",
    family_group: "streamer_baitfish",
    column: "mid",
    primary_pace: "medium",
    forage_tags: ["baitfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["smallmouth_bass", "largemouth_bass", "northern_pike"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Strip in long, smooth pulls so the saddle feathers breathe; add a pause every few strips for followers to close the gap.",
      "Retrieve with medium-to-long pulls and let the feathers collapse and flare; pause every 3-4 strips to let the profile swell and hang for trailing fish.",
      "Work it with a steady baitfish swim at medium cadence; slow down near structure and let it breathe on a semi-tight line between strips.",
    ],
  }),
  fly({
    id: "bucktail_baitfish_streamer",
    display_name: "Bucktail Streamer",
    family_group: "streamer_baitfish",
    column: "mid",
    primary_pace: "medium",
    secondary_pace: "slow",
    forage_tags: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    species_allowed: ["smallmouth_bass", "northern_pike", "trout"],
    water_types_allowed: [R],
    how_to_fish_variants: [
      "Strip with medium-length pulls at a steady baitfish pace; bucktail pulsates naturally between strips, so let it breathe by varying strip length slightly.",
      "Cast across or down and retrieve with consistent strips; add a pause every 4-5 strips so the bucktail flares and collapses like a stunned baitfish.",
      "Use a steady pulsing retrieve in open water, or short strips near structure where the pause and flare can trigger fish that are holding tight.",
    ],
  }),
  fly({
    id: "slim_minnow_streamer",
    display_name: "Slim Baitfish Streamer",
    family_group: "streamer_sparse",
    column: "upper",
    primary_pace: "medium",
    forage_tags: ["baitfish"],
    clarity_strengths: ["clear"],
    species_allowed: ["smallmouth_bass", "trout"],
    water_types_allowed: [R],
    how_to_fish_variants: [
      "Strip with short, quick pulls to make the slim profile dart; pause briefly so it hangs in the current or sinks an inch before the next strip.",
      "Retrieve with a mix of short darts and longer glides; the thin profile tracks like a small minnow on a tight line.",
      "Fish it on a dead-drift through seams, then activate with quick strips near holding structure; the slim silhouette works best in clear water at a measured pace.",
    ],
  }),
  fly({
    id: "articulated_baitfish_streamer",
    display_name: "Articulated Baitfish Streamer",
    family_group: "streamer_articulated",
    column: "mid",
    primary_pace: "medium",
    secondary_pace: "slow",
    forage_tags: ["baitfish"],
    clarity_strengths: ["stained", "dirty"],
    species_allowed: ["smallmouth_bass", "largemouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Strip with moderate pulls so the articulated body pulses; mix fast strips with full stops where the fly sinks and the sections hinge naturally.",
      "Work it across current and down with a varied strip cadence; when a fish follows, slow down and kill the retrieve to let the body spiral on the sink.",
      "Cover water at mid-depth with steady strips; add a hard single rip followed by a full pause to imitate an injured baitfish fleeing and then stopping.",
    ],
  }),
  fly({
    id: "articulated_dungeon_streamer",
    display_name: "Articulated Dungeon Streamer",
    family_group: "streamer_articulated",
    column: "mid",
    primary_pace: "slow",
    secondary_pace: "medium",
    forage_tags: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["stained", "dirty"],
    species_allowed: ["smallmouth_bass", "largemouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Strip it with long pulls and full pauses so the articulated profile kicks wide, then hangs and breathes in place.",
      "Use varied strip lengths with hard pauses after each burst; the fly should surge, then stall and hover like a wounded meal.",
      "Fish it on a sweep-pause cadence near cover and transitions, giving the bulky profile time to hang between strips before moving it again.",
    ],
  }),
  fly({
    id: "game_changer",
    display_name: "Game Changer",
    family_group: "streamer_segmented",
    column: "mid",
    primary_pace: "medium",
    forage_tags: ["baitfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["smallmouth_bass", "largemouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Use a mix of steady strips and sharp 6-inch twitches so the jointed body swims and stalls; pause when you see a follow.",
      "Strip with alternating long and short pulls so the articulated body undulates differently each time; kill the retrieve if you see a fish following and let it sink.",
      "Retrieve with medium strips, then occasionally rip hard so the body compresses and then springs apart — pause after each hard strip and hold your nerve.",
    ],
  }),
  fly({
    id: "woolly_bugger",
    display_name: "Woolly Bugger",
    family_group: "leech_family",
    column: "mid",
    primary_pace: "slow",
    secondary_pace: "medium",
    forage_tags: ["leech_worm"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["smallmouth_bass", "largemouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Let it sink to depth then retrieve with slow hand-twists or short strips; the marabou tail breathes best with long pauses at the end of each pull.",
      "Cast across and swing it on a tight line through the drift, then activate on the hang-down with short strips before lifting.",
      "Fish it on a dead-drift near the bottom, then come alive with a strip-pause retrieve through prime holding water; let the tail do most of the work.",
    ],
  }),
  fly({
    id: "rabbit_strip_leech",
    display_name: "Rabbit-Strip Leech",
    family_group: "leech_family",
    column: "bottom",
    primary_pace: "slow",
    secondary_pace: "medium",
    forage_tags: ["leech_worm", "baitfish"],
    clarity_strengths: ["stained", "dirty"],
    species_allowed: ["smallmouth_bass", "largemouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Let it sink to the strike zone then retrieve with long, slow strips; the rabbit hair undulates seductively between pulls, so don't rush the retrieve.",
      "Cast and count it down, then use a strip-pause retrieve with exaggerated pauses — the pulse on the stop is when most fish commit.",
      "Swim it slowly through deeper pockets and woody structure; the rabbit strip breathes on a semi-tight line, so use the absolute minimum retrieve speed.",
    ],
  }),
  fly({
    id: "jighead_marabou_leech",
    display_name: "Jighead Marabou Leech",
    family_group: "leech_family",
    column: "bottom",
    primary_pace: "slow",
    secondary_pace: "medium",
    forage_tags: ["leech_worm", "baitfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["largemouth_bass", "smallmouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Count it down to the bottom third, then crawl with slow 3–6 inch pulls and long pauses so the marabou pulses without lifting the fly out of the strike zone.",
      "Hop it along hard bottom and transitions with short lifts and dead drops; most bites come as the jighead ticks back down on a tight line.",
      "Dead-drift or swing through current, then tighten and strip just enough to make the head hunt along the substrate like a dislodged leech.",
    ],
  }),
  fly({
    id: "lead_eye_leech",
    display_name: "Lead-Eye Leech",
    family_group: "leech_family",
    column: "bottom",
    primary_pace: "slow",
    forage_tags: ["leech_worm"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["largemouth_bass", "smallmouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Fish it deep and slow with hand-twist retrieves or micro-strips so the lead eye keeps the fly tracking hook-up along the bottom.",
      "Drag and pause across silty flats and outside weed edges; let the fly settle after each pull so the slim profile breathes in place.",
      "Tick wood and rock with short pulls just strong enough to clear snags, then stall — lethargic winter bass often eat on the stall.",
    ],
  }),
  fly({
    id: "feather_jig_leech",
    display_name: "Feather Jig Leech",
    family_group: "leech_family",
    column: "bottom",
    primary_pace: "medium",
    secondary_pace: "slow",
    forage_tags: ["leech_worm", "baitfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["largemouth_bass", "smallmouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Swim it with steady medium strips along bottom transitions so the feather collar pulses without leaving the lower third of the water column.",
      "Rip it free from grass with a sharp strip, then kill it — the jig hook rides point-up and the feathers breathe on the drop for followers.",
      "Probe current breaks and wood with a lift-fall cadence; keep each lift short so the fly stays in the bottom lane where lethargic bass expect meals.",
    ],
  }),
  fly({
    id: "balanced_leech",
    display_name: "Balanced Leech",
    family_group: "leech_family",
    column: "bottom",
    primary_pace: "slow",
    forage_tags: ["leech_worm"],
    clarity_strengths: ["clear", "stained"],
    species_allowed: ["trout"],
    water_types_allowed: [L],
    how_to_fish_variants: [
      "Fish it under an indicator or on a slow hand-twist so the fly hovers level and pulses in place rather than diving nose-first.",
      "Let it suspend just off bottom or under cover and move it only with tiny strips; the balanced posture is the trigger, not speed.",
      "Count it down to the level you want, then use a very slow strip-pause cadence so the fly hangs horizontally through the zone.",
    ],
  }),
  fly({
    id: "zonker_streamer",
    display_name: "Zonker Streamer",
    family_group: "streamer_baitfish",
    column: "mid",
    primary_pace: "medium",
    secondary_pace: "slow",
    forage_tags: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    species_allowed: ["smallmouth_bass", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Strip with a mixed pace — a few short darts, then a longer glide; the rabbit wing wraps on fast strips and flares on the pause for a big profile change.",
      "Retrieve at moderate speed with intentional pauses where the fly sinks and the strip wing breathes; strikes often come as you restart the strip.",
      "Cast across current and strip steadily through the swing; add a momentary deadstop near structure so the wing collapses and then puffs back out.",
    ],
  }),
  fly({
    id: "sculpin_streamer",
    display_name: "Sculpin Streamer",
    family_group: "sculpin_family",
    column: "bottom",
    primary_pace: "slow",
    forage_tags: ["baitfish", "crawfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["smallmouth_bass", "trout"],
    water_types_allowed: [R],
    how_to_fish_variants: [
      "Bump bottom with short strips and let the fly tick along rocks; keep tension so you feel every stop against structure.",
      "Cast upstream and mend for a natural drift, then activate with short strips that make the fly bumble over the bottom like a sculpin retreating.",
      "Inch it along the bottom with tight-line strips; sculpin barely swim, so keep the fly close to the substrate and use current for most of the motion.",
    ],
  }),
  fly({
    id: "sculpzilla",
    display_name: "Sculpzilla",
    family_group: "sculpin_family",
    column: "bottom",
    primary_pace: "slow",
    secondary_pace: "medium",
    forage_tags: ["baitfish", "crawfish"],
    clarity_strengths: ["stained", "dirty"],
    species_allowed: ["smallmouth_bass", "trout"],
    water_types_allowed: [R],
    how_to_fish_variants: [
      "Drive it down near bottom, then strip it in short, hard pulls with pauses so the fly breathes and kicks like a fleeing sculpin.",
      "Cast across current and let it sink, then work it with compact strips that keep the fly close to the substrate without ripping it away from structure.",
      "Use a strip-pause crawl along the bottom with just enough speed to make the materials pulse; keep it low, heavy, and in the fish's lane.",
    ],
  }),
  fly({
    id: "muddler_sculpin",
    display_name: "Muddler Minnow",
    family_group: "sculpin_family",
    column: "bottom",
    primary_pace: "slow",
    forage_tags: ["baitfish", "crawfish"],
    clarity_strengths: ["clear", "stained"],
    species_allowed: ["smallmouth_bass", "trout"],
    water_types_allowed: [R],
    how_to_fish_variants: [
      "Sink and crawl it along bottom with rod-tip leads so the deer hair pushes water, or swing it through soft seams on a tight line.",
      "Work it as a swung wet fly in current with minimal stripping; on still water, hop it along the bottom with slow, erratic pulls.",
      "Cast across and let current animate the fly; add a slow retrieve in lakes and ponds, using rod dips to make the deer hair head push water and dive.",
    ],
  }),
  fly({
    id: "crawfish_streamer",
    display_name: "Crawfish Streamer",
    family_group: "crawfish_fly",
    column: "bottom",
    primary_pace: "slow",
    forage_tags: ["crawfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["smallmouth_bass", "trout"],
    water_types_allowed: [R],
    how_to_fish_variants: [
      "Tick it along the bottom with short, nervous strips so the claws scratch and flare; keep it close to the substrate and pause after contact with any rock or root.",
      "Cast upstream and mend for a dead-drift first; then come alive with quick, short strips that make the claw materials flex like a fleeing crawfish.",
      "Pinch the fly to the bottom and move it in erratic 1-2 inch hops with long pauses; the slower and lower, the better — crawfish don't sprint.",
    ],
  }),
  fly({
    id: "conehead_streamer",
    display_name: "Conehead Streamer",
    family_group: "streamer_weighted",
    column: "mid",
    primary_pace: "medium",
    forage_tags: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    species_allowed: ["smallmouth_bass", "trout"],
    water_types_allowed: [R],
    how_to_fish_variants: [
      "Let the cone dig and dart on each strip — medium pulls with pauses so the fly hunts just off the rocks or wood.",
      "Strip with consistent medium pulls; the cone keeps the fly diving nose-first on each retrieve, so use pauses to let it hunt and settle before the next strip.",
      "Cast across or down, let it sink to depth, then strip with a jig-like cadence where the cone tips the fly nose-down on each pause.",
    ],
  }),
  fly({
    id: "pike_bunny_streamer",
    display_name: "Large Rabbit Strip Streamer",
    family_group: "streamer_pike_large",
    column: "mid",
    primary_pace: "slow",
    secondary_pace: "medium",
    forage_tags: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["stained", "dirty"],
    species_allowed: ["northern_pike"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Strip with long, steady pulls so the rabbit hair breathes and the profile stays big; pause after every 2-3 strips to let following pike close.",
      "Retrieve at a consistent pace that keeps the fly moving but gives the rabbit strip time to pulse; deadstop near structure to trigger strike reactions.",
      "Work it on medium strips with deliberate pauses; the oversized rabbit profile holds fish attention — give it time to be seen before the next strip.",
    ],
  }),
  fly({
    id: "large_articulated_pike_streamer",
    display_name: "Articulated Pike Streamer",
    family_group: "streamer_pike_large",
    column: "mid",
    primary_pace: "slow",
    secondary_pace: "medium",
    forage_tags: ["baitfish"],
    clarity_strengths: ["stained", "dirty"],
    species_allowed: ["northern_pike"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Long sweeping strips with full pauses; the articulated body coils on the stop and then springs on the next strip — give it the full beat.",
      "Retrieve with slow, arm-length strips and complete stops; pike follow and commit on the pause, so hold the deadstop for a count of two.",
      "Run it at mid-depth on alternating long and short strips; after a follow, stop completely and let the articulated body collapse before the next strip.",
    ],
  }),
  fly({
    id: "unweighted_baitfish_streamer",
    display_name: "Unweighted Baitfish Streamer",
    family_group: "streamer_unweighted",
    column: "upper",
    primary_pace: "medium",
    secondary_pace: "slow",
    forage_tags: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained"],
    species_allowed: ["largemouth_bass", "smallmouth_bass", "northern_pike"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Fish it on a floating line with a medium strip so the unweighted body tracks just under the film, pushing a subtle V-wake for fish looking up.",
      "Strip-pause at medium pace over grass edges, pad lines, and shallow flats; the fly glides and hangs high in the column — the hang between strips is where most fish commit.",
      "Swing or slow-strip it through current seams and along shallow banks; keep the retrieve unhurried so the sparse profile breathes and rides high rather than diving.",
    ],
  }),
  fly({
    id: "baitfish_slider_fly",
    display_name: "Baitfish Slider Fly",
    family_group: "streamer_slider",
    column: "upper",
    primary_pace: "medium",
    secondary_pace: "fast",
    forage_tags: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["largemouth_bass", "smallmouth_bass", "northern_pike"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Fish it high in the column with brisk strips so the sparse head throws a little wake, then let it glide just under the film before the next pull.",
      "Strip it fast over grass lines and shallow cover, but kill it after each burst so the fly slides and hangs high where looking-up fish can track it.",
      "Work it as a fast dart-and-glide baitfish look around banks, pads, and seam edges; the fly should stay high and never dig deeper than the upper lane.",
    ],
  }),
  fly({
    id: "popper_fly",
    display_name: "Popper Fly",
    family_group: "fly_popper",
    column: "surface",
    primary_pace: "medium",
    secondary_pace: "slow",
    forage_tags: ["surface_prey", "bluegill_perch"],
    clarity_strengths: ["clear", "stained"],
    species_allowed: ["largemouth_bass", "smallmouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Pop once with a short strip, let the rings settle for two seconds, then pop again; in calm conditions, longer pauses are always better.",
      "Make a sharp strip-pause to spit water, then wait; the longer the pause in the ring, the more time a fish has to rise and commit.",
      "Work it with medium strips that spit and gurgle; slow the cadence near structure and let the fly rest after each pop — target the edge of any surface shadow.",
    ],
  }),
  fly({
    id: "deer_hair_slider",
    display_name: "Deer Hair Slider",
    family_group: "fly_slider",
    column: "surface",
    primary_pace: "medium",
    secondary_pace: "fast",
    forage_tags: ["surface_prey", "baitfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["largemouth_bass", "smallmouth_bass", "northern_pike", "trout"],
    water_types_allowed: [L, R],
    how_to_fish_variants: [
      "Skitter it with short, quick strips so it wakes and slides across the film, then let it stall for a beat before moving it again.",
      "Work it with brisk strips over shallow cover and bankside shade; the fly should slash just under the film and leave a visible V-wake.",
      "Strip fast enough to make it wake and skate, then pause long enough for followers to close; this is the louder, more urgent surface option when fish are willing to chase.",
    ],
  }),
  fly({
    id: "frog_fly",
    display_name: "Frog Fly",
    family_group: "fly_frog",
    column: "surface",
    primary_pace: "slow",
    secondary_pace: "medium",
    forage_tags: ["surface_prey"],
    /** Stained/dirty are peak realism over cover; clear stays eligible — pads/vegetation break sightlines like stain does open water. */
    clarity_strengths: ["clear", "stained", "dirty"],
    species_allowed: ["largemouth_bass", "northern_pike"],
    water_types_allowed: [L],
    how_to_fish_variants: [
      "Twitch with short strips over and along cover; when it lands near a gap, let it sit still for three seconds before moving — that pause triggers strikes.",
      "Walk it across the surface with alternating rod twitches; slow to a crawl near pad edges and let it rest fully before the next move.",
      "Retrieve with a strip-rest cadence; the fly should look like a frog resting, then kicking — most strikes come right after the stillness.",
    ],
  }),
  fly({
    id: "mouse_fly",
    display_name: "Mouse Fly",
    family_group: "fly_mouse",
    column: "surface",
    primary_pace: "slow",
    secondary_pace: "medium",
    forage_tags: ["surface_prey"],
    clarity_strengths: ["clear", "stained"],
    species_allowed: ["trout"],
    water_types_allowed: [R],
    how_to_fish_variants: [
      "Cast to structure and retrieve with a steady, slow V-wake strip; vary only slightly in speed and resist the urge to twitch — mice move in straight lines.",
      "Swim it on a constant slow retrieve just fast enough to leave a wake; target near-shore edges and structure where big fish expect food to cross.",
      "Work it with a slow, uninterrupted retrieve across open water; the V-wake is the trigger, so keep it moving at a steady pace and stay alert.",
    ],
  }),
];
