/**
 * Lure family metadata library.
 * Each family's metadata drives the scoring engine — not brands, just families.
 * Stable IDs are the future tackle-box compatibility bridge.
 */

import type { EngineContext } from "../../howFishingEngine/contracts/context.ts";
import type {
  ActivityLevel,
  CoverClass,
  DepthLane,
  FlashLevel,
  FlowSuitability,
  ForageMode,
  NoiseLevel,
  ProfileSize,
  SpeedPreference,
  TriggerType,
} from "../contracts/behavior.ts";
import type { LureFamilyId } from "../contracts/families.ts";
import type { SpeciesGroup } from "../contracts/species.ts";
import type { WaterClarity } from "../contracts/input.ts";

export type LureFamilyMetadata = {
  id: LureFamilyId;
  display_name: string;
  examples: string[];
  depth_match: DepthLane[];
  speed_match: SpeedPreference[];
  trigger_type: TriggerType;
  noise_level: NoiseLevel;
  flash_level: FlashLevel;
  profile: ProfileSize;
  clarity_strengths: WaterClarity[];
  cover_strengths: CoverClass[];
  current_suitability: FlowSuitability;
  tide_suitability: FlowSuitability;
  topwater: boolean;
  weedless: boolean;
  current_capable: boolean;
  forage_affinity: ForageMode[];
  activity_affinity: ActivityLevel[];
  valid_species: SpeciesGroup[];
  valid_contexts: EngineContext[];
};

export const LURE_FAMILIES: Record<LureFamilyId, LureFamilyMetadata> = {
  jig: {
    id: "jig",
    display_name: "Jig",
    examples: ["Bass jig", "Football jig", "Flipping jig", "Shaky head", "Finesse jig", "Arky jig", "Standup jig", "Structure jig", "Casting jig", "Pitch jig"],
    depth_match: ["near_bottom", "bottom", "mid"],
    speed_match: ["dead_slow", "slow", "moderate"],
    trigger_type: "natural_match",
    noise_level: "silent",
    flash_level: "subtle",
    profile: "medium",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["rock", "current_seam", "hard_structure", "bottom"],
    current_suitability: "strong",
    tide_suitability: "capable",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish", "crawfish", "shrimp", "leech"],
    activity_affinity: ["neutral", "active", "low"],
    valid_species: [
      "largemouth_bass", "smallmouth_bass", "walleye", "river_trout",
      "pike_musky", "redfish", "snook", "seatrout", "striped_bass", "tarpon",
    ],
    valid_contexts: [
      "freshwater_lake_pond", "freshwater_river", "coastal", "coastal_flats_estuary",
    ],
  },

  soft_swimbait: {
    id: "soft_swimbait",
    display_name: "Soft Swimbait",
    examples: ["Paddle tail swimbait", "Curly tail grub", "Boot tail shad", "Fluke swimbait", "Shad body swimbait", "Hollow belly swimbait", "Straight tail minnow", "Split tail trailer", "Ribbon tail swimbait"],
    depth_match: ["upper", "mid", "near_bottom"],
    speed_match: ["moderate", "fast", "slow"],
    trigger_type: "reaction",
    noise_level: "subtle",
    flash_level: "moderate",
    profile: "slim",
    clarity_strengths: ["clear", "stained", "dirty"],
    cover_strengths: ["open_water", "current_seam", "flats"],
    current_suitability: "capable",
    tide_suitability: "strong",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish"],
    activity_affinity: ["active", "aggressive", "neutral"],
    valid_species: [
      "largemouth_bass", "smallmouth_bass", "walleye", "pike_musky",
      "striped_bass", "redfish", "snook", "seatrout", "tarpon",
    ],
    valid_contexts: [
      "freshwater_lake_pond", "freshwater_river", "coastal", "coastal_flats_estuary",
    ],
  },

  soft_stickworm: {
    id: "soft_stickworm",
    display_name: "Soft Worm / Stick Worm",
    examples: ["Stick worm", "Straight-tail worm", "Ribbon-tail worm", "Weightless worm", "Floating worm", "Trick worm", "Finesse worm", "Slim worm", "Cut-tail worm"],
    depth_match: ["surface", "upper", "mid"],
    speed_match: ["dead_slow", "slow"],
    trigger_type: "finesse",
    noise_level: "silent",
    flash_level: "none",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["vegetation", "wood", "hard_structure"],
    current_suitability: "poor",
    tide_suitability: "poor",
    topwater: false,
    weedless: true,
    current_capable: false,
    forage_affinity: ["baitfish", "leech", "mixed"],
    activity_affinity: ["neutral", "low", "inactive"],
    valid_species: ["largemouth_bass", "smallmouth_bass"],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  soft_craw: {
    id: "soft_craw",
    display_name: "Soft Craw / Creature",
    examples: ["Craw bait", "Creature bait", "Beaver bait", "Texas-rigged craw", "Punch craw", "Flipping craw", "Twin-tail craw", "Compact craw", "Structure craw"],
    depth_match: ["near_bottom", "bottom"],
    speed_match: ["dead_slow", "slow"],
    trigger_type: "natural_match",
    noise_level: "subtle",
    flash_level: "none",
    profile: "medium",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["vegetation", "wood", "rock", "bottom"],
    current_suitability: "poor",
    tide_suitability: "poor",
    topwater: false,
    weedless: true,
    current_capable: false,
    forage_affinity: ["crawfish"],
    activity_affinity: ["neutral", "active", "low"],
    valid_species: [
      "largemouth_bass", "smallmouth_bass", "walleye", "river_trout", "pike_musky",
    ],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  lipless_crankbait: {
    id: "lipless_crankbait",
    display_name: "Lipless Crankbait",
    examples: ["Lipless crankbait", "Rat-L-Trap", "Red Eye Shad", "One-knocker", "Silent lipless", "Half-ounce lipless", "Mini lipless", "Rattle trap", "Chrome lipless"],
    depth_match: ["mid", "near_bottom", "upper"],
    speed_match: ["fast", "moderate", "vary"],
    trigger_type: "reaction",
    noise_level: "loud",
    flash_level: "heavy",
    profile: "medium",
    clarity_strengths: ["stained", "dirty"],
    cover_strengths: ["vegetation", "open_water", "flats"],
    current_suitability: "capable",
    tide_suitability: "capable",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish"],
    activity_affinity: ["active", "aggressive"],
    valid_species: [
      "largemouth_bass", "smallmouth_bass", "walleye", "striped_bass",
      "redfish", "seatrout",
    ],
    valid_contexts: [
      "freshwater_lake_pond", "freshwater_river", "coastal",
    ],
  },

  diving_crankbait: {
    id: "diving_crankbait",
    display_name: "Crankbait / Squarebill",
    examples: ["Squarebill crankbait", "Flat-side crankbait", "Round-bill crankbait", "Shallow diver", "Medium diver crankbait", "Deep diver crankbait", "Coffin-bill crankbait", "Wake crankbait", "Silent crankbait"],
    depth_match: ["upper", "mid", "near_bottom"],
    speed_match: ["moderate", "fast"],
    trigger_type: "reaction",
    noise_level: "moderate",
    flash_level: "moderate",
    profile: "medium",
    clarity_strengths: ["clear", "stained", "dirty"],
    cover_strengths: ["rock", "wood", "hard_structure", "vegetation"],
    current_suitability: "capable",
    tide_suitability: "poor",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish", "crawfish"],
    activity_affinity: ["active", "aggressive", "neutral"],
    valid_species: [
      "largemouth_bass", "smallmouth_bass", "walleye", "striped_bass",
    ],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  jerkbait: {
    id: "jerkbait",
    display_name: "Jerkbait / Fluke",
    examples: ["Suspending jerkbait", "Soft jerkbait", "Fluke-style minnow", "Twitch bait", "Deep jerkbait", "Slash bait", "Rip bait", "Shallow jerkbait", "Minnow jerkbait"],
    depth_match: ["upper", "mid"],
    speed_match: ["slow", "moderate", "vary"],
    trigger_type: "reaction",
    noise_level: "subtle",
    flash_level: "moderate",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["open_water", "hard_structure", "vegetation"],
    current_suitability: "capable",
    tide_suitability: "capable",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish"],
    activity_affinity: ["neutral", "active", "aggressive"],
    valid_species: [
      "largemouth_bass", "smallmouth_bass", "walleye", "pike_musky",
      "striped_bass", "snook", "seatrout", "tarpon",
    ],
    valid_contexts: [
      "freshwater_lake_pond", "freshwater_river", "coastal", "coastal_flats_estuary",
    ],
  },

  spinnerbait: {
    id: "spinnerbait",
    display_name: "Spinnerbait / Chatterbait",
    examples: ["Spinnerbait", "Bladed jig", "ChatterBait", "Compact spinnerbait", "Double-willow spinnerbait", "Colorado-blade spinnerbait", "Tandem spinnerbait", "Short-arm spinnerbait", "Finesse spinnerbait"],
    depth_match: ["upper", "mid"],
    speed_match: ["moderate", "fast", "slow"],
    trigger_type: "reaction",
    noise_level: "moderate",
    flash_level: "heavy",
    profile: "medium",
    clarity_strengths: ["stained", "dirty"],
    cover_strengths: ["vegetation", "wood", "open_water"],
    current_suitability: "capable",
    tide_suitability: "poor",
    topwater: false,
    weedless: true,
    current_capable: true,
    forage_affinity: ["baitfish"],
    activity_affinity: ["active", "aggressive", "neutral"],
    valid_species: [
      "largemouth_bass", "smallmouth_bass", "pike_musky", "striped_bass",
    ],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  topwater_popper: {
    id: "topwater_popper",
    display_name: "Topwater Popper",
    examples: ["Popper", "Chugger", "Splash bait", "Pencil popper", "Spit bait", "Cup-face popper", "Saltwater popper", "Mini popper", "Walk-and-pop"],
    depth_match: ["surface"],
    speed_match: ["slow", "vary"],
    trigger_type: "aggressive",
    noise_level: "loud",
    flash_level: "moderate",
    profile: "medium",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["open_water", "hard_structure", "current_seam"],
    current_suitability: "poor",
    tide_suitability: "poor",
    topwater: true,
    weedless: false,
    current_capable: false,
    forage_affinity: ["surface_prey", "baitfish"],
    activity_affinity: ["active", "aggressive"],
    valid_species: [
      "largemouth_bass", "smallmouth_bass", "pike_musky", "snook",
      "redfish", "seatrout", "striped_bass", "tarpon",
    ],
    valid_contexts: [
      "freshwater_lake_pond", "freshwater_river", "coastal", "coastal_flats_estuary",
    ],
  },

  topwater_walker: {
    id: "topwater_walker",
    display_name: "Walking Bait",
    examples: ["Walking bait", "Spook-style walker", "Pencil bait", "Walk-the-dog bait", "Cigar walker", "Saltwater walker", "Feathered walker", "Compact walker", "Weighted walker"],
    depth_match: ["surface"],
    speed_match: ["moderate", "slow"],
    trigger_type: "aggressive",
    noise_level: "moderate",
    flash_level: "moderate",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["open_water", "flats", "current_seam"],
    current_suitability: "poor",
    tide_suitability: "capable",
    topwater: true,
    weedless: false,
    current_capable: false,
    forage_affinity: ["surface_prey", "baitfish"],
    activity_affinity: ["active", "aggressive"],
    valid_species: [
      "largemouth_bass", "smallmouth_bass", "snook", "seatrout",
      "striped_bass", "redfish",
    ],
    valid_contexts: [
      "freshwater_lake_pond", "freshwater_river", "coastal", "coastal_flats_estuary",
    ],
  },

  topwater_frog: {
    id: "topwater_frog",
    display_name: "Hollow-Body Frog",
    examples: ["Hollow-body frog", "Toad", "Buzz frog", "Prop frog", "Walking frog", "Popping frog", "Rat bait", "Moss frog", "Pad-runner frog"],
    depth_match: ["surface"],
    speed_match: ["slow", "moderate"],
    trigger_type: "aggressive",
    noise_level: "moderate",
    flash_level: "none",
    profile: "medium",
    clarity_strengths: ["stained", "dirty"],
    cover_strengths: ["vegetation"],
    current_suitability: "poor",
    tide_suitability: "poor",
    topwater: true,
    weedless: true,
    current_capable: false,
    forage_affinity: ["surface_prey"],
    activity_affinity: ["active", "aggressive"],
    valid_species: ["largemouth_bass", "pike_musky"],
    valid_contexts: ["freshwater_lake_pond"],
  },

  shrimp_crab_plastic: {
    id: "shrimp_crab_plastic",
    display_name: "Shrimp / Crab Soft Plastic",
    examples: ["DOA Shrimp", "Vudu Shrimp", "Rigged shrimp soft plastic", "Crab soft plastic", "Live shrimp imitation", "Suspending shrimp", "Weighted crab bait", "Flats shrimp", "Jighead shrimp"],
    depth_match: ["near_bottom", "bottom", "mid"],
    speed_match: ["dead_slow", "slow"],
    trigger_type: "natural_match",
    noise_level: "silent",
    flash_level: "subtle",
    profile: "medium",
    clarity_strengths: ["clear", "stained", "dirty"],
    cover_strengths: ["flats", "bottom", "current_seam"],
    current_suitability: "capable",
    tide_suitability: "strong",
    topwater: false,
    weedless: true,
    current_capable: true,
    forage_affinity: ["shrimp", "crab"],
    activity_affinity: ["neutral", "active", "low", "aggressive"],
    valid_species: ["redfish", "snook", "seatrout", "tarpon"],
    valid_contexts: ["coastal", "coastal_flats_estuary"],
  },

  large_profile_swimbait: {
    id: "large_profile_swimbait",
    display_name: "Big Swimbait / Glide Bait",
    examples: ["Glide bait", "Line-through swimbait", "Big paddle tail", "Multi-jointed swimbait", "Hard-body swimbait", "Slow-sink glider", "Wake swimbait", "Trout swimbait", "Magnum swimbait"],
    depth_match: ["upper", "mid", "near_bottom"],
    speed_match: ["slow", "moderate"],
    trigger_type: "reaction",
    noise_level: "subtle",
    flash_level: "moderate",
    profile: "bulky",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["open_water", "hard_structure", "current_seam"],
    current_suitability: "capable",
    tide_suitability: "strong",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish"],
    activity_affinity: ["active", "aggressive", "neutral"],
    valid_species: ["pike_musky", "striped_bass", "largemouth_bass", "tarpon"],
    valid_contexts: [
      "freshwater_lake_pond", "freshwater_river", "coastal", "coastal_flats_estuary",
    ],
  },

  casting_spoon: {
    id: "casting_spoon",
    display_name: "Casting Spoon",
    examples: ["Casting spoon", "Flutter spoon", "Dardevle-style spoon", "Weedless spoon", "Jigging spoon", "Trolling spoon", "Slab spoon", "Heavy spoon", "Willow spoon"],
    depth_match: ["upper", "mid", "near_bottom"],
    speed_match: ["fast", "moderate", "vary"],
    trigger_type: "reaction",
    noise_level: "silent",
    flash_level: "heavy",
    profile: "slim",
    clarity_strengths: ["clear", "stained", "dirty"],
    cover_strengths: ["open_water", "current_seam", "flats"],
    current_suitability: "strong",
    tide_suitability: "strong",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish"],
    activity_affinity: ["active", "aggressive", "neutral"],
    valid_species: ["walleye", "pike_musky", "striped_bass", "river_trout"],
    valid_contexts: [
      "freshwater_lake_pond", "freshwater_river", "coastal",
    ],
  },

  ned_rig: {
    id: "ned_rig",
    display_name: "Ned Rig",
    examples: ["Ned rig", "Mushroom head jig", "TRD", "Finesse mushroom", "Half-craw ned", "Floating ned", "Midwest finesse rig", "Compact ned", "Stubby ned"],
    depth_match: ["near_bottom", "bottom", "mid"],
    speed_match: ["dead_slow", "slow"],
    trigger_type: "finesse",
    noise_level: "silent",
    flash_level: "none",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["rock", "hard_structure", "bottom", "open_water"],
    current_suitability: "capable",
    tide_suitability: "poor",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["crawfish", "leech", "mixed"],
    activity_affinity: ["low", "neutral", "inactive"],
    valid_species: ["largemouth_bass", "smallmouth_bass", "walleye"],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  drop_shot: {
    id: "drop_shot",
    display_name: "Drop Shot",
    examples: ["Drop shot rig", "Finesse worm drop shot", "Minnow drop shot", "Nose-hooked drop shot", "Shaky drop shot", "Deep drop shot", "Light-line drop shot", "Spinning drop shot", "Forward-facing drop shot"],
    depth_match: ["mid", "near_bottom", "bottom"],
    speed_match: ["dead_slow", "slow"],
    trigger_type: "finesse",
    noise_level: "silent",
    flash_level: "none",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["rock", "hard_structure", "open_water", "bottom"],
    current_suitability: "capable",
    tide_suitability: "poor",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish", "leech", "mixed"],
    activity_affinity: ["low", "neutral", "inactive"],
    valid_species: ["largemouth_bass", "smallmouth_bass", "walleye"],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  blade_bait: {
    id: "blade_bait",
    display_name: "Blade Bait",
    examples: ["Blade bait", "Silver Buddy", "Heddon Sonar", "Vertical blade", "Vibrating blade", "Compact blade", "Deep-water blade", "Winter blade", "Ripping blade"],
    depth_match: ["near_bottom", "bottom", "mid"],
    speed_match: ["vary", "slow", "moderate"],
    trigger_type: "reaction",
    noise_level: "moderate",
    flash_level: "heavy",
    profile: "slim",
    clarity_strengths: ["clear", "stained", "dirty"],
    cover_strengths: ["hard_structure", "rock", "open_water", "bottom"],
    current_suitability: "capable",
    tide_suitability: "capable",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish", "crawfish"],
    activity_affinity: ["low", "neutral", "active"],
    valid_species: ["walleye", "smallmouth_bass", "striped_bass", "largemouth_bass"],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  inline_spinner: {
    id: "inline_spinner",
    display_name: "Inline Spinner",
    examples: ["Inline spinner", "Rooster Tail", "Mepps spinner", "Panther Martin", "Dressed spinner", "Bucktail spinner", "Single-blade spinner", "Trout spinner", "Stream spinner"],
    depth_match: ["upper", "mid"],
    speed_match: ["moderate", "slow", "fast"],
    trigger_type: "reaction",
    noise_level: "moderate",
    flash_level: "heavy",
    profile: "slim",
    clarity_strengths: ["clear", "stained", "dirty"],
    cover_strengths: ["current_seam", "open_water", "rock"],
    current_suitability: "strong",
    tide_suitability: "poor",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish", "mixed"],
    activity_affinity: ["active", "neutral", "aggressive"],
    valid_species: ["river_trout", "smallmouth_bass", "pike_musky"],
    valid_contexts: ["freshwater_river", "freshwater_lake_pond"],
  },

  buzzbait: {
    id: "buzzbait",
    display_name: "Buzzbait",
    examples: ["Buzzbait", "Inline buzzbait", "Double-bladed buzzbait", "Clacker buzzbait", "Counter-rotation buzzbait", "Compact buzzbait", "Weedless buzzbait", "Squeaking buzzbait", "Tri-wing buzzbait"],
    depth_match: ["surface"],
    speed_match: ["fast", "moderate"],
    trigger_type: "aggressive",
    noise_level: "loud",
    flash_level: "moderate",
    profile: "medium",
    clarity_strengths: ["stained", "dirty"],
    cover_strengths: ["vegetation", "open_water", "wood"],
    current_suitability: "poor",
    tide_suitability: "poor",
    topwater: true,
    weedless: true,
    current_capable: false,
    forage_affinity: ["surface_prey", "baitfish"],
    activity_affinity: ["active", "aggressive"],
    valid_species: ["largemouth_bass", "pike_musky"],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  swim_jig: {
    id: "swim_jig",
    display_name: "Swim Jig",
    examples: ["Swim jig", "Vibrating swim jig", "Weedless swim jig", "Swim jig with trailer", "Grass swim jig", "Compact swim jig", "Open-water swim jig", "Bladed swim jig", "Finesse swim jig"],
    depth_match: ["upper", "mid"],
    speed_match: ["moderate", "slow", "fast"],
    trigger_type: "reaction",
    noise_level: "subtle",
    flash_level: "moderate",
    profile: "medium",
    clarity_strengths: ["stained", "dirty", "clear"],
    cover_strengths: ["vegetation", "wood", "open_water"],
    current_suitability: "capable",
    tide_suitability: "poor",
    topwater: false,
    weedless: true,
    current_capable: true,
    forage_affinity: ["baitfish"],
    activity_affinity: ["active", "aggressive", "neutral"],
    valid_species: ["largemouth_bass", "smallmouth_bass", "pike_musky"],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  underspin: {
    id: "underspin",
    display_name: "Underspin",
    examples: ["Underspin jighead", "Scrounger jig", "Keitech on underspin", "Bladed underspin", "Deep underspin", "Compact underspin", "Swimbait underspin", "Flutter underspin", "Finesse underspin"],
    depth_match: ["mid", "near_bottom"],
    speed_match: ["slow", "moderate"],
    trigger_type: "natural_match",
    noise_level: "subtle",
    flash_level: "moderate",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["open_water", "hard_structure", "rock"],
    current_suitability: "capable",
    tide_suitability: "capable",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish"],
    activity_affinity: ["neutral", "active", "low"],
    valid_species: ["walleye", "smallmouth_bass", "largemouth_bass", "striped_bass"],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river", "coastal"],
  },

  bucktail_jig: {
    id: "bucktail_jig",
    display_name: "Bucktail Jig",
    examples: ["Bucktail jig", "Spro bucktail", "Saltwater bucktail", "Hair jig", "Surf bucktail", "Jetty bucktail", "Light-tackle bucktail", "Flats bucktail", "Deep-water bucktail"],
    depth_match: ["mid", "near_bottom", "upper"],
    speed_match: ["moderate", "slow", "fast"],
    trigger_type: "natural_match",
    noise_level: "silent",
    flash_level: "subtle",
    profile: "medium",
    clarity_strengths: ["clear", "stained", "dirty"],
    cover_strengths: ["current_seam", "open_water", "hard_structure", "flats"],
    current_suitability: "strong",
    tide_suitability: "strong",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish", "shrimp"],
    activity_affinity: ["active", "neutral", "aggressive"],
    valid_species: ["striped_bass", "snook", "seatrout", "redfish"],
    valid_contexts: ["coastal", "coastal_flats_estuary"],
  },

  wacky_rig: {
    id: "wacky_rig",
    display_name: "Wacky Rig",
    examples: ["Wacky-rigged worm", "Wacky Senko", "Neko rig", "Wacky-rigged stickbait", "O-ring wacky", "Weighted wacky", "Flick-shake wacky", "Dock wacky", "Skipping wacky"],
    depth_match: ["upper", "mid", "near_bottom"],
    speed_match: ["dead_slow", "slow"],
    trigger_type: "finesse",
    noise_level: "silent",
    flash_level: "none",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["hard_structure", "open_water", "wood"],
    current_suitability: "poor",
    tide_suitability: "poor",
    topwater: false,
    weedless: false,
    current_capable: false,
    forage_affinity: ["baitfish", "leech", "mixed"],
    activity_affinity: ["low", "neutral", "inactive"],
    valid_species: ["largemouth_bass", "smallmouth_bass"],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river"],
  },

  topwater_prop: {
    id: "topwater_prop",
    display_name: "Topwater Prop Bait",
    examples: ["Prop bait", "Boy Howdy", "Devil's Horse", "Torpedo", "Tail spinner topwater", "Wounded minnow prop", "Twin-prop bait", "Compact prop bait", "Saltwater prop"],
    depth_match: ["surface"],
    speed_match: ["slow", "vary"],
    trigger_type: "aggressive",
    noise_level: "loud",
    flash_level: "moderate",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["open_water", "hard_structure", "current_seam"],
    current_suitability: "poor",
    tide_suitability: "poor",
    topwater: true,
    weedless: false,
    current_capable: false,
    forage_affinity: ["surface_prey", "baitfish"],
    activity_affinity: ["active", "aggressive"],
    valid_species: ["largemouth_bass", "smallmouth_bass", "striped_bass", "seatrout"],
    valid_contexts: ["freshwater_lake_pond", "freshwater_river", "coastal"],
  },
  gold_spoon: {
    id: "gold_spoon",
    display_name: "Gold Weedless Spoon",
    examples: ["Weedless gold spoon", "Flutter spoon", "Light gold spoon", "Flats spoon", "Redfish spoon", "Skinny-water spoon", "Shallow spoon", "Gold flash spoon", "Weedless flutter spoon"],
    depth_match: ["upper", "surface", "mid"],
    speed_match: ["moderate", "slow", "fast"],
    trigger_type: "reaction",
    noise_level: "silent",
    flash_level: "heavy",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["flats", "vegetation", "open_water"],
    current_suitability: "capable",
    tide_suitability: "strong",
    topwater: false,
    weedless: true,
    current_capable: true,
    forage_affinity: ["baitfish", "shrimp"],
    activity_affinity: ["active", "aggressive", "neutral"],
    valid_species: ["redfish", "seatrout", "snook"],
    valid_contexts: ["coastal", "coastal_flats_estuary"],
  },

  topwater_plug: {
    id: "topwater_plug",
    display_name: "Topwater Plug",
    examples: ["Topwater plug", "Saltwater walking plug", "Mullet plug", "Surface chugger", "Dawn plug", "Mangrove plug", "Flats-runner plug", "Channel walker plug", "Dock-light plug"],
    depth_match: ["surface"],
    speed_match: ["slow", "moderate", "vary"],
    trigger_type: "aggressive",
    noise_level: "moderate",
    flash_level: "subtle",
    profile: "medium",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["open_water", "flats", "current_seam", "hard_structure"],
    current_suitability: "poor",
    tide_suitability: "capable",
    topwater: true,
    weedless: false,
    current_capable: false,
    forage_affinity: ["surface_prey", "baitfish"],
    activity_affinity: ["active", "aggressive"],
    valid_species: ["snook", "seatrout", "redfish", "tarpon"],
    valid_contexts: ["coastal", "coastal_flats_estuary"],
  },

  soft_jerkbait_coastal: {
    id: "soft_jerkbait_coastal",
    display_name: "Coastal Soft Jerkbait",
    examples: ["Soft jerkbait", "Flats jerkbait", "Saltwater fluke", "Mullet imitation", "Soft twitch minnow", "Suspending jerk", "Coastal fluke", "Mangrove jerkbait", "Dock-light jerk"],
    depth_match: ["upper", "mid", "surface"],
    speed_match: ["slow", "moderate", "vary"],
    trigger_type: "reaction",
    noise_level: "silent",
    flash_level: "subtle",
    profile: "slim",
    clarity_strengths: ["clear", "stained"],
    cover_strengths: ["open_water", "hard_structure", "flats", "current_seam"],
    current_suitability: "capable",
    tide_suitability: "capable",
    topwater: false,
    weedless: false,
    current_capable: true,
    forage_affinity: ["baitfish"],
    activity_affinity: ["neutral", "active", "aggressive"],
    valid_species: ["snook", "seatrout", "redfish", "tarpon"],
    valid_contexts: ["coastal", "coastal_flats_estuary"],
  },
};

export function getLureFamily(id: LureFamilyId): LureFamilyMetadata {
  return LURE_FAMILIES[id];
}
