// Generated by scripts/generate-pier-cast-phase2.ts.
// SENSITIVITY RESEARCH ONLY. Not imported by runtime assembly.
import type { PierCastSpeciesId, PierCastTemperatureCurve } from "../types.ts";
export const PIER_CAST_ADDITIONAL_THERMAL_RESEARCH: {speciesId: PierCastSpeciesId; curve: PierCastTemperatureCurve}[] = [
  {
    "speciesId": "lake_trout",
    "curve": {
      "curveId": "lake_trout__additional_thermal_research__v0_1",
      "calibrationStatus": "provisional",
      "acceptedDomainC": [
        0,
        26
      ],
      "knots": [
        {
          "temperatureC": 0,
          "suitability": 0.65
        },
        {
          "temperatureC": 2,
          "suitability": 0.8
        },
        {
          "temperatureC": 4,
          "suitability": 0.9
        },
        {
          "temperatureC": 8,
          "suitability": 1
        },
        {
          "temperatureC": 11,
          "suitability": 1
        },
        {
          "temperatureC": 14,
          "suitability": 0.85
        },
        {
          "temperatureC": 16,
          "suitability": 0.65
        },
        {
          "temperatureC": 18,
          "suitability": 0.4
        },
        {
          "temperatureC": 20,
          "suitability": 0.2
        },
        {
          "temperatureC": 23,
          "suitability": 0.1
        },
        {
          "temperatureC": 26,
          "suitability": 0.05
        }
      ]
    }
  },
  {
    "speciesId": "walleye",
    "curve": {
      "curveId": "walleye__additional_thermal_research__v0_1",
      "calibrationStatus": "provisional",
      "acceptedDomainC": [
        0,
        32
      ],
      "knots": [
        {
          "temperatureC": 0,
          "suitability": 0.6
        },
        {
          "temperatureC": 4,
          "suitability": 0.75
        },
        {
          "temperatureC": 8,
          "suitability": 0.9
        },
        {
          "temperatureC": 12,
          "suitability": 1
        },
        {
          "temperatureC": 20,
          "suitability": 1
        },
        {
          "temperatureC": 23,
          "suitability": 0.9
        },
        {
          "temperatureC": 26,
          "suitability": 0.7
        },
        {
          "temperatureC": 29,
          "suitability": 0.4
        },
        {
          "temperatureC": 32,
          "suitability": 0.2
        }
      ]
    }
  },
  {
    "speciesId": "smallmouth_bass",
    "curve": {
      "curveId": "smallmouth_bass__additional_thermal_research__v0_1",
      "calibrationStatus": "provisional",
      "acceptedDomainC": [
        0,
        32
      ],
      "knots": [
        {
          "temperatureC": 0,
          "suitability": 0.35
        },
        {
          "temperatureC": 4,
          "suitability": 0.45
        },
        {
          "temperatureC": 8,
          "suitability": 0.6
        },
        {
          "temperatureC": 12,
          "suitability": 0.75
        },
        {
          "temperatureC": 16,
          "suitability": 0.9
        },
        {
          "temperatureC": 20,
          "suitability": 1
        },
        {
          "temperatureC": 26,
          "suitability": 1
        },
        {
          "temperatureC": 29,
          "suitability": 0.85
        },
        {
          "temperatureC": 32,
          "suitability": 0.6
        }
      ]
    }
  },
  {
    "speciesId": "freshwater_drum",
    "curve": {
      "curveId": "freshwater_drum__additional_thermal_research__v0_1",
      "calibrationStatus": "provisional",
      "acceptedDomainC": [
        0,
        32
      ],
      "knots": [
        {
          "temperatureC": 0,
          "suitability": 0.3
        },
        {
          "temperatureC": 4,
          "suitability": 0.4
        },
        {
          "temperatureC": 8,
          "suitability": 0.55
        },
        {
          "temperatureC": 12,
          "suitability": 0.7
        },
        {
          "temperatureC": 16,
          "suitability": 0.85
        },
        {
          "temperatureC": 20,
          "suitability": 0.95
        },
        {
          "temperatureC": 22,
          "suitability": 1
        },
        {
          "temperatureC": 27,
          "suitability": 1
        },
        {
          "temperatureC": 30,
          "suitability": 0.85
        },
        {
          "temperatureC": 32,
          "suitability": 0.65
        }
      ]
    }
  },
  {
    "speciesId": "yellow_perch",
    "curve": {
      "curveId": "yellow_perch__additional_thermal_research__v0_1",
      "calibrationStatus": "provisional",
      "acceptedDomainC": [
        0,
        32
      ],
      "knots": [
        {
          "temperatureC": 0,
          "suitability": 0.65
        },
        {
          "temperatureC": 4,
          "suitability": 0.8
        },
        {
          "temperatureC": 8,
          "suitability": 0.9
        },
        {
          "temperatureC": 12,
          "suitability": 0.95
        },
        {
          "temperatureC": 16,
          "suitability": 1
        },
        {
          "temperatureC": 21,
          "suitability": 1
        },
        {
          "temperatureC": 24,
          "suitability": 0.85
        },
        {
          "temperatureC": 27,
          "suitability": 0.65
        },
        {
          "temperatureC": 30,
          "suitability": 0.35
        },
        {
          "temperatureC": 32,
          "suitability": 0.2
        }
      ]
    }
  },
  {
    "speciesId": "lake_whitefish",
    "curve": {
      "curveId": "lake_whitefish__additional_thermal_research__v0_1",
      "calibrationStatus": "provisional",
      "acceptedDomainC": [
        0,
        26
      ],
      "knots": [
        {
          "temperatureC": 0,
          "suitability": 0.75
        },
        {
          "temperatureC": 3,
          "suitability": 0.9
        },
        {
          "temperatureC": 6,
          "suitability": 1
        },
        {
          "temperatureC": 12,
          "suitability": 1
        },
        {
          "temperatureC": 15,
          "suitability": 0.9
        },
        {
          "temperatureC": 18,
          "suitability": 0.65
        },
        {
          "temperatureC": 21,
          "suitability": 0.4
        },
        {
          "temperatureC": 24,
          "suitability": 0.2
        },
        {
          "temperatureC": 26,
          "suitability": 0.1
        }
      ]
    }
  },
  {
    "speciesId": "round_whitefish",
    "curve": {
      "curveId": "round_whitefish__additional_thermal_research__v0_1",
      "calibrationStatus": "provisional",
      "acceptedDomainC": [
        0,
        26
      ],
      "knots": [
        {
          "temperatureC": 0,
          "suitability": 0.75
        },
        {
          "temperatureC": 3,
          "suitability": 0.9
        },
        {
          "temperatureC": 6,
          "suitability": 1
        },
        {
          "temperatureC": 10,
          "suitability": 1
        },
        {
          "temperatureC": 14,
          "suitability": 0.85
        },
        {
          "temperatureC": 18,
          "suitability": 0.55
        },
        {
          "temperatureC": 22,
          "suitability": 0.25
        },
        {
          "temperatureC": 26,
          "suitability": 0.1
        }
      ]
    }
  },
  {
    "speciesId": "channel_catfish",
    "curve": {
      "curveId": "channel_catfish__additional_thermal_research__v0_1",
      "calibrationStatus": "provisional",
      "acceptedDomainC": [
        0,
        32
      ],
      "knots": [
        {
          "temperatureC": 0,
          "suitability": 0.4
        },
        {
          "temperatureC": 4,
          "suitability": 0.5
        },
        {
          "temperatureC": 8,
          "suitability": 0.65
        },
        {
          "temperatureC": 12,
          "suitability": 0.8
        },
        {
          "temperatureC": 16,
          "suitability": 0.9
        },
        {
          "temperatureC": 20,
          "suitability": 0.95
        },
        {
          "temperatureC": 24,
          "suitability": 1
        },
        {
          "temperatureC": 28,
          "suitability": 1
        },
        {
          "temperatureC": 30,
          "suitability": 0.9
        },
        {
          "temperatureC": 32,
          "suitability": 0.75
        }
      ]
    }
  },
  {
    "speciesId": "largemouth_bass",
    "curve": {
      "curveId": "largemouth_bass__additional_thermal_research__v0_1",
      "calibrationStatus": "provisional",
      "acceptedDomainC": [
        0,
        32
      ],
      "knots": [
        {
          "temperatureC": 0,
          "suitability": 0.35
        },
        {
          "temperatureC": 4,
          "suitability": 0.45
        },
        {
          "temperatureC": 8,
          "suitability": 0.6
        },
        {
          "temperatureC": 12,
          "suitability": 0.75
        },
        {
          "temperatureC": 16,
          "suitability": 0.9
        },
        {
          "temperatureC": 21,
          "suitability": 1
        },
        {
          "temperatureC": 28,
          "suitability": 1
        },
        {
          "temperatureC": 30,
          "suitability": 0.9
        },
        {
          "temperatureC": 32,
          "suitability": 0.7
        }
      ]
    }
  }
];
