// Generated by scripts/generate-pier-cast-remaining-seasonal.mjs.
// RESEARCH ONLY: owner research output; never active city profiles or public scope.
// Provisional seasonal calibration is not thermal/structure or public-release approval.
import type { PierCastCityId, PierCastSpeciesId, PierCastSeasonalOpportunityCurve } from "../types.ts";

export const PIER_CAST_ADDITIONAL_SEASONAL_RESEARCH: (PierCastSeasonalOpportunityCurve & {cityId: PierCastCityId; speciesId: PierCastSpeciesId})[] = [
  {
    "cityId": "ludington_mi",
    "speciesId": "smallmouth_bass",
    "curveId": "ludington_mi__smallmouth_bass__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 1.5
      },
      {
        "monthDay": "04-15",
        "rating": 1.5
      },
      {
        "monthDay": "05-15",
        "rating": 2.5
      },
      {
        "monthDay": "06-15",
        "rating": 3.5
      },
      {
        "monthDay": "07-15",
        "rating": 4.5
      },
      {
        "monthDay": "08-15",
        "rating": 4
      },
      {
        "monthDay": "09-15",
        "rating": 2.5
      },
      {
        "monthDay": "10-15",
        "rating": 1.5
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "ludington_mi",
    "speciesId": "freshwater_drum",
    "curveId": "ludington_mi__freshwater_drum__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 1.5
      },
      {
        "monthDay": "04-15",
        "rating": 1.5
      },
      {
        "monthDay": "05-15",
        "rating": 2
      },
      {
        "monthDay": "06-15",
        "rating": 2
      },
      {
        "monthDay": "07-15",
        "rating": 4.5
      },
      {
        "monthDay": "08-15",
        "rating": 3.5
      },
      {
        "monthDay": "09-15",
        "rating": 2
      },
      {
        "monthDay": "10-15",
        "rating": 1.5
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "ludington_mi",
    "speciesId": "yellow_perch",
    "curveId": "ludington_mi__yellow_perch__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 2
      },
      {
        "monthDay": "04-15",
        "rating": 2
      },
      {
        "monthDay": "05-15",
        "rating": 2
      },
      {
        "monthDay": "06-15",
        "rating": 5
      },
      {
        "monthDay": "07-15",
        "rating": 6
      },
      {
        "monthDay": "08-15",
        "rating": 2.5
      },
      {
        "monthDay": "09-15",
        "rating": 2
      },
      {
        "monthDay": "10-15",
        "rating": 1.5
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "grand_haven_mi",
    "speciesId": "smallmouth_bass",
    "curveId": "grand_haven_mi__smallmouth_bass__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 1.5
      },
      {
        "monthDay": "04-15",
        "rating": 2
      },
      {
        "monthDay": "05-15",
        "rating": 2.5
      },
      {
        "monthDay": "06-15",
        "rating": 3.5
      },
      {
        "monthDay": "07-15",
        "rating": 4
      },
      {
        "monthDay": "08-15",
        "rating": 5
      },
      {
        "monthDay": "09-15",
        "rating": 2.5
      },
      {
        "monthDay": "10-15",
        "rating": 1.5
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "grand_haven_mi",
    "speciesId": "freshwater_drum",
    "curveId": "grand_haven_mi__freshwater_drum__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 1.5
      },
      {
        "monthDay": "04-15",
        "rating": 2.5
      },
      {
        "monthDay": "05-15",
        "rating": 6.5
      },
      {
        "monthDay": "06-15",
        "rating": 7
      },
      {
        "monthDay": "07-15",
        "rating": 6.5
      },
      {
        "monthDay": "08-15",
        "rating": 6.5
      },
      {
        "monthDay": "09-15",
        "rating": 4.5
      },
      {
        "monthDay": "10-15",
        "rating": 2.5
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "grand_haven_mi",
    "speciesId": "lake_whitefish",
    "curveId": "grand_haven_mi__lake_whitefish__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 2
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 1.5
      },
      {
        "monthDay": "04-15",
        "rating": 2.5
      },
      {
        "monthDay": "05-15",
        "rating": 1.5
      },
      {
        "monthDay": "06-15",
        "rating": 1
      },
      {
        "monthDay": "07-15",
        "rating": 1
      },
      {
        "monthDay": "08-15",
        "rating": 1
      },
      {
        "monthDay": "09-15",
        "rating": 1
      },
      {
        "monthDay": "10-15",
        "rating": 2
      },
      {
        "monthDay": "11-15",
        "rating": 3.5
      },
      {
        "monthDay": "12-15",
        "rating": 2.5
      }
    ]
  },
  {
    "cityId": "grand_haven_mi",
    "speciesId": "round_whitefish",
    "curveId": "grand_haven_mi__round_whitefish__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 2
      },
      {
        "monthDay": "04-15",
        "rating": 4
      },
      {
        "monthDay": "05-15",
        "rating": 2
      },
      {
        "monthDay": "06-15",
        "rating": 1.5
      },
      {
        "monthDay": "07-15",
        "rating": 1
      },
      {
        "monthDay": "08-15",
        "rating": 1
      },
      {
        "monthDay": "09-15",
        "rating": 1.5
      },
      {
        "monthDay": "10-15",
        "rating": 2.5
      },
      {
        "monthDay": "11-15",
        "rating": 2.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "grand_haven_mi",
    "speciesId": "channel_catfish",
    "curveId": "grand_haven_mi__channel_catfish__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 2
      },
      {
        "monthDay": "04-15",
        "rating": 3
      },
      {
        "monthDay": "05-15",
        "rating": 4
      },
      {
        "monthDay": "06-15",
        "rating": 4
      },
      {
        "monthDay": "07-15",
        "rating": 4.5
      },
      {
        "monthDay": "08-15",
        "rating": 5.5
      },
      {
        "monthDay": "09-15",
        "rating": 5
      },
      {
        "monthDay": "10-15",
        "rating": 4
      },
      {
        "monthDay": "11-15",
        "rating": 2.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "grand_haven_mi",
    "speciesId": "largemouth_bass",
    "curveId": "grand_haven_mi__largemouth_bass__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 1.5
      },
      {
        "monthDay": "04-15",
        "rating": 2
      },
      {
        "monthDay": "05-15",
        "rating": 2.5
      },
      {
        "monthDay": "06-15",
        "rating": 4
      },
      {
        "monthDay": "07-15",
        "rating": 5
      },
      {
        "monthDay": "08-15",
        "rating": 6.5
      },
      {
        "monthDay": "09-15",
        "rating": 3.5
      },
      {
        "monthDay": "10-15",
        "rating": 2
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "manistee_mi",
    "speciesId": "lake_trout",
    "curveId": "manistee_mi__lake_trout__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 2
      },
      {
        "monthDay": "02-15",
        "rating": 2
      },
      {
        "monthDay": "03-15",
        "rating": 2.5
      },
      {
        "monthDay": "04-15",
        "rating": 3
      },
      {
        "monthDay": "05-15",
        "rating": 2.5
      },
      {
        "monthDay": "06-15",
        "rating": 1.5
      },
      {
        "monthDay": "07-15",
        "rating": 1
      },
      {
        "monthDay": "08-15",
        "rating": 1
      },
      {
        "monthDay": "09-15",
        "rating": 1.5
      },
      {
        "monthDay": "10-15",
        "rating": 3
      },
      {
        "monthDay": "11-15",
        "rating": 2.5
      },
      {
        "monthDay": "12-15",
        "rating": 2
      }
    ]
  },
  {
    "cityId": "manistee_mi",
    "speciesId": "walleye",
    "curveId": "manistee_mi__walleye__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 2
      },
      {
        "monthDay": "02-15",
        "rating": 2
      },
      {
        "monthDay": "03-15",
        "rating": 2.5
      },
      {
        "monthDay": "04-15",
        "rating": 3.5
      },
      {
        "monthDay": "05-15",
        "rating": 4.5
      },
      {
        "monthDay": "06-15",
        "rating": 2.5
      },
      {
        "monthDay": "07-15",
        "rating": 2.5
      },
      {
        "monthDay": "08-15",
        "rating": 2
      },
      {
        "monthDay": "09-15",
        "rating": 2
      },
      {
        "monthDay": "10-15",
        "rating": 2
      },
      {
        "monthDay": "11-15",
        "rating": 2
      },
      {
        "monthDay": "12-15",
        "rating": 2
      }
    ]
  },
  {
    "cityId": "manistee_mi",
    "speciesId": "smallmouth_bass",
    "curveId": "manistee_mi__smallmouth_bass__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 1.5
      },
      {
        "monthDay": "04-15",
        "rating": 2
      },
      {
        "monthDay": "05-15",
        "rating": 2.5
      },
      {
        "monthDay": "06-15",
        "rating": 3
      },
      {
        "monthDay": "07-15",
        "rating": 4.5
      },
      {
        "monthDay": "08-15",
        "rating": 3.5
      },
      {
        "monthDay": "09-15",
        "rating": 2
      },
      {
        "monthDay": "10-15",
        "rating": 1.5
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "manistee_mi",
    "speciesId": "freshwater_drum",
    "curveId": "manistee_mi__freshwater_drum__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 1.5
      },
      {
        "monthDay": "04-15",
        "rating": 1.5
      },
      {
        "monthDay": "05-15",
        "rating": 2.5
      },
      {
        "monthDay": "06-15",
        "rating": 3.5
      },
      {
        "monthDay": "07-15",
        "rating": 4.5
      },
      {
        "monthDay": "08-15",
        "rating": 2.5
      },
      {
        "monthDay": "09-15",
        "rating": 2
      },
      {
        "monthDay": "10-15",
        "rating": 1.5
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "manistee_mi",
    "speciesId": "yellow_perch",
    "curveId": "manistee_mi__yellow_perch__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 2.5
      },
      {
        "monthDay": "04-15",
        "rating": 6
      },
      {
        "monthDay": "05-15",
        "rating": 7
      },
      {
        "monthDay": "06-15",
        "rating": 4
      },
      {
        "monthDay": "07-15",
        "rating": 2
      },
      {
        "monthDay": "08-15",
        "rating": 1.5
      },
      {
        "monthDay": "09-15",
        "rating": 1.5
      },
      {
        "monthDay": "10-15",
        "rating": 1.5
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "manistee_mi",
    "speciesId": "round_whitefish",
    "curveId": "manistee_mi__round_whitefish__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 2
      },
      {
        "monthDay": "04-15",
        "rating": 3.5
      },
      {
        "monthDay": "05-15",
        "rating": 2.5
      },
      {
        "monthDay": "06-15",
        "rating": 1.5
      },
      {
        "monthDay": "07-15",
        "rating": 1
      },
      {
        "monthDay": "08-15",
        "rating": 1
      },
      {
        "monthDay": "09-15",
        "rating": 1.5
      },
      {
        "monthDay": "10-15",
        "rating": 3
      },
      {
        "monthDay": "11-15",
        "rating": 2.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  },
  {
    "cityId": "manistee_mi",
    "speciesId": "largemouth_bass",
    "curveId": "manistee_mi__largemouth_bass__annual_v1",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5
      },
      {
        "monthDay": "02-15",
        "rating": 1.5
      },
      {
        "monthDay": "03-15",
        "rating": 1.5
      },
      {
        "monthDay": "04-15",
        "rating": 1.5
      },
      {
        "monthDay": "05-15",
        "rating": 2
      },
      {
        "monthDay": "06-15",
        "rating": 2
      },
      {
        "monthDay": "07-15",
        "rating": 3
      },
      {
        "monthDay": "08-15",
        "rating": 3
      },
      {
        "monthDay": "09-15",
        "rating": 2
      },
      {
        "monthDay": "10-15",
        "rating": 1.5
      },
      {
        "monthDay": "11-15",
        "rating": 1.5
      },
      {
        "monthDay": "12-15",
        "rating": 1.5
      }
    ]
  }
];
