// Generated by scripts/generate-pier-cast-weekly-ratings.mjs.
// Source of truth: docs/PierCast_Core_Species_Seasonal_Curves.json.
// Do not hand-edit.
import type {
  PierCastCityId,
  PierCastSeasonalOpportunityCurve,
  PierCastSpeciesId,
} from "../types.ts";

export type PierCastCoreSeasonalCurve = PierCastSeasonalOpportunityCurve & {
  cityId: PierCastCityId;
  speciesId: PierCastSpeciesId;
};

export const PIER_CAST_CORE_SEASONAL_CURVES = [
  {
    "curveId": "ludington_mi__chinook_salmon__v0_1",
    "cityId": "ludington_mi",
    "speciesId": "chinook_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.4,
      },
      {
        "monthDay": "04-15",
        "rating": 1.7,
      },
      {
        "monthDay": "05-15",
        "rating": 3,
      },
      {
        "monthDay": "06-03",
        "rating": 5.8,
      },
      {
        "monthDay": "06-24",
        "rating": 4.1,
      },
      {
        "monthDay": "07-20",
        "rating": 3.6,
      },
      {
        "monthDay": "08-05",
        "rating": 4.8,
      },
      {
        "monthDay": "08-21",
        "rating": 6.8,
      },
      {
        "monthDay": "08-30",
        "rating": 8.2,
      },
      {
        "monthDay": "09-08",
        "rating": 7.8,
      },
      {
        "monthDay": "09-25",
        "rating": 4.6,
      },
      {
        "monthDay": "10-12",
        "rating": 2.1,
      },
      {
        "monthDay": "11-01",
        "rating": 1.5,
      },
      {
        "monthDay": "12-15",
        "rating": 1.4,
      },
    ],
  },
  {
    "curveId": "ludington_mi__coho_salmon__v0_1",
    "cityId": "ludington_mi",
    "speciesId": "coho_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.6,
      },
      {
        "monthDay": "03-10",
        "rating": 2.4,
      },
      {
        "monthDay": "04-05",
        "rating": 5.4,
      },
      {
        "monthDay": "05-05",
        "rating": 4.9,
      },
      {
        "monthDay": "06-05",
        "rating": 2.7,
      },
      {
        "monthDay": "07-20",
        "rating": 1.8,
      },
      {
        "monthDay": "08-25",
        "rating": 3,
      },
      {
        "monthDay": "09-26",
        "rating": 4.8,
      },
      {
        "monthDay": "10-20",
        "rating": 5,
      },
      {
        "monthDay": "11-08",
        "rating": 4.4,
      },
      {
        "monthDay": "12-05",
        "rating": 2,
      },
    ],
  },
  {
    "curveId": "ludington_mi__steelhead__v0_1",
    "cityId": "ludington_mi",
    "speciesId": "steelhead",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 2.4,
      },
      {
        "monthDay": "03-10",
        "rating": 3.5,
      },
      {
        "monthDay": "04-05",
        "rating": 5.8,
      },
      {
        "monthDay": "05-10",
        "rating": 4.2,
      },
      {
        "monthDay": "06-15",
        "rating": 2.8,
      },
      {
        "monthDay": "08-15",
        "rating": 2.5,
      },
      {
        "monthDay": "09-25",
        "rating": 3.4,
      },
      {
        "monthDay": "10-20",
        "rating": 5.4,
      },
      {
        "monthDay": "11-08",
        "rating": 6.2,
      },
      {
        "monthDay": "12-05",
        "rating": 5.1,
      },
      {
        "monthDay": "12-31",
        "rating": 2.9,
      },
    ],
  },
  {
    "curveId": "ludington_mi__brown_trout__v0_1",
    "cityId": "ludington_mi",
    "speciesId": "brown_trout",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.8,
      },
      {
        "monthDay": "03-10",
        "rating": 2.8,
      },
      {
        "monthDay": "04-05",
        "rating": 5.2,
      },
      {
        "monthDay": "04-25",
        "rating": 5,
      },
      {
        "monthDay": "05-20",
        "rating": 3.7,
      },
      {
        "monthDay": "06-20",
        "rating": 2.3,
      },
      {
        "monthDay": "08-15",
        "rating": 1.6,
      },
      {
        "monthDay": "10-15",
        "rating": 2.2,
      },
      {
        "monthDay": "11-20",
        "rating": 2.1,
      },
      {
        "monthDay": "12-31",
        "rating": 1.8,
      },
    ],
  },
  {
    "curveId": "grand_haven_mi__chinook_salmon__v0_1",
    "cityId": "grand_haven_mi",
    "speciesId": "chinook_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.3,
      },
      {
        "monthDay": "05-15",
        "rating": 1.9,
      },
      {
        "monthDay": "06-20",
        "rating": 2.8,
      },
      {
        "monthDay": "07-22",
        "rating": 5.6,
      },
      {
        "monthDay": "08-05",
        "rating": 5.2,
      },
      {
        "monthDay": "08-26",
        "rating": 6.7,
      },
      {
        "monthDay": "09-08",
        "rating": 6.1,
      },
      {
        "monthDay": "09-28",
        "rating": 3.8,
      },
      {
        "monthDay": "10-15",
        "rating": 1.9,
      },
      {
        "monthDay": "12-15",
        "rating": 1.3,
      },
    ],
  },
  {
    "curveId": "grand_haven_mi__coho_salmon__v0_1",
    "cityId": "grand_haven_mi",
    "speciesId": "coho_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5,
      },
      {
        "monthDay": "03-15",
        "rating": 2.8,
      },
      {
        "monthDay": "04-15",
        "rating": 5.7,
      },
      {
        "monthDay": "05-07",
        "rating": 5.1,
      },
      {
        "monthDay": "06-10",
        "rating": 2.5,
      },
      {
        "monthDay": "07-20",
        "rating": 1.7,
      },
      {
        "monthDay": "08-25",
        "rating": 3.4,
      },
      {
        "monthDay": "09-10",
        "rating": 4.4,
      },
      {
        "monthDay": "10-27",
        "rating": 4.6,
      },
      {
        "monthDay": "11-20",
        "rating": 2.7,
      },
      {
        "monthDay": "12-31",
        "rating": 1.5,
      },
    ],
  },
  {
    "curveId": "grand_haven_mi__steelhead__v0_1",
    "cityId": "grand_haven_mi",
    "speciesId": "steelhead",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 2,
      },
      {
        "monthDay": "03-15",
        "rating": 3,
      },
      {
        "monthDay": "04-20",
        "rating": 4.8,
      },
      {
        "monthDay": "05-10",
        "rating": 5.1,
      },
      {
        "monthDay": "06-15",
        "rating": 4.7,
      },
      {
        "monthDay": "07-22",
        "rating": 5.4,
      },
      {
        "monthDay": "08-20",
        "rating": 3.7,
      },
      {
        "monthDay": "09-25",
        "rating": 3.4,
      },
      {
        "monthDay": "10-30",
        "rating": 6.5,
      },
      {
        "monthDay": "11-10",
        "rating": 5.9,
      },
      {
        "monthDay": "12-31",
        "rating": 2.3,
      },
    ],
  },
  {
    "curveId": "grand_haven_mi__brown_trout__v0_1",
    "cityId": "grand_haven_mi",
    "speciesId": "brown_trout",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.7,
      },
      {
        "monthDay": "03-10",
        "rating": 2.7,
      },
      {
        "monthDay": "04-15",
        "rating": 5.5,
      },
      {
        "monthDay": "05-10",
        "rating": 4.9,
      },
      {
        "monthDay": "06-15",
        "rating": 2.6,
      },
      {
        "monthDay": "08-15",
        "rating": 1.6,
      },
      {
        "monthDay": "10-20",
        "rating": 2.2,
      },
      {
        "monthDay": "12-31",
        "rating": 1.7,
      },
    ],
  },
  {
    "curveId": "manistee_mi__chinook_salmon__v0_1",
    "cityId": "manistee_mi",
    "speciesId": "chinook_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.4,
      },
      {
        "monthDay": "04-15",
        "rating": 1.8,
      },
      {
        "monthDay": "05-15",
        "rating": 3,
      },
      {
        "monthDay": "06-03",
        "rating": 6,
      },
      {
        "monthDay": "06-20",
        "rating": 4.8,
      },
      {
        "monthDay": "07-20",
        "rating": 3.6,
      },
      {
        "monthDay": "08-05",
        "rating": 5,
      },
      {
        "monthDay": "08-20",
        "rating": 7.8,
      },
      {
        "monthDay": "08-30",
        "rating": 8.7,
      },
      {
        "monthDay": "09-07",
        "rating": 8.3,
      },
      {
        "monthDay": "09-24",
        "rating": 4.8,
      },
      {
        "monthDay": "10-12",
        "rating": 2.4,
      },
      {
        "monthDay": "11-15",
        "rating": 1.6,
      },
      {
        "monthDay": "12-31",
        "rating": 1.4,
      },
    ],
  },
  {
    "curveId": "manistee_mi__coho_salmon__v0_1",
    "cityId": "manistee_mi",
    "speciesId": "coho_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.9,
      },
      {
        "monthDay": "03-12",
        "rating": 4.6,
      },
      {
        "monthDay": "04-12",
        "rating": 5.8,
      },
      {
        "monthDay": "05-10",
        "rating": 4.5,
      },
      {
        "monthDay": "06-20",
        "rating": 2.3,
      },
      {
        "monthDay": "07-25",
        "rating": 2,
      },
      {
        "monthDay": "08-20",
        "rating": 4.9,
      },
      {
        "monthDay": "09-10",
        "rating": 6.4,
      },
      {
        "monthDay": "10-05",
        "rating": 6.7,
      },
      {
        "monthDay": "11-05",
        "rating": 5.3,
      },
      {
        "monthDay": "12-10",
        "rating": 2.4,
      },
    ],
  },
  {
    "curveId": "manistee_mi__steelhead__v0_1",
    "cityId": "manistee_mi",
    "speciesId": "steelhead",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 2.7,
      },
      {
        "monthDay": "03-12",
        "rating": 4.8,
      },
      {
        "monthDay": "04-10",
        "rating": 6.1,
      },
      {
        "monthDay": "05-07",
        "rating": 5.2,
      },
      {
        "monthDay": "06-26",
        "rating": 4.4,
      },
      {
        "monthDay": "07-15",
        "rating": 3.2,
      },
      {
        "monthDay": "08-25",
        "rating": 3,
      },
      {
        "monthDay": "10-05",
        "rating": 5.2,
      },
      {
        "monthDay": "10-28",
        "rating": 6.6,
      },
      {
        "monthDay": "11-10",
        "rating": 6.3,
      },
      {
        "monthDay": "12-05",
        "rating": 5.5,
      },
      {
        "monthDay": "12-31",
        "rating": 3.1,
      },
    ],
  },
  {
    "curveId": "manistee_mi__brown_trout__v0_1",
    "cityId": "manistee_mi",
    "speciesId": "brown_trout",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.9,
      },
      {
        "monthDay": "03-10",
        "rating": 3.1,
      },
      {
        "monthDay": "04-10",
        "rating": 6.2,
      },
      {
        "monthDay": "04-30",
        "rating": 5.9,
      },
      {
        "monthDay": "05-15",
        "rating": 4.7,
      },
      {
        "monthDay": "06-20",
        "rating": 2.6,
      },
      {
        "monthDay": "08-15",
        "rating": 1.7,
      },
      {
        "monthDay": "10-15",
        "rating": 2.3,
      },
      {
        "monthDay": "12-31",
        "rating": 1.9,
      },
    ],
  },
  {
    "curveId": "frankfort_elberta_mi__chinook_salmon__v0_1",
    "cityId": "frankfort_elberta_mi",
    "speciesId": "chinook_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.3,
      },
      {
        "monthDay": "04-15",
        "rating": 1.7,
      },
      {
        "monthDay": "05-20",
        "rating": 2.7,
      },
      {
        "monthDay": "06-17",
        "rating": 3.8,
      },
      {
        "monthDay": "06-25",
        "rating": 5.9,
      },
      {
        "monthDay": "07-20",
        "rating": 4,
      },
      {
        "monthDay": "08-05",
        "rating": 5.2,
      },
      {
        "monthDay": "08-16",
        "rating": 8.8,
      },
      {
        "monthDay": "08-27",
        "rating": 8.4,
      },
      {
        "monthDay": "09-10",
        "rating": 7.4,
      },
      {
        "monthDay": "09-26",
        "rating": 5.3,
      },
      {
        "monthDay": "10-15",
        "rating": 2.2,
      },
      {
        "monthDay": "11-15",
        "rating": 1.5,
      },
      {
        "monthDay": "12-31",
        "rating": 1.3,
      },
    ],
  },
  {
    "curveId": "frankfort_elberta_mi__coho_salmon__v0_1",
    "cityId": "frankfort_elberta_mi",
    "speciesId": "coho_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5,
      },
      {
        "monthDay": "03-15",
        "rating": 2,
      },
      {
        "monthDay": "04-15",
        "rating": 2.8,
      },
      {
        "monthDay": "06-15",
        "rating": 1.8,
      },
      {
        "monthDay": "08-16",
        "rating": 4.4,
      },
      {
        "monthDay": "09-15",
        "rating": 6,
      },
      {
        "monthDay": "10-05",
        "rating": 6.4,
      },
      {
        "monthDay": "11-01",
        "rating": 4.8,
      },
      {
        "monthDay": "12-01",
        "rating": 2,
      },
    ],
  },
  {
    "curveId": "frankfort_elberta_mi__steelhead__v0_1",
    "cityId": "frankfort_elberta_mi",
    "speciesId": "steelhead",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 2.5,
      },
      {
        "monthDay": "03-10",
        "rating": 4,
      },
      {
        "monthDay": "04-02",
        "rating": 7.2,
      },
      {
        "monthDay": "04-24",
        "rating": 5.4,
      },
      {
        "monthDay": "05-25",
        "rating": 3.2,
      },
      {
        "monthDay": "07-15",
        "rating": 2,
      },
      {
        "monthDay": "09-20",
        "rating": 4.5,
      },
      {
        "monthDay": "10-16",
        "rating": 8.4,
      },
      {
        "monthDay": "11-01",
        "rating": 6,
      },
      {
        "monthDay": "11-25",
        "rating": 4.5,
      },
      {
        "monthDay": "12-31",
        "rating": 2.8,
      },
    ],
  },
  {
    "curveId": "frankfort_elberta_mi__brown_trout__v0_1",
    "cityId": "frankfort_elberta_mi",
    "speciesId": "brown_trout",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.9,
      },
      {
        "monthDay": "03-10",
        "rating": 3.1,
      },
      {
        "monthDay": "04-05",
        "rating": 6,
      },
      {
        "monthDay": "05-10",
        "rating": 4.5,
      },
      {
        "monthDay": "06-25",
        "rating": 4.2,
      },
      {
        "monthDay": "07-20",
        "rating": 2.5,
      },
      {
        "monthDay": "09-01",
        "rating": 1.8,
      },
      {
        "monthDay": "10-15",
        "rating": 2.8,
      },
      {
        "monthDay": "11-20",
        "rating": 2.4,
      },
      {
        "monthDay": "12-31",
        "rating": 1.9,
      },
    ],
  },
  {
    "curveId": "sheboygan_wi__chinook_salmon__v0_1",
    "cityId": "sheboygan_wi",
    "speciesId": "chinook_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.4,
      },
      {
        "monthDay": "05-15",
        "rating": 1.8,
      },
      {
        "monthDay": "06-20",
        "rating": 2.5,
      },
      {
        "monthDay": "07-20",
        "rating": 3.4,
      },
      {
        "monthDay": "08-05",
        "rating": 4.7,
      },
      {
        "monthDay": "08-18",
        "rating": 6.6,
      },
      {
        "monthDay": "08-31",
        "rating": 8.3,
      },
      {
        "monthDay": "09-12",
        "rating": 7.6,
      },
      {
        "monthDay": "10-01",
        "rating": 5.2,
      },
      {
        "monthDay": "10-31",
        "rating": 2.3,
      },
      {
        "monthDay": "12-15",
        "rating": 1.4,
      },
    ],
  },
  {
    "curveId": "sheboygan_wi__coho_salmon__v0_1",
    "cityId": "sheboygan_wi",
    "speciesId": "coho_salmon",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 1.5,
      },
      {
        "monthDay": "03-15",
        "rating": 2.8,
      },
      {
        "monthDay": "04-15",
        "rating": 4.8,
      },
      {
        "monthDay": "05-15",
        "rating": 4.2,
      },
      {
        "monthDay": "06-20",
        "rating": 2.4,
      },
      {
        "monthDay": "07-25",
        "rating": 2,
      },
      {
        "monthDay": "08-25",
        "rating": 3.8,
      },
      {
        "monthDay": "09-15",
        "rating": 5.1,
      },
      {
        "monthDay": "10-15",
        "rating": 4.2,
      },
      {
        "monthDay": "11-15",
        "rating": 2.4,
      },
      {
        "monthDay": "12-31",
        "rating": 1.5,
      },
    ],
  },
  {
    "curveId": "sheboygan_wi__steelhead__v0_1",
    "cityId": "sheboygan_wi",
    "speciesId": "steelhead",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 2.1,
      },
      {
        "monthDay": "03-15",
        "rating": 3.5,
      },
      {
        "monthDay": "04-20",
        "rating": 5.3,
      },
      {
        "monthDay": "05-25",
        "rating": 4.4,
      },
      {
        "monthDay": "07-15",
        "rating": 3.5,
      },
      {
        "monthDay": "08-25",
        "rating": 3.8,
      },
      {
        "monthDay": "10-10",
        "rating": 5.5,
      },
      {
        "monthDay": "11-15",
        "rating": 4.4,
      },
      {
        "monthDay": "12-31",
        "rating": 2.4,
      },
    ],
  },
  {
    "curveId": "sheboygan_wi__brown_trout__v0_1",
    "cityId": "sheboygan_wi",
    "speciesId": "brown_trout",
    "calibrationStatus": "provisional",
    "knots": [
      {
        "monthDay": "01-15",
        "rating": 2.2,
      },
      {
        "monthDay": "03-10",
        "rating": 3.4,
      },
      {
        "monthDay": "04-15",
        "rating": 4.9,
      },
      {
        "monthDay": "05-20",
        "rating": 4,
      },
      {
        "monthDay": "07-15",
        "rating": 2.2,
      },
      {
        "monthDay": "09-10",
        "rating": 3.1,
      },
      {
        "monthDay": "10-20",
        "rating": 4.4,
      },
      {
        "monthDay": "11-25",
        "rating": 3.6,
      },
      {
        "monthDay": "12-31",
        "rating": 2.4,
      },
    ],
  },
] as const satisfies readonly PierCastCoreSeasonalCurve[];
