#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PATCH_SQL="$ROOT_DIR/docs/db-reconciliation/launch_required_safe_patch_20260518.sql"
VERIFY_SQL="$ROOT_DIR/docs/db-reconciliation/launch_required_safe_patch_verify_20260518.sql"
POOLER_URL_FILE="$ROOT_DIR/supabase/.temp/pooler-url"
PROJECT_REF_FILE="$ROOT_DIR/supabase/.temp/project-ref"
ENV_LOCAL_FILE="$ROOT_DIR/.env.local"
ENV_FILE="$ROOT_DIR/.env"
MODE="${1:---verify}"

if [[ "$MODE" != "--verify" && "$MODE" != "--apply" ]]; then
  echo "Usage: scripts/apply-launch-db-patch.sh [--verify|--apply]" >&2
  exit 2
fi

if [[ ! -f "$POOLER_URL_FILE" ]]; then
  echo "Missing Supabase pooler URL at $POOLER_URL_FILE." >&2
  echo "Run Supabase link/status first so the CLI writes supabase/.temp metadata." >&2
  exit 2
fi

if [[ ! -f "$PROJECT_REF_FILE" ]]; then
  echo "Missing Supabase project ref at $PROJECT_REF_FILE." >&2
  echo "Run Supabase link/status first so the CLI writes supabase/.temp metadata." >&2
  exit 2
fi

if [[ -n "${PSQL:-}" ]]; then
  PSQL_BIN="$PSQL"
elif command -v psql >/dev/null 2>&1; then
  PSQL_BIN="$(command -v psql)"
elif [[ -x "/Applications/Postgres.app/Contents/Versions/latest/bin/psql" ]]; then
  PSQL_BIN="/Applications/Postgres.app/Contents/Versions/latest/bin/psql"
else
  echo "Could not find psql. Install Postgres.app or put psql on PATH." >&2
  exit 2
fi

PROJECT_REF="$(cat "$PROJECT_REF_FILE")"
POOLER_URL="$(cat "$POOLER_URL_FILE")?sslmode=require"
CONNECT_RETRIES="${SUPABASE_DB_CONNECT_RETRIES:-6}"
RETRY_SLEEP_SECONDS="${SUPABASE_DB_RETRY_SLEEP_SECONDS:-10}"

prompt_for_password() {
  echo "Enter Supabase database password for project $PROJECT_REF:"
  read -r -s SUPABASE_DB_PASSWORD
  export SUPABASE_DB_PASSWORD
  echo
}

load_password_from_env_file() {
  local env_file="$1"
  local label="$2"

  if [[ -n "${SUPABASE_DB_PASSWORD:-}" || ! -f "$env_file" ]]; then
    return
  fi

  local value
  value="$(awk -F= '$1 == "SUPABASE_DB_PASSWORD" { sub(/^[^=]*=/, ""); print; exit }' "$env_file" | tr -d '\r')"
  value="${value%\"}"
  value="${value#\"}"
  value="${value%\'}"
  value="${value#\'}"
  if [[ -n "$value" ]]; then
    SUPABASE_DB_PASSWORD="$value"
    export SUPABASE_DB_PASSWORD
    echo "Loaded Supabase DB password from $label"
  fi
}

run_psql_file() {
  local url="$1"
  local sql_file="$2"
  PGPASSWORD="$SUPABASE_DB_PASSWORD" "$PSQL_BIN" "$url" \
    -v ON_ERROR_STOP=1 \
    -f "$sql_file"
}

run_psql_file_with_retries() {
  local sql_file="$1"
  local attempt=1

  while (( attempt <= CONNECT_RETRIES )); do
    echo "Connecting through Supabase pooler (attempt $attempt/$CONNECT_RETRIES)..."
    if run_psql_file "$POOLER_URL" "$sql_file"; then
      return 0
    fi

    if (( attempt < CONNECT_RETRIES )); then
      echo "Connection failed; waiting ${RETRY_SLEEP_SECONDS}s before retry..."
      sleep "$RETRY_SLEEP_SECONDS"
    fi
    attempt=$((attempt + 1))
  done

  return 1
}

load_password_from_env_file "$ENV_LOCAL_FILE" ".env.local"
load_password_from_env_file "$ENV_FILE" ".env"

if [[ -z "${SUPABASE_DB_PASSWORD:-}" ]]; then
  prompt_for_password
fi

if [[ "$MODE" == "--apply" ]]; then
  echo "Applying launch-required DB patch..."
  COMBINED_SQL="$(mktemp)"
  trap 'rm -f "$COMBINED_SQL"' EXIT
  {
    printf -- "-- Combined launch patch plus verification. Generated by %s.\n\n" "$0"
    printf -- "-- Begin patch SQL\n"
    cat "$PATCH_SQL"
    printf "\n-- Begin verification SQL\n"
    cat "$VERIFY_SQL"
  } > "$COMBINED_SQL"

  if ! run_psql_file_with_retries "$COMBINED_SQL"; then
    echo
    echo "Could not apply the launch DB patch." >&2
    echo "No SQL runs unless a connection succeeds. If this is still an auth error, wait a few minutes after the DB password reset and retry." >&2
    exit 1
  fi
else
  echo "Running launch DB verification..."
  if ! run_psql_file_with_retries "$VERIFY_SQL"; then
    echo
    echo "Could not run launch DB verification." >&2
    echo "If this is still an auth error, wait a few minutes after the DB password reset and retry." >&2
    exit 1
  fi
fi
