import {
  addDays,
  type AuditedRiverRunProfile,
  buildConditionRefresh,
  buildDailySnapshot,
  GRAND_CONFIGURATION_DOCUMENT,
  GRAND_FALL_CHINOOK_RUN_PROFILE,
  GRAND_FALL_COHO_RUN_PROFILE,
  GRAND_FALL_STEELHEAD_RUN_PROFILE,
  GRAND_RIVER_PROFILE,
  PLATTE_CONFIGURATION_DOCUMENT,
  PLATTE_FALL_CHINOOK_RUN_PROFILE,
  PLATTE_FALL_COHO_RUN_PROFILE,
  PLATTE_FALL_STEELHEAD_RUN_PROFILE,
  PLATTE_RIVER_PROFILE,
  resolveActiveRunWindow,
  resolveFlowBand,
  type RiverProfile,
  type RiverRunConditionRefresh,
  WHITE_CONFIGURATION_DOCUMENT,
  WHITE_FALL_CHINOOK_RUN_PROFILE,
  WHITE_FALL_COHO_RUN_PROFILE,
  WHITE_FALL_STEELHEAD_RUN_PROFILE,
  WHITE_RIVER_PROFILE,
} from "../supabase/functions/_shared/riverRunEngine/index.ts";
import type { RiverRunSnapshotResponse } from "../lib/riverRunContracts.ts";
import type { RiverRunReviewGroup } from "../lib/riverRunReviewFixtures.types.ts";
import { buildReviewLiveConditionsFixture } from "./river-run-review-live-conditions-fixture.ts";

type DraftTarget = {
  river: RiverProfile;
  run: AuditedRiverRunProfile;
  configVersion: string;
};

type ScenarioInput = {
  flowCfs?: number | null;
  flowSignal?:
    | "falling"
    | "stable"
    | "rising"
    | "meaningful_rise"
    | "sharp_rise"
    | "unknown";
  flowDelta24h?: number | null;
  flowPercentDelta24h?: number | null;
  waterTempF?: number | null;
  gaugeFreshness?: "fresh" | "stale" | "missing";
  waterTemperatureFreshness?: "fresh" | "stale" | "missing";
  weatherFreshness?: "fresh" | "stale" | "missing";
  cloudCoverPct?: number;
  shortwaveWm2?: number;
  precipitationIn?: number;
  rainSignal?:
    | "missing_rain_data"
    | "dry"
    | "light_rain"
    | "meaningful_rain"
    | "strong_rain"
    | "heavy_rain";
  activityTargetDate?: string;
};

const targets: DraftTarget[] = [
  ...[
    GRAND_FALL_CHINOOK_RUN_PROFILE,
    GRAND_FALL_COHO_RUN_PROFILE,
    GRAND_FALL_STEELHEAD_RUN_PROFILE,
  ].map((run) => ({
    river: GRAND_RIVER_PROFILE,
    run,
    configVersion: GRAND_CONFIGURATION_DOCUMENT.configVersion,
  })),
  ...[
    PLATTE_FALL_CHINOOK_RUN_PROFILE,
    PLATTE_FALL_COHO_RUN_PROFILE,
    PLATTE_FALL_STEELHEAD_RUN_PROFILE,
  ].map((run) => ({
    river: PLATTE_RIVER_PROFILE,
    run,
    configVersion: PLATTE_CONFIGURATION_DOCUMENT.configVersion,
  })),
  ...[
    WHITE_FALL_CHINOOK_RUN_PROFILE,
    WHITE_FALL_COHO_RUN_PROFILE,
    WHITE_FALL_STEELHEAD_RUN_PROFILE,
  ].map((run) => ({
    river: WHITE_RIVER_PROFILE,
    run,
    configVersion: WHITE_CONFIGURATION_DOCUMENT.configVersion,
  })),
];

const engineVersion = "river-run-v1.13.0-onboarding-review";
const groupsByRunId = Object.fromEntries(
  targets.map((target) => [target.run.runId, buildGroups(target)]),
);
const outputPath = new URL(
  "../lib/riverRunOnboardingReviewFixtures.generated.ts",
  import.meta.url,
);
const generated =
  `// This file is generated by scripts/generate-river-run-onboarding-review-fixtures.ts.
// Do not hand-edit. These hidden owner-review fixtures do not enter the public run registry.

import type { RiverRunReviewGroup } from "./riverRunReviewFixtures.types";

export const RIVER_RUN_ONBOARDING_REVIEW_GROUPS_BY_RUN_ID: Record<string, RiverRunReviewGroup[]> = ${
    JSON.stringify(groupsByRunId, null, 2)
  } as unknown as Record<string, RiverRunReviewGroup[]>;
`;

if (Deno.args.includes("--check")) {
  const current = await Deno.readTextFile(outputPath).catch(() => "");
  if (current !== generated) {
    console.error("Grand, Platte, and White review fixtures are stale.");
    Deno.exit(1);
  }
  console.log(
    `Grand, Platte, and White review fixtures are current (${scenarioCount()} scenarios).`,
  );
} else {
  await Deno.writeTextFile(outputPath, generated);
  console.log(
    `Generated ${scenarioCount()} Grand, Platte, and White review scenarios.`,
  );
}

function buildGroups(target: DraftTarget): RiverRunReviewGroup[] {
  const { run } = target;
  const window = resolveActiveRunWindow(run, `2026-${run.runWindow.peak}`);
  const stageDates = uniqueDates([
    addDays(window.preRunStartDate, -1),
    window.preRunStartDate,
    window.stagingStartDate,
    window.startDate,
    window.beginningEndDate,
    addDays(window.beginningEndDate, 1),
    window.buildingEstablishedStartDate,
    window.buildingBroadStartDate,
    window.peakStartDate,
    window.peakDate,
    window.peakEndDate,
    addDays(window.peakEndDate, 1),
    window.taperingEndDate,
    addDays(window.taperingEndDate, 1),
    window.endDate,
    addDays(window.endDate, 1),
    window.lateEndDate,
    addDays(window.lateEndDate, 1),
    window.postRunLateCopyEndDate,
    addDays(window.postRunLateCopyEndDate, 1),
  ]);
  const presenceDates = uniqueDates([
    addDays(window.startDate, -1),
    ...run.historicalPresence.anchors.map((anchor) =>
      addDays(window.startDate, anchor.dayOffsetFromStart)
    ),
    addDays(window.lateEndDate, 1),
  ]);
  const reviewDate = window.peakDate;
  const defaultFlow = representativeFlow(run);
  const activityScenarios = run.primitiveCapabilities.activity.status ===
      "unavailable"
    ? [
      scenario(
        target,
        "activity_unavailable",
        "Unavailable · reach contract",
        reviewDate,
      ),
    ]
    : [
      scenario(target, "activity_bright_dry", "Bright and dry", reviewDate, {
        cloudCoverPct: 5,
        shortwaveWm2: 720,
        precipitationIn: 0,
        rainSignal: "dry",
      }),
      scenario(target, "activity_overcast", "Overcast", reviewDate, {
        cloudCoverPct: 90,
        shortwaveWm2: 100,
        precipitationIn: 0,
        rainSignal: "dry",
      }),
      scenario(
        target,
        "activity_light_rain",
        "Overcast with light rain",
        reviewDate,
        {
          cloudCoverPct: 95,
          shortwaveWm2: 80,
          precipitationIn: 0.02,
          rainSignal: "light_rain",
        },
      ),
      scenario(
        target,
        "activity_missing_weather",
        "Unavailable weather",
        reviewDate,
        {
          weatherFreshness: "missing",
          rainSignal: "missing_rain_data",
        },
      ),
      scenario(target, "activity_tomorrow", "Tomorrow forecast", reviewDate, {
        cloudCoverPct: 90,
        shortwaveWm2: 100,
        precipitationIn: 0.02,
        rainSignal: "light_rain",
        activityTargetDate: addDays(reviewDate, 1),
      }),
      ...(run.activity?.dataMode !== "weather_only"
        ? [
          scenario(
            target,
            "activity_missing_temperature",
            "Moderate · temperature unavailable",
            reviewDate,
            { waterTempF: null, waterTemperatureFreshness: "missing" },
          ),
          scenario(
            target,
            "activity_missing_hydraulics",
            "Moderate · hydraulics unavailable",
            reviewDate,
            { flowCfs: null, gaugeFreshness: "missing", flowSignal: "unknown" },
          ),
          scenario(
            target,
            "activity_missing_both_river_inputs",
            "Unavailable · river inputs unavailable",
            reviewDate,
            {
              flowCfs: null,
              gaugeFreshness: "missing",
              flowSignal: "unknown",
              waterTempF: null,
              waterTemperatureFreshness: "missing",
            },
          ),
        ]
        : []),
    ];
  const fishabilityScenarios = run.primitiveCapabilities.fishability.status ===
        "unavailable" || !run.fishabilityBands
    ? [
      scenario(
        target,
        "fishability_unavailable",
        "Unavailable · no representative source",
        reviewDate,
      ),
    ]
    : fishabilityValues(run).map(({ id, label, value }) =>
      scenario(target, `fishability_${id}`, label, reviewDate, {
        flowCfs: value,
      })
    ).concat([
      scenario(
        target,
        "fishability_missing",
        "Unavailable · missing gauge",
        reviewDate,
        {
          flowCfs: null,
          gaugeFreshness: "missing",
          flowSignal: "unknown",
          flowDelta24h: null,
          flowPercentDelta24h: null,
        },
      ),
    ]);
  const liveConditionsScenarios = [
    scenario(
      target,
      "conditions_available",
      "Gauge Read · available",
      reviewDate,
    ),
    scenario(
      target,
      "conditions_missing_flow",
      "Gauge Read · flow missing",
      reviewDate,
      {
        flowCfs: null,
        gaugeFreshness: "missing",
        flowSignal: "unknown",
        flowDelta24h: null,
        flowPercentDelta24h: null,
      },
    ),
    ...(target.river.waterTemperatureSources.length > 0
      ? [
        scenario(
          target,
          "conditions_missing_temperature",
          "Gauge Read · temperature missing",
          reviewDate,
          {
            waterTempF: null,
            waterTemperatureFreshness: "missing",
          },
        ),
      ]
      : []),
    scenario(
      target,
      "conditions_recovered",
      "Gauge Read · recovered numeric reading",
      reviewDate,
      {
        flowCfs: defaultFlow,
        gaugeFreshness: "fresh",
        flowSignal: "rising",
        flowDelta24h: Math.max(1, Math.round(defaultFlow * 0.06)),
        flowPercentDelta24h: 6,
      },
    ),
  ];

  return [
    {
      id: "run_stage",
      label: "Migration Stage",
      scenarios: stageDates.map((date, index) => {
        const item = scenario(target, `stage_${index + 1}`, date, date);
        return {
          ...item,
          label: `${item.snapshot.runStage.label} · ${date}`,
        };
      }),
    },
    {
      id: "activity",
      label: "Activity Outlook",
      scenarios: activityScenarios,
    },
    {
      id: "fish_in_river",
      label: "Fish In River",
      scenarios: presenceDates.map((date, index) => {
        const item = scenario(target, `presence_${index + 1}`, date, date);
        return {
          ...item,
          label: `${item.snapshot.fishInRiver.label} · ${date}`,
        };
      }),
    },
    {
      id: "fishability",
      label: "Fishability",
      scenarios: fishabilityScenarios,
    },
    {
      id: "live_conditions",
      label: "Gauge Read",
      scenarios: liveConditionsScenarios,
    },
  ];
}

function scenario(
  target: DraftTarget,
  id: string,
  label: string,
  localDate: string,
  overrides: ScenarioInput = {},
) {
  const daily = buildDailySnapshot({
    river: target.river,
    run: target.run,
    localDate,
    conditionsEvidenceByDate: {},
    conditionsBaselines: null,
    engineVersion,
    configVersion: `${target.configVersion}-review`,
  });
  const condition = buildCondition(target, daily, localDate, overrides);
  const liveConditions = buildReviewLiveConditionsFixture({
    river: target.river,
    localDate,
    refreshSlot: "16:00",
    refreshedAt: `${localDate}T19:45:00.000Z`,
    flowCfs: condition.sourceMetrics.gauge?.value ?? null,
    flowDelta24h: condition.sourceMetrics.gauge?.absoluteChange24h ?? null,
    flowPercentDelta24h: condition.sourceMetrics.gauge?.percentChange24h ??
      null,
    waterTempF: condition.sourceMetrics.waterTemperature?.waterTempF ?? null,
  });
  const snapshot: RiverRunSnapshotResponse = {
    riverId: target.run.riverId,
    runId: target.run.runId,
    localDate,
    timezone: target.river.timezone,
    progressionSnapshotAt: `${localDate}T12:00:00.000Z`,
    conditionRefreshAt: `${localDate}T20:00:00.000Z`,
    refreshSlot: "16:00",
    progressionExpiresAt: `${localDate}T23:59:59.000Z`,
    nextConditionRefreshAt: `${addDays(localDate, 1)}T05:00:00.000Z`,
    runStage: condition.runStage,
    conditionsSuggest: condition.conditionsSuggest,
    push: condition.push,
    pushHistory: {
      status: "none_recorded",
      minimumSupportiveScore: 50,
      trackingStartDate: condition.runStage.window.startDate,
      trackingEndDate: condition.runStage.window.endDate,
      throughDate: localDate,
      recentDailyReadsStatus: "available",
      recentDailyReads: [],
    },
    fishability: condition.fishability,
    activity: condition.activity,
    fishInRiver: condition.fishInRiver,
    riverConditions: liveConditions,
    gauge: condition.sourceMetrics.gauge ?? null,
    weather: condition.sourceMetrics.weather ?? null,
    waterTemperature: condition.sourceMetrics.waterTemperature ?? null,
    conditionsWaterTemperature:
      condition.sourceMetrics.conditionsWaterTemperature ?? null,
    freshness: condition.freshness,
    dataQuality: condition.dataQuality,
    interpretationNote: condition.interpretationNote ?? null,
    secondaryNote: target.river.gaugeLimitationCopy,
    safety: {
      regulationReminder: target.river.regulationReminderCopy ??
        "Check current regulations and posted boundaries before fishing.",
      gaugeBasis: target.river.gaugeLimitationCopy,
      activityDisclaimer:
        "River Migration is not a wading, boating, floating, or personal-safety rating.",
    },
    engineVersion: condition.engineVersion,
    configVersion: condition.configVersion,
  };
  return {
    id,
    label,
    note:
      `${target.river.displayName} ${target.run.displayName} hidden owner-review fixture`,
    snapshot,
  };
}

function buildCondition(
  target: DraftTarget,
  daily: ReturnType<typeof buildDailySnapshot>,
  localDate: string,
  overrides: ScenarioInput,
): RiverRunConditionRefresh {
  const run = target.run;
  const river = target.river;
  const hydraulic = river.hydraulicSources.find((source) =>
    source.role === "primary"
  );
  const temperature =
    [...river.waterTemperatureSources].sort((a, b) =>
      a.priority - b.priority
    )[0];
  const weatherPoint = river.weatherPoints.find((point) =>
    point.role === "primary"
  );
  const flowCfs = overrides.flowCfs === undefined
    ? representativeFlow(run)
    : overrides.flowCfs;
  const waterTempF = overrides.waterTempF === undefined
    ? temperature ? 58 : null
    : overrides.waterTempF;
  const gaugeFreshness = overrides.gaugeFreshness ??
    (flowCfs == null ? "missing" : "fresh");
  const waterTemperatureFreshness = overrides.waterTemperatureFreshness ??
    (waterTempF == null ? "missing" : "fresh");
  const weatherFreshness = overrides.weatherFreshness ?? "fresh";
  const flowSignal = overrides.flowSignal ?? "stable";
  const flowDelta24h = overrides.flowDelta24h === undefined
    ? 0
    : overrides.flowDelta24h;
  const flowPercentDelta24h = overrides.flowPercentDelta24h === undefined
    ? 0
    : overrides.flowPercentDelta24h;
  const targetDate = overrides.activityTargetDate ?? localDate;
  const targetDaily = targetDate === localDate ? daily : buildDailySnapshot({
    river,
    run,
    localDate: targetDate,
    conditionsEvidenceByDate: {},
    conditionsBaselines: null,
    engineVersion,
    configVersion: `${target.configVersion}-review`,
  });
  const activityActive =
    targetDate >= targetDaily.runStage.window.stagingStartDate &&
    targetDate <= targetDaily.runStage.window.lateEndDate;
  const flowBand = flowCfs == null || !run.fishabilityBands
    ? undefined
    : resolveFlowBand({
      metric: "flow_cfs",
      value: flowCfs,
      fishabilityBands: run.fishabilityBands,
    })?.band;
  const hourlyActivityWeather = Array.from({ length: 24 }, (_, hour) => ({
    time_local: `${targetDate}T${String(hour).padStart(2, "0")}:00`,
    cloud_cover_pct: overrides.cloudCoverPct ?? 65,
    shortwave_w_m2: hour >= 8 && hour <= 18 ? overrides.shortwaveWm2 ?? 260 : 0,
    clear_sky_shortwave_w_m2: hour >= 8 && hour <= 18 ? 650 : 0,
    precipitation_in: overrides.precipitationIn ?? 0,
  }));

  return buildConditionRefresh({
    dailySnapshot: daily,
    localDate,
    refreshSlot: "16:00",
    movementEngineId: run.movementEngineId,
    primitiveCapabilities: run.primitiveCapabilities,
    pushRules: run.push,
    fishabilityBands: run.fishabilityBands,
    activityRules: activityActive ? run.activity : undefined,
    activityTargetDate: activityActive ? targetDate : undefined,
    activityTargetStage: targetDaily.runStage.stage,
    activityStaging: targetDaily.runStage.stagingContext,
    gaugeFreshness,
    weatherFreshness,
    waterTemperatureFreshness,
    conditionsWaterTemperatureFreshness: waterTemperatureFreshness,
    flowBand,
    currentHydraulicValue: flowCfs,
    hydraulicAbsoluteChange24h: flowDelta24h,
    hydraulicPercentChange24h: flowPercentDelta24h,
    rainSignal: overrides.rainSignal ?? "dry",
    flowSignal,
    temperatureSignal: "neutral",
    temperatureSourceType: temperature?.sourceType ?? "unavailable",
    waterTempF,
    missingNonGaugeInputCount: weatherFreshness === "missing" ? 1 : 0,
    sourceMetrics: {
      ...(flowCfs == null || !hydraulic ? {} : {
        gauge: {
          provider: "USGS" as const,
          siteId: hydraulic.siteId,
          observedAt: `${localDate}T19:45:00.000Z`,
          primaryMetric: "flow_cfs" as const,
          value: flowCfs,
          band: flowBand,
          trend: flowSignal,
          absoluteChange24h: flowDelta24h,
          percentChange24h: flowPercentDelta24h,
        },
      }),
      ...(weatherFreshness === "missing" || !weatherPoint ? {} : {
        weather: {
          provider: "OPEN_METEO" as const,
          evidenceType: "modeled_grid" as const,
          weatherPointId: weatherPoint.weatherPointId,
          rain24hIn: overrides.precipitationIn ?? 0,
          rain48hIn: overrides.precipitationIn ?? 0,
          rain72hIn: overrides.precipitationIn ?? 0,
          hourlyActivityWeather,
        },
      }),
      ...(waterTempF == null || !temperature ? {} : {
        waterTemperature: {
          provider: temperature.provider,
          sourceId: temperature.sourceId,
          siteId: temperature.siteId,
          observedAt: `${localDate}T19:45:00.000Z`,
          waterTempF,
          trend: "neutral" as const,
          sourceType: temperature.sourceType,
          attribution: temperature.attribution,
        },
        conditionsWaterTemperature: {
          provider: temperature.provider,
          sourceId: temperature.sourceId,
          siteId: temperature.siteId,
          observedAt: `${localDate}T19:45:00.000Z`,
          waterTempF,
          trend: "neutral" as const,
          sourceType: temperature.sourceType,
          attribution: temperature.attribution,
        },
      }),
    },
    engineVersion,
    configVersion: `${target.configVersion}-review`,
  });
}

function representativeFlow(run: AuditedRiverRunProfile): number {
  const bands = run.fishabilityBands;
  if (!bands) return 165;
  return Math.round((bands.ideal.min + bands.ideal.max) / 2);
}

function fishabilityValues(run: AuditedRiverRunProfile) {
  const bands = run.fishabilityBands!;
  return [
    {
      id: "very_low",
      label: `Very low · ${
        Math.max(1, bands.tooLow.max - 1).toLocaleString("en-US")
      } CFS`,
      value: Math.max(1, bands.tooLow.max - 1),
    },
    {
      id: "low",
      label: `Low · ${bands.lowFishable.min.toLocaleString("en-US")} CFS`,
      value: bands.lowFishable.min,
    },
    {
      id: "ideal",
      label: `Ideal · ${representativeFlow(run).toLocaleString("en-US")} CFS`,
      value: representativeFlow(run),
    },
    {
      id: "high",
      label: `High · ${bands.highFishable.min.toLocaleString("en-US")} CFS`,
      value: bands.highFishable.min,
    },
    {
      id: "very_high",
      label: `Very high · ${
        Math.max(bands.highFishable.max + 1, bands.blownOut.min - 1)
          .toLocaleString("en-US")
      } CFS`,
      value: Math.max(bands.highFishable.max + 1, bands.blownOut.min - 1),
    },
    {
      id: "blown_out",
      label: `Blown out · ${bands.blownOut.min.toLocaleString("en-US")} CFS`,
      value: bands.blownOut.min,
    },
  ];
}

function uniqueDates(values: Array<string | undefined>): string[] {
  return [
    ...new Set(values.filter((value): value is string => Boolean(value))),
  ];
}

function scenarioCount(): number {
  return Object.values(groupsByRunId).reduce(
    (total, groups) =>
      total + groups.reduce(
        (groupTotal, group) => groupTotal + group.scenarios.length,
        0,
      ),
    0,
  );
}
