type RiverDefinition = {
  id: "milwaukee" | "sheboygan" | "root";
  siteId: string;
  startYear: number;
  endYear: number;
  targetEndMonthDay: string;
};

type DailyValue = { localDate: string; value: number };
type GeneratedNormal = {
  average: number;
  p10: number;
  p25: number;
  median: number;
  p75: number;
  p90: number;
  historicalYears: number;
  sampleCount: number;
  availableWindowDays: number;
  windowStartMonthDay: string;
  windowEndMonthDay: string;
};

const RIVERS: RiverDefinition[] = [
  {
    id: "milwaukee",
    siteId: "04087000",
    startYear: 2019,
    endYear: 2025,
    targetEndMonthDay: "02-15",
  },
  {
    id: "sheboygan",
    siteId: "04086000",
    startYear: 2019,
    endYear: 2025,
    targetEndMonthDay: "02-15",
  },
  {
    id: "root",
    siteId: "04087240",
    startYear: 2019,
    endYear: 2024,
    targetEndMonthDay: "02-15",
  },
];

const OUTPUT = new URL(
  "../supabase/functions/_shared/riverRunEngine/config/onboarding/wisconsinFixedFlowSeasonal.generated.ts",
  import.meta.url,
);

const output: Record<string, Record<string, GeneratedNormal>> = {};
for (const river of RIVERS) {
  const daily = await fetchDailyValues(river);
  validateDailyCoverage(river, daily);
  output[river.id] = buildNormals(daily, river.targetEndMonthDay);
}

const source =
  `// Generated by scripts/generate-wisconsin-fixed-flow-seasonal-baselines.ts.\n` +
  `// Do not edit by hand. Values are approved USGS daily mean discharge.\n\n` +
  `import type { FixedFlowSeasonalNormal } from "../../types.ts";\n\n` +
  `export const WISCONSIN_FIXED_FLOW_SEASONAL_NORMALS: Readonly<Record<string, Readonly<Record<string, FixedFlowSeasonalNormal>>>> = ${
    JSON.stringify(output, null, 2)
  };\n`;
await Deno.writeTextFile(OUTPUT, source);

async function fetchDailyValues(
  river: RiverDefinition,
): Promise<DailyValue[]> {
  const url = new URL("https://waterservices.usgs.gov/nwis/dv/");
  url.search = new URLSearchParams({
    format: "json",
    sites: river.siteId,
    startDT: `${river.startYear}-01-01`,
    endDT: `${river.endYear}-12-31`,
    parameterCd: "00060",
    statCd: "00003",
    siteStatus: "all",
  }).toString();
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${river.id}: USGS ${response.status}`);
  const payload = await response.json();
  const raw = payload?.value?.timeSeries?.[0]?.values?.[0]?.value ?? [];
  return raw.flatMap((item: { dateTime?: unknown; value?: unknown }) => {
    const localDate = String(item.dateTime ?? "").slice(0, 10);
    const value = Number(item.value);
    return /^\d{4}-\d{2}-\d{2}$/.test(localDate) && Number.isFinite(value) &&
        value >= 0
      ? [{ localDate, value }]
      : [];
  });
}

function buildNormals(
  daily: DailyValue[],
  targetEndMonthDay: string,
): Record<string, GeneratedNormal> {
  const result: Record<string, GeneratedNormal> = {};
  for (const target of targetMonthDays(targetEndMonthDay)) {
    const window = windowMonthDays(target);
    const allowed = new Set(window);
    const samples = daily.filter((item) =>
      allowed.has(item.localDate.slice(5))
    );
    const values = samples.map((item) => item.value);
    if (values.length === 0) {
      throw new Error(`${target}: no valid daily values in the ±3-day window`);
    }
    result[target] = {
      average: rounded(mean(values)),
      p10: rounded(percentile(values, .1)),
      p25: rounded(percentile(values, .25)),
      median: rounded(percentile(values, .5)),
      p75: rounded(percentile(values, .75)),
      p90: rounded(percentile(values, .9)),
      historicalYears: new Set(samples.map((item) =>
        item.localDate.slice(0, 4)
      )).size,
      sampleCount: samples.length,
      availableWindowDays:
        new Set(samples.map((item) => item.localDate.slice(5))).size,
      windowStartMonthDay: window[0],
      windowEndMonthDay: window[window.length - 1],
    };
  }
  return result;
}

function validateDailyCoverage(
  river: RiverDefinition,
  daily: DailyValue[],
): void {
  if (daily.length === 0) {
    throw new Error(`${river.id}: USGS returned no valid daily mean discharge`);
  }
  const years = new Set(daily.map((item) => item.localDate.slice(0, 4)));
  const expectedYears = river.endYear - river.startYear + 1;
  if (years.size !== expectedYears) {
    throw new Error(
      `${river.id}: expected data from ${expectedYears} calendar years, received ${years.size}`,
    );
  }
  const invalidYear = [...years].find((year) => {
    const numeric = Number(year);
    return numeric < river.startYear || numeric > river.endYear;
  });
  if (invalidYear) {
    throw new Error(`${river.id}: received out-of-range year ${invalidYear}`);
  }
}

function targetMonthDays(endMonthDay: string): string[] {
  const start = Date.parse("2000-08-01T12:00:00Z");
  const endYear = endMonthDay < "08-01" ? 2001 : 2000;
  const end = Date.parse(`${endYear}-${endMonthDay}T12:00:00Z`);
  const result: string[] = [];
  for (let time = start; time <= end; time += 86_400_000) {
    result.push(new Date(time).toISOString().slice(5, 10));
  }
  return result;
}

function windowMonthDays(monthDay: string): string[] {
  const year = monthDay.startsWith("01-") ? 2001 : 2000;
  const center = Date.parse(`${year}-${monthDay}T12:00:00Z`);
  return Array.from(
    { length: 7 },
    (_, index) =>
      new Date(center + (index - 3) * 86_400_000).toISOString().slice(5, 10),
  );
}

function mean(values: number[]): number {
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function percentile(values: number[], fraction: number): number {
  const sorted = [...values].sort((left, right) => left - right);
  const index = (sorted.length - 1) * fraction;
  const lower = Math.floor(index);
  const upper = Math.ceil(index);
  return sorted[lower] + (sorted[upper] - sorted[lower]) * (index - lower);
}

function rounded(value: number): number {
  return Math.round(value * 1000) / 1000;
}
