import {
  addDays,
  canonicalBaselineDay,
  type ConditionsSuggestCheckpoint,
  type ConditionsSuggestEvidence,
  type ConditionsSuggestEvidenceByDate,
  daysBetween,
  PERE_MARQUETTE_FALL_CHINOOK_RUN_PROFILE,
  type PrimitiveDisplay,
  resolveConditionsSuggestCheckpoints,
  resolveInterpretationNote,
  resolveRunStage,
  type RiverRunConditionsSuggestBaseline,
  type RiverRunCopyVariant,
  scoreConditionsSuggest,
  scoreFishability,
  scoreFishInRiver,
  scorePush,
} from "../supabase/functions/_shared/riverRunEngine/index.ts";
import type {
  RiverRunConditionsSuggest,
  RiverRunFishability,
  RiverRunFishInRiver,
  RiverRunPush,
  RiverRunSnapshotResponse,
  RiverRunStage,
} from "../lib/riverRunContracts.ts";

type Scenario = {
  id: string;
  label: string;
  note?: string;
  snapshot: RiverRunSnapshotResponse;
};

type Group = {
  id: string;
  label: string;
  scenarios: Scenario[];
};

const run = PERE_MARQUETTE_FALL_CHINOOK_RUN_PROFILE;
const checkpoints = resolveConditionsSuggestCheckpoints(run, "2026-09-20");
const outputPath = new URL(
  "../lib/riverRunReviewFixtures.generated.ts",
  import.meta.url,
);

const groups: Group[] = [
  runStageGroup(),
  conditionsGroup(),
  pushGroup(),
  fishabilityGroup(),
  fishInRiverGroup(),
  combinedGroup(),
  evidenceGroup(),
];
const baseByVariant = {
  A: snapshotScenario({
    id: "generated_base",
    label: "Generated base",
    localDate: "2026-09-05",
    variant: "A",
  }).snapshot,
  B: snapshotScenario({
    id: "generated_base",
    label: "Generated base",
    localDate: "2026-09-05",
    variant: "B",
  }).snapshot,
};
const compactGroups = groups.map((group) => ({
  id: group.id,
  label: group.label,
  scenarios: group.scenarios.map((scenario) => {
    const variant = scenario.snapshot.runStage.copyVariant ?? "A";
    return {
      id: scenario.id,
      label: scenario.label,
      note: scenario.note,
      variant,
      snapshotOverride: shallowSnapshotDiff(
        baseByVariant[variant],
        scenario.snapshot,
      ),
    };
  }),
}));

const generated =
  `// This file is generated by scripts/generate-river-run-review-fixtures.ts.
// Do not hand-edit. Every primitive card below comes from production scoring code.

import type { RiverRunReviewGroup } from "./riverRunReviewFixtures.types";
import type { RiverRunSnapshotResponse } from "./riverRunContracts";

const BASE_BY_VARIANT = ${
    JSON.stringify(baseByVariant, null, 2)
  } as unknown as Record<"A" | "B", RiverRunSnapshotResponse>;

const GROUP_SEEDS = ${JSON.stringify(compactGroups, null, 2)} as const;

export const RIVER_RUN_REVIEW_GROUPS: RiverRunReviewGroup[] = GROUP_SEEDS.map(
  (group) => ({
    id: group.id,
    label: group.label,
    scenarios: group.scenarios.map((scenario) => ({
      id: scenario.id,
      label: scenario.label,
      note: scenario.note,
      snapshot: {
        ...BASE_BY_VARIANT[scenario.variant],
        ...scenario.snapshotOverride,
      } as RiverRunSnapshotResponse,
    })),
  }),
);
`;

if (Deno.args.includes("--check")) {
  const current = await Deno.readTextFile(outputPath).catch(() => "");
  if (current !== generated) {
    console.error(
      "River Run review fixtures are stale. Run npm run generate:river-run:review-fixtures.",
    );
    Deno.exit(1);
  }
  console.log(
    `River Run review fixtures match production copy (${
      scenarioCount(groups)
    } scenarios).`,
  );
} else {
  await Deno.writeTextFile(outputPath, generated);
  console.log(
    `Generated ${
      scenarioCount(groups)
    } River Run review scenarios from production scoring code.`,
  );
}

function runStageGroup(): Group {
  const states = [
    ["before_staging", "Before staging", "2026-07-20"],
    ["staging", "Staging period", "2026-08-01"],
    ["beginning", "Beginning", "2026-08-15"],
    ["building", "Building", "2026-09-05"],
    ["peak", "Peak", "2026-09-20"],
    ["tapering", "Tapering", "2026-10-01"],
    ["ending", "Ending", "2026-10-15"],
    ["post", "Post-run", "2026-11-05"],
  ] as const;
  return {
    id: "run_stage",
    label: "Run Stage",
    scenarios: withBothVariants(
      states.flatMap(([id, label, localDate]) =>
        variants().map((variant) =>
          snapshotScenario({
            id: `stage_${id}`,
            label,
            localDate,
            variant,
          })
        )
      ),
    ),
  };
}

function conditionsGroup(): Group {
  const target = checkpoint("river_start");
  const second = checkpoint("building_start");
  const peakComplete = checkpoint("peak_complete");

  const basic = [
    {
      id: "before_collection",
      label: "Before evidence collection",
      localDate: "2026-07-20",
      make: (variant: RiverRunCopyVariant) =>
        scoreConditionsSuggest({
          localDate: "2026-07-20",
          run,
          evidenceByDate: {},
          baselines: [],
          copyVariant: variant,
        }),
    },
    {
      id: "collecting",
      label: "Collecting first read",
      localDate: "2026-08-01",
      make: (variant: RiverRunCopyVariant) =>
        scoreConditionsSuggest({
          localDate: "2026-08-01",
          run,
          evidenceByDate: {},
          baselines: [],
          copyVariant: variant,
        }),
    },
    ...(["ahead", "typical", "delayed"] as const).map((kind) => ({
      id: kind,
      label: title(kind),
      localDate: target.checkpointDate,
      make: (variant: RiverRunCopyVariant) =>
        scoreConditionsSuggest({
          localDate: target.checkpointDate,
          run,
          evidenceByDate: cumulativeEvidence(target, kind),
          baselines: [baseline(target)],
          copyVariant: variant,
        }),
    })),
    {
      id: "mixed",
      label: "Typical · mixed signals",
      localDate: target.checkpointDate,
      make: (variant: RiverRunCopyVariant) =>
        scoreConditionsSuggest({
          localDate: target.checkpointDate,
          run,
          evidenceByDate: mixedEvidence(target),
          baselines: [baseline(target)],
          copyVariant: variant,
        }),
    },
    {
      id: "tempered_reversal",
      label: "Typical · reversal tempered",
      localDate: second.checkpointDate,
      make: (variant: RiverRunCopyVariant) =>
        scoreConditionsSuggest({
          localDate: second.checkpointDate,
          run,
          evidenceByDate: cumulativeEvidence(second, "ahead"),
          baselines: [
            baseline(target),
            delayedSecondBaseline(second),
          ],
          copyVariant: variant,
        }),
    },
    {
      id: "complete_underway",
      label: "Timing complete · underway",
      localDate: peakComplete.checkpointDate,
      make: (variant: RiverRunCopyVariant) =>
        scoreConditionsSuggest({
          localDate: peakComplete.checkpointDate,
          run,
          evidenceByDate: cumulativeEvidence(peakComplete, "typical"),
          baselines: allBaselines(),
          copyVariant: variant,
        }),
    },
    {
      id: "complete_post",
      label: "Timing complete · post-run",
      localDate: "2026-10-25",
      make: (variant: RiverRunCopyVariant) =>
        scoreConditionsSuggest({
          localDate: "2026-10-25",
          run,
          evidenceByDate: cumulativeEvidence(peakComplete, "typical"),
          baselines: allBaselines(),
          copyVariant: variant,
        }),
    },
    {
      id: "complete_insufficient",
      label: "Timing complete · insufficient",
      localDate: peakComplete.checkpointDate,
      make: (variant: RiverRunCopyVariant) =>
        scoreConditionsSuggest({
          localDate: peakComplete.checkpointDate,
          run,
          evidenceByDate: cumulativeEvidence(peakComplete, "typical"),
          baselines: allBaselines().slice(0, 3),
          copyVariant: variant,
        }),
    },
  ];

  const insufficient = insufficientConditionCases(target);
  return {
    id: "conditions",
    label: "Run Timing",
    scenarios: withBothVariants(
      [...basic, ...insufficient].flatMap((item) =>
        variants().map((variant) =>
          snapshotScenario({
            id: `conditions_${item.id}`,
            label: item.label,
            localDate: item.localDate,
            variant,
            conditionsSuggest: item.make(variant),
          })
        )
      ),
    ),
  };
}

function pushGroup(): Group {
  const base = {
    movementEngineId: "fall_cooling" as const,
    rules: run.push,
    gaugeFreshness: "fresh" as const,
    rainSignal: "light_rain" as const,
    flowSignal: "stable" as const,
    currentHydraulicValue: 550,
    hydraulicAbsoluteChange24h: 0,
    hydraulicPercentChange24h: 0,
    temperatureSignal: "neutral" as const,
    temperatureSourceType: "same_gauge" as const,
    waterTempF: 60,
    trackingState: "active" as const,
    trackingStartDate: "2026-08-15",
    trackingEndDate: "2026-10-20",
    localDate: "2026-09-05",
  };
  const cases = [
    ["weak", "Weak · warm, dry, falling", {
      rainSignal: "dry",
      flowSignal: "falling",
      currentHydraulicValue: 500,
      hydraulicAbsoluteChange24h: -40,
      hydraulicPercentChange24h: -7.4,
      temperatureSignal: "strong_warming",
      waterTempF: 69,
    }],
    ["no_clear", "No clear push · steady", {}],
    ["possible", "Possible · early response", {
      rainSignal: "meaningful_rain",
      flowSignal: "rising",
      currentHydraulicValue: 600,
      hydraulicAbsoluteChange24h: 25,
      hydraulicPercentChange24h: 4.3,
      temperatureSignal: "cooling",
      waterTempF: 62,
    }],
    ["strong", "Strong · meaningful rise", {
      rainSignal: "strong_rain",
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      temperatureSignal: "cooling",
      waterTempF: 59,
    }],
    ["very_strong", "Very strong · sharp rise", {
      rainSignal: "heavy_rain",
      flowSignal: "sharp_rise",
      currentHydraulicValue: 800,
      hydraulicAbsoluteChange24h: 130,
      hydraulicPercentChange24h: 19.4,
      temperatureSignal: "strong_cooling",
      waterTempF: 57,
    }],
    ["rain_precursor", "Rain · early precursor", {
      rainSignal: "heavy_rain",
      flowSignal: "stable",
      temperatureSignal: "cooling",
    }],
    ["rain_absorbed", "Rain · reflected in gauge", {
      rainSignal: "heavy_rain",
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
    }],
    ["rain_suppressed", "Rain · river already high", {
      rainSignal: "heavy_rain",
      flowSignal: "rising",
      currentHydraulicValue: 900,
      hydraulicAbsoluteChange24h: 30,
      hydraulicPercentChange24h: 3.4,
    }],
    ["rain_missing", "Rain · unavailable", {
      rainSignal: "missing_rain_data",
    }],
    ["temperature_transitional", "Temperature · transitional warm", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      waterTempF: 67.5,
      temperatureSignal: "cooling",
    }],
    ["temperature_too_warm", "Temperature · too warm", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      waterTempF: 69,
      temperatureSignal: "cooling",
    }],
    ["temperature_barrier", "Temperature · warm barrier", {
      flowSignal: "sharp_rise",
      currentHydraulicValue: 800,
      hydraulicAbsoluteChange24h: 130,
      hydraulicPercentChange24h: 19.4,
      waterTempF: 70,
      temperatureSignal: "strong_cooling",
    }],
    ["temperature_plateau", "Temperature · cool plateau", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      waterTempF: 48,
      temperatureSignal: "strong_cooling",
    }],
    ["upstream_no_credit", "Temperature · upstream fallback", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      temperatureSignal: "strong_cooling",
      temperatureSourceType: "nearby_gauge",
      temperaturePositiveSignalCap: 0,
    }],
    ["unknown_trend", "Gauge trend · unresolved", {
      flowSignal: "unknown",
      hydraulicAbsoluteChange24h: null,
      hydraulicPercentChange24h: null,
      rainSignal: "heavy_rain",
      temperatureSignal: "cooling",
    }],
    ["stale_cap", "Gauge · stale", {
      gaugeFreshness: "stale",
      flowSignal: "sharp_rise",
      currentHydraulicValue: 800,
      hydraulicAbsoluteChange24h: 130,
      hydraulicPercentChange24h: 19.4,
      rainSignal: "heavy_rain",
      temperatureSignal: "strong_cooling",
    }],
    ["severe_high", "Gauge · severe high cap", {
      flowSignal: "sharp_rise",
      currentHydraulicValue: 1200,
      hydraulicAbsoluteChange24h: 200,
      hydraulicPercentChange24h: 20,
      rainSignal: "heavy_rain",
      temperatureSignal: "strong_cooling",
    }],
    ["unavailable_gauge", "Unavailable · gauge", {
      gaugeFreshness: "missing",
      currentHydraulicValue: null,
    }],
    ["unavailable_temperature", "Unavailable · water temperature", {
      temperatureSourceType: "unavailable",
      waterTempF: null,
    }],
    ["unavailable_engine", "Unavailable · run type", {
      movementEngineId: "spring_warming",
    }],
    ["not_started", "Tracking not started", {
      trackingState: "not_started",
      localDate: "2026-08-01",
    }],
    ["complete", "Tracking complete", {
      trackingState: "complete",
      localDate: "2026-10-25",
    }],
  ] as const;

  return {
    id: "push",
    label: "Push",
    scenarios: withBothVariants(
      cases.flatMap(([id, label, overrides]) =>
        variants().map((variant) => {
          const input = { ...base, ...overrides, copyVariant: variant };
          return snapshotScenario({
            id: `push_${id}`,
            label,
            localDate: input.localDate,
            variant,
            push: scorePush(input),
          });
        })
      ),
    ),
  };
}

function fishabilityGroup(): Group {
  const base = {
    rules: run.fishabilityBands,
    gaugeFreshness: "fresh" as const,
    flowSignal: "stable" as const,
    currentHydraulicValue: 600,
    hydraulicAbsoluteChange24h: 0,
    hydraulicPercentChange24h: 0,
    localDate: "2026-09-05",
  };
  const cases = [
    ["very_low", "Tough · very low", {
      flowBand: "very_low",
      currentHydraulicValue: 350,
    }],
    ["low", "Fishable · low", {
      flowBand: "low",
      currentHydraulicValue: 450,
    }],
    ["normal", "Good · normal", {
      flowBand: "normal_fishable",
      currentHydraulicValue: 500,
    }],
    ["ideal", "Excellent · ideal", {
      flowBand: "ideal",
      currentHydraulicValue: 600,
    }],
    ["high", "Fishable · high", {
      flowBand: "high_fishable",
      currentHydraulicValue: 850,
    }],
    ["very_high", "Tough · very high", {
      flowBand: "very_high",
      currentHydraulicValue: 1200,
    }],
    ["blown", "Poor · blown out", {
      flowBand: "blown_out",
      currentHydraulicValue: 1700,
    }],
    ["falling", "Trend · falling", {
      flowBand: "ideal",
      flowSignal: "falling",
      currentHydraulicValue: 600,
      hydraulicAbsoluteChange24h: -45,
      hydraulicPercentChange24h: -7,
    }],
    ["rising", "Trend · early rise", {
      flowBand: "ideal",
      flowSignal: "rising",
      currentHydraulicValue: 650,
      hydraulicAbsoluteChange24h: 25,
      hydraulicPercentChange24h: 4,
    }],
    ["meaningful", "Trend · meaningful rise", {
      flowBand: "high_fishable",
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 850,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 9,
    }],
    ["sharp", "Trend · sharp rise", {
      flowBand: "high_fishable",
      flowSignal: "sharp_rise",
      currentHydraulicValue: 900,
      hydraulicAbsoluteChange24h: 130,
      hydraulicPercentChange24h: 17,
    }],
    ["unknown", "Trend · unresolved", {
      flowBand: "ideal",
      flowSignal: "unknown",
      hydraulicAbsoluteChange24h: null,
      hydraulicPercentChange24h: null,
    }],
    ["stale", "Gauge · stale", {
      flowBand: "ideal",
      gaugeFreshness: "stale",
    }],
    ["unavailable_gauge", "Unavailable · gauge", {
      flowBand: "ideal",
      gaugeFreshness: "missing",
      currentHydraulicValue: null,
    }],
    ["unavailable_band", "Unavailable · river bands", {
      flowBand: undefined,
    }],
  ] as const;
  return {
    id: "fishability",
    label: "Fishability",
    scenarios: withBothVariants(
      cases.flatMap(([id, label, overrides]) =>
        variants().map((variant) =>
          snapshotScenario({
            id: `fishability_${id}`,
            label,
            localDate: base.localDate,
            variant,
            fishability: scoreFishability({
              ...base,
              ...overrides,
              copyVariant: variant,
            }),
          })
        )
      ),
    ),
  };
}

function fishInRiverGroup(): Group {
  const byBranch = new Map<string, string>();
  for (
    let localDate = "2026-07-20";
    localDate <= "2026-11-10";
    localDate = addDays(localDate, 1)
  ) {
    const result = scoreFishInRiver(run, localDate, { copyVariant: "A" });
    const phase = result.score === 0
      ? result.stage
      : `${result.label}:${result.curveDirection}`;
    if (!byBranch.has(phase)) byBranch.set(phase, localDate);
  }
  const scenarios = [...byBranch.entries()].flatMap(([branch, localDate]) =>
    variants().map((variant) => {
      const result = scoreFishInRiver(run, localDate, {
        copyVariant: variant,
      });
      return snapshotScenario({
        id: `fish_in_river_${slug(branch)}`,
        label: `${result.score} / ${result.maximum} · ${
          title(result.curveDirection.replace("_", " "))
        }`,
        localDate,
        variant,
        fishInRiver: result,
      });
    })
  );
  const cappedRun = {
    ...run,
    historicalPresence: {
      ...run.historicalPresence,
      maximum: 6 as const,
    },
  };
  for (const variant of variants()) {
    const result = scoreFishInRiver(cappedRun, "2026-09-20", {
      copyVariant: variant,
    });
    scenarios.push(snapshotScenario({
      id: "fish_in_river_lower_cap",
      label: "River cap · 6 / 6",
      localDate: "2026-09-20",
      variant,
      fishInRiver: result,
    }));
  }
  return {
    id: "fish_in_river",
    label: "Fish In River",
    scenarios: withBothVariants(scenarios),
  };
}

function combinedGroup(): Group {
  const cases = [
    ["strong_tough", "Strong Push + Tough fishing", {
      localDate: "2026-09-05",
      push: pushResult("Strong", "A"),
      fishability: fishabilityResult("Tough", "A"),
    }],
    ["peak_weak", "Peak + weak Push", {
      localDate: "2026-09-20",
      push: pushResult("Weak", "A"),
    }],
    ["good_low", "Good shape + low presence", {
      localDate: "2026-08-15",
      fishability: fishabilityResult("Good", "A"),
    }],
    ["delayed_strong", "Delayed + strong Push", {
      localDate: "2026-09-15",
      conditionsSuggest: conditionResult("Delayed", "A"),
      push: pushResult("Strong", "A"),
    }],
  ] as const;
  return {
    id: "combined",
    label: "Combined reads",
    scenarios: cases.map(([id, label, overrides]) =>
      snapshotScenario({
        id: `combined_${id}`,
        label,
        variant: "A",
        ...overrides,
      })
    ),
  };
}

function evidenceGroup(): Group {
  return {
    id: "evidence",
    label: "Evidence quality",
    scenarios: [
      snapshotScenario({
        id: "evidence_fresh",
        label: "Fresh",
        variant: "A",
      }),
      snapshotScenario({
        id: "evidence_limited",
        label: "Limited · unavailable cards",
        variant: "A",
        push: scorePush({
          ...basePushInput("A"),
          gaugeFreshness: "missing",
          currentHydraulicValue: null,
        }),
        fishability: scoreFishability({
          ...baseFishabilityInput("A"),
          gaugeFreshness: "missing",
          currentHydraulicValue: null,
        }),
        dataQuality: {
          label: "Limited",
          reasonCodes: ["data_quality_limited"],
        },
        missingSources: true,
      }),
    ],
  };
}

function snapshotScenario(input: {
  id: string;
  label: string;
  localDate?: string;
  variant: RiverRunCopyVariant;
  conditionsSuggest?: RiverRunConditionsSuggest;
  push?: RiverRunPush;
  fishability?: RiverRunFishability;
  fishInRiver?: RiverRunFishInRiver;
  dataQuality?: RiverRunSnapshotResponse["dataQuality"];
  missingSources?: boolean;
}): Scenario {
  const localDate = input.localDate ?? "2026-09-05";
  const runStage = resolveRunStage(run, localDate, {
    copyVariant: input.variant,
  }) as RiverRunStage;
  const fishInRiver = input.fishInRiver ??
    scoreFishInRiver(run, localDate, {
      copyVariant: input.variant,
    }) as RiverRunFishInRiver;
  const conditionsSuggest = input.conditionsSuggest ??
    conditionResult("Typical", input.variant);
  const push = input.push ?? scorePush({
    ...basePushInput(input.variant),
    localDate,
  }) as RiverRunPush;
  const fishability = input.fishability ?? scoreFishability({
    ...baseFishabilityInput(input.variant),
    localDate,
  }) as RiverRunFishability;
  const interpretationNote = resolveInterpretationNote({
    runStage: runStage.stage as ReturnType<typeof resolveRunStage>["stage"],
    conditionsSuggestLabel: conditionsSuggest.label,
    push: push as PrimitiveDisplay,
    fishability: fishability as PrimitiveDisplay,
    fishInRiver: fishInRiver as PrimitiveDisplay,
  });
  const inactive = localDate < "2026-08-15"
    ? "not_started"
    : localDate > "2026-10-20"
    ? "complete"
    : push.score != null && push.score >= 50
    ? "active_now"
    : "none_recorded";
  return {
    id: `${input.id}_${input.variant.toLowerCase()}`,
    label: `${input.label} · ${input.variant}`,
    note: input.variant === "A"
      ? "Canonical headline and takeaway"
      : "Alternate headline and takeaway; facts are unchanged",
    snapshot: {
      riverId: "pere_marquette",
      runId: run.runId,
      localDate,
      timezone: "America/Detroit",
      progressionSnapshotAt: `${localDate}T12:00:00.000Z`,
      conditionRefreshAt: `${localDate}T20:00:00.000Z`,
      refreshSlot: "16:00",
      progressionExpiresAt: `${localDate}T23:59:59.000Z`,
      nextConditionRefreshAt: `${localDate}T22:00:00.000Z`,
      runStage,
      conditionsSuggest,
      push,
      pushHistory: {
        status: inactive,
        minimumSupportiveScore: 50,
        trackingStartDate: "2026-08-15",
        trackingEndDate: "2026-10-20",
        throughDate: localDate,
      },
      fishability,
      fishInRiver,
      gauge: input.missingSources ? null : {
        provider: "USGS",
        siteId: "04122500",
        primaryMetric: "flow_cfs",
        observedAt: `${localDate}T19:45:00.000Z`,
        value: 600,
        band: "ideal",
        trend: "stable",
        absoluteChange24h: 0,
        percentChange24h: 0,
      },
      weather: input.missingSources ? null : {
        provider: "OPEN_METEO",
        evidenceType: "modeled_grid",
        weatherPointId: "pere_marquette_primary",
        rain24hIn: 0.1,
        rain48hIn: 0.2,
        rain72hIn: 0.3,
      },
      waterTemperature: input.missingSources ? null : {
        provider: "MONITOR_MY_WATERSHED",
        sourceId: "pmtu_maple_leaf",
        siteId: "PMTU-MapleLeaf",
        seriesId: "4939",
        observedAt: `${localDate}T19:30:00.000Z`,
        waterTempF: 60,
        trend: "steady",
        sourceType: "same_gauge",
        attribution: "Measured water temperature",
      },
      conditionsWaterTemperature: input.missingSources ? null : {
        provider: "MONITOR_MY_WATERSHED",
        sourceId: "pmtu_m37",
        siteId: "PMTU-M37",
        seriesId: "3201",
        observedAt: `${localDate}T19:30:00.000Z`,
        waterTempF: 60,
        trend: "steady",
        sourceType: "same_gauge",
        attribution: "Measured water temperature",
      },
      freshness: input.missingSources
        ? {
          gauge: "missing",
          weather: "fresh",
          waterTemperature: "missing",
          conditionsWaterTemperature: "missing",
          conditionsSuggestDaysUsable: 0,
        }
        : {
          gauge: "fresh",
          weather: "fresh",
          waterTemperature: "fresh",
          conditionsWaterTemperature: "fresh",
          conditionsSuggestDaysUsable: 40,
        },
      dataQuality: input.dataQuality ?? {
        label: "Fresh",
        reasonCodes: ["data_quality_fresh"],
      },
      interpretationNote: interpretationNote ?? null,
      safety: {
        regulationReminder:
          "Check current regulations, closures, and access rules before fishing.",
        gaugeBasis:
          "Fishability describes the river stretch represented by the Scottville gauge; conditions can differ elsewhere.",
        activityDisclaimer:
          "River Run is not a wading, boating, floating, or personal-safety rating.",
      },
      engineVersion: "river-run-v1.3.0-review",
      configVersion: "2026-07-29.1-review",
    },
  };
}

function insufficientConditionCases(target: ConditionsSuggestCheckpoint) {
  const fullEvidence = cumulativeEvidence(target, "typical");
  const cutoff = target.cutoffDate;
  const sparseEvidence: ConditionsSuggestEvidenceByDate = {};
  for (let index = 0; index < 3; index += 1) {
    const localDate = addDays(target.observationStartDate, index);
    sparseEvidence[localDate] = fullEvidence[localDate];
  }
  sparseEvidence[cutoff] = fullEvidence[cutoff];
  return [
    ["missing_baseline", "Insufficient · no historical baseline", []],
    [
      "few_years",
      "Insufficient · fewer than five years",
      [baseline(target, { distinctYears: 4 })],
    ],
    [
      "version_mismatch",
      "Insufficient · baseline version mismatch",
      [baseline(target, { baselineVersion: "old-version" })],
    ],
    [
      "window_mismatch",
      "Insufficient · window mismatch",
      [baseline(target, { expectedDays: baseline(target).expectedDays + 1 })],
    ],
    [
      "missing_gauge",
      "Insufficient · checkpoint gauge missing",
      [baseline(target)],
    ],
    [
      "missing_temperature",
      "Insufficient · checkpoint temperature missing",
      [baseline(target)],
    ],
    [
      "source_mismatch",
      "Insufficient · source mismatch",
      [baseline(target)],
    ],
    [
      "limited_days",
      "Insufficient · limited matching days",
      [baseline(target)],
    ],
  ].map(([id, label, baselines]) => ({
    id: id as string,
    label: label as string,
    localDate: target.checkpointDate,
    make: (variant: RiverRunCopyVariant) => {
      let evidenceByDate = fullEvidence;
      if (id === "missing_gauge") {
        evidenceByDate = {
          ...fullEvidence,
          [cutoff]: {
            "16:00": evidence(600, 60, { gaugeFreshness: "missing" }),
          },
        };
      }
      if (id === "missing_temperature") {
        evidenceByDate = {
          ...fullEvidence,
          [cutoff]: {
            "16:00": evidence(600, 60, {
              waterTemperatureFreshness: "missing",
              waterTempF: null,
            }),
          },
        };
      }
      if (id === "source_mismatch") {
        evidenceByDate = {
          ...fullEvidence,
          [cutoff]: {
            "16:00": evidence(600, 60, {
              waterTemperatureSourceId: "other-source",
            }),
          },
        };
      }
      if (id === "limited_days") evidenceByDate = sparseEvidence;
      return scoreConditionsSuggest({
        localDate: target.checkpointDate,
        run,
        evidenceByDate,
        baselines: baselines as RiverRunConditionsSuggestBaseline[],
        copyVariant: variant,
      });
    },
  }));
}

function conditionResult(
  label: "Typical" | "Delayed",
  variant: RiverRunCopyVariant,
): RiverRunConditionsSuggest {
  const target = label === "Delayed"
    ? checkpoint("peak_start")
    : checkpoint("building_start");
  return scoreConditionsSuggest({
    localDate: target.checkpointDate,
    run,
    evidenceByDate: cumulativeEvidence(
      target,
      label === "Delayed" ? "delayed" : "typical",
    ),
    baselines: checkpoints
      .filter((item) => item.checkpointDate <= target.checkpointDate)
      .map((item) => baseline(item)),
    copyVariant: variant,
  });
}

function pushResult(
  label: "Weak" | "Strong",
  variant: RiverRunCopyVariant,
): RiverRunPush {
  return scorePush({
    ...basePushInput(variant),
    ...(label === "Weak"
      ? {
        rainSignal: "dry",
        flowSignal: "falling",
        currentHydraulicValue: 500,
        hydraulicAbsoluteChange24h: -40,
        hydraulicPercentChange24h: -7.4,
        temperatureSignal: "strong_warming",
        waterTempF: 69,
      } as const
      : {
        rainSignal: "strong_rain",
        flowSignal: "meaningful_rise",
        currentHydraulicValue: 700,
        hydraulicAbsoluteChange24h: 70,
        hydraulicPercentChange24h: 11.1,
        temperatureSignal: "cooling",
        waterTempF: 59,
      } as const),
  });
}

function fishabilityResult(
  label: "Good" | "Tough",
  variant: RiverRunCopyVariant,
): RiverRunFishability {
  return scoreFishability({
    ...baseFishabilityInput(variant),
    ...(label === "Good"
      ? {
        flowBand: "normal_fishable",
        currentHydraulicValue: 500,
      } as const
      : {
        flowBand: "very_high",
        currentHydraulicValue: 1200,
      } as const),
  });
}

function basePushInput(variant: RiverRunCopyVariant) {
  return {
    movementEngineId: "fall_cooling" as const,
    rules: run.push,
    gaugeFreshness: "fresh" as const,
    rainSignal: "light_rain" as const,
    flowSignal: "stable" as const,
    currentHydraulicValue: 550,
    hydraulicAbsoluteChange24h: 0,
    hydraulicPercentChange24h: 0,
    temperatureSignal: "neutral" as const,
    temperatureSourceType: "same_gauge" as const,
    waterTempF: 60,
    trackingState: "active" as const,
    trackingStartDate: "2026-08-15",
    trackingEndDate: "2026-10-20",
    localDate: "2026-09-05",
    copyVariant: variant,
  };
}

function baseFishabilityInput(variant: RiverRunCopyVariant) {
  return {
    rules: run.fishabilityBands,
    gaugeFreshness: "fresh" as const,
    flowBand: "ideal" as const,
    flowSignal: "stable" as const,
    currentHydraulicValue: 600,
    hydraulicAbsoluteChange24h: 0,
    hydraulicPercentChange24h: 0,
    localDate: "2026-09-05",
    copyVariant: variant,
  };
}

function checkpoint(id: ConditionsSuggestCheckpoint["checkpointId"]) {
  return checkpoints.find((item) => item.checkpointId === id)!;
}

function baseline(
  target: ConditionsSuggestCheckpoint,
  overrides: Partial<RiverRunConditionsSuggestBaseline> = {},
): RiverRunConditionsSuggestBaseline {
  const expectedDays = daysBetween(
    target.observationStartDate,
    target.cutoffDate,
  ) + 1;
  return {
    riverId: "pere_marquette",
    runId: run.runId,
    checkpointId: target.checkpointId,
    referenceDayOfYear: canonicalBaselineDay(target.checkpointDate),
    observationStartDayOfYear: canonicalBaselineDay(
      target.observationStartDate,
    ),
    baselineVersion: run.conditionsSuggest.baselineVersion,
    gaugeMetric: "flow_cfs",
    gaugeSiteId: "04122500",
    temperatureSourceId: run.conditionsSuggest.temperatureSourceId,
    componentSamples: {
      gaugeAbsoluteRise: [0, 200, 400, 600, 800],
      gaugeRelativeRisePct: [0, 20, 40, 60, 80],
      meanWaterTempF: [50, 55, 60, 65, 70],
      waterCoolingF: [-5, 0, 5, 10, 15],
    },
    historicalSamples: [10, 30, 50, 70, 90].map((
      evidenceIndex,
      index,
    ) => ({
      year: 2021 + index,
      usableDays: expectedDays,
      gaugeAbsoluteRise: index * 200,
      gaugeRelativeRisePct: index * 20,
      meanWaterTempF: 70 - index * 5,
      waterCoolingF: -5 + index * 5,
      gaugeResponsePercentile: 10 + index * 20,
      waterTemperaturePercentile: 10 + index * 20,
      evidenceIndex,
    })),
    indexPercentiles: { p10: 18, p25: 30, p75: 70, p90: 82 },
    distinctYears: 5,
    expectedDays,
    minimumUsableDays: Math.ceil(
      expectedDays * run.conditionsSuggest.minimumCoveragePercent,
    ),
    sourceNotes: "Generated review fixture.",
    ...overrides,
  };
}

function delayedSecondBaseline(
  target: ConditionsSuggestCheckpoint,
): RiverRunConditionsSuggestBaseline {
  return baseline(target, {
    componentSamples: {
      gaugeAbsoluteRise: [2_000, 2_500, 3_000, 3_500, 4_000],
      gaugeRelativeRisePct: [200, 250, 300, 350, 400],
      meanWaterTempF: [30, 35, 40, 45, 50],
      waterCoolingF: [30, 35, 40, 45, 50],
    },
    historicalSamples: [10, 30, 50, 70, 90].map((
      evidenceIndex,
      index,
    ) => ({
      year: 2021 + index,
      usableDays: 27,
      gaugeAbsoluteRise: 2_000 + index * 500,
      gaugeRelativeRisePct: 200 + index * 50,
      meanWaterTempF: 50 - index * 5,
      waterCoolingF: 30 + index * 5,
      gaugeResponsePercentile: 10 + index * 20,
      waterTemperaturePercentile: 10 + index * 20,
      evidenceIndex,
    })),
  });
}

function allBaselines() {
  return checkpoints.map((item) => baseline(item));
}

function evidence(
  gaugeValue: number,
  waterTempF: number,
  overrides: Partial<ConditionsSuggestEvidence> = {},
): ConditionsSuggestEvidence {
  return {
    gaugeFreshness: "fresh",
    gaugeValue,
    gaugeMetric: "flow_cfs",
    gaugeSiteId: "04122500",
    waterTemperatureFreshness: "fresh",
    waterTempF,
    waterTemperatureSourceId: run.conditionsSuggest.temperatureSourceId,
    reasonCodes: ["gauge_fresh", "temperature_measured"],
    ...overrides,
  };
}

function cumulativeEvidence(
  target: ConditionsSuggestCheckpoint,
  kind: "ahead" | "typical" | "delayed",
): ConditionsSuggestEvidenceByDate {
  const count = daysBetween(
    target.observationStartDate,
    target.cutoffDate,
  ) + 1;
  const result: ConditionsSuggestEvidenceByDate = {};
  for (let index = 0; index < count; index += 1) {
    const localDate = addDays(target.observationStartDate, index);
    const gaugeValue = kind === "ahead"
      ? 400 + index * 60
      : kind === "delayed"
      ? 500
      : 500 + index * 20;
    const waterTempF = kind === "ahead"
      ? 65 - index
      : kind === "delayed"
      ? 70
      : 64 - index * 0.4;
    result[localDate] = {
      "16:00": evidence(gaugeValue, waterTempF),
    };
  }
  return result;
}

function mixedEvidence(
  target: ConditionsSuggestCheckpoint,
): ConditionsSuggestEvidenceByDate {
  const result = cumulativeEvidence(target, "ahead");
  for (const date of Object.keys(result)) {
    const current = result[date]["16:00"]!;
    result[date] = {
      "16:00": { ...current, waterTempF: 70 },
    };
  }
  return result;
}

function variants(): RiverRunCopyVariant[] {
  return ["A", "B"];
}

function withBothVariants(scenarios: Scenario[]): Scenario[] {
  return scenarios;
}

function scenarioCount(value: Group[]): number {
  return value.reduce((total, group) => total + group.scenarios.length, 0);
}

function shallowSnapshotDiff(
  base: RiverRunSnapshotResponse,
  target: RiverRunSnapshotResponse,
): Partial<RiverRunSnapshotResponse> {
  const diff: Partial<RiverRunSnapshotResponse> = {};
  for (
    const key of Object.keys(target) as Array<keyof RiverRunSnapshotResponse>
  ) {
    if (JSON.stringify(base[key]) === JSON.stringify(target[key])) continue;
    (diff as Record<string, unknown>)[key] = target[key];
  }
  return diff;
}

function title(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(
    /^_|_$/g,
    "",
  );
}
