import {
  addDays,
  type AuditedRiverRunProfile,
  canonicalBaselineDay,
  type ConditionsSuggestCheckpoint,
  type ConditionsSuggestEvidence,
  type ConditionsSuggestEvidenceByDate,
  daysBetween,
  PERE_MARQUETTE_FALL_CHINOOK_RUN_PROFILE,
  PERE_MARQUETTE_FALL_COHO_RUN_PROFILE,
  PERE_MARQUETTE_FALL_STEELHEAD_RUN_PROFILE,
  type PrimitiveDisplay,
  resolveActiveRunWindow,
  resolveConditionsSuggestCheckpoints,
  resolveConditionsSuggestCheckpointState,
  resolveInterpretationNote,
  resolveRunStage,
  type RiverRunConditionsSuggestBaseline,
  scoreConditionsSuggest,
  scoreFishability,
  scoreFishInRiver,
  scorePush,
} from "../supabase/functions/_shared/riverRunEngine/index.ts";
import type {
  RiverRunConditionsSuggest,
  RiverRunFishability,
  RiverRunFishInRiver,
  RiverRunPush,
  RiverRunSnapshotResponse,
  RiverRunStage,
} from "../lib/riverRunContracts.ts";

type Scenario = {
  id: string;
  label: string;
  note?: string;
  snapshot: RiverRunSnapshotResponse;
};

type Group = {
  id: string;
  label: string;
  scenarios: Scenario[];
};

const requestedRunId = argumentValue("--run-id") ??
  "pere_marquette_fall_chinook";
const run: AuditedRiverRunProfile = requestedRunId ===
    PERE_MARQUETTE_FALL_CHINOOK_RUN_PROFILE.runId
  ? PERE_MARQUETTE_FALL_CHINOOK_RUN_PROFILE
  : requestedRunId === PERE_MARQUETTE_FALL_COHO_RUN_PROFILE.runId
  ? PERE_MARQUETTE_FALL_COHO_RUN_PROFILE
  : requestedRunId === PERE_MARQUETTE_FALL_STEELHEAD_RUN_PROFILE.runId
  ? PERE_MARQUETTE_FALL_STEELHEAD_RUN_PROFILE
  : (() => {
    throw new Error(`Unsupported review run ID: ${requestedRunId}`);
  })();
const moderateCopyRun: typeof run = {
  ...run,
  runId: "qa_moderate_opportunity",
  displayName: "QA Moderate Opportunity",
  historicalPresence: {
    ...run.historicalPresence,
    maximum: 6,
    distributionScope: "sectional",
  },
};
const limitedCopyRun: typeof run = {
  ...run,
  runId: "qa_limited_opportunity",
  displayName: "QA Limited Opportunity",
  historicalPresence: {
    ...run.historicalPresence,
    maximum: 3,
    distributionScope: "concentrated",
  },
};
const reviewWindow = resolveActiveRunWindow(run, "2026-09-20");
const reviewBaseDate = reviewWindow.buildingEstablishedStartDate;
const checkpoints = resolveConditionsSuggestCheckpoints(
  run,
  reviewWindow.peakDate,
);
const cohoReview = run.species === "coho_salmon";
const steelheadReview = run.species === "steelhead";
const outputPath = new URL(
  steelheadReview
    ? "../lib/riverRunSteelheadReviewFixtures.generated.ts"
    : cohoReview
    ? "../lib/riverRunCohoReviewFixtures.generated.ts"
    : "../lib/riverRunReviewFixtures.generated.ts",
  import.meta.url,
);
const exportName = cohoReview
  ? "RIVER_RUN_COHO_REVIEW_GROUPS"
  : steelheadReview
  ? "RIVER_RUN_STEELHEAD_REVIEW_GROUPS"
  : "RIVER_RUN_REVIEW_GROUPS";

const groups: Group[] = [
  runStageGroup(),
  conditionsGroup(),
  pushGroup(),
  fishabilityGroup(),
  fishInRiverGroup(),
  opportunityCopyGroup(),
  combinedGroup(),
  evidenceGroup(),
];
const baseSnapshot = snapshotScenario({
  id: "generated_base",
  label: "Generated base",
  localDate: reviewBaseDate,
}).snapshot;
const compactGroups = groups.map((group) => ({
  id: group.id,
  label: group.label,
  scenarios: group.scenarios.map((scenario) => {
    return {
      id: scenario.id,
      label: scenario.label,
      note: scenario.note,
      snapshotOverride: shallowSnapshotDiff(
        baseSnapshot,
        scenario.snapshot,
      ),
    };
  }),
}));

const generated =
  `// This file is generated by scripts/generate-river-run-review-fixtures.ts.
// Do not hand-edit. Every primitive card below comes from production scoring code.

import type { RiverRunReviewGroup } from "./riverRunReviewFixtures.types";
import type { RiverRunSnapshotResponse } from "./riverRunContracts";

const BASE_SNAPSHOT = ${
    JSON.stringify(baseSnapshot, null, 2)
  } as unknown as RiverRunSnapshotResponse;

const GROUP_SEEDS = ${JSON.stringify(compactGroups, null, 2)} as const;

export const ${exportName}: RiverRunReviewGroup[] = GROUP_SEEDS.map(
  (group) => ({
    id: group.id,
    label: group.label,
    scenarios: group.scenarios.map((scenario) => ({
      id: scenario.id,
      label: scenario.label,
      note: scenario.note,
      snapshot: {
        ...BASE_SNAPSHOT,
        ...scenario.snapshotOverride,
      } as RiverRunSnapshotResponse,
    })),
  }),
);
`;

if (Deno.args.includes("--check")) {
  const current = await Deno.readTextFile(outputPath).catch(() => "");
  if (current !== generated) {
    console.error(
      "River Run review fixtures are stale. Run npm run generate:river-run:review-fixtures.",
    );
    Deno.exit(1);
  }
  console.log(
    `River Run review fixtures match production copy (${
      scenarioCount(groups)
    } ${run.displayName} scenarios).`,
  );
} else {
  await Deno.writeTextFile(outputPath, generated);
  console.log(
    `Generated ${
      scenarioCount(groups)
    } ${run.displayName} review scenarios from production scoring code.`,
  );
}

function argumentValue(flag: string): string | null {
  const inline = Deno.args.find((arg) => arg.startsWith(`${flag}=`));
  if (inline) return inline.slice(flag.length + 1) || null;
  const index = Deno.args.indexOf(flag);
  return index >= 0 ? Deno.args[index + 1] ?? null : null;
}

function runStageGroup(): Group {
  const states = [
    [
      "offseason",
      "True offseason",
      run.handoff
        ? addDays(reviewWindow.preRunStartDate, -1)
        : addDays(reviewWindow.postRunLateCopyEndDate, 1),
    ],
    [
      "before_staging",
      "Before staging",
      addDays(reviewWindow.preRunStartDate, 9),
    ],
    ["staging", "Staging period", addDays(reviewWindow.stagingStartDate, 4)],
    ["beginning", "Beginning", reviewWindow.startDate],
    [
      "building_early",
      "Building — early",
      addDays(reviewWindow.beginningEndDate, 1),
    ],
    ["building_established", "Building — established", reviewBaseDate],
    ...(reviewWindow.buildingBroadStartDate
      ? [
        [
          "building_broad",
          "Building — broadly established",
          reviewWindow.buildingBroadStartDate,
        ] as const,
      ]
      : []),
    ["peak", "Peak", reviewWindow.peakDate],
    ["tapering", "Tapering", addDays(reviewWindow.peakEndDate, 1)],
    ["ending", "Ending", addDays(reviewWindow.taperingEndDate, 1)],
    [
      "post",
      "After the main migration window",
      addDays(reviewWindow.endDate, 1),
    ],
  ] as const;
  return {
    id: "run_stage",
    label: "Migration Stage",
    scenarios: states.map(([id, label, localDate]) =>
      snapshotScenario({
        id: `stage_${id}`,
        label,
        localDate,
      })
    ),
  };
}

function conditionsGroup(): Group {
  const target = checkpoint("river_start");
  const second = checkpoint("building_start");
  const peakComplete = checkpoint("peak_complete");
  const beforeCollectionDate = addDays(reviewWindow.stagingStartDate, -8);
  const collectingDate = addDays(reviewWindow.stagingStartDate, 4);
  const postRunDate = addDays(reviewWindow.endDate, 1);

  const basic = [
    {
      id: "before_collection",
      label: "Before evidence collection",
      localDate: beforeCollectionDate,
      make: () =>
        scoreConditionsSuggest({
          localDate: beforeCollectionDate,
          run,
          evidenceByDate: {},
          baselines: [],
        }),
    },
    {
      id: "collecting",
      label: "Collecting first read",
      localDate: collectingDate,
      make: () =>
        scoreConditionsSuggest({
          localDate: collectingDate,
          run,
          evidenceByDate: {},
          baselines: [],
        }),
    },
    ...(["ahead", "typical", "delayed"] as const).map((kind) => ({
      id: kind,
      label: title(kind),
      localDate: target.checkpointDate,
      make: () =>
        scoreConditionsSuggest({
          localDate: target.checkpointDate,
          run,
          evidenceByDate: cumulativeEvidence(target, kind),
          baselines: [baseline(target)],
        }),
    })),
    {
      id: "mixed",
      label: "Typical · mixed signals",
      localDate: target.checkpointDate,
      make: () =>
        scoreConditionsSuggest({
          localDate: target.checkpointDate,
          run,
          evidenceByDate: mixedEvidence(target),
          baselines: [baseline(target)],
        }),
    },
    {
      id: "tempered_reversal",
      label: "Typical · reversal tempered",
      localDate: second.checkpointDate,
      make: () =>
        scoreConditionsSuggest({
          localDate: second.checkpointDate,
          run,
          evidenceByDate: cumulativeEvidence(second, "ahead"),
          baselines: [
            baseline(target),
            delayedSecondBaseline(second),
          ],
        }),
    },
    {
      id: "complete_underway",
      label: "Timing complete · underway",
      localDate: peakComplete.checkpointDate,
      make: () =>
        scoreConditionsSuggest({
          localDate: peakComplete.checkpointDate,
          run,
          evidenceByDate: cumulativeEvidence(peakComplete, "typical"),
          baselines: allBaselines(),
        }),
    },
    {
      id: "complete_post",
      label: "Timing complete · post-run",
      localDate: postRunDate,
      make: () =>
        scoreConditionsSuggest({
          localDate: postRunDate,
          run,
          evidenceByDate: cumulativeEvidence(peakComplete, "typical"),
          baselines: allBaselines(),
        }),
    },
    {
      id: "complete_insufficient",
      label: "Timing complete · insufficient",
      localDate: peakComplete.checkpointDate,
      make: () =>
        scoreConditionsSuggest({
          localDate: peakComplete.checkpointDate,
          run,
          evidenceByDate: cumulativeEvidence(peakComplete, "typical"),
          baselines: allBaselines().slice(0, 3),
        }),
    },
  ];

  const insufficient = insufficientConditionCases(target);
  return {
    id: "conditions",
    label: "Migration Timing",
    scenarios: [...basic, ...insufficient].map((item) =>
      snapshotScenario({
        id: `conditions_${item.id}`,
        label: item.label,
        localDate: item.localDate,
        conditionsSuggest: item.make(),
      })
    ),
  };
}

function pushGroup(): Group {
  const base = {
    movementEngineId: run.movementEngineId,
    rules: run.push,
    gaugeFreshness: "fresh" as const,
    rainSignal: "light_rain" as const,
    flowSignal: "stable" as const,
    currentHydraulicValue: 550,
    hydraulicAbsoluteChange24h: 0,
    hydraulicPercentChange24h: 0,
    temperatureSignal: "neutral" as const,
    temperatureSourceType: "same_gauge" as const,
    waterTempF: (run.push.temperature.supportiveMinF +
      run.push.temperature.supportiveMaxF) / 2,
    trackingState: "active" as const,
    trackingStartDate: reviewWindow.startDate,
    trackingEndDate: reviewWindow.endDate,
    localDate: reviewBaseDate,
  };
  const cases = [
    ["weak", "Weak · warm, dry, falling", {
      rainSignal: "dry",
      flowSignal: "falling",
      currentHydraulicValue: 500,
      hydraulicAbsoluteChange24h: -40,
      hydraulicPercentChange24h: -7.4,
      temperatureSignal: "strong_warming",
      waterTempF: run.push.temperature.tooWarmF + 1,
    }],
    ["no_clear", "No clear push · steady", {}],
    ["possible", "Possible · early response", {
      rainSignal: "meaningful_rain",
      flowSignal: "rising",
      currentHydraulicValue: 600,
      hydraulicAbsoluteChange24h: 25,
      hydraulicPercentChange24h: 4.3,
      temperatureSignal: "cooling",
      waterTempF: run.push.temperature.supportiveMaxF,
    }],
    ["strong", "Strong · meaningful rise", {
      rainSignal: "strong_rain",
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      temperatureSignal: "cooling",
      waterTempF: (run.push.temperature.supportiveMinF +
        run.push.temperature.supportiveMaxF) / 2,
    }],
    ["very_strong", "Very strong · sharp rise", {
      rainSignal: "heavy_rain",
      flowSignal: "sharp_rise",
      currentHydraulicValue: 800,
      hydraulicAbsoluteChange24h: 130,
      hydraulicPercentChange24h: 19.4,
      temperatureSignal: "strong_cooling",
      waterTempF: run.push.temperature.supportiveMaxF - 1,
    }],
    ["rain_precursor", "Rain · early precursor", {
      rainSignal: "heavy_rain",
      flowSignal: "stable",
      temperatureSignal: "cooling",
    }],
    ["rain_absorbed", "Rain · reflected in gauge", {
      rainSignal: "heavy_rain",
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
    }],
    ["rain_suppressed", "Rain · river already high", {
      rainSignal: "heavy_rain",
      flowSignal: "rising",
      currentHydraulicValue: 900,
      hydraulicAbsoluteChange24h: 30,
      hydraulicPercentChange24h: 3.4,
    }],
    ["rain_missing", "Rain · unavailable", {
      rainSignal: "missing_rain_data",
    }],
    ["temperature_transitional", "Temperature · transitional warm", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      waterTempF: (run.push.temperature.supportiveMaxF +
        run.push.temperature.tooWarmF) / 2,
      temperatureSignal: "cooling",
    }],
    ["temperature_too_warm", "Temperature · too warm", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      waterTempF: (run.push.temperature.tooWarmF +
        run.push.temperature.migrationBarrierF) / 2,
      temperatureSignal: "cooling",
    }],
    ["temperature_barrier", "Temperature · warm barrier", {
      flowSignal: "sharp_rise",
      currentHydraulicValue: 800,
      hydraulicAbsoluteChange24h: 130,
      hydraulicPercentChange24h: 19.4,
      waterTempF: run.push.temperature.migrationBarrierF,
      temperatureSignal: "strong_cooling",
    }],
    ["temperature_plateau", "Temperature · cool plateau", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      waterTempF: run.push.temperature.supportiveMinF - 2,
      temperatureSignal: "strong_cooling",
    }],
    ["temperature_cold_active", "Temperature · cold but active", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      waterTempF: run.push.temperature.preferredMinF != null
        ? run.push.temperature.preferredMinF - 2
        : run.push.temperature.supportiveMinF - 2,
      temperatureSignal: "neutral",
    }],
    ["temperature_cold_holding", "Temperature · cold holding", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      waterTempF: run.push.temperature.coldHoldingF ??
        run.push.temperature.supportiveMinF - 4,
      temperatureSignal: "strong_cooling",
    }],
    ["upstream_no_credit", "Temperature · upstream fallback", {
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 700,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 11.1,
      temperatureSignal: "strong_cooling",
      temperatureSourceType: "nearby_gauge",
      temperaturePositiveSignalCap: 0,
    }],
    ["unknown_trend", "Gauge trend · unresolved", {
      flowSignal: "unknown",
      hydraulicAbsoluteChange24h: null,
      hydraulicPercentChange24h: null,
      rainSignal: "heavy_rain",
      temperatureSignal: "cooling",
    }],
    ["stale_cap", "Gauge · stale", {
      gaugeFreshness: "stale",
      flowSignal: "sharp_rise",
      currentHydraulicValue: 800,
      hydraulicAbsoluteChange24h: 130,
      hydraulicPercentChange24h: 19.4,
      rainSignal: "heavy_rain",
      temperatureSignal: "strong_cooling",
    }],
    ["severe_high", "Gauge · severe high cap", {
      flowSignal: "sharp_rise",
      currentHydraulicValue: 1200,
      hydraulicAbsoluteChange24h: 200,
      hydraulicPercentChange24h: 20,
      rainSignal: "heavy_rain",
      temperatureSignal: "strong_cooling",
    }],
    ["unavailable_gauge", "Unavailable · gauge", {
      gaugeFreshness: "missing",
      currentHydraulicValue: null,
    }],
    ["unavailable_temperature", "Unavailable · water temperature", {
      temperatureSourceType: "unavailable",
      waterTempF: null,
    }],
    ["unavailable_engine", "Unavailable · run type", {
      movementEngineId: "spring_warming",
    }],
    ["not_started", "Waiting for migration", {
      trackingState: "not_started",
      localDate: addDays(reviewWindow.stagingStartDate, 4),
    }],
    ["offseason", "Offseason", {
      trackingState: "offseason",
      localDate: addDays(reviewWindow.postRunLateCopyEndDate, 1),
    }],
    ["first_day", "History · first run day", {
      localDate: reviewWindow.startDate,
    }],
    ["complete", "Migration complete", {
      trackingState: "complete",
      localDate: addDays(reviewWindow.endDate, 1),
    }],
  ] as const;

  return {
    id: "push",
    label: "Push",
    scenarios: cases.filter(([id]) =>
      run.species === "steelhead" ||
      !["temperature_cold_active", "temperature_cold_holding"].includes(id)
    ).map(([id, label, overrides]) => {
      const input = { ...base, ...overrides };
      return snapshotScenario({
        id: `push_${id}`,
        label,
        localDate: input.localDate,
        push: scorePush(input),
      });
    }),
  };
}

function fishabilityGroup(): Group {
  const base = {
    rules: run.fishabilityBands,
    gaugeFreshness: "fresh" as const,
    flowSignal: "stable" as const,
    currentHydraulicValue: 600,
    hydraulicAbsoluteChange24h: 0,
    hydraulicPercentChange24h: 0,
    localDate: reviewBaseDate,
  };
  const cases = [
    ["very_low", "Tough · very low", {
      flowBand: "very_low",
      currentHydraulicValue: 350,
    }],
    ["low", "Fishable · low", {
      flowBand: "low",
      currentHydraulicValue: 450,
    }],
    ["normal", "Good · normal", {
      flowBand: "normal_fishable",
      currentHydraulicValue: 500,
    }],
    ["ideal", "Excellent · ideal", {
      flowBand: "ideal",
      currentHydraulicValue: 600,
    }],
    ["high", "Fishable · high", {
      flowBand: "high_fishable",
      currentHydraulicValue: 850,
    }],
    ["very_high", "Tough · very high", {
      flowBand: "very_high",
      currentHydraulicValue: 1200,
    }],
    ["blown", "Poor · blown out", {
      flowBand: "blown_out",
      currentHydraulicValue: 1700,
    }],
    ["falling", "Trend · falling", {
      flowBand: "ideal",
      flowSignal: "falling",
      currentHydraulicValue: 600,
      hydraulicAbsoluteChange24h: -45,
      hydraulicPercentChange24h: -7,
    }],
    ["rising", "Trend · early rise", {
      flowBand: "ideal",
      flowSignal: "rising",
      currentHydraulicValue: 650,
      hydraulicAbsoluteChange24h: 25,
      hydraulicPercentChange24h: 4,
    }],
    ["meaningful", "Trend · meaningful rise", {
      flowBand: "high_fishable",
      flowSignal: "meaningful_rise",
      currentHydraulicValue: 850,
      hydraulicAbsoluteChange24h: 70,
      hydraulicPercentChange24h: 9,
    }],
    ["sharp", "Trend · sharp rise", {
      flowBand: "high_fishable",
      flowSignal: "sharp_rise",
      currentHydraulicValue: 900,
      hydraulicAbsoluteChange24h: 130,
      hydraulicPercentChange24h: 17,
    }],
    ["unknown", "Trend · unresolved", {
      flowBand: "ideal",
      flowSignal: "unknown",
      hydraulicAbsoluteChange24h: null,
      hydraulicPercentChange24h: null,
    }],
    ["stale", "Gauge · stale", {
      flowBand: "ideal",
      gaugeFreshness: "stale",
    }],
    ["unavailable_gauge", "Unavailable · gauge", {
      flowBand: "ideal",
      gaugeFreshness: "missing",
      currentHydraulicValue: null,
    }],
    ["unavailable_band", "Unavailable · river bands", {
      flowBand: undefined,
    }],
  ] as const;
  return {
    id: "fishability",
    label: "Fishability",
    scenarios: cases.map(([id, label, overrides]) =>
      snapshotScenario({
        id: `fishability_${id}`,
        label,
        localDate: base.localDate,
        fishability: scoreFishability({
          ...base,
          ...overrides,
        }),
      })
    ),
  };
}

function fishInRiverGroup(): Group {
  const byBranch = new Map<string, string>();
  for (
    let localDate = addDays(reviewWindow.preRunStartDate, -1);
    localDate <= addDays(reviewWindow.postRunLateCopyEndDate, 1);
    localDate = addDays(localDate, 1)
  ) {
    const result = scoreFishInRiver(run, localDate);
    const phase = result.score === 0
      ? `${result.stage}:${result.label}`
      : result.label === "High presence" && result.curveFraction >= 0.8
      ? `${result.label}:${result.curveDirection}:upper_shoulder`
      : `${result.label}:${result.curveDirection}`;
    if (!byBranch.has(phase)) byBranch.set(phase, localDate);
  }
  const scenarios = [...byBranch.entries()].map(([branch, localDate]) => {
    const result = scoreFishInRiver(run, localDate);
    return snapshotScenario({
      id: `fish_in_river_${slug(branch)}`,
      label: `${result.score} / ${result.maximum} · ${
        title(result.curveDirection.replace("_", " "))
      }`,
      localDate,
      fishInRiver: result,
    });
  });
  const cappedRun = {
    ...run,
    historicalPresence: {
      ...run.historicalPresence,
      maximum: 6 as const,
      distributionScope: "sectional" as const,
    },
  };
  const result = scoreFishInRiver(cappedRun, reviewWindow.peakDate);
  scenarios.push(snapshotScenario({
    id: "fish_in_river_moderate_cap",
    label: "QA only · moderate sectional run · 60 / 100",
    localDate: reviewWindow.peakDate,
    fishInRiver: result,
  }));
  return {
    id: "fish_in_river",
    label: "Fish In River",
    scenarios,
  };
}

function opportunityCopyGroup(): Group {
  const stageDates = [
    ["building", "Building", reviewBaseDate],
    ["peak", "Peak", reviewWindow.peakDate],
    ["tapering", "Tapering", addDays(reviewWindow.peakEndDate, 5)],
    ["ending", "Ending", addDays(reviewWindow.taperingEndDate, 4)],
  ] as const;
  const presenceDates = [
    ["rising", "Presence · rising", addDays(reviewWindow.peakStartDate, -1)],
    ["peak", "Presence · peak", reviewWindow.peakDate],
    ["falling", "Presence · falling", addDays(reviewWindow.peakEndDate, 2)],
  ] as const;
  const profiles = [
    ["moderate", "Moderate / sectional", moderateCopyRun],
    ["limited", "Limited / concentrated", limitedCopyRun],
  ] as const;
  const scenarios: Scenario[] = [];
  for (const [tierId, tierLabel, profile] of profiles) {
    for (const [stateId, stateLabel, localDate] of stageDates) {
      scenarios.push(snapshotScenario({
        id: `opportunity_${tierId}_stage_${stateId}`,
        label: `${tierLabel} · Stage · ${stateLabel}`,
        localDate,
        profile,
      }));
    }
    for (const [stateId, stateLabel, localDate] of presenceDates) {
      scenarios.push(snapshotScenario({
        id: `opportunity_${tierId}_presence_${stateId}`,
        label: `${tierLabel} · ${stateLabel}`,
        localDate,
        profile,
      }));
    }
  }
  return {
    id: "opportunity_copy",
    label: "Opportunity Copy Tiers",
    scenarios,
  };
}

function combinedGroup(): Group {
  const cases = [
    ["strong_tough", "Strong Push + Tough fishing", {
      localDate: reviewBaseDate,
      push: pushResult("Strong"),
      fishability: fishabilityResult("Tough"),
    }],
    ["peak_weak", "Peak + weak Push", {
      localDate: reviewWindow.peakDate,
      push: pushResult("Weak"),
    }],
    ["good_low", "Good shape + low presence", {
      localDate: reviewWindow.startDate,
      fishability: fishabilityResult("Good"),
    }],
    ["delayed_strong", "Delayed + strong Push", {
      localDate: reviewWindow.peakStartDate,
      conditionsSuggest: conditionResult("Delayed"),
      push: pushResult("Strong"),
    }],
  ] as const;
  return {
    id: "combined",
    label: "Combined reads",
    scenarios: cases.map(([id, label, overrides]) =>
      snapshotScenario({
        id: `combined_${id}`,
        label,
        ...overrides,
      })
    ),
  };
}

function evidenceGroup(): Group {
  return {
    id: "evidence",
    label: "Evidence quality",
    scenarios: [
      snapshotScenario({
        id: "evidence_fresh",
        label: "Fresh",
      }),
      snapshotScenario({
        id: "evidence_limited",
        label: "Limited · unavailable cards",
        push: scorePush({
          ...basePushInput(),
          gaugeFreshness: "missing",
          currentHydraulicValue: null,
        }),
        fishability: scoreFishability({
          ...baseFishabilityInput(),
          gaugeFreshness: "missing",
          currentHydraulicValue: null,
        }),
        dataQuality: {
          label: "Limited",
          reasonCodes: ["data_quality_limited"],
        },
        missingSources: true,
      }),
    ],
  };
}

function snapshotScenario(input: {
  id: string;
  label: string;
  localDate?: string;
  conditionsSuggest?: RiverRunConditionsSuggest;
  push?: RiverRunPush;
  fishability?: RiverRunFishability;
  fishInRiver?: RiverRunFishInRiver;
  dataQuality?: RiverRunSnapshotResponse["dataQuality"];
  missingSources?: boolean;
  profile?: typeof run;
}): Scenario {
  const localDate = input.localDate ?? reviewBaseDate;
  const profile = input.profile ?? run;
  const runStage = resolveRunStage(profile, localDate) as RiverRunStage;
  const fishInRiver = input.fishInRiver ??
    scoreFishInRiver(profile, localDate) as RiverRunFishInRiver;
  const conditionsSuggest = input.conditionsSuggest ??
    typicalConditionResultForDate(localDate);
  const trackingState = runStage.label === "Offseason"
    ? "offseason"
    : reviewTrackingState(localDate);
  const push = input.push ?? scorePush({
    ...basePushInput(),
    localDate,
    trackingState,
  }) as RiverRunPush;
  const fishability = input.fishability ?? scoreFishability({
    ...baseFishabilityInput(),
    localDate,
  }) as RiverRunFishability;
  const interpretationNote = resolveInterpretationNote({
    runStage: runStage.stage as ReturnType<typeof resolveRunStage>["stage"],
    broadBuildingContext: runStage.broadBuildingContext,
    conditionsSuggestLabel: conditionsSuggest.label,
    push: push as PrimitiveDisplay,
    fishability: fishability as PrimitiveDisplay,
    fishInRiver: fishInRiver as PrimitiveDisplay,
  });
  const inactive = localDate < reviewWindow.startDate
    ? "not_started"
    : localDate > reviewWindow.endDate
    ? "complete"
    : push.score != null && push.score >= 50
    ? "active_now"
    : "none_recorded";
  const pushHistoryThroughDate = inactive === "complete"
    ? reviewWindow.endDate
    : localDate;
  const recentDailyPushReads = reviewRecentDailyPushReads(
    inactive === "complete" ? addDays(reviewWindow.endDate, 1) : localDate,
  );
  return {
    id: input.id,
    label: input.label,
    note: "Canonical production copy",
    snapshot: {
      riverId: "pere_marquette",
      runId: profile.runId,
      localDate,
      timezone: "America/Detroit",
      progressionSnapshotAt: `${localDate}T12:00:00.000Z`,
      conditionRefreshAt: `${localDate}T20:00:00.000Z`,
      refreshSlot: "16:00",
      progressionExpiresAt: `${localDate}T23:59:59.000Z`,
      nextConditionRefreshAt: `${localDate}T22:00:00.000Z`,
      runStage,
      conditionsSuggest,
      push,
      pushHistory: {
        status: inactive,
        minimumSupportiveScore: 50,
        trackingStartDate: reviewWindow.startDate,
        trackingEndDate: reviewWindow.endDate,
        throughDate: pushHistoryThroughDate,
        recentDailyReadsStatus: "available",
        recentDailyReads: recentDailyPushReads,
        ...(inactive === "active_now"
          ? {
            lastSupportiveConditions: {
              localDate,
              refreshSlot: "16:00",
              conditionRefreshAt: `${localDate}T20:00:00.000Z`,
              score: push.score ?? 50,
              label: push.label,
            },
          }
          : {}),
      },
      fishability,
      fishInRiver,
      gauge: input.missingSources ? null : {
        provider: "USGS",
        siteId: "04122500",
        primaryMetric: "flow_cfs",
        observedAt: `${localDate}T19:45:00.000Z`,
        value: 600,
        band: "ideal",
        trend: "stable",
        absoluteChange24h: 0,
        percentChange24h: 0,
      },
      weather: input.missingSources ? null : {
        provider: "OPEN_METEO",
        evidenceType: "modeled_grid",
        weatherPointId: "pere_marquette_primary",
        rain24hIn: 0.1,
        rain48hIn: 0.2,
        rain72hIn: 0.3,
      },
      waterTemperature: input.missingSources ? null : {
        provider: "MONITOR_MY_WATERSHED",
        sourceId: "pmtu_maple_leaf",
        siteId: "PMTU-MapleLeaf",
        seriesId: "4939",
        observedAt: `${localDate}T19:30:00.000Z`,
        waterTempF: 60,
        trend: "steady",
        sourceType: "same_gauge",
        attribution: "Measured water temperature",
      },
      conditionsWaterTemperature: input.missingSources ? null : {
        provider: "MONITOR_MY_WATERSHED",
        sourceId: "pmtu_m37",
        siteId: "PMTU-M37",
        seriesId: "3201",
        observedAt: `${localDate}T19:30:00.000Z`,
        waterTempF: 60,
        trend: "steady",
        sourceType: "same_gauge",
        attribution: "Measured water temperature",
      },
      freshness: input.missingSources
        ? {
          gauge: "missing",
          weather: "fresh",
          waterTemperature: "missing",
          conditionsWaterTemperature: "missing",
          conditionsSuggestDaysUsable: 0,
        }
        : {
          gauge: "fresh",
          weather: "fresh",
          waterTemperature: "fresh",
          conditionsWaterTemperature: "fresh",
          conditionsSuggestDaysUsable: 40,
        },
      dataQuality: input.dataQuality ?? {
        label: "Fresh",
        reasonCodes: ["data_quality_fresh"],
      },
      interpretationNote: interpretationNote ?? null,
      safety: {
        regulationReminder:
          "Check current regulations, closures, and access rules before fishing.",
        gaugeBasis:
          "Fishability describes the river stretch represented by the Scottville gauge; conditions can differ elsewhere.",
        activityDisclaimer:
          "River Run is not a wading, boating, floating, or personal-safety rating.",
      },
      engineVersion: "river-run-v1.5.3-review",
      configVersion: "2026-08-05.6-review",
    },
  };
}

function reviewRecentDailyPushReads(localDate: string) {
  const examples = [
    { score: null, label: "No supportive window", slot: null },
    { score: null, label: "No supportive window", slot: null },
    { score: 63, label: "Possible", slot: "08:00" },
    { score: null, label: "No supportive window", slot: null },
    { score: 81, label: "Strong", slot: "20:00" },
    { score: 63, label: "Possible", slot: "16:00" },
    { score: null, label: "No supportive window", slot: null },
  ];
  const reads = [];
  for (let dayOffset = 1; dayOffset <= 7; dayOffset += 1) {
    const readDate = addDays(localDate, -dayOffset);
    if (readDate < reviewWindow.startDate) break;
    const example = examples[dayOffset - 1];
    reads.push(
      example.slot
        ? {
          localDate: readDate,
          status: "supportive_window" as const,
          refreshSlot: example.slot,
          conditionRefreshAt: `${readDate}T23:59:00.000Z`,
          score: example.score,
          label: example.label,
        }
        : {
          localDate: readDate,
          status: "no_supportive_window" as const,
          score: null,
          label: "No supportive window" as const,
        },
    );
  }
  return reads;
}

function insufficientConditionCases(target: ConditionsSuggestCheckpoint) {
  const fullEvidence = cumulativeEvidence(target, "typical");
  const cutoff = target.cutoffDate;
  const sparseEvidence: ConditionsSuggestEvidenceByDate = {};
  for (let index = 0; index < 3; index += 1) {
    const localDate = addDays(target.observationStartDate, index);
    sparseEvidence[localDate] = fullEvidence[localDate];
  }
  sparseEvidence[cutoff] = fullEvidence[cutoff];
  return [
    ["missing_baseline", "Insufficient · no historical baseline", []],
    [
      "few_years",
      "Insufficient · fewer than five years",
      [baseline(target, { distinctYears: 4 })],
    ],
    [
      "version_mismatch",
      "Insufficient · baseline version mismatch",
      [baseline(target, { baselineVersion: "old-version" })],
    ],
    [
      "window_mismatch",
      "Insufficient · window mismatch",
      [baseline(target, { expectedDays: baseline(target).expectedDays + 1 })],
    ],
    [
      "missing_gauge",
      "Insufficient · checkpoint gauge missing",
      [baseline(target)],
    ],
    [
      "missing_temperature",
      "Insufficient · checkpoint temperature missing",
      [baseline(target)],
    ],
    [
      "source_mismatch",
      "Insufficient · source mismatch",
      [baseline(target)],
    ],
    [
      "limited_days",
      "Insufficient · limited matching days",
      [baseline(target)],
    ],
  ].map(([id, label, baselines]) => ({
    id: id as string,
    label: label as string,
    localDate: target.checkpointDate,
    make: () => {
      let evidenceByDate = fullEvidence;
      if (id === "missing_gauge") {
        evidenceByDate = {
          ...fullEvidence,
          [cutoff]: {
            "16:00": evidence(600, 60, { gaugeFreshness: "missing" }),
          },
        };
      }
      if (id === "missing_temperature") {
        evidenceByDate = {
          ...fullEvidence,
          [cutoff]: {
            "16:00": evidence(600, 60, {
              waterTemperatureFreshness: "missing",
              waterTempF: null,
            }),
          },
        };
      }
      if (id === "source_mismatch") {
        evidenceByDate = {
          ...fullEvidence,
          [cutoff]: {
            "16:00": evidence(600, 60, {
              waterTemperatureSourceId: "other-source",
            }),
          },
        };
      }
      if (id === "limited_days") evidenceByDate = sparseEvidence;
      return scoreConditionsSuggest({
        localDate: target.checkpointDate,
        run,
        evidenceByDate,
        baselines: baselines as RiverRunConditionsSuggestBaseline[],
      });
    },
  }));
}

function conditionResult(
  label: "Typical" | "Delayed",
): RiverRunConditionsSuggest {
  const target = label === "Delayed"
    ? checkpoint("peak_start")
    : checkpoint("building_start");
  return scoreConditionsSuggest({
    localDate: target.checkpointDate,
    run,
    evidenceByDate: cumulativeEvidence(
      target,
      label === "Delayed" ? "delayed" : "typical",
    ),
    baselines: checkpoints
      .filter((item) => item.checkpointDate <= target.checkpointDate)
      .map((item) => baseline(item)),
  });
}

function typicalConditionResultForDate(
  localDate: string,
): RiverRunConditionsSuggest {
  const state = resolveConditionsSuggestCheckpointState(run, localDate);
  const target = state.activeCheckpoint;
  if (!target) {
    return scoreConditionsSuggest({
      localDate,
      run,
      evidenceByDate: {},
      baselines: [],
    });
  }
  return scoreConditionsSuggest({
    localDate,
    run,
    evidenceByDate: cumulativeEvidence(target, "typical"),
    baselines: checkpoints
      .filter((item) => item.checkpointDate <= target.checkpointDate)
      .map((item) => baseline(item)),
  });
}

function reviewTrackingState(localDate: string) {
  if (localDate < reviewWindow.startDate) return "not_started" as const;
  if (localDate > reviewWindow.endDate) return "complete" as const;
  return "active" as const;
}

function pushResult(
  label: "Weak" | "Strong",
): RiverRunPush {
  return scorePush({
    ...basePushInput(),
    ...(label === "Weak"
      ? {
        rainSignal: "dry",
        flowSignal: "falling",
        currentHydraulicValue: 500,
        hydraulicAbsoluteChange24h: -40,
        hydraulicPercentChange24h: -7.4,
        temperatureSignal: "strong_warming",
        waterTempF: 69,
      } as const
      : {
        rainSignal: "strong_rain",
        flowSignal: "meaningful_rise",
        currentHydraulicValue: 700,
        hydraulicAbsoluteChange24h: 70,
        hydraulicPercentChange24h: 11.1,
        temperatureSignal: "cooling",
        waterTempF: 59,
      } as const),
  });
}

function fishabilityResult(
  label: "Good" | "Tough",
): RiverRunFishability {
  return scoreFishability({
    ...baseFishabilityInput(),
    ...(label === "Good"
      ? {
        flowBand: "normal_fishable",
        currentHydraulicValue: 500,
      } as const
      : {
        flowBand: "very_high",
        currentHydraulicValue: 1200,
      } as const),
  });
}

function basePushInput() {
  return {
    movementEngineId: run.movementEngineId,
    rules: run.push,
    gaugeFreshness: "fresh" as const,
    rainSignal: "light_rain" as const,
    flowSignal: "stable" as const,
    currentHydraulicValue: 550,
    hydraulicAbsoluteChange24h: 0,
    hydraulicPercentChange24h: 0,
    temperatureSignal: "neutral" as const,
    temperatureSourceType: "same_gauge" as const,
    waterTempF: (run.push.temperature.supportiveMinF +
      run.push.temperature.supportiveMaxF) / 2,
    trackingState: "active" as const,
    trackingStartDate: reviewWindow.startDate,
    trackingEndDate: reviewWindow.endDate,
    localDate: reviewBaseDate,
  };
}

function baseFishabilityInput() {
  return {
    rules: run.fishabilityBands,
    gaugeFreshness: "fresh" as const,
    flowBand: "ideal" as const,
    flowSignal: "stable" as const,
    currentHydraulicValue: 600,
    hydraulicAbsoluteChange24h: 0,
    hydraulicPercentChange24h: 0,
    localDate: reviewBaseDate,
  };
}

function checkpoint(id: ConditionsSuggestCheckpoint["checkpointId"]) {
  return checkpoints.find((item) => item.checkpointId === id)!;
}

function baseline(
  target: ConditionsSuggestCheckpoint,
  overrides: Partial<RiverRunConditionsSuggestBaseline> = {},
): RiverRunConditionsSuggestBaseline {
  const expectedDays = daysBetween(
    target.observationStartDate,
    target.cutoffDate,
  ) + 1;
  return {
    riverId: "pere_marquette",
    runId: run.runId,
    checkpointId: target.checkpointId,
    referenceDayOfYear: canonicalBaselineDay(target.checkpointDate),
    observationStartDayOfYear: canonicalBaselineDay(
      target.observationStartDate,
    ),
    baselineVersion: run.conditionsSuggest.baselineVersion,
    gaugeMetric: "flow_cfs",
    gaugeSiteId: "04122500",
    temperatureSourceId: run.conditionsSuggest.temperatureSourceId,
    componentSamples: {
      gaugeAbsoluteRise: [0, 200, 400, 600, 800],
      gaugeRelativeRisePct: [0, 20, 40, 60, 80],
      meanWaterTempF: [50, 55, 60, 65, 70],
      waterCoolingF: [-5, 0, 5, 10, 15],
    },
    historicalSamples: [10, 30, 50, 70, 90].map((
      evidenceIndex,
      index,
    ) => ({
      year: 2021 + index,
      usableDays: expectedDays,
      gaugeAbsoluteRise: index * 200,
      gaugeRelativeRisePct: index * 20,
      meanWaterTempF: 70 - index * 5,
      waterCoolingF: -5 + index * 5,
      gaugeResponsePercentile: 10 + index * 20,
      waterTemperaturePercentile: 10 + index * 20,
      evidenceIndex,
    })),
    indexPercentiles: { p10: 18, p25: 30, p75: 70, p90: 82 },
    distinctYears: 5,
    expectedDays,
    minimumUsableDays: Math.ceil(
      expectedDays * run.conditionsSuggest.minimumCoveragePercent,
    ),
    sourceNotes: "Generated review fixture.",
    ...overrides,
  };
}

function delayedSecondBaseline(
  target: ConditionsSuggestCheckpoint,
): RiverRunConditionsSuggestBaseline {
  return baseline(target, {
    componentSamples: {
      gaugeAbsoluteRise: [2_000, 2_500, 3_000, 3_500, 4_000],
      gaugeRelativeRisePct: [200, 250, 300, 350, 400],
      meanWaterTempF: [30, 35, 40, 45, 50],
      waterCoolingF: [30, 35, 40, 45, 50],
    },
    historicalSamples: [10, 30, 50, 70, 90].map((
      evidenceIndex,
      index,
    ) => ({
      year: 2021 + index,
      usableDays: 27,
      gaugeAbsoluteRise: 2_000 + index * 500,
      gaugeRelativeRisePct: 200 + index * 50,
      meanWaterTempF: 50 - index * 5,
      waterCoolingF: 30 + index * 5,
      gaugeResponsePercentile: 10 + index * 20,
      waterTemperaturePercentile: 10 + index * 20,
      evidenceIndex,
    })),
  });
}

function allBaselines() {
  return checkpoints.map((item) => baseline(item));
}

function evidence(
  gaugeValue: number,
  waterTempF: number,
  overrides: Partial<ConditionsSuggestEvidence> = {},
): ConditionsSuggestEvidence {
  return {
    gaugeFreshness: "fresh",
    gaugeValue,
    gaugeMetric: "flow_cfs",
    gaugeSiteId: "04122500",
    waterTemperatureFreshness: "fresh",
    waterTempF,
    waterTemperatureSourceId: run.conditionsSuggest.temperatureSourceId,
    reasonCodes: ["gauge_fresh", "temperature_measured"],
    ...overrides,
  };
}

function cumulativeEvidence(
  target: ConditionsSuggestCheckpoint,
  kind: "ahead" | "typical" | "delayed",
): ConditionsSuggestEvidenceByDate {
  const count = daysBetween(
    target.observationStartDate,
    target.cutoffDate,
  ) + 1;
  const result: ConditionsSuggestEvidenceByDate = {};
  for (let index = 0; index < count; index += 1) {
    const localDate = addDays(target.observationStartDate, index);
    const progress = count <= 1 ? 1 : index / (count - 1);
    const gaugeValue = kind === "ahead"
      ? 300 + progress * 900
      : kind === "delayed"
      ? 500
      : 500 + index * 20;
    const waterTempF = kind === "ahead"
      ? 70 - progress * 20
      : kind === "delayed"
      ? 70
      : 64 - index * 0.4;
    result[localDate] = {
      "16:00": evidence(gaugeValue, waterTempF),
    };
  }
  return result;
}

function mixedEvidence(
  target: ConditionsSuggestCheckpoint,
): ConditionsSuggestEvidenceByDate {
  const result = cumulativeEvidence(target, "ahead");
  for (const date of Object.keys(result)) {
    const current = result[date]["16:00"]!;
    result[date] = {
      "16:00": { ...current, waterTempF: 70 },
    };
  }
  return result;
}

function scenarioCount(value: Group[]): number {
  return value.reduce((total, group) => total + group.scenarios.length, 0);
}

function shallowSnapshotDiff(
  base: RiverRunSnapshotResponse,
  target: RiverRunSnapshotResponse,
): Partial<RiverRunSnapshotResponse> {
  const diff: Partial<RiverRunSnapshotResponse> = {};
  for (
    const key of Object.keys(target) as Array<keyof RiverRunSnapshotResponse>
  ) {
    if (JSON.stringify(base[key]) === JSON.stringify(target[key])) continue;
    (diff as Record<string, unknown>)[key] = target[key];
  }
  return diff;
}

function title(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(
    /^_|_$/g,
    "",
  );
}
