import type { EngineContext } from "../supabase/functions/_shared/howFishingEngine/contracts/context.ts";
import type { RegionKey } from "../supabase/functions/_shared/howFishingEngine/contracts/region.ts";
import type { WaterClarity } from "../supabase/functions/_shared/recommenderEngine/contracts/input.ts";
import type { SpeciesGroup } from "../supabase/functions/_shared/recommenderEngine/contracts/species.ts";
import type {
  ResolvedColorThemeV3,
  RecommenderV3ArchetypeId,
} from "../supabase/functions/_shared/recommenderEngine/v3/contracts.ts";

export type RecommenderAuditSpecies =
  | "largemouth_bass"
  | "smallmouth_bass"
  | "pike_musky"
  | "river_trout";

export type RecommenderAuditRegionPriority =
  | "core"
  | "secondary";

export type RecommenderAuditScoreKey =
  | "seasonal_fit"
  | "daily_fit"
  | "water_column_fit"
  | "archetype_fit"
  | "color_fit"
  | "top3_variety"
  | "boundedness";

export type RecommenderAuditExpectation = {
  seasonal_story: string;
  primary_lanes: RecommenderV3ArchetypeId[];
  acceptable_secondary_lanes?: RecommenderV3ArchetypeId[];
  disallowed_lanes?: RecommenderV3ArchetypeId[];
  expected_color_lanes: ResolvedColorThemeV3[];
  notes?: string[];
};

export type ArchivedRecommenderAuditScenario = {
  id: string;
  label: string;
  priority: RecommenderAuditRegionPriority;
  latitude: number;
  longitude: number;
  state_code: string;
  timezone: string;
  local_date: string;
  species: RecommenderAuditSpecies;
  context: EngineContext;
  water_clarity: WaterClarity;
  expectation: RecommenderAuditExpectation;
  /** When set, matrix archive bundles use this region instead of recomputing from coordinates. */
  audit_region_key?: RegionKey;
};

export const RECOMMENDER_AUDIT_SCORE_KEYS: RecommenderAuditScoreKey[] = [
  "seasonal_fit",
  "daily_fit",
  "water_column_fit",
  "archetype_fit",
  "color_fit",
  "top3_variety",
  "boundedness",
];

export const FRESHWATER_V3_AUDIT_SPECIES_ORDER: RecommenderAuditSpecies[] = [
  "largemouth_bass",
  "smallmouth_bass",
  "river_trout",
  "pike_musky",
];

export const LARGEMOUTH_V3_ARCHIVED_SCENARIOS: ArchivedRecommenderAuditScenario[] = [
  {
    id: "lmb_florida_jan_pond_postfront",
    label: "Florida pond largemouth, winter post-front control day",
    priority: "core",
    latitude: 28.0614,
    longitude: -82.3026,
    state_code: "FL",
    timezone: "America/New_York",
    local_date: "2025-01-23",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Winter Florida bass should stay in a controlled bottom-to-lower-mid lane, not a surface lane.",
      primary_lanes: ["football_jig", "texas_rigged_soft_plastic_craw", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["compact_flipping_jig", "shaky_head_worm", "paddle_tail_swimbait"],
      disallowed_lanes: ["hollow_body_frog", "walking_topwater", "mouse_fly"],
      expected_color_lanes: ["natural", "natural", "dark"],
      notes: ["Daily warming may raise pace slightly, but should not create a drastic surface jump."],
    },
  },
  {
    id: "lmb_florida_mar_lake_prespawn",
    label: "Florida natural lake largemouth, prespawn opening window",
    priority: "core",
    latitude: 28.5383,
    longitude: -81.3792,
    state_code: "FL",
    timezone: "America/New_York",
    local_date: "2025-03-20",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Prespawn Florida largemouth should allow moving bait and jerkbait lanes without abandoning bottom-control options.",
      primary_lanes: ["suspending_jerkbait", "paddle_tail_swimbait", "compact_flipping_jig"],
      acceptable_secondary_lanes: ["spinnerbait", "weightless_stick_worm", "swim_jig"],
      disallowed_lanes: ["blade_bait", "mouse_fly"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "lmb_texas_feb_reservoir_wind",
    label: "Texas reservoir largemouth, late-winter windy baitfish day",
    priority: "core",
    latitude: 31.101,
    longitude: -95.566,
    state_code: "TX",
    timezone: "America/Chicago",
    local_date: "2025-02-19",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Southern reservoir bass can lean baitfish and wind-reactive, but truly harsh late-winter cold snaps can still collapse the day back toward a football jig while keeping one moving-lane backup alive.",
      primary_lanes: ["football_jig", "spinnerbait", "bladed_jig", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["paddle_tail_swimbait", "texas_rigged_soft_plastic_craw", "swim_jig"],
      disallowed_lanes: ["hollow_body_frog", "popper_fly"],
      expected_color_lanes: ["natural", "bright", "dark"],
    },
  },
  {
    id: "lmb_alabama_may_river_current",
    label: "Alabama river largemouth, spring current seam pattern",
    priority: "core",
    latitude: 34.8,
    longitude: -87.67,
    state_code: "AL",
    timezone: "America/Chicago",
    local_date: "2025-05-12",
    species: "largemouth_bass",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "River largemouth should still reflect bass current positioning instead of generic lake behavior.",
      primary_lanes: ["spinnerbait", "swim_jig", "soft_jerkbait"],
      acceptable_secondary_lanes: ["compact_flipping_jig", "paddle_tail_swimbait", "game_changer"],
      disallowed_lanes: ["hollow_body_frog"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "lmb_mississippi_jun_backwater_dirty",
    label: "Mississippi backwater largemouth, warm stained summer cover day",
    priority: "secondary",
    latitude: 35.143,
    longitude: -90.052,
    state_code: "TN",
    timezone: "America/Chicago",
    local_date: "2025-06-18",
    species: "largemouth_bass",
    context: "freshwater_river",
    water_clarity: "dirty",
    expectation: {
      seasonal_story: "Warm dirty river largemouth should favor visible cover-oriented lanes first; cleaner baitfish flies can exist only as a low-priority fallback rather than the core story.",
      primary_lanes: ["compact_flipping_jig", "texas_rigged_soft_plastic_craw", "spinnerbait"],
      acceptable_secondary_lanes: ["bladed_jig", "frog_fly", "swim_jig", "clouser_minnow"],
      disallowed_lanes: ["drop_shot_worm"],
      expected_color_lanes: ["dark", "natural", "bright"],
    },
  },
  {
    id: "lmb_louisiana_sep_shallow_grass",
    label: "Louisiana largemouth, early-fall stained grass pattern",
    priority: "core",
    latitude: 30.208,
    longitude: -92.329,
    state_code: "LA",
    timezone: "America/Chicago",
    local_date: "2025-09-17",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Early-fall southern largemouth should open surface and horizontal cover lanes more freely than summer bluebird windows.",
      primary_lanes: ["walking_topwater", "swim_jig", "spinnerbait"],
      acceptable_secondary_lanes: ["hollow_body_frog", "bladed_jig", "popper_fly"],
      disallowed_lanes: ["blade_bait"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "lmb_ozarks_oct_shad_transition",
    label: "Ozarks largemouth, fall shad transition reservoir day",
    priority: "core",
    latitude: 36.525,
    longitude: -93.214,
    state_code: "MO",
    timezone: "America/Chicago",
    local_date: "2025-10-11",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Fall largemouth should strongly respect baitfish transition lanes, and on calm mixed-light shad days a suspending jerkbait can lead without breaking the transition story.",
      primary_lanes: ["squarebill_crankbait", "spinnerbait", "paddle_tail_swimbait", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["soft_jerkbait", "flat_sided_crankbait", "game_changer"],
      disallowed_lanes: ["texas_rigged_soft_plastic_craw"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "lmb_california_nov_delta_stained",
    label: "California Delta largemouth, late-fall stained tidal freshwater grass",
    priority: "secondary",
    latitude: 38.035,
    longitude: -121.636,
    state_code: "CA",
    timezone: "America/Los_Angeles",
    local_date: "2025-11-06",
    species: "largemouth_bass",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Late-fall largemouth should slow some, but Delta-style stained water still needs visible horizontal or cover-oriented lanes.",
      primary_lanes: ["bladed_jig", "compact_flipping_jig", "spinnerbait"],
      acceptable_secondary_lanes: ["paddle_tail_swimbait", "rabbit_strip_leech"],
      disallowed_lanes: ["walking_topwater"],
      expected_color_lanes: ["dark", "bright", "natural"],
    },
  },
  {
    id: "lmb_texas_dec_pond_cold_clear",
    label: "Texas pond largemouth, early-winter clear slowdown",
    priority: "core",
    latitude: 32.7767,
    longitude: -96.797,
    state_code: "TX",
    timezone: "America/Chicago",
    local_date: "2025-12-14",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-winter largemouth should tighten to slower lower-column lanes with only mild daily openings.",
      primary_lanes: ["football_jig", "shaky_head_worm", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["blade_bait", "rabbit_strip_leech"],
      disallowed_lanes: ["walking_topwater", "hollow_body_frog"],
      expected_color_lanes: ["natural", "dark", "natural"],
    },
  },
  {
    id: "lmb_florida_feb_natural_lake_prespawn_stained",
    label: "Florida natural lake largemouth, stained prespawn push",
    priority: "core",
    latitude: 26.94,
    longitude: -80.8,
    state_code: "FL",
    timezone: "America/New_York",
    local_date: "2025-02-19",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Florida prespawn largemouth should lean baitfish and craw transition lanes without jumping straight into pure surface behavior.",
      primary_lanes: ["suspending_jerkbait", "paddle_tail_swimbait", "spinnerbait"],
      acceptable_secondary_lanes: ["compact_flipping_jig", "swim_jig", "football_jig"],
      disallowed_lanes: ["hollow_body_frog", "mouse_fly"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "lmb_florida_oct_grass_lake_fall",
    label: "Florida lake largemouth, fall grass and baitfish shift",
    priority: "core",
    latitude: 26.94,
    longitude: -80.8,
    state_code: "FL",
    timezone: "America/New_York",
    local_date: "2025-10-15",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Florida fall largemouth should allow stronger shallow baitfish and surface-cover options than the summer slowdown windows.",
      primary_lanes: ["walking_topwater", "swim_jig", "spinnerbait"],
      acceptable_secondary_lanes: ["bladed_jig", "hollow_body_frog", "popper_fly"],
      disallowed_lanes: ["blade_bait"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "lmb_texas_nov_reservoir_latefall",
    label: "Texas reservoir largemouth, late-fall tightening baitfish window",
    priority: "core",
    latitude: 31.101,
    longitude: -95.566,
    state_code: "TX",
    timezone: "America/Chicago",
    local_date: "2025-11-12",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Late-fall south-central reservoir bass should tighten around slower baitfish lanes with bottom-control backups still in play.",
      primary_lanes: ["suspending_jerkbait", "flat_sided_crankbait", "football_jig"],
      acceptable_secondary_lanes: ["blade_bait", "paddle_tail_swimbait", "rabbit_strip_leech"],
      disallowed_lanes: ["walking_topwater", "hollow_body_frog"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "lmb_alabama_mar_river_prespawn",
    label: "Alabama river largemouth, prespawn current opening",
    priority: "core",
    latitude: 34.8,
    longitude: -87.67,
    state_code: "AL",
    timezone: "America/Chicago",
    local_date: "2025-03-20",
    species: "largemouth_bass",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "River largemouth in prespawn should use current seams and softer edges with moving search lanes that still feel river-specific.",
      primary_lanes: ["spinnerbait", "swim_jig", "soft_jerkbait"],
      acceptable_secondary_lanes: ["squarebill_crankbait", "texas_rigged_soft_plastic_craw", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "lmb_alabama_sep_river_fall_current",
    label: "Alabama river largemouth, early-fall current and baitfish movement",
    priority: "core",
    latitude: 34.8,
    longitude: -87.67,
    state_code: "AL",
    timezone: "America/Chicago",
    local_date: "2025-09-17",
    species: "largemouth_bass",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Early-fall river largemouth should open horizontal baitfish lanes around current edges without losing river-specific control.",
      primary_lanes: ["spinnerbait", "paddle_tail_swimbait", "squarebill_crankbait"],
      acceptable_secondary_lanes: ["bladed_jig", "soft_jerkbait", "clouser_minnow"],
      disallowed_lanes: ["drop_shot_worm"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "lmb_louisiana_nov_grass_lake_latefall",
    label: "Louisiana grass lake largemouth, late-fall stained grass slowdown",
    priority: "secondary",
    latitude: 30.208,
    longitude: -92.329,
    state_code: "LA",
    timezone: "America/Chicago",
    local_date: "2025-11-12",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Late-fall southern grass largemouth should slow some, but still favor visible shallow cover and horizontal baitfish lanes over dead winter behavior.",
      primary_lanes: ["bladed_jig", "spinnerbait", "compact_flipping_jig"],
      acceptable_secondary_lanes: ["paddle_tail_swimbait", "rabbit_strip_leech", "hollow_body_frog"],
      disallowed_lanes: ["blade_bait"],
      expected_color_lanes: ["dark", "bright", "natural"],
    },
  },
  {
    id: "lmb_ozarks_feb_clear_reservoir_prespawn",
    label: "Ozarks largemouth, clear cold prespawn reservoir day",
    priority: "secondary",
    latitude: 36.525,
    longitude: -93.214,
    state_code: "MO",
    timezone: "America/Chicago",
    local_date: "2025-02-19",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Cold clear Ozarks largemouth should stay disciplined around jerkbait, flat-side, and jig lanes instead of jumping too shallow or too loud.",
      primary_lanes: ["suspending_jerkbait", "flat_sided_crankbait", "football_jig"],
      acceptable_secondary_lanes: ["paddle_tail_swimbait", "blade_bait", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog", "walking_topwater"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "lmb_florida_aug_grass_lake_heat_dirty",
    label: "Florida grass lake largemouth, dirty late-summer heat control",
    priority: "core",
    latitude: 26.94,
    longitude: -80.8,
    state_code: "FL",
    timezone: "America/New_York",
    local_date: "2025-08-14",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "dirty",
    expectation: {
      seasonal_story: "Late-summer Florida largemouth in dirty grass should stay cover-oriented with bold visible lanes, not drift into clear-water finesse.",
      primary_lanes: ["compact_flipping_jig", "texas_rigged_soft_plastic_craw", "hollow_body_frog"],
      acceptable_secondary_lanes: ["swim_jig", "buzzbait", "prop_bait", "frog_fly"],
      disallowed_lanes: ["drop_shot_worm", "suspending_jerkbait"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
  {
    id: "lmb_texas_jan_reservoir_cold_stained",
    label: "Texas reservoir largemouth, stained midwinter tightening window",
    priority: "core",
    latitude: 31.101,
    longitude: -95.566,
    state_code: "TX",
    timezone: "America/Chicago",
    local_date: "2025-01-16",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Midwinter south-central reservoir bass should stay controlled and lower-column, but stained water can still keep a jerkbait or flat-side in play.",
      primary_lanes: ["football_jig", "suspending_jerkbait", "flat_sided_crankbait"],
      acceptable_secondary_lanes: ["shaky_head_worm", "texas_rigged_soft_plastic_craw", "rabbit_strip_leech"],
      disallowed_lanes: ["walking_topwater", "hollow_body_frog"],
      expected_color_lanes: ["natural", "natural", "dark"],
    },
  },
  {
    id: "lmb_georgia_dec_highland_clear",
    label: "Georgia highland largemouth, clear early-winter reservoir day",
    priority: "secondary",
    latitude: 34.579,
    longitude: -83.543,
    state_code: "GA",
    timezone: "America/New_York",
    local_date: "2025-12-10",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear highland winter largemouth should stay disciplined around baitfish and subtle lower-mid control, not noisy dirty-water lanes.",
      primary_lanes: ["suspending_jerkbait", "flat_sided_crankbait", "paddle_tail_swimbait"],
      acceptable_secondary_lanes: ["football_jig", "drop_shot_worm", "clouser_minnow"],
      disallowed_lanes: ["buzzbait", "prop_bait", "hollow_body_frog"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "lmb_louisiana_mar_grass_lake_prespawn_dirty",
    label: "Louisiana grass lake largemouth, dirty prespawn push",
    priority: "core",
    latitude: 30.208,
    longitude: -92.329,
    state_code: "LA",
    timezone: "America/Chicago",
    local_date: "2025-03-20",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "dirty",
    expectation: {
      seasonal_story: "Dirty-water southern prespawn bass should still push shallow with visible grass and baitfish lanes, but without leaping into pure surface-only behavior.",
      primary_lanes: ["spinnerbait", "bladed_jig", "compact_flipping_jig"],
      acceptable_secondary_lanes: ["swim_jig", "paddle_tail_swimbait", "game_changer"],
      disallowed_lanes: ["drop_shot_worm", "walking_topwater"],
      expected_color_lanes: ["dark", "bright", "natural"],
    },
  },
  {
    id: "lmb_minnesota_sep_weed_lake_stained",
    label: "Minnesota weed lake largemouth, stained early-fall edge pattern",
    priority: "secondary",
    latitude: 46.7296,
    longitude: -94.6859,
    state_code: "MN",
    timezone: "America/Chicago",
    local_date: "2025-09-17",
    species: "largemouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Northern early-fall weedline largemouth should open horizontal edge lanes and a surface option, but still through a cooler-water seasonal posture.",
      primary_lanes: ["spinnerbait", "swim_jig", "walking_topwater"],
      acceptable_secondary_lanes: ["paddle_tail_swimbait", "hollow_body_frog", "mouse_fly"],
      disallowed_lanes: ["blade_bait"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "lmb_california_mar_delta_clear",
    label: "California Delta largemouth, clearer prespawn tidal-fresh setup",
    priority: "secondary",
    latitude: 38.035,
    longitude: -121.636,
    state_code: "CA",
    timezone: "America/Los_Angeles",
    local_date: "2025-03-20",
    species: "largemouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clearer prespawn Delta largemouth should still respect current and cover, but with cleaner baitfish and target lanes than the stained late-fall version.",
      primary_lanes: ["soft_jerkbait", "compact_flipping_jig", "spinnerbait"],
      acceptable_secondary_lanes: ["swim_jig", "paddle_tail_swimbait", "game_changer"],
      disallowed_lanes: ["walking_topwater", "blade_bait"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
];

export const SMALLMOUTH_V3_BATCH_TARGETS = {
  core_regions: ["great_lakes_upper_midwest", "appalachian", "northeast", "midwest_interior"],
  target_gold_scenarios: 50,
} as const;

export const SMALLMOUTH_V3_ARCHIVED_SCENARIOS: ArchivedRecommenderAuditScenario[] = [
  {
    id: "smb_michigan_jan_clear_lake_winter",
    label: "Michigan smallmouth, clear natural lake winter control day",
    priority: "core",
    latitude: 44.9747,
    longitude: -85.2278,
    state_code: "MI",
    timezone: "America/Detroit",
    local_date: "2025-01-16",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Cold clear winter smallmouth should stay disciplined around bottom-to-lower-mid control with tubes, hair, blade, and jerkbait lanes.",
      primary_lanes: ["tube_jig", "hair_jig", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["blade_bait", "drop_shot_worm", "sculpin_streamer"],
      disallowed_lanes: ["walking_topwater", "popping_topwater", "frog_fly"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "smb_tennessee_mar_river_prespawn_stained",
    label: "Tennessee river smallmouth, stained prespawn current opening",
    priority: "core",
    latitude: 35.3973,
    longitude: -84.6705,
    state_code: "TN",
    timezone: "America/New_York",
    local_date: "2025-03-20",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Prespawn river smallmouth should use current seams with tube, Ned, spinner, jerkbait, and soft-minnow lanes that still feel current-driven.",
      primary_lanes: ["tube_jig", "ned_rig", "spinnerbait"],
      acceptable_secondary_lanes: ["soft_jerkbait", "suspending_jerkbait", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog", "buzzbait", "prop_bait"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "smb_newyork_apr_lake_clear_prespawn",
    label: "New York lake smallmouth, clear prespawn setup",
    priority: "core",
    latitude: 43.0829,
    longitude: -76.176,
    state_code: "NY",
    timezone: "America/New_York",
    local_date: "2025-04-16",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear prespawn smallmouth lakes should strongly respect tube, football, jerkbait, swimbait, and hair-jig lanes without noisy surface drift.",
      primary_lanes: ["tube_jig", "football_jig", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["hair_jig", "paddle_tail_swimbait", "clouser_minnow"],
      disallowed_lanes: ["walking_topwater", "popping_topwater", "mouse_fly"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "smb_missouri_may_river_spawn_clear",
    label: "Missouri river smallmouth, clear late-spring seam and rock day",
    priority: "secondary",
    latitude: 37.9643,
    longitude: -91.8318,
    state_code: "MO",
    timezone: "America/Chicago",
    local_date: "2025-05-15",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Late-spring river smallmouth should still feel current- and rock-oriented, mixing tube/Ned control with moving seam reads.",
      primary_lanes: ["tube_jig", "ned_rig", "soft_jerkbait"],
      acceptable_secondary_lanes: ["spinnerbait", "squarebill_crankbait", "crawfish_streamer"],
      disallowed_lanes: ["hollow_body_frog", "buzzbait", "prop_bait"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "smb_michigan_jun_lake_postspawn_clear",
    label: "Michigan smallmouth, clear postspawn lake baitfish shift",
    priority: "core",
    latitude: 45.0727,
    longitude: -84.6748,
    state_code: "MI",
    timezone: "America/Detroit",
    local_date: "2025-06-18",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Postspawn lake smallmouth should open horizontal baitfish and clean topwater lanes while keeping tube/drop-shot as disciplined backups.",
      primary_lanes: ["soft_jerkbait", "paddle_tail_swimbait", "walking_topwater"],
      acceptable_secondary_lanes: ["tube_jig", "drop_shot_worm", "game_changer"],
      disallowed_lanes: ["hollow_body_frog"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "smb_tennessee_jul_river_stained_summer",
    label: "Tennessee river smallmouth, stained midsummer current and shade pattern",
    priority: "core",
    latitude: 35.3973,
    longitude: -84.6705,
    state_code: "TN",
    timezone: "America/New_York",
    local_date: "2025-07-16",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Summer river smallmouth should lean current-edge topwater, inline spinner, spinnerbait, and soft-minnow lanes rather than lake-style bottom dragging.",
      primary_lanes: ["walking_topwater", "inline_spinner", "spinnerbait"],
      acceptable_secondary_lanes: ["tube_jig", "soft_jerkbait", "popper_fly"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["natural", "bright", "bright"],
    },
  },
  {
    id: "smb_wisconsin_aug_lake_clear_summer",
    label: "Wisconsin smallmouth, clear summer natural lake bluebird setup",
    priority: "core",
    latitude: 46.0481,
    longitude: -89.486,
    state_code: "WI",
    timezone: "America/Chicago",
    local_date: "2025-08-14",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Bluebird summer smallmouth should still allow topwater and baitfish lanes, but only alongside clean drop-shot, tube, and hair-jig control.",
      primary_lanes: ["drop_shot_worm", "tube_jig", "hair_jig"],
      acceptable_secondary_lanes: ["walking_topwater", "paddle_tail_swimbait", "game_changer"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "smb_pennsylvania_sep_river_clear_fall",
    label: "Pennsylvania river smallmouth, clear early-fall baitfish movement",
    priority: "core",
    latitude: 41.9912,
    longitude: -77.5542,
    state_code: "PA",
    timezone: "America/New_York",
    local_date: "2025-09-17",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-fall river smallmouth should open jerkbait, spinnerbait, swimbait, and inline-search lanes while staying river-current aware.",
      primary_lanes: ["suspending_jerkbait", "spinnerbait", "paddle_tail_swimbait"],
      acceptable_secondary_lanes: ["inline_spinner", "tube_jig", "slim_minnow_streamer"],
      disallowed_lanes: ["hollow_body_frog"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "smb_minnesota_oct_lake_stained_fall",
    label: "Minnesota smallmouth, stained fall lake tightening window",
    priority: "secondary",
    latitude: 46.7296,
    longitude: -94.6859,
    state_code: "MN",
    timezone: "America/Chicago",
    local_date: "2025-10-15",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Fall lake smallmouth should tighten around jerkbait, swimbait, spinnerbait, and blade lanes without drifting toward warmwater-only cover baits.",
      primary_lanes: ["suspending_jerkbait", "paddle_tail_swimbait", "blade_bait"],
      acceptable_secondary_lanes: ["spinnerbait", "hair_jig", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "smb_colorado_dec_river_clear_winter",
    label: "Colorado river smallmouth, clear early-winter control day",
    priority: "secondary",
    latitude: 38.4783,
    longitude: -107.8762,
    state_code: "CO",
    timezone: "America/Denver",
    local_date: "2025-12-10",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-winter western river smallmouth should stay in subtle lower-column control with tubes, hair, Ned, blade, and sculpin-style flies.",
      primary_lanes: ["tube_jig", "hair_jig", "ned_rig"],
      acceptable_secondary_lanes: ["blade_bait", "suspending_jerkbait", "sculpin_streamer"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
];

export const SMALLMOUTH_V3_GOLD_BATCH_1_IDS = [
  "smb_michigan_jan_clear_lake_winter",
  "smb_tennessee_mar_river_prespawn_stained",
  "smb_newyork_apr_lake_clear_prespawn",
  "smb_missouri_may_river_spawn_clear",
  "smb_michigan_jun_lake_postspawn_clear",
  "smb_tennessee_jul_river_stained_summer",
  "smb_wisconsin_aug_lake_clear_summer",
  "smb_pennsylvania_sep_river_clear_fall",
  "smb_minnesota_oct_lake_stained_fall",
  "smb_colorado_dec_river_clear_winter",
] as const;

export const SMALLMOUTH_V3_GOLD_BATCH_1 = SMALLMOUTH_V3_ARCHIVED_SCENARIOS.filter(
  (scenario) => SMALLMOUTH_V3_GOLD_BATCH_1_IDS.includes(
    scenario.id as typeof SMALLMOUTH_V3_GOLD_BATCH_1_IDS[number],
  ),
);

export const SMALLMOUTH_V3_ARCHIVED_SCENARIOS_BATCH_2: ArchivedRecommenderAuditScenario[] = [
  {
    id: "smb_tennessee_feb_river_clear_coldfront",
    label: "Tennessee river smallmouth, clear late-winter cold-front reset",
    priority: "core",
    latitude: 35.3973,
    longitude: -84.6705,
    state_code: "TN",
    timezone: "America/New_York",
    local_date: "2025-02-19",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Late-winter clear river smallmouth should stay in subtle current-aware control with tube, hair, Ned, blade, and jerkbait lanes.",
      primary_lanes: ["tube_jig", "hair_jig", "ned_rig"],
      acceptable_secondary_lanes: ["blade_bait", "suspending_jerkbait", "sculpin_streamer"],
      disallowed_lanes: ["walking_topwater", "popping_topwater", "buzzbait", "prop_bait"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "smb_kentucky_apr_lake_stained_wind",
    label: "Kentucky highland lake smallmouth, stained windy spring push",
    priority: "core",
    latitude: 36.9156,
    longitude: -86.3922,
    state_code: "KY",
    timezone: "America/Chicago",
    local_date: "2025-04-16",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Windy stained spring smallmouth lakes should still feel prespawn-to-spawn disciplined, but allow jerkbait, crankbait, and swimbait lanes to open up.",
      primary_lanes: ["tube_jig", "suspending_jerkbait", "paddle_tail_swimbait"],
      acceptable_secondary_lanes: ["flat_sided_crankbait", "hair_jig", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog", "buzzbait", "prop_bait"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "smb_wisconsin_may_lake_clear_spawn",
    label: "Wisconsin smallmouth, clear lake spawn-stage control",
    priority: "core",
    latitude: 46.0481,
    longitude: -89.486,
    state_code: "WI",
    timezone: "America/Chicago",
    local_date: "2025-05-15",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Spawn-stage clear lake smallmouth should stay target- and bottom-aware with tube, Ned, drop-shot, and clean jerkbait lanes rather than noisy surface jumps.",
      primary_lanes: ["tube_jig", "ned_rig", "drop_shot_worm"],
      acceptable_secondary_lanes: ["suspending_jerkbait", "hair_jig", "crawfish_streamer"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "smb_colorado_jun_river_clear_postspawn",
    label: "Colorado river smallmouth, clear postspawn baitfish opening",
    priority: "secondary",
    latitude: 38.4783,
    longitude: -107.8762,
    state_code: "CO",
    timezone: "America/Denver",
    local_date: "2025-06-18",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear western postspawn river smallmouth should open soft-minnow, spinner, and topwater lanes, but still carry a clean tube backup.",
      primary_lanes: ["soft_jerkbait", "inline_spinner", "walking_topwater"],
      acceptable_secondary_lanes: ["tube_jig", "paddle_tail_swimbait", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "smb_michigan_jul_lake_clear_topwater",
    label: "Michigan smallmouth, clear midsummer lake topwater window",
    priority: "core",
    latitude: 45.0727,
    longitude: -84.6748,
    state_code: "MI",
    timezone: "America/Detroit",
    local_date: "2025-07-16",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear midsummer lake smallmouth should allow topwater and clean baitfish lanes, but still through a smallmouth lens with tube/drop-shot support.",
      primary_lanes: ["walking_topwater", "paddle_tail_swimbait", "drop_shot_worm"],
      acceptable_secondary_lanes: ["tube_jig", "hair_jig", "popper_fly"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
  {
    id: "smb_missouri_aug_river_stained_lowlight",
    label: "Missouri river smallmouth, stained low-light summer seam pattern",
    priority: "core",
    latitude: 37.9643,
    longitude: -91.8318,
    state_code: "MO",
    timezone: "America/Chicago",
    local_date: "2025-08-14",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Stained low-light summer river smallmouth should open inline spinner, spinnerbait, topwater, and minnow lanes rather than only bottom control.",
      primary_lanes: ["inline_spinner", "spinnerbait", "walking_topwater"],
      acceptable_secondary_lanes: ["soft_jerkbait", "tube_jig", "popper_fly"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["bright", "natural", "bright"],
    },
  },
  {
    id: "smb_pennsylvania_oct_river_clear_latefall",
    label: "Pennsylvania river smallmouth, clear late-fall tightening baitfish day",
    priority: "core",
    latitude: 41.9912,
    longitude: -77.5542,
    state_code: "PA",
    timezone: "America/New_York",
    local_date: "2025-10-15",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Late-fall clear river smallmouth should tighten around jerkbait, swimbait, blade, and minnow-streamer lanes without warmwater surface drift.",
      primary_lanes: ["suspending_jerkbait", "paddle_tail_swimbait", "blade_bait"],
      acceptable_secondary_lanes: ["inline_spinner", "slim_minnow_streamer", "tube_jig"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "smb_minnesota_nov_lake_stained_latefall",
    label: "Minnesota smallmouth, stained late-fall lake control window",
    priority: "secondary",
    latitude: 46.7296,
    longitude: -94.6859,
    state_code: "MN",
    timezone: "America/Chicago",
    local_date: "2025-11-12",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Late-fall stained lake smallmouth should tighten into jerkbait, blade, hair, and swimbait lanes with a disciplined lower-column read.",
      primary_lanes: ["suspending_jerkbait", "blade_bait", "hair_jig"],
      acceptable_secondary_lanes: ["paddle_tail_swimbait", "tube_jig", "slim_minnow_streamer"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "smb_washington_sep_river_clear_fall",
    label: "Washington river smallmouth, clear early-fall current and baitfish movement",
    priority: "secondary",
    latitude: 46.2396,
    longitude: -119.1006,
    state_code: "WA",
    timezone: "America/Los_Angeles",
    local_date: "2025-09-17",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear early-fall western river smallmouth should keep current-aware jerkbait, spinner, and swimbait lanes in front, with a tube backup not a largemouth cover read.",
      primary_lanes: ["suspending_jerkbait", "inline_spinner", "paddle_tail_swimbait"],
      acceptable_secondary_lanes: ["spinnerbait", "tube_jig", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "smb_ohio_dec_lake_clear_winter",
    label: "Ohio smallmouth, clear early-winter reservoir tightening day",
    priority: "core",
    latitude: 40.367,
    longitude: -82.9962,
    state_code: "OH",
    timezone: "America/New_York",
    local_date: "2025-12-10",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-winter clear smallmouth lakes should stay in subtle lower-column control with tube, hair, blade, and jerkbait lanes, not warm-season power.",
      primary_lanes: ["tube_jig", "hair_jig", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["blade_bait", "drop_shot_worm", "sculpin_streamer"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["natural", "natural", "natural"],
    },
  },
];

export const SMALLMOUTH_V3_GOLD_BATCH_2_IDS = [
  "smb_tennessee_feb_river_clear_coldfront",
  "smb_kentucky_apr_lake_stained_wind",
  "smb_wisconsin_may_lake_clear_spawn",
  "smb_colorado_jun_river_clear_postspawn",
  "smb_michigan_jul_lake_clear_topwater",
  "smb_missouri_aug_river_stained_lowlight",
  "smb_washington_sep_river_clear_fall",
  "smb_pennsylvania_oct_river_clear_latefall",
  "smb_minnesota_nov_lake_stained_latefall",
  "smb_ohio_dec_lake_clear_winter",
] as const;

export const SMALLMOUTH_V3_GOLD_BATCH_2 = SMALLMOUTH_V3_ARCHIVED_SCENARIOS_BATCH_2.filter(
  (scenario) => SMALLMOUTH_V3_GOLD_BATCH_2_IDS.includes(
    scenario.id as typeof SMALLMOUTH_V3_GOLD_BATCH_2_IDS[number],
  ),
);

export const SMALLMOUTH_V3_ARCHIVED_SCENARIOS_BATCH_3: ArchivedRecommenderAuditScenario[] = [
  {
    id: "smb_tennessee_mar_river_stained_spinner_push",
    label: "Tennessee river smallmouth, stained prespawn spinner push",
    priority: "core",
    latitude: 35.3973,
    longitude: -84.6705,
    state_code: "TN",
    timezone: "America/New_York",
    local_date: "2025-03-12",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Stained prespawn river smallmouth should still feel current-seam and rock disciplined, but spinnerbait, tube, and soft-minnow lanes should open naturally.",
      primary_lanes: ["spinnerbait", "tube_jig", "soft_jerkbait"],
      acceptable_secondary_lanes: ["suspending_jerkbait", "inline_spinner", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog", "buzzbait", "prop_bait"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "smb_ohio_apr_lake_dirty_prespawn",
    label: "Ohio smallmouth, dirty prespawn reservoir adjustment",
    priority: "core",
    latitude: 40.367,
    longitude: -82.9962,
    state_code: "OH",
    timezone: "America/New_York",
    local_date: "2025-04-09",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "dirty",
    expectation: {
      seasonal_story: "Dirty prespawn smallmouth lakes should stay disciplined, but allow spinnerbait, tube, and suspending-jerkbait lanes rather than only clean-water finesse.",
      primary_lanes: ["spinnerbait", "tube_jig", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["paddle_tail_swimbait", "flat_sided_crankbait", "clouser_minnow"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "smb_kentucky_may_lake_stained_wind",
    label: "Kentucky smallmouth, stained late-spring wind lane",
    priority: "core",
    latitude: 36.9156,
    longitude: -86.3922,
    state_code: "KY",
    timezone: "America/Chicago",
    local_date: "2025-05-14",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Late-spring stained smallmouth lakes should let wind-opened spinnerbait, swimbait, and tube lanes work without drifting into largemouth cover logic.",
      primary_lanes: ["spinnerbait", "paddle_tail_swimbait", "tube_jig"],
      acceptable_secondary_lanes: ["soft_jerkbait", "flat_sided_crankbait", "game_changer"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "smb_wisconsin_jun_river_clear_postspawn",
    label: "Wisconsin river smallmouth, clear postspawn eddy and minnow lane",
    priority: "secondary",
    latitude: 46.0481,
    longitude: -89.486,
    state_code: "WI",
    timezone: "America/Chicago",
    local_date: "2025-06-19",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear postspawn river smallmouth should open soft-minnow, inline-spinner, and tube lanes while staying current-aware and not overcommitting to largemouth-style power.",
      primary_lanes: ["soft_jerkbait", "inline_spinner", "tube_jig"],
      acceptable_secondary_lanes: ["paddle_tail_swimbait", "walking_topwater", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "smb_colorado_jul_river_stained_summer",
    label: "Colorado river smallmouth, stained summer current-search day",
    priority: "secondary",
    latitude: 38.4783,
    longitude: -107.8762,
    state_code: "CO",
    timezone: "America/Denver",
    local_date: "2025-07-17",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Stained summer western river smallmouth should open spinner, inline, and soft-minnow lanes more than bottom-only control, but still through a river lens.",
      primary_lanes: ["spinnerbait", "inline_spinner", "soft_jerkbait"],
      acceptable_secondary_lanes: ["paddle_tail_swimbait", "tube_jig", "clouser_minnow"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["bright", "natural", "bright"],
    },
  },
  {
    id: "smb_michigan_aug_lake_stained_wind",
    label: "Michigan smallmouth, stained windy late-summer lake lane",
    priority: "core",
    latitude: 45.0727,
    longitude: -84.6748,
    state_code: "MI",
    timezone: "America/Detroit",
    local_date: "2025-08-20",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Windy stained late-summer lake smallmouth should allow spinnerbait, walking topwater, and swimbait lanes while still carrying tube support.",
      primary_lanes: ["spinnerbait", "walking_topwater", "paddle_tail_swimbait"],
      acceptable_secondary_lanes: ["tube_jig", "drop_shot_worm", "popper_fly"],
      disallowed_lanes: ["hollow_body_frog", "compact_flipping_jig"],
      expected_color_lanes: ["natural", "bright", "natural"],
    },
  },
  {
    id: "smb_pennsylvania_sep_river_dirty_flow_bump",
    label: "Pennsylvania river smallmouth, dirty early-fall flow-bump day",
    priority: "core",
    latitude: 41.9912,
    longitude: -77.5542,
    state_code: "PA",
    timezone: "America/New_York",
    local_date: "2025-09-24",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "dirty",
    expectation: {
      seasonal_story: "A dirty early-fall river bump should tighten smallmouth some, but spinnerbait, swimbait, and visible streamer lanes should still lead over clean-water finesse.",
      primary_lanes: ["spinnerbait", "paddle_tail_swimbait", "clouser_minnow"],
      acceptable_secondary_lanes: ["tube_jig", "squarebill_crankbait", "game_changer"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["bright", "natural", "dark"],
    },
  },
  {
    id: "smb_minnesota_oct_lake_clear_fall",
    label: "Minnesota smallmouth, clear fall lake baitfish tightening",
    priority: "core",
    latitude: 46.7296,
    longitude: -94.6859,
    state_code: "MN",
    timezone: "America/Chicago",
    local_date: "2025-10-14",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear fall smallmouth lakes should tighten around jerkbait, swimbait, and hair-jig lanes with clean baitfish colors and little warmwater drift.",
      primary_lanes: ["suspending_jerkbait", "paddle_tail_swimbait", "hair_jig"],
      acceptable_secondary_lanes: ["blade_bait", "tube_jig", "slim_minnow_streamer"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "smb_missouri_nov_river_clear_blade",
    label: "Missouri river smallmouth, clear late-fall blade and jerkbait day",
    priority: "secondary",
    latitude: 37.9643,
    longitude: -91.8318,
    state_code: "MO",
    timezone: "America/Chicago",
    local_date: "2025-11-13",
    species: "smallmouth_bass",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear late-fall river smallmouth should live in blade, jerkbait, and swimbait lanes with tube and minnow-streamer backup, not surface or cover lanes.",
      primary_lanes: ["blade_bait", "suspending_jerkbait", "paddle_tail_swimbait"],
      acceptable_secondary_lanes: ["tube_jig", "slim_minnow_streamer", "inline_spinner"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["bright", "natural", "natural"],
    },
  },
  {
    id: "smb_washington_dec_lake_dirty_winter",
    label: "Washington smallmouth, dirty early-winter reservoir control day",
    priority: "secondary",
    latitude: 46.2396,
    longitude: -119.1006,
    state_code: "WA",
    timezone: "America/Los_Angeles",
    local_date: "2025-12-11",
    species: "smallmouth_bass",
    context: "freshwater_lake_pond",
    water_clarity: "dirty",
    expectation: {
      seasonal_story: "Dirty early-winter smallmouth reservoirs should still stay lower-column and disciplined, but visible jerkbait, blade, and hair/tube lanes should remain in play.",
      primary_lanes: ["suspending_jerkbait", "blade_bait", "hair_jig"],
      acceptable_secondary_lanes: ["tube_jig", "paddle_tail_swimbait", "clouser_minnow"],
      disallowed_lanes: ["walking_topwater", "popping_topwater"],
      expected_color_lanes: ["natural", "bright", "dark"],
    },
  },
];

export const SMALLMOUTH_V3_GOLD_BATCH_3_IDS = [
  "smb_tennessee_mar_river_stained_spinner_push",
  "smb_ohio_apr_lake_dirty_prespawn",
  "smb_kentucky_may_lake_stained_wind",
  "smb_wisconsin_jun_river_clear_postspawn",
  "smb_colorado_jul_river_stained_summer",
  "smb_michigan_aug_lake_stained_wind",
  "smb_pennsylvania_sep_river_dirty_flow_bump",
  "smb_minnesota_oct_lake_clear_fall",
  "smb_missouri_nov_river_clear_blade",
  "smb_washington_dec_lake_dirty_winter",
] as const;

export const SMALLMOUTH_V3_GOLD_BATCH_3 = SMALLMOUTH_V3_ARCHIVED_SCENARIOS_BATCH_3.filter(
  (scenario) => SMALLMOUTH_V3_GOLD_BATCH_3_IDS.includes(
    scenario.id as typeof SMALLMOUTH_V3_GOLD_BATCH_3_IDS[number],
  ),
);

export const LARGEMOUTH_V3_GOLD_BATCH_1_IDS = [
  "lmb_florida_jan_pond_postfront",
  "lmb_florida_mar_lake_prespawn",
  "lmb_texas_feb_reservoir_wind",
  "lmb_georgia_apr_highland_clear",
  "lmb_alabama_may_river_current",
  "lmb_mississippi_jun_backwater_dirty",
  "lmb_newyork_aug_natural_lake_bluebird",
  "lmb_louisiana_sep_shallow_grass",
  "lmb_ozarks_oct_shad_transition",
  "lmb_texas_dec_pond_cold_clear",
] as const;

export const LARGEMOUTH_V3_GOLD_BATCH_1 = LARGEMOUTH_V3_ARCHIVED_SCENARIOS.filter(
  (scenario) => LARGEMOUTH_V3_GOLD_BATCH_1_IDS.includes(
    scenario.id as typeof LARGEMOUTH_V3_GOLD_BATCH_1_IDS[number],
  ),
);

export const LARGEMOUTH_V3_GOLD_BATCH_2_IDS = [
  "lmb_florida_feb_natural_lake_prespawn_stained",
  "lmb_florida_jun_grass_lake_summer",
  "lmb_florida_oct_grass_lake_fall",
  "lmb_texas_apr_reservoir_spawn_transition",
  "lmb_texas_nov_reservoir_latefall",
  "lmb_alabama_mar_river_prespawn",
  "lmb_alabama_sep_river_fall_current",
  "lmb_louisiana_nov_grass_lake_latefall",
  "lmb_california_nov_delta_stained",
  "lmb_ozarks_feb_clear_reservoir_prespawn",
] as const;

export const LARGEMOUTH_V3_GOLD_BATCH_2 = LARGEMOUTH_V3_ARCHIVED_SCENARIOS.filter(
  (scenario) => LARGEMOUTH_V3_GOLD_BATCH_2_IDS.includes(
    scenario.id as typeof LARGEMOUTH_V3_GOLD_BATCH_2_IDS[number],
  ),
);

export const LARGEMOUTH_V3_GOLD_BATCH_3_IDS = [
  "lmb_florida_apr_spawn_lake_clear",
  "lmb_florida_aug_grass_lake_heat_dirty",
  "lmb_texas_jan_reservoir_cold_stained",
  "lmb_texas_jul_reservoir_brush_dirty",
  "lmb_georgia_dec_highland_clear",
  "lmb_louisiana_mar_grass_lake_prespawn_dirty",
  "lmb_ozarks_may_postspawn_clear",
  "lmb_minnesota_sep_weed_lake_stained",
  "lmb_alabama_jul_river_stained",
  "lmb_california_mar_delta_clear",
] as const;

export const LARGEMOUTH_V3_GOLD_BATCH_3 = LARGEMOUTH_V3_ARCHIVED_SCENARIOS.filter(
  (scenario) => LARGEMOUTH_V3_GOLD_BATCH_3_IDS.includes(
    scenario.id as typeof LARGEMOUTH_V3_GOLD_BATCH_3_IDS[number],
  ),
);

export const TROUT_V3_BATCH_TARGETS = {
  core_regions: ["appalachian", "mountain_west", "pacific_northwest", "northeast"],
  target_gold_scenarios: 40,
} as const;

export const TROUT_V3_ARCHIVED_SCENARIOS: ArchivedRecommenderAuditScenario[] = [
  {
    id: "trout_northcarolina_jan_tailwater_clear_winter",
    label: "North Carolina trout, clear tailwater winter control day",
    priority: "core",
    latitude: 35.4306,
    longitude: -83.4477,
    state_code: "NC",
    timezone: "America/New_York",
    local_date: "2025-01-16",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear winter tailwater trout should stay lower-column and subtle with sculpin, bugger, leech, and disciplined jerkbait / hair lanes.",
      primary_lanes: ["sculpin_streamer", "woolly_bugger", "hair_jig"],
      acceptable_secondary_lanes: ["rabbit_strip_leech", "suspending_jerkbait", "conehead_streamer"],
      disallowed_lanes: ["popper_fly", "mouse_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
  {
    id: "trout_pennsylvania_mar_freestone_clear_earlyspring",
    label: "Pennsylvania trout, clear freestone early-spring streamer window",
    priority: "core",
    latitude: 41.7268,
    longitude: -77.4529,
    state_code: "PA",
    timezone: "America/New_York",
    local_date: "2025-03-20",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-spring trout should open minnow, bugger, sculpin, spinner, and suspending-minnow lanes without getting gaudy.",
      primary_lanes: ["slim_minnow_streamer", "woolly_bugger", "inline_spinner"],
      acceptable_secondary_lanes: ["clouser_minnow", "suspending_jerkbait", "muddler_sculpin"],
      disallowed_lanes: ["popper_fly", "frog_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "natural", "dark"],
    },
  },
  {
    id: "trout_colorado_may_western_clear_spring",
    label: "Colorado trout, clear western spring runoff-edge streamer day",
    priority: "core",
    latitude: 38.4783,
    longitude: -107.8762,
    state_code: "CO",
    timezone: "America/Denver",
    local_date: "2025-05-15",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Western spring trout should let streamer and inline-spinner lanes breathe while keeping the read clean and baitfish-forward.",
      primary_lanes: ["slim_minnow_streamer", "sculpin_streamer", "inline_spinner"],
      acceptable_secondary_lanes: ["clouser_minnow", "woolly_bugger", "suspending_jerkbait"],
      disallowed_lanes: ["popper_fly", "mouse_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "trout_washington_jun_clear_pocketwater_summer",
    label: "Washington trout, clear early-summer pocket-water baitfish lane",
    priority: "secondary",
    latitude: 47.4918,
    longitude: -121.7864,
    state_code: "WA",
    timezone: "America/Los_Angeles",
    local_date: "2025-06-18",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-summer trout should allow clean baitfish streamer and spinner lanes, with one tasteful mouse option only if conditions support it.",
      primary_lanes: ["slim_minnow_streamer", "inline_spinner", "clouser_minnow"],
      acceptable_secondary_lanes: ["muddler_sculpin", "mouse_fly", "casting_spoon"],
      disallowed_lanes: ["frog_fly", "popping_topwater", "buzzbait", "prop_bait"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "trout_tennessee_jul_tailwater_clear_heat",
    label: "Tennessee trout, clear warm-tailwater midsummer restraint day",
    priority: "core",
    latitude: 35.4409,
    longitude: -84.6013,
    state_code: "TN",
    timezone: "America/New_York",
    local_date: "2025-07-16",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Warm-tailwater summer trout should tighten back up with lower, subtler streamer lanes instead of overcommitting to fast summer searching.",
      primary_lanes: ["muddler_sculpin", "woolly_bugger", "rabbit_strip_leech"],
      acceptable_secondary_lanes: ["sculpin_streamer", "hair_jig", "slim_minnow_streamer"],
      disallowed_lanes: ["popper_fly", "mouse_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
  {
    id: "trout_northcarolina_aug_tailwater_stained_flowbump",
    label: "North Carolina trout, stained late-summer tailwater flow-bump day",
    priority: "core",
    latitude: 35.4306,
    longitude: -83.4477,
    state_code: "NC",
    timezone: "America/New_York",
    local_date: "2025-08-14",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "A stained late-summer tailwater bump should still stay trout-clean, but visible bugger, sculpin, and minnow lanes should rise naturally.",
      primary_lanes: ["woolly_bugger", "sculpin_streamer", "slim_minnow_streamer"],
      acceptable_secondary_lanes: ["rabbit_strip_leech", "clouser_minnow", "inline_spinner"],
      disallowed_lanes: ["frog_fly", "popping_topwater", "buzzbait", "prop_bait"],
      expected_color_lanes: ["dark", "natural", "bright"],
    },
  },
  {
    id: "trout_montana_sep_clear_fall_baitfish",
    label: "Montana trout, clear early-fall baitfish streamer push",
    priority: "core",
    latitude: 45.6621,
    longitude: -111.0891,
    state_code: "MT",
    timezone: "America/Denver",
    local_date: "2025-09-17",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear fall trout should strongly reward baitfish streamer and minnow lanes, with one mouse option allowed but not mandatory.",
      primary_lanes: ["game_changer", "slim_minnow_streamer", "articulated_baitfish_streamer"],
      acceptable_secondary_lanes: ["zonker_streamer", "mouse_fly", "suspending_jerkbait"],
      disallowed_lanes: ["frog_fly", "popping_topwater", "buzzbait", "prop_bait"],
      expected_color_lanes: ["natural", "natural", "dark"],
    },
  },
  {
    id: "trout_california_oct_clear_fall_streamer",
    label: "Northern California trout, clear fall streamer tightening day",
    priority: "secondary",
    latitude: 41.7922,
    longitude: -122.6217,
    state_code: "CA",
    timezone: "America/Los_Angeles",
    local_date: "2025-10-15",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Fall western trout should center on minnow and articulated streamer lanes, with jerkbait and spinner support where the water allows it.",
      primary_lanes: ["slim_minnow_streamer", "articulated_baitfish_streamer", "sculpin_streamer"],
      acceptable_secondary_lanes: ["suspending_jerkbait", "inline_spinner", "zonker_streamer"],
      disallowed_lanes: ["frog_fly", "popping_topwater", "walking_topwater"],
      expected_color_lanes: ["natural", "natural", "dark"],
    },
  },
  {
    id: "trout_pennsylvania_nov_stained_highwater_fall",
    label: "Pennsylvania trout, stained late-fall high-water control day",
    priority: "core",
    latitude: 41.7268,
    longitude: -77.4529,
    state_code: "PA",
    timezone: "America/New_York",
    local_date: "2025-11-12",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "Late-fall stained trout water should stay disciplined but visible, leaning minnow, bugger, and spinner lanes rather than random surface changeups.",
      primary_lanes: ["articulated_baitfish_streamer", "woolly_bugger", "inline_spinner"],
      acceptable_secondary_lanes: ["slim_minnow_streamer", "zonker_streamer", "casting_spoon"],
      disallowed_lanes: ["popper_fly", "mouse_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "dark", "bright"],
    },
  },
  {
    id: "trout_colorado_dec_clear_winter_classic",
    label: "Colorado trout, clear early-winter classic streamer control day",
    priority: "secondary",
    latitude: 38.4783,
    longitude: -107.8762,
    state_code: "CO",
    timezone: "America/Denver",
    local_date: "2025-12-10",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-winter western trout should live in sculpin, bugger, leech, and restrained jerkbait lanes with no warm-season noise.",
      primary_lanes: ["sculpin_streamer", "woolly_bugger", "rabbit_strip_leech"],
      acceptable_secondary_lanes: ["conehead_streamer", "suspending_jerkbait", "hair_jig"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
];

export const TROUT_V3_GOLD_BATCH_1_IDS = [
  "trout_northcarolina_jan_tailwater_clear_winter",
  "trout_pennsylvania_mar_freestone_clear_earlyspring",
  "trout_colorado_may_western_clear_spring",
  "trout_washington_jun_clear_pocketwater_summer",
  "trout_tennessee_jul_tailwater_clear_heat",
  "trout_northcarolina_aug_tailwater_stained_flowbump",
  "trout_montana_sep_clear_fall_baitfish",
  "trout_california_oct_clear_fall_streamer",
  "trout_pennsylvania_nov_stained_highwater_fall",
  "trout_colorado_dec_clear_winter_classic",
] as const;

export const TROUT_V3_GOLD_BATCH_1 = TROUT_V3_ARCHIVED_SCENARIOS.filter(
  (scenario) => TROUT_V3_GOLD_BATCH_1_IDS.includes(
    scenario.id as typeof TROUT_V3_GOLD_BATCH_1_IDS[number],
  ),
);

export const TROUT_V3_ARCHIVED_SCENARIOS_BATCH_2: ArchivedRecommenderAuditScenario[] = [
  {
    id: "trout_california_feb_clear_winter_minnow",
    label: "Northern California trout, clear late-winter minnow and sculpin control",
    priority: "core",
    latitude: 41.7922,
    longitude: -122.6217,
    state_code: "CA",
    timezone: "America/Los_Angeles",
    local_date: "2025-02-19",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Late-winter western trout should stay controlled with sculpin, bugger, and restrained minnow lanes rather than broad warmwater movement.",
      primary_lanes: ["sculpin_streamer", "woolly_bugger", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["rabbit_strip_leech", "slim_minnow_streamer", "hair_jig"],
      disallowed_lanes: ["popper_fly", "mouse_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
  {
    id: "trout_tennessee_apr_tailwater_stained_generation",
    label: "Tennessee trout, stained spring generation pulse",
    priority: "core",
    latitude: 35.4409,
    longitude: -84.6013,
    state_code: "TN",
    timezone: "America/New_York",
    local_date: "2025-04-16",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "A stained spring tailwater pulse should open visible streamer and spinner lanes, but still stay trout-clean and current-aware.",
      primary_lanes: ["clouser_minnow", "slim_minnow_streamer", "inline_spinner"],
      acceptable_secondary_lanes: ["woolly_bugger", "suspending_jerkbait", "muddler_sculpin"],
      disallowed_lanes: ["frog_fly", "buzzbait", "prop_bait", "popping_topwater"],
      expected_color_lanes: ["natural", "bright", "dark"],
    },
  },
  {
    id: "trout_westvirginia_may_appalachian_clear_spring",
    label: "West Virginia trout, clear Appalachian spring freestone push",
    priority: "secondary",
    latitude: 38.9215,
    longitude: -79.8464,
    state_code: "WV",
    timezone: "America/New_York",
    local_date: "2025-05-15",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Clear Appalachian spring trout should favor bugger, sculpin, slim-minnow, and spinner lanes that still feel trout-disciplined.",
      primary_lanes: ["woolly_bugger", "slim_minnow_streamer", "inline_spinner"],
      acceptable_secondary_lanes: ["sculpin_streamer", "clouser_minnow", "suspending_jerkbait"],
      disallowed_lanes: ["popper_fly", "mouse_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "natural", "dark"],
    },
  },
  {
    id: "trout_idaho_jun_runoff_edge_stained",
    label: "Idaho trout, stained runoff-edge western river day",
    priority: "core",
    latitude: 44.0772,
    longitude: -114.742,
    state_code: "ID",
    timezone: "America/Boise",
    local_date: "2025-06-18",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "A runoff-edge western trout day should promote visible minnow, bugger, and spinner lanes without turning into bass power fishing.",
      primary_lanes: ["clouser_minnow", "woolly_bugger", "inline_spinner"],
      acceptable_secondary_lanes: ["slim_minnow_streamer", "muddler_sculpin", "casting_spoon"],
      disallowed_lanes: ["frog_fly", "buzzbait", "prop_bait", "hollow_body_frog"],
      expected_color_lanes: ["natural", "bright", "dark"],
    },
  },
  {
    id: "trout_northcarolina_jul_tailwater_clear_bluebird",
    label: "North Carolina trout, clear bluebird tailwater midsummer restraint",
    priority: "core",
    latitude: 35.4306,
    longitude: -83.4477,
    state_code: "NC",
    timezone: "America/New_York",
    local_date: "2025-07-16",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Bluebird midsummer tailwater trout should tighten into subtle lower and mid-column streamers, not race into fast aggressive search lanes.",
      primary_lanes: ["muddler_sculpin", "woolly_bugger", "rabbit_strip_leech"],
      acceptable_secondary_lanes: ["sculpin_streamer", "hair_jig", "slim_minnow_streamer"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
  {
    id: "trout_washington_aug_clear_lowwater_summer",
    label: "Washington trout, clear low-water late-summer pocket-water day",
    priority: "secondary",
    latitude: 47.4918,
    longitude: -121.7864,
    state_code: "WA",
    timezone: "America/Los_Angeles",
    local_date: "2025-08-14",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Low-water late-summer trout should stay clean and controlled with slim minnow, muddler, and understated bugger lanes.",
      primary_lanes: ["clouser_minnow", "slim_minnow_streamer", "muddler_sculpin"],
      acceptable_secondary_lanes: ["woolly_bugger", "inline_spinner", "mouse_fly"],
      disallowed_lanes: ["frog_fly", "buzzbait", "prop_bait", "popping_topwater"],
      expected_color_lanes: ["natural", "natural", "dark"],
    },
  },
  {
    id: "trout_alaska_sep_clear_fall_baitfish",
    label: "Alaska trout, clear early-fall baitfish and leech streamer window",
    priority: "core",
    latitude: 61.5799,
    longitude: -149.4411,
    state_code: "AK",
    timezone: "America/Anchorage",
    local_date: "2025-09-17",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-fall Alaska trout should reward articulated baitfish, slim-minnow, and leech-style streamers without surface nonsense.",
      primary_lanes: ["articulated_baitfish_streamer", "sculpin_streamer", "rabbit_strip_leech"],
      acceptable_secondary_lanes: ["slim_minnow_streamer", "game_changer", "zonker_streamer"],
      disallowed_lanes: ["popper_fly", "frog_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "dark", "natural"],
    },
  },
  {
    id: "trout_pennsylvania_oct_stained_flow_bump",
    label: "Pennsylvania trout, stained fall flow-bump visibility day",
    priority: "core",
    latitude: 41.7268,
    longitude: -77.4529,
    state_code: "PA",
    timezone: "America/New_York",
    local_date: "2025-10-15",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "A stained fall flow bump should elevate visible baitfish, bugger, and spinner lanes while keeping the trout read disciplined.",
      primary_lanes: ["articulated_baitfish_streamer", "woolly_bugger", "inline_spinner"],
      acceptable_secondary_lanes: ["slim_minnow_streamer", "game_changer", "suspending_jerkbait"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "bright", "dark"],
    },
  },
  {
    id: "trout_oregon_nov_clear_latefall_minnow",
    label: "Oregon trout, clear late-fall minnow and zonker tightening",
    priority: "secondary",
    latitude: 44.3539,
    longitude: -121.5498,
    state_code: "OR",
    timezone: "America/Los_Angeles",
    local_date: "2025-11-12",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Late-fall western trout should center on slim-minnow, zonker, and articulated baitfish lanes with controlled jerkbait support.",
      primary_lanes: ["slim_minnow_streamer", "zonker_streamer", "articulated_baitfish_streamer"],
      acceptable_secondary_lanes: ["suspending_jerkbait", "game_changer", "inline_spinner"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "natural", "dark"],
    },
  },
  {
    id: "trout_colorado_mar_clear_shoulder_coldfront",
    label: "Colorado trout, clear shoulder-season cold-front reset",
    priority: "core",
    latitude: 38.4783,
    longitude: -107.8762,
    state_code: "CO",
    timezone: "America/Denver",
    local_date: "2025-03-20",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "A cold-front western shoulder-season trout day should stay in sculpin, bugger, and restrained minnow lanes with little aggression inflation.",
      primary_lanes: ["sculpin_streamer", "woolly_bugger", "suspending_jerkbait"],
      acceptable_secondary_lanes: ["slim_minnow_streamer", "hair_jig", "conehead_streamer"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
];

export const TROUT_V3_GOLD_BATCH_2_IDS = [
  "trout_california_feb_clear_winter_minnow",
  "trout_tennessee_apr_tailwater_stained_generation",
  "trout_westvirginia_may_appalachian_clear_spring",
  "trout_idaho_jun_runoff_edge_stained",
  "trout_northcarolina_jul_tailwater_clear_bluebird",
  "trout_washington_aug_clear_lowwater_summer",
  "trout_alaska_sep_clear_fall_baitfish",
  "trout_pennsylvania_oct_stained_flow_bump",
  "trout_oregon_nov_clear_latefall_minnow",
  "trout_colorado_mar_clear_shoulder_coldfront",
] as const;

export const TROUT_V3_GOLD_BATCH_2 = TROUT_V3_ARCHIVED_SCENARIOS_BATCH_2.filter(
  (scenario) => TROUT_V3_GOLD_BATCH_2_IDS.includes(
    scenario.id as typeof TROUT_V3_GOLD_BATCH_2_IDS[number],
  ),
);

export const TROUT_V3_ARCHIVED_SCENARIOS_BATCH_3: ArchivedRecommenderAuditScenario[] = [
  {
    id: "trout_montana_apr_stained_runoffedge_sculpin",
    label: "Montana trout, stained spring runoff-edge sculpin and bugger day",
    priority: "core",
    latitude: 45.6621,
    longitude: -111.0891,
    state_code: "MT",
    timezone: "America/Denver",
    local_date: "2025-04-16",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "A stained spring runoff edge should make trout more visible and streamer-friendly, but still disciplined around sculpin, bugger, and minnow lanes.",
      primary_lanes: ["sculpin_streamer", "woolly_bugger", "clouser_minnow"],
      acceptable_secondary_lanes: ["slim_minnow_streamer", "inline_spinner", "muddler_sculpin"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "bright"],
    },
  },
  {
    id: "trout_utah_may_clear_postfront_control",
    label: "Utah trout, clear post-front spring control day",
    priority: "secondary",
    latitude: 40.6736,
    longitude: -111.7998,
    state_code: "UT",
    timezone: "America/Denver",
    local_date: "2025-05-15",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "A clear post-front western trout day should stay restrained with sculpin, bugger, and slim-minnow control instead of over-accelerating.",
      primary_lanes: ["sculpin_streamer", "clouser_minnow", "woolly_bugger"],
      acceptable_secondary_lanes: ["slim_minnow_streamer", "suspending_jerkbait", "hair_jig"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
  {
    id: "trout_virginia_jun_tailwater_clear_baitfish",
    label: "Virginia trout, clear early-summer tailwater baitfish opening",
    priority: "core",
    latitude: 37.2721,
    longitude: -80.0984,
    state_code: "VA",
    timezone: "America/New_York",
    local_date: "2025-06-18",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-summer tailwater trout can open slim-minnow, clouser, and inline-spinner lanes, but should still feel measured and current-aware.",
      primary_lanes: ["slim_minnow_streamer", "clouser_minnow", "inline_spinner"],
      acceptable_secondary_lanes: ["muddler_sculpin", "woolly_bugger", "suspending_jerkbait"],
      disallowed_lanes: ["frog_fly", "buzzbait", "prop_bait", "hollow_body_frog"],
      expected_color_lanes: ["natural", "natural", "bright"],
    },
  },
  {
    id: "trout_idaho_jul_clear_hopperbank_streamer",
    label: "Idaho trout, clear midsummer bank and streamer crossover",
    priority: "secondary",
    latitude: 44.0772,
    longitude: -114.742,
    state_code: "ID",
    timezone: "America/Boise",
    local_date: "2025-07-16",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Even with summertime bank activity, trout V3 should stay streamer-minded here and not drift into noisy surface recommendations by default.",
      primary_lanes: ["muddler_sculpin", "slim_minnow_streamer", "woolly_bugger"],
      acceptable_secondary_lanes: ["clouser_minnow", "mouse_fly", "inline_spinner"],
      disallowed_lanes: ["frog_fly", "buzzbait", "prop_bait", "popping_topwater"],
      expected_color_lanes: ["natural", "dark", "natural"],
    },
  },
  {
    id: "trout_newhampshire_aug_clear_lowlight_minnow",
    label: "New Hampshire trout, clear low-light late-summer minnow push",
    priority: "core",
    latitude: 44.1662,
    longitude: -71.6421,
    state_code: "NH",
    timezone: "America/New_York",
    local_date: "2025-08-14",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Low-light late-summer trout should let slim-minnow, clouser, and bugger lanes breathe without turning into aggressive warmwater chaos.",
      primary_lanes: ["slim_minnow_streamer", "clouser_minnow", "woolly_bugger"],
      acceptable_secondary_lanes: ["muddler_sculpin", "inline_spinner", "mouse_fly"],
      disallowed_lanes: ["frog_fly", "buzzbait", "prop_bait", "hollow_body_frog"],
      expected_color_lanes: ["natural", "natural", "dark"],
    },
  },
  {
    id: "trout_california_sep_clear_brownwindow",
    label: "Northern California trout, clear early-fall brown-window streamer day",
    priority: "secondary",
    latitude: 41.7922,
    longitude: -122.6217,
    state_code: "CA",
    timezone: "America/Los_Angeles",
    local_date: "2025-09-17",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-fall western trout should reward articulated baitfish, game-changer, and slim-minnow lanes with strong baitfish posture and no surface clutter.",
      primary_lanes: ["articulated_baitfish_streamer", "game_changer", "slim_minnow_streamer"],
      acceptable_secondary_lanes: ["zonker_streamer", "suspending_jerkbait", "sculpin_streamer"],
      disallowed_lanes: ["popper_fly", "frog_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "natural", "dark"],
    },
  },
  {
    id: "trout_maine_oct_stained_fallpulse",
    label: "Maine trout, stained fall pulse visibility day",
    priority: "core",
    latitude: 45.1582,
    longitude: -67.4097,
    state_code: "ME",
    timezone: "America/New_York",
    local_date: "2025-10-15",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "stained",
    expectation: {
      seasonal_story: "A stained fall pulse should still keep trout in visible baitfish, bugger, and zonker lanes rather than broad warmwater search behavior.",
      primary_lanes: ["articulated_baitfish_streamer", "woolly_bugger", "zonker_streamer"],
      acceptable_secondary_lanes: ["slim_minnow_streamer", "inline_spinner", "game_changer"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "dark", "bright"],
    },
  },
  {
    id: "trout_oregon_nov_clear_postfront_tight",
    label: "Oregon trout, clear late-fall post-front tightening",
    priority: "core",
    latitude: 44.3539,
    longitude: -121.5498,
    state_code: "OR",
    timezone: "America/Los_Angeles",
    local_date: "2025-11-12",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "A clear late-fall post-front trout day should tighten into slim-minnow, zonker, and sculpin control with little appetite for flashy extras.",
      primary_lanes: ["articulated_baitfish_streamer", "slim_minnow_streamer", "zonker_streamer"],
      acceptable_secondary_lanes: ["sculpin_streamer", "woolly_bugger", "suspending_jerkbait"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["natural", "dark", "natural"],
    },
  },
  {
    id: "trout_alaska_dec_clear_winter_heavy",
    label: "Alaska trout, clear early-winter heavy-streamer control",
    priority: "secondary",
    latitude: 61.5799,
    longitude: -149.4411,
    state_code: "AK",
    timezone: "America/Anchorage",
    local_date: "2025-12-10",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Early-winter Alaska trout should stay in sculpin, leech, and heavy bugger lanes with almost no tolerance for surface or warm-season noise.",
      primary_lanes: ["sculpin_streamer", "rabbit_strip_leech", "conehead_streamer"],
      acceptable_secondary_lanes: ["woolly_bugger", "hair_jig", "suspending_jerkbait"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
  {
    id: "trout_pennsylvania_feb_clear_deepwinter",
    label: "Pennsylvania trout, clear deep-winter low-energy control",
    priority: "core",
    latitude: 41.7268,
    longitude: -77.4529,
    state_code: "PA",
    timezone: "America/New_York",
    local_date: "2025-02-19",
    species: "river_trout",
    context: "freshwater_river",
    water_clarity: "clear",
    expectation: {
      seasonal_story: "Deep-winter trout should remain subtle and lower-column with sculpin, bugger, leech, and restrained jerkbait control.",
      primary_lanes: ["sculpin_streamer", "woolly_bugger", "rabbit_strip_leech"],
      acceptable_secondary_lanes: ["conehead_streamer", "suspending_jerkbait", "hair_jig"],
      disallowed_lanes: ["mouse_fly", "popper_fly", "walking_topwater"],
      expected_color_lanes: ["dark", "natural", "natural"],
    },
  },
];

export const TROUT_V3_GOLD_BATCH_3_IDS = [
  "trout_montana_apr_stained_runoffedge_sculpin",
  "trout_utah_may_clear_postfront_control",
  "trout_virginia_jun_tailwater_clear_baitfish",
  "trout_idaho_jul_clear_hopperbank_streamer",
  "trout_newhampshire_aug_clear_lowlight_minnow",
  "trout_california_sep_clear_brownwindow",
  "trout_maine_oct_stained_fallpulse",
  "trout_oregon_nov_clear_postfront_tight",
  "trout_alaska_dec_clear_winter_heavy",
  "trout_pennsylvania_feb_clear_deepwinter",
] as const;

export const TROUT_V3_GOLD_BATCH_3 = TROUT_V3_ARCHIVED_SCENARIOS_BATCH_3.filter(
  (scenario) => TROUT_V3_GOLD_BATCH_3_IDS.includes(
    scenario.id as typeof TROUT_V3_GOLD_BATCH_3_IDS[number],
  ),
);

export const PIKE_V3_BATCH_TARGETS = {
  core_regions: ["great_lakes_upper_midwest", "midwest_interior", "mountain_west"],
  target_gold_scenarios: 35,
} as const;
