"""Read-only pixel analysis for illustrated artwork layout; never edits PNGs.

Run after adding artwork. Dark ink/material pixels establish the specimen bounds;
2% canvas padding protects pale fibers, antialiasing, and hook tips. Review the
result at card size before accepting generated assets.
"""
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
manifest = json.loads((ROOT / 'docs/recommender-artwork/generation_manifest.json').read_text())
paths = sorted(set(
    ['assets/images/color-picker/illustrated/' + name + '.png'
     for name in manifest['reusedColorMatch'].values()]
    + ['assets/images/color-picker/illustrated/' + name + '.png'
       for name in ['clear', 'stained', 'dirty']]
    + [job['path'] for job in manifest['jobs']]
))
records = []
missing = []
for path in paths:
    full = ROOT / path
    if not full.exists():
        missing.append(path)
        continue
    with Image.open(full) as image:
        width, height = image.size
        assert width == height, f'Expected square source: {path}'
        # Only analyze: mask is not exported or used as replacement artwork.
        rgb = image.convert('RGB')
        mask = rgb.convert('L').point(lambda value: 255 if value < 220 else 0)
        box = mask.getbbox()
        assert box, f'Empty artwork: {path}'
        left, top, right, bottom = box
        bounds = [max(0, left / width - .02), max(0, top / height - .02),
                  min(1, right / width + .02), min(1, bottom / height + .02)]
        records.append(dict(path=path, pixels=[width, height], bounds=[round(x, 6) for x in bounds],
                            sha256=hashlib.sha256(full.read_bytes()).hexdigest()))
lines = ["// Generated by scripts/recommender-artwork-bounds.py. Source pixels are unchanged.",
         "import type { ArtworkBounds } from './fitArtwork';",
         'const BOUNDS = new Map<unknown, ArtworkBounds>([']
for record in records:
    lines.append("  [require('../" + record['path'] + "'), " + json.dumps(record['bounds']) + '],')
lines += [']);', '', 'export function getRecommenderArtworkBounds(source: unknown) {',
          '  return BOUNDS.get(source);', '}', '']
(ROOT / 'lib/recommenderArtworkBounds.ts').write_text('\n'.join(lines))
(ROOT / 'docs/recommender-artwork/asset_audit.json').write_text(json.dumps(dict(assets=records, missing=missing), indent=2) + '\n')
print(f'Analyzed {len(records)} assets; {len(missing)} not generated yet.')
