const MIN_YEARS_PER_DATE = 2;
const WINDOW_RADIUS_DAYS = 3;
const DAY_MS = 86_400_000;

const SITES = [
  {
    siteId: "04085427",
    slug: "manitowoc",
    constant: "MANITOWOC_HISTORICAL_WATER_TEMPERATURE_NORMALS",
    name: "Manitowoc River at Michigan Avenue, WI",
    startYear: 2011,
    endYear: 2022,
  },
  {
    siteId: "04249000",
    slug: "oswego",
    constant: "OSWEGO_HISTORICAL_WATER_TEMPERATURE_NORMALS",
    name: "Oswego River at Lock 7, Oswego, NY",
    startYear: 2010,
    endYear: 2024,
  },
] as const;

type DailyMean = {
  localDate: string;
  monthDay: string;
  year: number;
  meanC: number;
};

for (const site of SITES) {
  const sourceUrl =
    `https://waterservices.usgs.gov/nwis/dv/?format=json&sites=${site.siteId}&startDT=${site.startYear}-01-01&endDT=${site.endYear}-12-31&parameterCd=00010&siteStatus=all`;
  const response = await fetch(sourceUrl);
  if (!response.ok) {
    throw new Error(`${site.siteId} USGS daily values failed: ${response.status}`);
  }
  const payload = await response.json() as {
    value?: { timeSeries?: Array<{
      variable?: { options?: { option?: Array<{ optionCode?: string }> } };
      values?: Array<{ value?: Array<{
        value?: string;
        qualifiers?: string[];
        dateTime?: string;
      }> }>;
    }> };
  };
  const meanSeries = payload.value?.timeSeries?.find((series) =>
    series.variable?.options?.option?.some((option) =>
      option.optionCode === "00003"
    )
  );
  if (!meanSeries) throw new Error(`${site.siteId} has no daily-mean series.`);
  const dailyMeans: DailyMean[] = (meanSeries.values?.[0]?.value ?? [])
    .flatMap((observation) => {
      const localDate = observation.dateTime?.slice(0, 10) ?? "";
      const meanC = Number(observation.value);
      if (
        !/^\d{4}-\d{2}-\d{2}$/.test(localDate) ||
        !Number.isFinite(meanC) ||
        meanC < -2 ||
        meanC > 35 ||
        !observation.qualifiers?.includes("A")
      ) return [];
      return [{
        localDate,
        monthDay: localDate.slice(5),
        year: Number(localDate.slice(0, 4)),
        meanC,
      }];
    });

  const normals = Object.fromEntries(calendarMonthDays().flatMap((monthDay) => {
    const target = monthDayIndex(monthDay);
    const observations = dailyMeans.filter((day) =>
      circularDistance(monthDayIndex(day.monthDay), target) <=
        WINDOW_RADIUS_DAYS * DAY_MS
    );
    const years = [...new Set(observations.map((day) => day.year))].toSorted();
    if (years.length < MIN_YEARS_PER_DATE) return [];
    const valuesF = observations.map((day) => day.meanC * 9 / 5 + 32);
    return [[monthDay, {
      averageF: round(mean(valuesF), 1),
      p10F: round(percentile(valuesF, .1), 1),
      p25F: round(percentile(valuesF, .25), 1),
      medianF: round(percentile(valuesF, .5), 1),
      p75F: round(percentile(valuesF, .75), 1),
      p90F: round(percentile(valuesF, .9), 1),
      historicalYears: years.length,
      sampleCount: observations.length,
      years,
    }]];
  }));

  const report = {
    siteId: site.siteId,
    sourceName: site.name,
    sourceUrl,
    recordYearsUsed: `${site.startYear}-${site.endYear}`,
    method:
      `USGS approved daily-mean water temperature (parameter 00010, statistic 00003), pooled by calendar date ±${WINDOW_RADIUS_DAYS} days. Invalid sentinels, provisional values, and implausible temperatures are excluded. Each displayed normal requires at least ${MIN_YEARS_PER_DATE} qualifying years. Historical context only; never a current reading or Activity input.`,
    approvedDailyMeans: dailyMeans.length,
    firstApprovedDate: dailyMeans.at(0)?.localDate,
    lastApprovedDate: dailyMeans.at(-1)?.localDate,
    calendarWindowNormals: Object.keys(normals).length,
    normals,
  };

  if (Deno.args.includes("--write")) {
    await Deno.mkdir("docs/audits", { recursive: true });
    await Deno.writeTextFile(
      `docs/audits/river-run-${site.slug}-historical-water-temperature.json`,
      JSON.stringify(report, null, 2) + "\n",
    );
    await Deno.writeTextFile(
      `supabase/functions/_shared/riverRunEngine/config/onboarding/${site.slug}HistoricalTemperature.generated.ts`,
      `// Generated by scripts/river-run-fall-2026-temperature-baseline.ts.\n` +
        `// Calendar-date ±${WINDOW_RADIUS_DAYS}-day archival context only; never a current measured reading.\n` +
        `export const ${site.constant} = ${JSON.stringify(normals, null, 2)} as const;\n`,
    );
  }

  console.log(JSON.stringify({ ...report, normals: undefined }, null, 2));
}

function calendarMonthDays(): string[] {
  const values: string[] = [];
  for (
    let time = Date.parse("2000-01-01T00:00:00Z");
    time <= Date.parse("2000-12-31T00:00:00Z");
    time += DAY_MS
  ) {
    const monthDay = new Date(time).toISOString().slice(5, 10);
    if (monthDay !== "02-29") values.push(monthDay);
  }
  return values;
}

function monthDayIndex(monthDay: string): number {
  const normalized = monthDay === "02-29" ? "02-28" : monthDay;
  return Date.parse(`2001-${normalized}T00:00:00Z`);
}

function circularDistance(left: number, right: number): number {
  const yearMs = 365 * DAY_MS;
  const distance = Math.abs(left - right);
  return Math.min(distance, yearMs - distance);
}

function mean(values: number[]) {
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function percentile(values: number[], p: number) {
  const sorted = values.toSorted((left, right) => left - right);
  const index = (sorted.length - 1) * p;
  const lower = Math.floor(index);
  const upper = Math.ceil(index);
  return lower === upper
    ? sorted[lower]
    : sorted[lower] + (sorted[upper] - sorted[lower]) * (index - lower);
}

function round(value: number, digits: number) {
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}
