const STATION_ID = "10A040";
const WATER_YEARS = [2024, 2025] as const;
const MIN_YEARS_PER_DATE = 2;
const WINDOW_RADIUS_DAYS = 3;
const INPUT_DIRECTORY = Deno.args.find((argument) =>
  argument.startsWith("--input-dir=")
)?.slice("--input-dir=".length);
const SOURCE_ROOT =
  `https://apps.ecology.wa.gov/continuousflowandwq/StationData/Prod/${STATION_ID}`;

type DailyMean = {
  localDate: string;
  year: number;
  monthDay: string;
  meanC: number;
  qualityCode: 2 | 3;
};

const dailyMeans: DailyMean[] = [];
const sourceFiles: Array<{
  waterYear: number;
  sourceUrl: string;
  acceptedDailyMeans: number;
}> = [];

for (const waterYear of WATER_YEARS) {
  const filename = `${STATION_ID}_${waterYear}_WTM_DV.TXT`;
  const sourceUrl = `${SOURCE_ROOT}/${filename}`;
  const text = INPUT_DIRECTORY
    ? await Deno.readTextFile(`${INPUT_DIRECTORY}/${filename}`)
    : await fetchText(sourceUrl);
  const parsed = parseDailyMeans(text);
  dailyMeans.push(...parsed);
  sourceFiles.push({
    waterYear,
    sourceUrl,
    acceptedDailyMeans: parsed.length,
  });
}

const uniqueDailyMeans = [...new Map(
  dailyMeans.map((day) => [day.localDate, day]),
).values()].toSorted((left, right) =>
  left.localDate.localeCompare(right.localDate)
);
const normals = Object.fromEntries(
  calendarMonthDays("07-01", "12-31").flatMap((monthDay) => {
    const target = monthDayIndex(monthDay);
    const days = uniqueDailyMeans.filter((day) =>
      Math.abs(monthDayIndex(day.monthDay) - target) <=
        WINDOW_RADIUS_DAYS * 86_400_000
    );
    const years = [...new Set(days.map((day) => day.year))].toSorted();
    if (years.length < MIN_YEARS_PER_DATE) return [];
    const valuesF = days.map((day) => celsiusToFahrenheit(day.meanC));
    return [[monthDay, {
      averageF: round(mean(valuesF), 1),
      p10F: round(percentile(valuesF, .1), 1),
      p25F: round(percentile(valuesF, .25), 1),
      medianF: round(percentile(valuesF, .5), 1),
      p75F: round(percentile(valuesF, .75), 1),
      p90F: round(percentile(valuesF, .9), 1),
      historicalYears: years.length,
      sampleCount: days.length,
      years,
    }]];
  }),
);

const report = {
  stationId: STATION_ID,
  sourceName: "Puyallup R @ USGS Puyallup",
  recordYearsUsed: "2023-2025 (Ecology water-year 2024 and 2025 tables)",
  method:
    `Washington Department of Ecology published mean-daily water-temperature tables. Only numeric daily means with quality code 2 (good provisional) or 3 (good provisional, edited) are retained, then pooled inside the same calendar date ±${WINDOW_RADIUS_DAYS} days. Missing and incomplete days are never imputed, and every displayed average requires observations from at least ${MIN_YEARS_PER_DATE} calendar years. This is limited archival context from a currently inactive station, never a current reading.`,
  sourceFiles,
  acceptedUniqueDailyMeans: uniqueDailyMeans.length,
  calendarWindowNormals: Object.keys(normals).length,
  expectedCalendarDates: 184,
  calendarDateCoveragePercent: round(
    Object.keys(normals).length / 184 * 100,
    2,
  ),
  normals,
};

if (Deno.args.includes("--write")) {
  await Deno.mkdir("docs/audits", { recursive: true });
  await Deno.writeTextFile(
    "docs/audits/river-run-puyallup-historical-water-temperature.json",
    JSON.stringify(report, null, 2) + "\n",
  );
  await Deno.writeTextFile(
    "supabase/functions/_shared/riverRunEngine/config/onboarding/puyallupHistoricalTemperature.generated.ts",
    `// Generated by scripts/river-run-puyallup-temperature-baseline.ts.\n` +
      `// Calendar-date ±${WINDOW_RADIUS_DAYS}-day historical context only; never a current measured reading.\n` +
      `export const PUYALLUP_HISTORICAL_WATER_TEMPERATURE_NORMALS = ${
        JSON.stringify(normals, null, 2)
      } as const;\n`,
  );
}

console.log(JSON.stringify(
  {
    ...report,
    normals: undefined,
    examples: Object.fromEntries(
      ["07-15", "08-01", "08-31", "09-15", "10-01", "10-15", "11-15", "12-01"]
        .flatMap((monthDay) =>
          normals[monthDay] ? [[monthDay, normals[monthDay]]] : []
        ),
    ),
  },
  null,
  2,
));

async function fetchText(sourceUrl: string) {
  const response = await fetch(sourceUrl, {
    headers: { "user-agent": "Mozilla/5.0" },
  });
  if (!response.ok) throw new Error(`${sourceUrl} failed: ${response.status}`);
  return await response.text();
}

function parseDailyMeans(text: string): DailyMean[] {
  const rows: DailyMean[] = [];
  const pattern = /^(\d{2})\/(\d{2})\/(\d{4})\s+(-?\d+(?:\.\d+)?)\s+(\d+)$/gm;
  for (const match of text.matchAll(pattern)) {
    const qualityCode = Number(match[5]);
    const meanC = Number(match[4]);
    if ((qualityCode !== 2 && qualityCode !== 3) || meanC < -2 || meanC > 30) {
      continue;
    }
    const localDate = `${match[3]}-${match[1]}-${match[2]}`;
    rows.push({
      localDate,
      year: Number(match[3]),
      monthDay: `${match[1]}-${match[2]}`,
      meanC,
      qualityCode,
    });
  }
  return rows;
}

function calendarMonthDays(start: string, end: string): string[] {
  const values: string[] = [];
  for (
    let time = monthDayIndex(start);
    time <= monthDayIndex(end);
    time += 86_400_000
  ) {
    values.push(new Date(time).toISOString().slice(5, 10));
  }
  return values;
}

function monthDayIndex(monthDay: string): number {
  return Date.parse(`2000-${monthDay}T00:00:00Z`);
}

function celsiusToFahrenheit(value: number) {
  return value * 9 / 5 + 32;
}

function mean(values: number[]) {
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function percentile(values: number[], p: number) {
  const sorted = values.toSorted((left, right) => left - right);
  if (sorted.length === 1) return sorted[0];
  const index = (sorted.length - 1) * p;
  const lower = Math.floor(index);
  const upper = Math.ceil(index);
  if (lower === upper) return sorted[lower];
  return sorted[lower] + (sorted[upper] - sorted[lower]) * (index - lower);
}

function round(value: number, digits: number) {
  const scale = 10 ** digits;
  return Math.round(value * scale) / scale;
}
