const SITE_ID = "04026005";
const START_YEAR = 2021;
const END_YEAR = 2023;
const START_MONTH = 7;
const END_MONTH = 11;
const MIN_SAMPLES_PER_DAY = 72;
const MIN_YEARS_PER_DATE = 2;

type Observation = {
  localDate: string;
  waterTempF: number;
};

type DailyMean = {
  localDate: string;
  year: number;
  monthDay: string;
  sampleCount: number;
  meanF: number;
};

const observations: Observation[] = [];
for (let year = START_YEAR; year <= END_YEAR; year++) {
  for (let month = START_MONTH; month <= END_MONTH; month++) {
    const start = `${year}-${String(month).padStart(2, "0")}-01`;
    const endDate = new Date(Date.UTC(year, month, 0));
    const end = endDate.toISOString().slice(0, 10);
    observations.push(...await fetchMonth(start, end));
  }
}

const byDate = new Map<string, number[]>();
for (const observation of observations) {
  byDate.set(observation.localDate, [
    ...(byDate.get(observation.localDate) ?? []),
    observation.waterTempF,
  ]);
}
const dailyMeans: DailyMean[] = [...byDate.entries()].flatMap(
  ([localDate, values]) =>
    values.length >= MIN_SAMPLES_PER_DAY
      ? [{
        localDate,
        year: Number(localDate.slice(0, 4)),
        monthDay: localDate.slice(5),
        sampleCount: values.length,
        meanF: round(mean(values), 2),
      }]
      : [],
);

const byMonthDay = new Map<string, DailyMean[]>();
for (const daily of dailyMeans) {
  byMonthDay.set(daily.monthDay, [
    ...(byMonthDay.get(daily.monthDay) ?? []),
    daily,
  ]);
}

const normals = Object.fromEntries(
  [...byMonthDay.entries()].toSorted(([left], [right]) =>
    left.localeCompare(right)
  ).flatMap(([monthDay, days]) => {
    const values = days.map((day) => day.meanF);
    const years = [...new Set(days.map((day) => day.year))].toSorted();
    if (years.length < MIN_YEARS_PER_DATE) return [];
    return [[monthDay, {
      averageF: round(mean(values), 1),
      p10F: round(percentile(values, .1), 1),
      p25F: round(percentile(values, .25), 1),
      medianF: round(percentile(values, .5), 1),
      p75F: round(percentile(values, .75), 1),
      p90F: round(percentile(values, .9), 1),
      historicalYears: years.length,
      sampleCount: days.reduce((sum, day) => sum + day.sampleCount, 0),
      years,
    }]];
  }),
);

const report = {
  siteId: SITE_ID,
  sourceName: "Bois Brule River near Lake Superior, WI",
  parameterCode: "00010",
  recordYears: `${START_YEAR}-${END_YEAR}`,
  method:
    `USGS legacy instantaneous approved water-temperature observations. One daily mean requires at least ${MIN_SAMPLES_PER_DAY} valid 15-minute samples; each exact calendar-date normal averages every qualifying daily mean and requires at least ${MIN_YEARS_PER_DATE} years. No missing day or year is imputed.`,
  observationCount: observations.length,
  qualifyingDailyMeans: dailyMeans.length,
  expectedDailyMeans: expectedDayCount(),
  dailyCoveragePercent: round(dailyMeans.length / expectedDayCount() * 100, 2),
  exactDateNormals: Object.keys(normals).length,
  expectedExactDates: expectedMonthDayCount(),
  exactDateCoveragePercent: round(
    Object.keys(normals).length / expectedMonthDayCount() * 100,
    2,
  ),
  dailyMeansByYear: Object.fromEntries(
    Array.from(
      { length: END_YEAR - START_YEAR + 1 },
      (_, index) => START_YEAR + index,
    ).map((year) => [
      year,
      dailyMeans.filter((day) => day.year === year).length,
    ]),
  ),
  normals,
};

if (Deno.args.includes("--write")) {
  await Deno.mkdir("docs/audits", { recursive: true });
  await Deno.writeTextFile(
    "docs/audits/river-run-bois-brule-historical-water-temperature.json",
    JSON.stringify(report, null, 2) + "\n",
  );
  const generated =
    `// Generated by scripts/river-run-bois-brule-temperature-baseline.ts.\n` +
    `// Exact-date historical context only; never a current measured reading.\n` +
    `export const BOIS_BRULE_HISTORICAL_WATER_TEMPERATURE_NORMALS = ${
      JSON.stringify(normals, null, 2)
    } as const;\n`;
  await Deno.writeTextFile(
    "supabase/functions/_shared/riverRunEngine/config/onboarding/boisBruleHistoricalTemperature.generated.ts",
    generated,
  );
}

console.log(JSON.stringify(
  {
    ...report,
    normals: undefined,
    examples: Object.fromEntries(
      [
        "07-01",
        "07-15",
        "08-01",
        "08-15",
        "09-01",
        "09-15",
        "10-01",
        "10-15",
        "10-31",
        "11-15",
      ]
        .flatMap((monthDay) =>
          normals[monthDay] ? [[monthDay, normals[monthDay]]] : []
        ),
    ),
  },
  null,
  2,
));

async function fetchMonth(startDate: string, endDate: string) {
  const url = new URL("https://waterservices.usgs.gov/nwis/iv/");
  for (
    const [key, value] of Object.entries({
      format: "json",
      sites: SITE_ID,
      startDT: startDate,
      endDT: endDate,
      parameterCd: "00010",
      siteStatus: "all",
    })
  ) url.searchParams.set(key, value);
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`USGS ${startDate} request failed: ${response.status}`);
  }
  const payload = await response.json() as {
    value?: {
      timeSeries?: Array<{
        values?: Array<{
          value?: Array<{
            value?: string;
            qualifiers?: string[];
            dateTime?: string;
          }>;
        }>;
      }>;
    };
  };
  return (payload.value?.timeSeries ?? []).flatMap((series) =>
    (series.values ?? []).flatMap((group) =>
      (group.value ?? []).flatMap((item) => {
        const celsius = Number(item.value);
        const localDate = String(item.dateTime ?? "").slice(0, 10);
        const qualifiers = item.qualifiers ?? [];
        const approved = qualifiers.includes("A") &&
          !qualifiers.some((value) => /eqp|equip|dis/i.test(value));
        return approved && Number.isFinite(celsius) && celsius > -2 &&
            celsius < 40 && /^\d{4}-\d{2}-\d{2}$/.test(localDate)
          ? [{ localDate, waterTempF: celsius * 9 / 5 + 32 }]
          : [];
      })
    )
  );
}

function expectedDayCount() {
  let total = 0;
  for (let year = START_YEAR; year <= END_YEAR; year++) {
    for (let month = START_MONTH; month <= END_MONTH; month++) {
      total += new Date(Date.UTC(year, month, 0)).getUTCDate();
    }
  }
  return total;
}

function expectedMonthDayCount() {
  let total = 0;
  for (let month = START_MONTH; month <= END_MONTH; month++) {
    total += new Date(Date.UTC(2023, month, 0)).getUTCDate();
  }
  return total;
}

function mean(values: number[]) {
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function percentile(values: number[], p: number) {
  const sorted = values.toSorted((left, right) => left - right);
  if (sorted.length === 1) return sorted[0];
  const index = (sorted.length - 1) * p;
  const lower = Math.floor(index);
  const upper = Math.ceil(index);
  return lower === upper
    ? sorted[lower]
    : sorted[lower] + (sorted[upper] - sorted[lower]) * (index - lower);
}

function round(value: number, digits: number) {
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}
