import type { FlyArchetypeIdV3, RecommenderV3ArchetypeProfile } from "../contracts.ts";
import { selectThemeShadesV3 } from "../colors.ts";

function fly(
  profile: RecommenderV3ArchetypeProfile,
): RecommenderV3ArchetypeProfile {
  return profile;
}

export const FLY_ARCHETYPES_V3: Record<FlyArchetypeIdV3, RecommenderV3ArchetypeProfile> = {
  clouser_minnow: fly({
    id: "clouser_minnow",
    display_name: "Clouser Minnow",
    gear_mode: "fly",
    family_key: "baitfish_streamer",
    preferred_water_columns: ["shallow", "mid", "bottom"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "fly_baitfish",
    allowed_color_themes: ["white_shad", "natural_baitfish", "bright_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "natural_baitfish", "bright_contrast"],
      {
        bright_contrast: ["white/chartreuse", "chartreuse/white", "firetiger"],
      },
    ),
  }),
  deceiver: fly({
    id: "deceiver",
    display_name: "Deceiver",
    gear_mode: "fly",
    family_key: "baitfish_streamer",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "fly_baitfish",
    allowed_color_themes: ["white_shad", "natural_baitfish", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "natural_baitfish", "dark_contrast"],
      {
        dark_contrast: ["black/purple", "black", "black/red"],
      },
    ),
  }),
  bucktail_baitfish_streamer: fly({
    id: "bucktail_baitfish_streamer",
    display_name: "Bucktail Baitfish Streamer",
    gear_mode: "fly",
    family_key: "baitfish_streamer",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "fly_baitfish",
    allowed_color_themes: ["natural_baitfish", "white_shad", "perch_bluegill"],
    shade_examples_by_theme: selectThemeShadesV3(["natural_baitfish", "white_shad", "perch_bluegill"]),
  }),
  slim_minnow_streamer: fly({
    id: "slim_minnow_streamer",
    display_name: "Slim Minnow Streamer",
    gear_mode: "fly",
    family_key: "baitfish_streamer",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "fly_baitfish",
    allowed_color_themes: ["natural_baitfish", "white_shad", "bright_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["natural_baitfish", "white_shad", "bright_contrast"],
      {
        bright_contrast: ["white/chartreuse", "yellow/white", "chartreuse/olive"],
      },
    ),
  }),
  articulated_baitfish_streamer: fly({
    id: "articulated_baitfish_streamer",
    display_name: "Articulated Baitfish Streamer",
    gear_mode: "fly",
    family_key: "baitfish_streamer",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "fly_baitfish",
    allowed_color_themes: ["natural_baitfish", "white_shad", "perch_bluegill"],
    shade_examples_by_theme: selectThemeShadesV3(["natural_baitfish", "white_shad", "perch_bluegill"]),
  }),
  game_changer: fly({
    id: "game_changer",
    display_name: "Game Changer",
    gear_mode: "fly",
    family_key: "articulated_streamer",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "fly_baitfish",
    allowed_color_themes: ["white_shad", "natural_baitfish", "perch_bluegill", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "natural_baitfish", "perch_bluegill", "dark_contrast"],
      {
        dark_contrast: ["black/purple", "black/blue", "midnight"],
      },
    ),
  }),
  woolly_bugger: fly({
    id: "woolly_bugger",
    display_name: "Woolly Bugger",
    gear_mode: "fly",
    family_key: "bugger_leech",
    preferred_water_columns: ["shallow", "mid", "bottom"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["leech_worm", "baitfish", "crawfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "fly_bottom",
    allowed_color_themes: ["dark_contrast", "natural_baitfish", "craw_natural"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["dark_contrast", "natural_baitfish", "craw_natural"],
      {
        dark_contrast: ["black", "black/olive", "black/purple"],
        natural_baitfish: ["olive", "white/olive", "gray/white"],
      },
    ),
  }),
  rabbit_strip_leech: fly({
    id: "rabbit_strip_leech",
    display_name: "Rabbit-Strip Leech",
    gear_mode: "fly",
    family_key: "bugger_leech",
    preferred_water_columns: ["mid", "bottom"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["leech_worm", "baitfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "fly_bottom",
    allowed_color_themes: ["dark_contrast", "natural_baitfish", "craw_natural"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["dark_contrast", "natural_baitfish", "craw_natural"],
      {
        dark_contrast: ["black", "black/purple", "black/blue"],
      },
    ),
  }),
  zonker_streamer: fly({
    id: "zonker_streamer",
    display_name: "Zonker Streamer",
    gear_mode: "fly",
    family_key: "bugger_leech",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced"],
    forage_matches: ["baitfish", "leech_worm"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "fly_baitfish",
    allowed_color_themes: ["natural_baitfish", "white_shad", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["natural_baitfish", "white_shad", "dark_contrast"],
      {
        dark_contrast: ["black", "black/purple", "black/olive"],
      },
    ),
  }),
  sculpin_streamer: fly({
    id: "sculpin_streamer",
    display_name: "Sculpin Streamer",
    gear_mode: "fly",
    family_key: "bottom_streamer",
    preferred_water_columns: ["mid", "bottom"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish", "crawfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "fly_bottom",
    allowed_color_themes: ["craw_natural", "natural_baitfish", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["craw_natural", "natural_baitfish", "dark_contrast"],
      {
        natural_baitfish: ["olive", "sculpin olive", "tan/olive"],
      },
    ),
  }),
  muddler_sculpin: fly({
    id: "muddler_sculpin",
    display_name: "Muddler-Style Sculpin",
    gear_mode: "fly",
    family_key: "bottom_streamer",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish", "crawfish", "insect_misc"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "fly_bottom",
    allowed_color_themes: ["natural_baitfish", "craw_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["natural_baitfish", "craw_natural", "dark_contrast"],
      {
        natural_baitfish: ["natural", "olive", "tan/olive"],
      },
    ),
  }),
  crawfish_streamer: fly({
    id: "crawfish_streamer",
    display_name: "Crawfish Streamer",
    gear_mode: "fly",
    family_key: "bottom_streamer",
    preferred_water_columns: ["bottom"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["crawfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "fly_bottom",
    allowed_color_themes: ["craw_natural", "green_pumpkin_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["craw_natural", "green_pumpkin_natural", "dark_contrast"],
      {
        dark_contrast: ["black", "black/rust", "black/brown"],
      },
    ),
  }),
  conehead_streamer: fly({
    id: "conehead_streamer",
    display_name: "Conehead Bugger / Streamer",
    gear_mode: "fly",
    family_key: "weighted_streamer",
    preferred_water_columns: ["mid", "bottom"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["balanced"],
    forage_matches: ["baitfish", "leech_worm", "crawfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "fly_bottom",
    allowed_color_themes: ["natural_baitfish", "dark_contrast", "craw_natural"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["natural_baitfish", "dark_contrast", "craw_natural"],
      {
        dark_contrast: ["black", "black/blue", "black/purple"],
      },
    ),
  }),
  pike_bunny_streamer: fly({
    id: "pike_bunny_streamer",
    display_name: "Pike Bunny Streamer",
    gear_mode: "fly",
    family_key: "pike_streamer",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "pike_big_profile",
    allowed_color_themes: ["perch_bluegill", "bright_contrast", "white_shad"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["perch_bluegill", "bright_contrast", "white_shad"],
      {
        bright_contrast: ["firetiger", "orange/white", "chartreuse/white"],
      },
    ),
  }),
  large_articulated_pike_streamer: fly({
    id: "large_articulated_pike_streamer",
    display_name: "Large Articulated Pike Streamer",
    gear_mode: "fly",
    family_key: "pike_streamer",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "pike_big_profile",
    allowed_color_themes: ["perch_bluegill", "white_shad", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["perch_bluegill", "white_shad", "dark_contrast"],
      {
        dark_contrast: ["black/red", "black/purple", "midnight"],
      },
    ),
  }),
  popper_fly: fly({
    id: "popper_fly",
    display_name: "Popper Fly",
    gear_mode: "fly",
    family_key: "surface_fly",
    preferred_water_columns: ["top"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch", "insect_misc"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "fly_surface",
    allowed_color_themes: ["white_shad", "bright_contrast", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "bright_contrast", "dark_contrast"],
      {
        bright_contrast: ["chartreuse", "yellow", "firetiger"],
        dark_contrast: ["black", "black/yellow", "black/orange"],
      },
    ),
  }),
  frog_fly: fly({
    id: "frog_fly",
    display_name: "Topwater Frog Fly",
    gear_mode: "fly",
    family_key: "surface_fly",
    preferred_water_columns: ["top", "shallow"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["bluegill_perch", "baitfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "fly_surface",
    allowed_color_themes: ["frog_natural", "dark_contrast", "bright_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["frog_natural", "dark_contrast", "bright_contrast"],
      {
        bright_contrast: ["chartreuse frog", "yellow frog", "white frog"],
      },
    ),
  }),
  mouse_fly: fly({
    id: "mouse_fly",
    display_name: "Topwater Mouse Fly",
    gear_mode: "fly",
    family_key: "surface_fly",
    preferred_water_columns: ["top", "shallow"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "insect_misc"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "fly_surface",
    allowed_color_themes: ["mouse_natural", "dark_contrast", "white_shad"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["mouse_natural", "dark_contrast", "white_shad"],
      {
        white_shad: ["white mouse", "cream mouse", "pearl mouse"],
      },
    ),
  }),
};
