import type { RecommenderV3ArchetypeProfile } from "../contracts.ts";
import type { LureArchetypeIdV3 } from "../contracts.ts";
import { selectThemeShadesV3 } from "../colors.ts";

function lure(
  profile: RecommenderV3ArchetypeProfile,
): RecommenderV3ArchetypeProfile {
  return profile;
}

export const LURE_ARCHETYPES_V3: Record<LureArchetypeIdV3, RecommenderV3ArchetypeProfile> = {
  weightless_stick_worm: lure({
    id: "weightless_stick_worm",
    display_name: "Weightless Stick Worm",
    gear_mode: "lure",
    family_key: "stick_worm",
    preferred_water_columns: ["top", "shallow"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["subtle"],
    forage_matches: ["leech_worm"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "finesse_subtle",
    allowed_color_themes: ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
      {
        dark_contrast: ["black", "black/blue", "junebug"],
      },
    ),
  }),
  texas_rigged_stick_worm: lure({
    id: "texas_rigged_stick_worm",
    display_name: "Texas-Rigged Stick Worm",
    gear_mode: "lure",
    family_key: "stick_worm",
    preferred_water_columns: ["shallow", "mid", "bottom"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["leech_worm"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "cover_weedless",
    allowed_color_themes: ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
      {
        dark_contrast: ["black/blue", "junebug", "black grape"],
      },
    ),
  }),
  wacky_rigged_stick_worm: lure({
    id: "wacky_rigged_stick_worm",
    display_name: "Wacky-Rigged Stick Worm",
    gear_mode: "lure",
    family_key: "stick_worm",
    preferred_water_columns: ["top", "shallow", "mid"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["subtle"],
    forage_matches: ["leech_worm"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "finesse_subtle",
    how_to_fish_text:
      "Hook through the midsection, let it sink with a slow wobble, then lift and dead-stick with long pauses so both ends flutter.",
    allowed_color_themes: ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
      {
        dark_contrast: ["black", "junebug", "black/blue"],
      },
    ),
  }),
  carolina_rigged_stick_worm: lure({
    id: "carolina_rigged_stick_worm",
    display_name: "Carolina-Rigged Stick Worm",
    gear_mode: "lure",
    family_key: "stick_worm",
    preferred_water_columns: ["mid", "bottom"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["leech_worm", "baitfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "bottom_contact",
    how_to_fish_text:
      "Drag the rig slowly across hard bottom and transitions so the leader lets the worm hunt above the weight; pause when you feel it tick structure.",
    allowed_color_themes: ["green_pumpkin_natural", "watermelon_natural", "natural_baitfish"],
    shade_examples_by_theme: selectThemeShadesV3(["green_pumpkin_natural", "watermelon_natural", "natural_baitfish"]),
  }),
  shaky_head_worm: lure({
    id: "shaky_head_worm",
    display_name: "Shaky-Head Worm",
    gear_mode: "lure",
    family_key: "finesse_worm",
    preferred_water_columns: ["mid", "bottom"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["subtle"],
    forage_matches: ["leech_worm"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "bottom_contact",
    allowed_color_themes: ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
      {
        dark_contrast: ["black", "black grape", "junebug"],
      },
    ),
  }),
  drop_shot_worm_minnow: lure({
    id: "drop_shot_worm_minnow",
    display_name: "Drop-Shot Worm / Minnow",
    gear_mode: "lure",
    family_key: "drop_shot",
    preferred_water_columns: ["mid", "bottom"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["subtle"],
    forage_matches: ["baitfish", "leech_worm"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "finesse_subtle",
    how_to_fish_text:
      "Keep the bait vertical under the boat or bank: tiny hops and shakes with the rod tip, then let it hang still so the minnow or worm quivers on a tight line.",
    allowed_color_themes: ["natural_baitfish", "green_pumpkin_natural", "watermelon_natural"],
    shade_examples_by_theme: selectThemeShadesV3(["natural_baitfish", "green_pumpkin_natural", "watermelon_natural"]),
  }),
  ned_rig: lure({
    id: "ned_rig",
    display_name: "Ned Rig",
    gear_mode: "lure",
    family_key: "ned_rig",
    preferred_water_columns: ["shallow", "mid", "bottom"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["subtle"],
    forage_matches: ["crawfish", "leech_worm"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "bottom_contact",
    how_to_fish_text:
      "Drag and shake the small head along bottom like a tiny craw — short pulls, let it settle, repeat instead of big hops.",
    allowed_color_themes: ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["green_pumpkin_natural", "watermelon_natural", "dark_contrast"],
      {
        dark_contrast: ["black/blue", "black", "pb&j"],
      },
    ),
  }),
  tube_jig: lure({
    id: "tube_jig",
    display_name: "Tube Jig",
    gear_mode: "lure",
    family_key: "tube",
    preferred_water_columns: ["shallow", "mid", "bottom"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["crawfish", "baitfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "bottom_contact",
    how_to_fish_text:
      "Snap the tube off bottom with short pops so it spirals on the fall, then let it glide back down on slack or semi-slack line.",
    allowed_color_themes: ["craw_natural", "green_pumpkin_natural", "natural_baitfish"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["craw_natural", "green_pumpkin_natural", "natural_baitfish"],
      {
        natural_baitfish: ["smoke purple", "goby", "olive smoke"],
      },
    ),
  }),
  texas_rigged_soft_plastic_craw: lure({
    id: "texas_rigged_soft_plastic_craw",
    display_name: "Texas-Rigged Soft-Plastic Craw",
    gear_mode: "lure",
    family_key: "soft_craw",
    preferred_water_columns: ["bottom"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["crawfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "cover_weedless",
    how_to_fish_text:
      "Flip or pitch into cover, let the craw fall straight on semi-slack line, then hop it once or twice before the next pitch.",
    allowed_color_themes: ["craw_natural", "green_pumpkin_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["craw_natural", "green_pumpkin_natural", "dark_contrast"],
      {
        dark_contrast: ["black/blue", "black/red", "junebug"],
      },
    ),
  }),
  football_jig: lure({
    id: "football_jig",
    display_name: "Football Jig",
    gear_mode: "lure",
    family_key: "jig",
    preferred_water_columns: ["mid", "bottom"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["crawfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "bottom_contact",
    allowed_color_themes: ["craw_natural", "green_pumpkin_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["craw_natural", "green_pumpkin_natural", "dark_contrast"],
      {
        dark_contrast: ["black/blue", "black/purple", "black/brown"],
      },
    ),
  }),
  compact_flipping_jig: lure({
    id: "compact_flipping_jig",
    display_name: "Compact Flipping / Pitching Jig",
    gear_mode: "lure",
    family_key: "jig",
    preferred_water_columns: ["shallow", "mid", "bottom"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["crawfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "cover_weedless",
    allowed_color_themes: ["green_pumpkin_natural", "dark_contrast", "perch_bluegill"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["green_pumpkin_natural", "dark_contrast", "perch_bluegill"],
      {
        dark_contrast: ["black/blue", "black/purple", "black/red"],
        perch_bluegill: ["bluegill", "green pumpkin bluegill", "sunfish"],
      },
    ),
  }),
  swim_jig: lure({
    id: "swim_jig",
    display_name: "Swim Jig",
    gear_mode: "lure",
    family_key: "jig",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "horizontal_search",
    allowed_color_themes: ["white_shad", "perch_bluegill", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "perch_bluegill", "dark_contrast"],
      {
        dark_contrast: ["black/blue", "black/purple", "black"],
      },
    ),
  }),
  hair_jig: lure({
    id: "hair_jig",
    display_name: "Hair Jig / Marabou Jig",
    gear_mode: "lure",
    family_key: "hair_jig",
    preferred_water_columns: ["shallow", "mid", "bottom"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish", "leech_worm", "crawfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "finesse_subtle",
    allowed_color_themes: ["natural_baitfish", "white_shad", "dark_contrast", "craw_natural"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["natural_baitfish", "white_shad", "dark_contrast", "craw_natural"],
      {
        white_shad: ["white", "pearl", "white/silver"],
        dark_contrast: ["black", "brown/black", "black/purple"],
      },
    ),
  }),
  inline_spinner: lure({
    id: "inline_spinner",
    display_name: "Inline Spinner",
    gear_mode: "lure",
    family_key: "spinner",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "insect_misc"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "horizontal_search",
    allowed_color_themes: ["metal_flash", "bright_contrast", "natural_baitfish"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["metal_flash", "bright_contrast", "natural_baitfish"],
      {
        metal_flash: ["silver blade", "gold blade", "copper blade"],
      },
    ),
  }),
  spinnerbait: lure({
    id: "spinnerbait",
    display_name: "Spinnerbait",
    gear_mode: "lure",
    family_key: "spinnerbait",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["stained", "dirty"],
    tactical_lane: "horizontal_search",
    allowed_color_themes: ["white_shad", "bright_contrast", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "bright_contrast", "dark_contrast"],
      {
        white_shad: ["white", "white/blue", "white/silver"],
        bright_contrast: ["white/chartreuse", "firetiger", "chartreuse/white"],
        dark_contrast: ["black", "black/blue", "red/black"],
      },
    ),
  }),
  bladed_jig: lure({
    id: "bladed_jig",
    display_name: "Bladed Jig",
    gear_mode: "lure",
    family_key: "bladed_jig",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["stained", "dirty"],
    tactical_lane: "horizontal_search",
    how_to_fish_text:
      "Yo-yo the blade: snap the rod so the head kicks and vibrates, then let it pendulum back with a controlled semi-slack fall.",
    allowed_color_themes: ["white_shad", "green_pumpkin_natural", "dark_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "green_pumpkin_natural", "dark_contrast"],
      {
        white_shad: ["white", "white/chartreuse", "pearl shad"],
        green_pumpkin_natural: ["green pumpkin", "green pumpkin shad", "bluegill"],
        dark_contrast: ["black/blue", "black/purple", "black"],
      },
    ),
  }),
  paddle_tail_swimbait: lure({
    id: "paddle_tail_swimbait",
    display_name: "Paddle-Tail Swimbait",
    gear_mode: "lure",
    family_key: "swimbait",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "horizontal_search",
    how_to_fish_text:
      "Reel at a steady pace with the rod low so the tail thumps; speed up slightly over bait or slow after a follow.",
    allowed_color_themes: ["natural_baitfish", "white_shad", "perch_bluegill"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["natural_baitfish", "white_shad", "perch_bluegill"],
      {
        perch_bluegill: ["bluegill", "perch", "sunfish"],
      },
    ),
  }),
  soft_jerkbait: lure({
    id: "soft_jerkbait",
    display_name: "Soft Jerkbait",
    gear_mode: "lure",
    family_key: "soft_jerkbait",
    preferred_water_columns: ["top", "shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "horizontal_search",
    how_to_fish_text:
      "Twitch it with slack in the line so the bait darts and glides erratically; pause and let it sink a few inches between twitches.",
    allowed_color_themes: ["natural_baitfish", "white_shad", "bright_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["natural_baitfish", "white_shad", "bright_contrast"],
      {
        bright_contrast: ["bubblegum", "albino", "white/chartreuse"],
      },
    ),
  }),
  suspending_jerkbait: lure({
    id: "suspending_jerkbait",
    display_name: "Suspending Jerkbait",
    gear_mode: "lure",
    family_key: "jerkbait",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["negative", "neutral", "active"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "reaction_mid_column",
    allowed_color_themes: ["natural_baitfish", "white_shad", "bright_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["natural_baitfish", "white_shad", "bright_contrast"],
      {
        natural_baitfish: ["ghost minnow", "pro blue", "olive shad"],
        white_shad: ["pearl", "table rock shad", "white/silver"],
        bright_contrast: ["clown", "firetiger", "chartreuse shad"],
      },
    ),
  }),
  squarebill_crankbait: lure({
    id: "squarebill_crankbait",
    display_name: "Squarebill Crankbait",
    gear_mode: "lure",
    family_key: "crankbait",
    preferred_water_columns: ["shallow"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "crawfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "horizontal_search",
    allowed_color_themes: ["white_shad", "bright_contrast", "craw_natural", "perch_bluegill"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "bright_contrast", "craw_natural", "perch_bluegill"],
      {
        white_shad: ["sexy shad", "pearl shad", "white chart back"],
        bright_contrast: ["firetiger", "chartreuse black back", "chartreuse blue"],
        craw_natural: ["red craw", "brown craw", "rust craw"],
      },
    ),
  }),
  flat_sided_crankbait: lure({
    id: "flat_sided_crankbait",
    display_name: "Flat-Sided Crankbait",
    gear_mode: "lure",
    family_key: "crankbait",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["subtle", "balanced"],
    forage_matches: ["baitfish", "crawfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "reaction_mid_column",
    allowed_color_themes: ["natural_baitfish", "white_shad", "craw_natural"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["natural_baitfish", "white_shad", "craw_natural"],
      {
        natural_baitfish: ["ghost shad", "smoke shad", "olive shad"],
        craw_natural: ["red craw", "brown craw", "mud craw"],
      },
    ),
  }),
  medium_diving_crankbait: lure({
    id: "medium_diving_crankbait",
    display_name: "Medium-Diving Crankbait",
    gear_mode: "lure",
    family_key: "crankbait",
    preferred_water_columns: ["mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "crawfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "horizontal_search",
    allowed_color_themes: ["white_shad", "bright_contrast", "craw_natural"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "bright_contrast", "craw_natural"],
      {
        white_shad: ["sexy shad", "pearl shad", "white/silver"],
        bright_contrast: ["firetiger", "chartreuse blue", "chartreuse black back"],
        craw_natural: ["red craw", "brown craw", "orange belly craw"],
      },
    ),
  }),
  deep_diving_crankbait: lure({
    id: "deep_diving_crankbait",
    display_name: "Deep-Diving Crankbait",
    gear_mode: "lure",
    family_key: "crankbait",
    preferred_water_columns: ["mid", "bottom"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "crawfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "horizontal_search",
    allowed_color_themes: ["white_shad", "natural_baitfish", "craw_natural"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "natural_baitfish", "craw_natural"],
      {
        natural_baitfish: ["gizzard shad", "olive shad", "smoke shad"],
      },
    ),
  }),
  lipless_crankbait: lure({
    id: "lipless_crankbait",
    display_name: "Lipless Crankbait",
    gear_mode: "lure",
    family_key: "lipless",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "crawfish"],
    clarity_strengths: ["stained", "dirty"],
    tactical_lane: "horizontal_search",
    allowed_color_themes: ["bright_contrast", "metal_flash", "craw_natural"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["bright_contrast", "metal_flash", "craw_natural"],
      {
        bright_contrast: ["firetiger", "chartreuse shad", "orange craw"],
        metal_flash: ["chrome/blue", "chrome/black", "gold/black"],
        craw_natural: ["red craw", "brown craw", "rayburn red"],
      },
    ),
  }),
  blade_bait: lure({
    id: "blade_bait",
    display_name: "Blade Bait",
    gear_mode: "lure",
    family_key: "blade_bait",
    preferred_water_columns: ["mid", "bottom"],
    preferred_moods: ["negative", "neutral"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "reaction_mid_column",
    allowed_color_themes: ["metal_flash", "bright_contrast", "white_shad"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["metal_flash", "bright_contrast", "white_shad"],
      {
        bright_contrast: ["firetiger", "chartreuse chrome", "orange/chartreuse"],
      },
    ),
  }),
  casting_spoon: lure({
    id: "casting_spoon",
    display_name: "Casting Spoon",
    gear_mode: "lure",
    family_key: "spoon",
    preferred_water_columns: ["mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "reaction_mid_column",
    allowed_color_themes: ["metal_flash", "white_shad", "bright_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["metal_flash", "white_shad", "bright_contrast"],
      {
        bright_contrast: ["chartreuse chrome", "firetiger spoon", "orange/chartreuse"],
      },
    ),
  }),
  walking_topwater: lure({
    id: "walking_topwater",
    display_name: "Walking Topwater",
    gear_mode: "lure",
    family_key: "topwater",
    preferred_water_columns: ["top"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained"],
    tactical_lane: "surface",
    allowed_color_themes: ["white_shad", "dark_contrast", "perch_bluegill"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "dark_contrast", "perch_bluegill"],
      {
        white_shad: ["bone", "white", "pearl"],
        dark_contrast: ["black", "black shad", "black chrome"],
      },
    ),
  }),
  popping_topwater: lure({
    id: "popping_topwater",
    display_name: "Popping Topwater",
    gear_mode: "lure",
    family_key: "topwater",
    preferred_water_columns: ["top"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "surface",
    allowed_color_themes: ["white_shad", "dark_contrast", "bright_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "dark_contrast", "bright_contrast"],
      {
        white_shad: ["bone", "white", "pearl"],
        dark_contrast: ["black", "black chrome", "midnight"],
        bright_contrast: ["firetiger", "chartreuse", "orange belly"],
      },
    ),
  }),
  buzzbait_prop_bait: lure({
    id: "buzzbait_prop_bait",
    display_name: "Buzzbait / Prop Bait",
    gear_mode: "lure",
    family_key: "topwater",
    preferred_water_columns: ["top"],
    preferred_moods: ["active"],
    preferred_presentation_styles: ["bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["stained", "dirty"],
    tactical_lane: "surface",
    allowed_color_themes: ["white_shad", "dark_contrast", "bright_contrast"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["white_shad", "dark_contrast", "bright_contrast"],
      {
        white_shad: ["white", "white/chartreuse", "pearl"],
        dark_contrast: ["black", "black/blue", "black/red"],
      },
    ),
  }),
  hollow_body_frog: lure({
    id: "hollow_body_frog",
    display_name: "Hollow-Body Frog",
    gear_mode: "lure",
    family_key: "frog",
    preferred_water_columns: ["top", "shallow"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["bluegill_perch", "baitfish"],
    clarity_strengths: ["stained", "dirty", "clear"],
    tactical_lane: "cover_weedless",
    allowed_color_themes: ["frog_natural", "dark_contrast", "white_shad"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["frog_natural", "dark_contrast", "white_shad"],
      {
        dark_contrast: ["black frog", "black/blue frog", "midnight frog"],
        white_shad: ["white", "bone", "pearl frog"],
      },
    ),
  }),
  large_profile_pike_swimbait: lure({
    id: "large_profile_pike_swimbait",
    display_name: "Large-Profile Pike Swimbait",
    gear_mode: "lure",
    family_key: "pike_swimbait",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "pike_big_profile",
    allowed_color_themes: ["perch_bluegill", "bright_contrast", "white_shad"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["perch_bluegill", "bright_contrast", "white_shad"],
      {
        bright_contrast: ["firetiger", "orange perch", "hot pike"],
      },
    ),
  }),
  pike_jerkbait: lure({
    id: "pike_jerkbait",
    display_name: "Pike Jerkbait",
    gear_mode: "lure",
    family_key: "pike_jerkbait",
    preferred_water_columns: ["shallow", "mid"],
    preferred_moods: ["neutral", "active"],
    preferred_presentation_styles: ["balanced", "bold"],
    forage_matches: ["baitfish", "bluegill_perch"],
    clarity_strengths: ["clear", "stained", "dirty"],
    tactical_lane: "pike_big_profile",
    allowed_color_themes: ["perch_bluegill", "bright_contrast", "white_shad"],
    shade_examples_by_theme: selectThemeShadesV3(
      ["perch_bluegill", "bright_contrast", "white_shad"],
      {
        bright_contrast: ["firetiger", "clown", "redhead"],
        white_shad: ["silver/black", "pearl", "whitefish"],
      },
    ),
  }),
};
