export {
  LARGEMOUTH_V3_SEASONAL_ROWS,
  LARGEMOUTH_V3_SUPPORTED_REGIONS,
} from "./largemouth.ts";
export {
  SMALLMOUTH_V3_SEASONAL_ROWS,
  SMALLMOUTH_V3_SUPPORTED_REGIONS,
} from "./smallmouth.ts";
export {
  TROUT_V3_SEASONAL_ROWS,
  TROUT_V3_SUPPORTED_REGIONS,
} from "./trout.ts";
export {
  NORTHERN_PIKE_V3_SEASONAL_ROWS,
  NORTHERN_PIKE_V3_SUPPORTED_REGIONS,
} from "./pike.ts";
