import type { EngineContext } from "../../supabase/functions/_shared/howFishingEngine/contracts/context.ts";
import type { RegionKey } from "../../supabase/functions/_shared/howFishingEngine/contracts/region.ts";
import type { ForageMode } from "../../supabase/functions/_shared/recommenderEngine/contracts/behavior.ts";
import type { SpeciesGroup } from "../../supabase/functions/_shared/recommenderEngine/contracts/species.ts";

export type RecommenderAuditFishery = {
  key: string;
  label: string;
  fishery_group: string;
  latitude: number;
  longitude: number;
  local_timezone: string;
  context: EngineContext;
  region_key: RegionKey;
  state_code: string;
  tide_station_id?: string;
  species_targets: SpeciesGroup[];
  expected_forage_modes: Partial<Record<SpeciesGroup, ForageMode[]>>;
  notes: string;
};

export const PRIORITY_RECOMMENDER_AUDIT_FISHERIES: RecommenderAuditFishery[] = [
  {
    key: "lake_okeechobee",
    label: "Lake Okeechobee, FL",
    fishery_group: "Florida freshwater lake",
    latitude: 26.94,
    longitude: -80.8,
    local_timezone: "America/New_York",
    context: "freshwater_lake_pond",
    region_key: "florida",
    state_code: "FL",
    species_targets: ["largemouth_bass"],
    expected_forage_modes: {
      largemouth_bass: ["baitfish", "crawfish", "surface_prey"],
    },
    notes: "Flagship Florida bass lake for warmwater seasonal and forage-driven checks.",
  },
  {
    key: "lake_guntersville",
    label: "Lake Guntersville, AL",
    fishery_group: "Southern bass lake",
    latitude: 34.39,
    longitude: -86.29,
    local_timezone: "America/Chicago",
    context: "freshwater_lake_pond",
    region_key: "south_central",
    state_code: "AL",
    species_targets: ["largemouth_bass"],
    expected_forage_modes: {
      largemouth_bass: ["baitfish", "crawfish", "surface_prey"],
    },
    notes: "Mainstream grass-and-ledge bass benchmark with real pressure and seasonal swing.",
  },
  {
    key: "lake_lanier",
    label: "Lake Lanier, GA",
    fishery_group: "Southeast reservoir",
    latitude: 34.15,
    longitude: -84.02,
    local_timezone: "America/New_York",
    context: "freshwater_lake_pond",
    region_key: "south_central",
    state_code: "GA",
    species_targets: ["largemouth_bass", "striped_bass"],
    expected_forage_modes: {
      largemouth_bass: ["baitfish", "crawfish"],
      striped_bass: ["baitfish"],
    },
    notes: "High-pressure Southeast lake that helps test inland baitfish logic for both bass and stripers.",
  },
  {
    key: "sam_rayburn",
    label: "Sam Rayburn Reservoir, TX",
    fishery_group: "Southern bass lake",
    latitude: 31.06,
    longitude: -94.16,
    local_timezone: "America/Chicago",
    context: "freshwater_lake_pond",
    region_key: "south_central",
    state_code: "TX",
    species_targets: ["largemouth_bass"],
    expected_forage_modes: {
      largemouth_bass: ["baitfish", "crawfish", "surface_prey"],
    },
    notes: "Elite Texas bass benchmark for common warmwater tackle families and daily aggressiveness shifts.",
  },
  {
    key: "mille_lacs",
    label: "Mille Lacs, MN",
    fishery_group: "Upper Midwest lake",
    latitude: 46.24,
    longitude: -93.67,
    local_timezone: "America/Chicago",
    context: "freshwater_lake_pond",
    region_key: "great_lakes_upper_midwest",
    state_code: "MN",
    species_targets: ["smallmouth_bass", "walleye", "pike_musky"],
    expected_forage_modes: {
      smallmouth_bass: ["crawfish", "baitfish"],
      walleye: ["baitfish"],
      pike_musky: ["baitfish"],
    },
    notes: "Mainstream Upper Midwest benchmark with strong smallmouth, walleye, and pike relevance.",
  },
  {
    key: "lake_erie_western_basin",
    label: "Lake Erie Western Basin, OH",
    fishery_group: "Great Lakes lake",
    latitude: 41.69,
    longitude: -83.37,
    local_timezone: "America/New_York",
    context: "freshwater_lake_pond",
    region_key: "great_lakes_upper_midwest",
    state_code: "OH",
    species_targets: ["walleye", "smallmouth_bass"],
    expected_forage_modes: {
      walleye: ["baitfish"],
      smallmouth_bass: ["crawfish", "baitfish"],
    },
    notes: "Great Lakes benchmark for mainstream walleye and smallmouth selection.",
  },
  {
    key: "susquehanna_river",
    label: "Susquehanna River, PA",
    fishery_group: "Appalachian river",
    latitude: 40.26,
    longitude: -76.89,
    local_timezone: "America/New_York",
    context: "freshwater_river",
    region_key: "northeast",
    state_code: "PA",
    species_targets: ["smallmouth_bass"],
    expected_forage_modes: {
      smallmouth_bass: ["crawfish", "baitfish"],
    },
    notes: "Mainstream smallmouth river for current, clarity, and river-forage correctness.",
  },
  {
    key: "detroit_river",
    label: "Detroit River, MI",
    fishery_group: "Great Lakes river",
    latitude: 42.33,
    longitude: -83.04,
    local_timezone: "America/Detroit",
    context: "freshwater_river",
    region_key: "great_lakes_upper_midwest",
    state_code: "MI",
    species_targets: ["walleye", "smallmouth_bass"],
    expected_forage_modes: {
      walleye: ["baitfish"],
      smallmouth_bass: ["crawfish", "baitfish"],
    },
    notes: "High-pressure current-oriented Midwest river benchmark.",
  },
  {
    key: "white_river",
    label: "White River, AR",
    fishery_group: "Southern trout river",
    latitude: 36.24,
    longitude: -92.55,
    local_timezone: "America/Chicago",
    context: "freshwater_river",
    region_key: "south_central",
    state_code: "AR",
    species_targets: ["river_trout"],
    expected_forage_modes: {
      river_trout: ["baitfish", "leech"],
    },
    notes: "Mainstream tailwater trout benchmark for streamer-only scope in V1.",
  },
  {
    key: "west_branch_delaware",
    label: "West Branch Delaware, NY",
    fishery_group: "Northeast trout river",
    latitude: 42.01,
    longitude: -75.39,
    local_timezone: "America/New_York",
    context: "freshwater_river",
    region_key: "northeast",
    state_code: "NY",
    species_targets: ["river_trout"],
    expected_forage_modes: {
      river_trout: ["baitfish", "leech"],
    },
    notes: "Classic Northeast trout river with strong seasonal temperature sensitivity.",
  },
  {
    key: "chesapeake_bay",
    label: "Chesapeake Bay, MD",
    fishery_group: "Atlantic inshore",
    latitude: 38.97,
    longitude: -76.48,
    local_timezone: "America/New_York",
    context: "coastal",
    region_key: "southeast_atlantic",
    state_code: "MD",
    tide_station_id: "8574680",
    species_targets: ["striped_bass"],
    expected_forage_modes: {
      striped_bass: ["baitfish"],
    },
    notes: "Core East Coast striper benchmark for tide, baitfish, and current alignment.",
  },
  {
    key: "tampa_bay",
    label: "Tampa Bay, FL",
    fishery_group: "Florida inshore",
    latitude: 27.73,
    longitude: -82.55,
    local_timezone: "America/New_York",
    context: "coastal",
    region_key: "florida",
    state_code: "FL",
    tide_station_id: "8726520",
    species_targets: ["redfish", "snook", "seatrout", "tarpon"],
    expected_forage_modes: {
      redfish: ["baitfish", "shrimp"],
      snook: ["baitfish", "shrimp"],
      seatrout: ["baitfish", "shrimp"],
      tarpon: ["baitfish", "shrimp"],
    },
    notes: "High-volume Florida inshore system covering major salt species in mainstream conditions.",
  },
  {
    key: "mosquito_lagoon",
    label: "Mosquito Lagoon, FL",
    fishery_group: "Florida flats",
    latitude: 28.98,
    longitude: -80.85,
    local_timezone: "America/New_York",
    context: "coastal_flats_estuary",
    region_key: "florida",
    state_code: "FL",
    tide_station_id: "8721604",
    species_targets: ["redfish", "seatrout", "snook"],
    expected_forage_modes: {
      redfish: ["crab", "shrimp"],
      seatrout: ["shrimp", "baitfish"],
      snook: ["shrimp", "baitfish"],
    },
    notes: "Florida skinny-water benchmark where forage and color should shift clearly by clarity.",
  },
  {
    key: "lower_laguna_madre",
    label: "Lower Laguna Madre, TX",
    fishery_group: "Gulf flats",
    latitude: 26.07,
    longitude: -97.17,
    local_timezone: "America/Chicago",
    context: "coastal_flats_estuary",
    region_key: "gulf_coast",
    state_code: "TX",
    tide_station_id: "8779770",
    species_targets: ["redfish", "seatrout"],
    expected_forage_modes: {
      redfish: ["crab", "shrimp"],
      seatrout: ["shrimp", "baitfish"],
    },
    notes: "Mainstream Texas flats benchmark with strong visibility and tide sensitivity.",
  },
  {
    key: "galveston_bay",
    label: "Galveston Bay, TX",
    fishery_group: "Gulf inshore",
    latitude: 29.44,
    longitude: -94.87,
    local_timezone: "America/Chicago",
    context: "coastal",
    region_key: "gulf_coast",
    state_code: "TX",
    tide_station_id: "8771450",
    species_targets: ["redfish", "seatrout"],
    expected_forage_modes: {
      redfish: ["baitfish", "shrimp"],
      seatrout: ["baitfish", "shrimp"],
    },
    notes: "Large Gulf inshore benchmark with real moving-water and dirty-water relevance.",
  },
];
